---
permalink: api-automation/concept_manage_access_endpoint.html 
sidebar: sidebar 
keywords: manage, endpoints, access 
summary: Storage Virtual Machine（SVM）、LUN、およびファイル共有のプロビジョニングに必要な、アクセスエンドポイントまたは論理インターフェイス（LIF）を作成する必要があります。Active IQ Unified Manager 環境内の SVM 、 LUN 、またはファイル共有のアクセスエンドポイントを表示、作成、変更、および削除できます。 
---
= APIを使用したアクセスエンドポイントの管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Storage Virtual Machine（SVM）、LUN、およびファイル共有のプロビジョニングに必要な、アクセスエンドポイントまたは論理インターフェイス（LIF）を作成する必要があります。Active IQ Unified Manager 環境内の SVM 、 LUN 、またはファイル共有のアクセスエンドポイントを表示、作成、変更、および削除できます。



== アクセスエンドポイントの表示

Unified Manager 環境のアクセスエンドポイントのリストを表示するには、次のメソッドを使用します。特定のSVM、LUN、またはファイル共有のアクセスエンドポイントのリストを照会するには、SVM、LUN、またはファイル共有の一意の識別子を入力する必要があります。一意のアクセスエンドポイントキーを入力して、特定のアクセスエンドポイントの詳細を取得することもできます。

[cols="3*"]
|===
| カテゴリ | HTTP動詞 | パス 


 a| 
ストレージプロバイダ
 a| 
取得
 a| 
`/storage-provider/access-endpoints`

`/storage-provider/access-endpoints/\{key}`

|===


== アクセスエンドポイントの追加

カスタムアクセスエンドポイントを作成し、必要なプロパティを割り当てることができます。作成するアクセスエンドポイントの詳細を入力パラメータとして入力する必要があります。この API 、または System Manager または ONTAP CLI を使用して、各ノードにアクセスエンドポイントを作成できます。アクセスエンドポイントの作成では、IPv4アドレスとIPv6アドレスの両方がサポートされます。

[NOTE]
====
LUNとファイル共有をプロビジョニングするには、SVMにノードあたりの最小アクセスエンドポイント数を設定する必要があります。SVMには、ノードごとに少なくとも2つのアクセスエンドポイントを設定する必要があります。1つはCIFSプロトコルとNFSプロトコルをサポートし、もう1つはiSCSIプロトコルまたはFCPプロトコルをサポートします。

====
[cols="3*"]
|===
| カテゴリ | HTTP動詞 | パス 


 a| 
ストレージプロバイダ
 a| 
投稿
 a| 
`/storage-provider/access-endpoints`

|===


== アクセスエンドポイントの削除

特定のアクセスエンドポイントを削除するには、次のメソッドを使用します。特定のアクセスエンドポイントを削除するには、入力パラメータとしてアクセスエンドポイントキーを指定する必要があります。

[cols="3*"]
|===
| カテゴリ | HTTP動詞 | パス 


 a| 
ストレージプロバイダ
 a| 
削除
 a| 
`/storage-provider/access-endpoints/\{key}`

|===


== アクセスエンドポイントの変更

アクセスエンドポイントを変更し、そのプロパティを更新するには、次のメソッドを使用します。特定のアクセスエンドポイントを変更するには、アクセスエンドポイントキーを指定する必要があります。また、更新するプロパティとその値を入力する必要があります。

[cols="3*"]
|===
| カテゴリ | HTTP動詞 | パス 


 a| 
ストレージプロバイダ
 a| 
パッチ
 a| 
`/storage-provider/access-endpoints/\{key}`

|===