---
permalink: api-automation/concept_manage_fileshares_api.html 
sidebar: sidebar 
keywords: manage, file, share 
summary: /storage-provider/file-shares API を使用して、データセンター環境内の CIFS および NFS のファイル共有ボリュームを表示、追加、変更、および削除できます。 
---
= APIを使用したファイル共有の管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
APIを使用して、データセンター環境でCIFSおよびNFSファイル共有ボリュームを表示、追加、変更、削除できます `/storage-provider/file-shares`。

ファイル共有ボリュームをプロビジョニングする前に、SVMが作成され、サポートされるプロトコルでプロビジョニングされていることを確認してください。パフォーマンスサービスレベル（PSL）またはストレージ効率化ポリシー（SEP）を割り当てる場合は、プロビジョニング時にファイル共有を作成する前にPSLまたはSEPを作成する必要があります。



== ファイル共有の表示

Unified Manager環境で使用可能なファイル共有ボリュームを表示するには、次のメソッドを使用します。Active IQ Unified Manager のデータソースとして ONTAP クラスタを追加すると、それらのクラスタのストレージワークロードが Unified Manager インスタンスに自動的に追加されます。このAPIは、Unified Managerインスタンスに自動および手動で追加されたファイル共有を取得します。特定のファイル共有の詳細を表示するには、ファイル共有キーを指定してこのAPIを実行します。

[cols="3*"]
|===
| カテゴリ | HTTP動詞 | パス 


 a| 
ストレージプロバイダ
 a| 
取得
 a| 
`/storage-provider/file-shares`

`/storage-provider/file-shares/\{key}`

|===


== ファイル共有の追加

SVMにCIFSおよびNFSファイル共有を追加するには、次のメソッドを使用します。作成するファイル共有の詳細を入力パラメータとして指定する必要があります。このAPIを使用してFlexGroupボリュームを追加することはできません。

[cols="3*"]
|===
| カテゴリ | HTTP動詞 | パス 


 a| 
ストレージプロバイダ
 a| 
投稿
 a| 
`/storage-provider/file-shares`

|===
[NOTE]
====
アクセス制御リスト（ACL）パラメータとエクスポートポリシーパラメータのどちらを指定するかに応じて、CIFS共有またはNFSファイル共有が作成されます。ACLパラメータの値を指定しないと、CIFS共有は作成されず、デフォルトでNFS共有が作成されてすべてのアクセスが許可されます。

====
*データ保護ボリュームを作成する*：SVMにファイル共有を追加する場合、マウントされるボリュームのタイプは、デフォルトで（読み取り/書き込み）です `rw`。データ保護（DP）ボリュームを作成する場合は、パラメータの値として `type`を指定します `dp`。



== ファイル共有の削除

特定のファイル共有を削除するには、次のメソッドを使用します。特定のファイル共有を削除するには、入力パラメータとしてファイル共有キーを入力する必要があります。

[cols="3*"]
|===
| カテゴリ | HTTP動詞 | パス 


 a| 
ストレージプロバイダ
 a| 
削除
 a| 
`/storage-provider/file-shares/\{key}`

|===


== ファイル共有の変更

ファイル共有を変更し、そのプロパティを更新するには、次のメソッドを使用します。

特定のファイル共有を変更するには、ファイル共有キーを指定する必要があります。また、更新するプロパティとその値を入力する必要があります。

[NOTE]
====
このAPIの1回の呼び出しで更新できるプロパティは1つだけです。複数の更新を行う場合は、このAPIを何度も実行する必要があります。

====
[cols="3*"]
|===
| カテゴリ | HTTP動詞 | パス 


 a| 
ストレージプロバイダ
 a| 
パッチ
 a| 
`/storage-provider/file-shares/\{key}`

|===