---
permalink: api-automation/concept_manage_psl.html 
sidebar: sidebar 
keywords: manage, performance, service, level 
summary: Active IQ Unified Manager でストレージプロバイダ API を使用して、パフォーマンスサービスレベルを表示、作成、変更、および削除できます。 
---
= APIを使用したパフォーマンスサービスレベルの管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager でストレージプロバイダ API を使用して、パフォーマンスサービスレベルを表示、作成、変更、および削除できます。



== パフォーマンスサービスレベルの表示

ストレージワークロードに割り当てる際にパフォーマンスサービスレベルを表示するには、次のメソッドを使用します。このAPIは、システム定義およびユーザ作成のすべてのパフォーマンスサービスレベルをリストし、すべてのパフォーマンスサービスレベルの属性を取得します。特定のパフォーマンスサービスレベルを照会する場合は、パフォーマンスサービスレベルの一意のIDを入力して詳細を取得する必要があります。

[cols="3*"]
|===
| カテゴリ | HTTP動詞 | パス 


 a| 
ストレージプロバイダ
 a| 
取得
 a| 
`/storage-provider/performance-service-levels`

`/storage-provider/performance-service-levels/\{key}`

|===


== パフォーマンスサービスレベルの追加

システム定義のパフォーマンスサービスレベルがストレージワークロードに必要なサービスレベル目標（SLO）を満たしていない場合は、次のメソッドを使用してカスタムのパフォーマンスサービスレベルを作成し、ストレージワークロードに割り当てることができます。作成するパフォーマンスサービスレベルの詳細を入力します。IOPSプロパティには、有効な値の範囲を入力してください。

[cols="3*"]
|===
| カテゴリ | HTTP動詞 | パス 


 a| 
ストレージプロバイダ
 a| 
投稿
 a| 
`/storage-provider/performance-service-levels`

|===


== パフォーマンスサービスレベルの削除

特定のパフォーマンスサービスレベルを削除するには、次のメソッドを使用します。ワークロードに割り当てられている場合、または使用可能な唯一のパフォーマンスサービスレベルである場合、そのパフォーマンスサービスレベルは削除できません。特定のパフォーマンスサービスレベルを削除するには、パフォーマンスサービスレベルの一意のIDを入力パラメータとして指定する必要があります。

[cols="3*"]
|===
| カテゴリ | HTTP動詞 | パス 


 a| 
ストレージプロバイダ
 a| 
削除
 a| 
`/storage-provider/performance-service-levels/\{key}`

|===


== パフォーマンスサービスレベルの変更

パフォーマンスサービスレベルを変更し、そのプロパティを更新するには、次のメソッドを使用します。システム定義のパフォーマンスサービスレベル、またはワークロードに割り当てられているパフォーマンスサービスレベルは変更できません。特定のパフォーマンスサービスレベルを変更するには、の一意のIDを指定する必要があります。また、更新するIOPSプロパティと有効な値を入力する必要があります。

[cols="3*"]
|===
| カテゴリ | HTTP動詞 | パス 


 a| 
ストレージプロバイダ
 a| 
パッチ
 a| 
`/storage-provider/performance-service-levels/\{key}`

|===


== パフォーマンスサービスレベルに基づくアグリゲート機能の表示

パフォーマンスサービスレベルに基づいてアグリゲート機能を照会するには、次のメソッドを使用します。このAPIは、データセンターで使用可能なアグリゲートのリストを返し、それらのアグリゲートでサポートできるパフォーマンスサービスレベルに関する機能を示します。ボリュームでワークロードをプロビジョニングする際に、特定のパフォーマンスサービスレベルをサポートするアグリゲートの機能を表示し、その機能に基づいてワークロードをプロビジョニングすることができます。アグリゲートを指定できるのは、APIを使用してワークロードをプロビジョニングする場合のみです。この機能は Unified Manager Web UI では使用できません。

[cols="3*"]
|===
| カテゴリ | HTTP動詞 | パス 


 a| 
ストレージプロバイダ
 a| 
取得
 a| 
`/storage-provider/aggregate-capabilities`

`/storage-provider/aggregate-capabilities/\{key}`

|===