---
permalink: api-automation/concept_events_api.html 
sidebar: sidebar 
keywords: view, events, system, details 
summary: イベント API を使用すると、データセンター内の監視対象クラスタに対して生成されたイベントを取得できます。 
---
= APIを使用したイベントとアラートの管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
 `alerts`カテゴリのAPI、 `management-server`、およびを `scripts`使用して、 `events`Active IQ Unified Manager環境内のイベント、アラート、およびアラートに関連付けられているスクリプトを管理できます。



== イベントの表示と変更

Unified Managerは、Unified Managerによって監視および管理されているクラスタについて、ONTAPで生成されたイベントを受け取ります。これらのAPIを使用して、クラスタに対して生成されたイベントを表示し、解決および更新できます。

APIのメソッドを `/management-server/events`実行すると、 `GET`履歴データを含むデータセンター内のイベントを照会できます。組み込みのフィルタ（名前、影響レベル、影響領域、重大度、状態、リソース名、リソースタイプなど）を使用して、特定のイベントを表示します。リソースタイプと領域のパラメータはイベントが発生したストレージオブジェクトに関する情報を返し、影響領域はイベントが発生した問題に関する情報（可用性、容量、構成、セキュリティ、保護、パフォーマンスなど）を返します。

このAPIに対してPATCH処理を実行することで、イベントの解決ワークフローを有効にすることができます。自分または別のユーザにイベントを割り当てて、イベントの受信を確認することができます。イベントをトリガーした問題を解決するための手順をリソースに対して実行すると、このAPIを使用してイベントを解決済みとしてマークできます。

イベントの詳細については、を参照してくださいlink:../events/concept_manage_events.html["イベントの管理"]。

[cols="4*"]
|===
| カテゴリ | HTTP動詞 | パス | 製品説明 


 a| 
management-server
 a| 
取得
 a| 
`/management-server/events`
`/management-server/events/{key}`
 a| 
GET ALLメソッドを実行すると、応答の本文はデータセンター内のすべてのイベントの詳細で構成されます。特定のキーでイベントの詳細を取得すると、特定のイベントの詳細を表示し、リソースに対して次の一連の処理を実行できます。応答の本文は、そのイベントの詳細で構成されます。



 a| 
management-server
 a| 
パッチ
 a| 
`management-server/events/{key}`
 a| 
このAPIを実行してイベントを割り当てるか、状態をacknowledgedまたはresolvedに変更します。このメソッドを使用して、自分または別のユーザにイベントを割り当てることもできます。これは同期処理です。

|===


== アラートの管理

イベントは自動的かつ継続的に生成されます。Unified Managerでは、イベントが特定のフィルタ条件を満たしている場合にのみアラートが生成されます。アラートを生成するイベントを選択できます。APIを使用する `/management-server/alerts`と、特定のイベントまたは特定の重大度タイプのイベントが発生したときに自動的に通知を送信するようにアラートを設定できます。

アラートの詳細については、を参照してくださいlink:../events/concept_manage_alerts.html["アラートの管理"]。

[cols="4*"]
|===
| カテゴリ | HTTP動詞 | パス | 製品説明 


 a| 
management-server
 a| 
取得
 a| 
`/management-server/alerts`
`/management-server/alerts/{key}`
 a| 
alertキーを使用して、環境内の既存のすべてのアラートまたは特定のアラートを照会します。アラートの説明、アクション、通知の送信先EメールID、イベントや重大度など、環境で生成されたアラートに関する情報を確認できます。



 a| 
management-server
 a| 
投稿
 a| 
`/management-server/alerts`
 a| 
このメソッドを使用すると、特定のイベントのアラートを追加できます。アラート名、アラートを適用する物理リソースまたは論理リソース、またはイベント、アラートが有効になっているかどうか、SNMPトラップを発行しているかどうかを追加する必要があります。アクション、通知EメールID、スクリプトの詳細、アラートスクリプトを追加する場合のスクリプトの詳細など、アラートを生成する詳細を追加できます。



 a| 
management-server
 a| 
パッチと削除
 a| 
`management-server/events/{key}`
 a| 
これらのメソッドを使用して、特定のアラートを変更および削除できます。説明や名前、アラートの有効化と無効化など、さまざまな属性を変更できます。不要になったアラートを削除できます。

|===

NOTE: アラートを追加するリソースを選択する際に、リソースとしてクラスタを選択しても、そのクラスタ内のストレージオブジェクトは自動的には選択されないことに注意してください。たとえば、すべてのクラスタのすべての重大イベントに対するアラートを作成すると、クラスタの重大イベントに対するアラートのみが送信されます。ノードやアグリゲートなどの重大イベントに対するアラートは受信しません。



== スクリプトの管理

APIを使用する `/management-server/scripts`と、アラートがトリガーされたときに実行されるスクリプトにアラートを関連付けることもできます。Unified Manager で複数のストレージオブジェクトを自動的に変更または更新するスクリプトを作成することができます。スクリプトはアラートに関連付けられます。イベントによってアラートがトリガーされると、スクリプトが実行されます。カスタムスクリプトをアップロードし、アラートが生成されたときの実行をテストすることができます。Unified Managerでイベントに対してアラートが生成されたときにスクリプトが実行されるように、スクリプトにアラートを関連付けることができます。

スクリプトの詳細については、を参照してくださいlink:../events/concept_manage_scripts.html["スクリプトの管理"]。

[cols="4*"]
|===
| カテゴリ | HTTP動詞 | パス | 製品説明 


 a| 
management-server
 a| 
取得
 a| 
`/management-server/scripts`
 a| 
このAPIを使用して、環境内のすべての既存スクリプトを照会します。特定のスクリプトのみを表示するには、標準のフィルタおよび順序指定操作を使用します。



 a| 
management-server
 a| 
投稿
 a| 
`/management-server/scripts`
 a| 
このAPIを使用して、スクリプトの説明を追加し、アラートに関連付けられているスクリプトファイルをアップロードします。

|===