---
permalink: api-automation/concept_security_apis.html 
sidebar: sidebar 
keywords: manage, user 
summary: セキュリティカテゴリの API を使用して、 Active IQ Unified Manager 内の選択したクラスタオブジェクトへのユーザアクセスを制御できます。ローカルユーザまたはデータベースユーザを追加できます。認証サーバに属するリモートユーザやリモートグループを追加することもできます。ユーザに割り当てたロールのPrivilegesに基づいて、ストレージオブジェクトを管理したり、Unified Managerでデータを表示したりできます。 
---
= APIを使用したユーザの管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
カテゴリのAPIを使用して、Active IQ Unified Managerで選択したクラスタオブジェクトへのユーザアクセスを制御できます `security`。ローカルユーザまたはデータベースユーザを追加できます。認証サーバに属するリモートユーザやリモートグループを追加することもできます。ユーザに割り当てたロールのPrivilegesに基づいて、ストレージオブジェクトを管理したり、Unified Managerでデータを表示したりできます。

[NOTE]
====
これらの処理を実行するには、アプリケーション管理者ロールが必要です。これらの設定は、Unified Manager Web UIを使用して行うこともできます。

====
カテゴリのAPI `security`では、ユーザエンティティの一意の識別子としてキーパラメータではなく、usersパラメータ（ユーザ名）を使用します。

[cols="3*"]
|===
| HTTP動詞 | パス | 製品説明 


 a| 
`GET`

`POST`
 a| 
`/security/users`

`/security/users`
 a| 
これらのメソッドを使用して、ユーザの詳細を取得したり、Unified Managerに新しいユーザを追加したりできます。

ユーザのタイプに基づいて、ユーザに特定のロールを追加できます。ユーザを追加する際には、ローカルユーザ、メンテナンスユーザ、およびデータベースユーザのパスワードを指定する必要があります。



 a| 
`GET`

`PATCH`

`DELETE`
 a| 
`/security/users/\{name}`
 a| 
getメソッドを使用すると、名前、Eメールアドレス、ロール、認証タイプなど、ユーザのすべての詳細を取得できます。patchメソッドを使用すると、詳細を更新できます。deleteメソッドを使用すると、ユーザを削除できます。

|===