---
permalink: api-automation/concept_manage_lun.html 
sidebar: sidebar 
keywords: manage, lun 
summary: /storage-provider/LUNs API を使用して、データセンター環境の LUN を表示、追加、変更、および削除できます。 
---
= APIを使用したLUNの管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
APIを使用して、データセンター環境のLUNを表示、追加、変更、削除できます `/storage-provider/luns`。

LUNをプロビジョニングする前に、SVMが作成され、サポートされるプロトコルでプロビジョニングされていることを確認してください。パフォーマンスサービスレベル（PSL）またはストレージ効率化ポリシー（SEP）を割り当てる場合は、プロビジョニング時にLUNを作成する前にPSLまたはSEPを作成する必要があります。



== LUNの表示

Unified Manager環境では、次のメソッドを使用してLUNを表示できます。Active IQ Unified Manager のデータソースとして ONTAP クラスタを追加すると、それらのクラスタのストレージワークロードが Unified Manager インスタンスに自動的に追加されます。このAPIは、Unified Managerインスタンスに自動および手動で追加されたすべてのLUNを取得します。特定のLUNの詳細を表示するには、LUNキーを指定してこのAPIを実行します。

[cols="3*"]
|===
| カテゴリ | HTTP動詞 | パス 


 a| 
ストレージプロバイダ
 a| 
取得
 a| 
`/storage-provider/luns`

`/storage-provider/luns/\{key}`

|===


== LUNの追加

SVMにLUNを追加するには、次のメソッドを使用します。

[cols="3*"]
|===
| カテゴリ | HTTP動詞 | パス 


 a| 
ストレージプロバイダ
 a| 
投稿
 a| 
`/storage-provider/luns`

|===
[NOTE]
====
cURL要求で、オプションのパラメータvolume_name_tagの値を入力に指定すると、その値がLUNの作成時にボリュームの命名に使用されます。このタグを使用すると、ボリュームを簡単に検索できます。要求にボリュームキーを指定した場合、タギングはスキップされます。

====


== LUNの削除

特定のLUNを削除するには、次のメソッドを使用します。特定のLUNを削除するには、LUNキーを指定する必要があります。

[NOTE]
====
ONTAP でボリュームを作成し、そのボリュームで Unified Manager を使用して LUN をプロビジョニングした場合、この API を使用してすべての LUN を削除すると、ボリュームも ONTAP クラスタから削除されます。

====
[cols="3*"]
|===
| カテゴリ | HTTP動詞 | パス 


 a| 
ストレージプロバイダ
 a| 
削除
 a| 
`/storage-provider/luns/\{key}`

|===


== LUNの変更

LUNを変更し、そのプロパティを更新するには、次のメソッドを使用します。特定のLUNを変更するには、LUNキーを指定する必要があります。また、更新するLUNプロパティとその値を入力する必要があります。この API を使用して LUN アレイを更新する場合は ' API の使用に関する推奨事項を確認する必要があります

[NOTE]
====
このAPIの1回の呼び出しで更新できるプロパティは1つだけです。複数の更新を行う場合は、このAPIを何度も実行する必要があります。

====
|===


| カテゴリ | HTTP動詞 | パス 


 a| 
ストレージプロバイダ
 a| 
パッチ
 a| 
`/storage-provider/luns/\{key}`

|===