---
permalink: api-automation/concept_rest_api_access_and_authentication_in_um_apis.html 
sidebar: sidebar 
keywords: rest api, access, authentication, active iq, unified, manager 
summary: Active IQ Unified Manager REST API には、問題 HTTP 要求を実行できる任意の Web ブラウザまたはプログラミングプラットフォームを使用してアクセスできます。Unified Manager は、基本的な HTTP 認証メカニズムをサポートしています。Unified Manager REST API を呼び出す前に、ユーザを認証する必要があります。 
---
= Active IQ Unified ManagerでのREST APIアクセスと認証
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager REST APIには、基本的なHTTP認証メカニズムを使用してHTTP要求を発行できるRESTクライアントまたはプログラミングプラットフォームを使用してアクセスできます。

要求と応答の例：

* * リクエスト *
+
[listing]
----
GET
https://<IP address/hostname>:<port_number>/api/v2/datacenter/cluster/clusters
----
* * 応答 *
+
[listing]
----
{
  "records": [
    {
      "key": "4c6bf721-2e3f-11e9-a3e2-00a0985badbb:type=cluster,uuid=4c6bf721-2e3f-11e9-a3e2-00a0985badbb",
      "name": "fas8040-206-21",
      "uuid": "4c6bf721-2e3f-11e9-a3e2-00a0985badbb",
      "contact": null,
      "location": null,
      "version": {
        "full": "NetApp Release Dayblazer__9.5.0: Thu Jan 17 10:28:33 UTC 2019",
        "generation": 9,
        "major": 5,
        "minor": 0
      },
      "isSanOptimized": false,
      "management_ip": "10.226.207.25",
      "nodes": [
        {
          "key": "4c6bf721-2e3f-11e9-a3e2-00a0985badbb:type=cluster_node,uuid=12cf06cc-2e3a-11e9-b9b4-00a0985badbb",
          "uuid": "12cf06cc-2e3a-11e9-b9b4-00a0985badbb",
          "name": "fas8040-206-21-01",
          "_links": {
            "self": {
              "href": "/api/datacenter/cluster/nodes/4c6bf721-2e3f-11e9-a3e2-00a0985badbb:type=cluster_node,uuid=12cf06cc-2e3a-11e9-b9b4-00a0985badbb"
            }
          },
          "location": null,
          "version": {
            "full": "NetApp Release Dayblazer__9.5.0: Thu Jan 17 10:28:33 UTC 2019",
            "generation": 9,
            "major": 5,
            "minor": 0
          },
          "model": "FAS8040",
          "uptime": 13924095,
          "serial_number": "701424000157"
        },
        {
          "key": "4c6bf721-2e3f-11e9-a3e2-00a0985badbb:type=cluster_node,uuid=1ed606ed-2e3a-11e9-a270-00a0985bb9b7",
          "uuid": "1ed606ed-2e3a-11e9-a270-00a0985bb9b7",
          "name": "fas8040-206-21-02",
          "_links": {
            "self": {
              "href": "/api/datacenter/cluster/nodes/4c6bf721-2e3f-11e9-a3e2-00a0985badbb:type=cluster_node,uuid=1ed606ed-2e3a-11e9-a270-00a0985bb9b7"
            }
          },
          "location": null,
          "version": {
            "full": "NetApp Release Dayblazer__9.5.0: Thu Jan 17 10:28:33 UTC 2019",
            "generation": 9,
            "major": 5,
            "minor": 0
          },
          "model": "FAS8040",
          "uptime": 14012386,
          "serial_number": "701424000564"
        }
      ],
      "_links": {
        "self": {
          "href": "/api/datacenter/cluster/clusters/4c6bf721-2e3f-11e9-a3e2-00a0985badbb:type=cluster,uuid=4c6bf721-2e3f-11e9-a3e2-00a0985badbb"
        }
      }
    },
----
+
** `_IP address/hostname_`は、APIサーバのIPアドレスまたは完全修飾ドメイン名（FQDN）です。
** ポート443
+
デフォルトのHTTPSポートは443です。必要に応じて、HTTPSポートをカスタマイズできます。



+
WebブラウザからHTTP要求を発行するには、REST APIブラウザプラグインを使用する必要があります。cURLやPerlなどのスクリプトプラットフォームを使用してREST APIにアクセスすることもできます。





== 認証

Unified Managerでは、APIのベーシックHTTP認証方式がサポートされています。情報のフロー（要求と応答）を保護するために、REST APIにはHTTPS経由でのみアクセスできます。APIサーバは、サーバ検証のためにすべてのクライアントに自己署名SSL証明書を提供します。この証明書は、カスタム証明書（CA証明書）に置き換えることができます。

REST APIを呼び出すには、APIサーバへのユーザアクセスを設定する必要があります。ユーザには、ローカルユーザ（ローカルデータベースに格納されているユーザプロファイル）またはLDAPユーザ（LDAP経由で認証するようにAPIサーバを設定している場合）を指定できます。Unified Manager Administration Consoleのユーザインターフェイスにログインして、ユーザアクセスを管理できます。
