---
permalink: api-automation/concept_workflow_intro.html 
sidebar: sidebar 
keywords: common, workflows, storage, management 
summary: 一般的なワークフローでは、クライアントアプリケーション開発者がクライアントアプリケーションからActive IQ Unified Manager APIを呼び出して一般的なストレージ管理機能を実行する方法の例を紹介します。ここでは、いくつかのサンプルワークフローについて説明します。 
---
= ストレージ管理のための一般的なAPIワークフロー
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
一般的なワークフローでは、クライアントアプリケーション開発者がクライアントアプリケーションからActive IQ Unified Manager APIを呼び出して一般的なストレージ管理機能を実行する方法の例を紹介します。ここでは、いくつかのサンプルワークフローについて説明します。

以下のワークフローでは、ストレージ管理でよく使用されるいくつかのユースケースとサンプルコードについて説明します。各タスクについて、 1 つ以上の API 呼び出しで構成されるワークフロープロセスを使用して説明します。



== ワークフローで使用されるAPI呼び出しの概要

Unified Manager インスタンスから、すべての REST API 呼び出しの詳細を含むオンラインドキュメントページを表示できます。このドキュメントでは、オンラインドキュメントの詳細については説明しません。このドキュメントのワークフローサンプルで使用されている各API呼び出しには、ドキュメントページで呼び出しを検索するために必要な情報のみが含まれています。特定のAPI呼び出しを検索したら、入力パラメータ、出力形式、HTTPステータスコード、要求処理タイプなど、呼び出しのすべての詳細を確認できます。

ワークフロー内の各API呼び出しについて、ドキュメントページで呼び出しを見つけるのに役立つ次の情報が含まれています。

* カテゴリ：ドキュメントページでは、機能的な関連領域またはカテゴリ別に API 呼び出しが分類されています。特定のAPI呼び出しを検索するには、ページの一番下までスクロールし、該当するAPIカテゴリをクリックします。
* HTTP 動詞（呼び出し）： HTTP 動詞は、リソースに対して実行する操作を示します。各API呼び出しは、単一のHTTP動詞を使用して実行されます。
* パス：このパスは、呼び出しの実行中に環境が処理する特定のリソースを指定します。パス文字列がコアURLに追加され、リソースを識別する完全なURLが形成されます。

