---
permalink: api-automation/concept_rest_services_offered_in_unified_manager_apis.html 
sidebar: sidebar 
keywords: rest, services, offer, active iq, unified, manager 
summary: Active IQ Unified Manager API の使用を開始する前に、提供される REST サービスと処理について理解しておく必要があります。 
---
= Active IQ Unified Manager で提供される REST サービス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager API の使用を開始する前に、提供される REST サービスと処理について理解しておく必要があります。

APIサーバの設定に使用されるプロビジョニングAPIと管理APIでは、読み取り（GET）処理または書き込み（POST、PATCH、DELETE）処理がサポートされます。APIでサポートされるGET、PATCH、POST、DELETEの各処理の例を次に示します。

* GETの例： `GET /datacenter/cluster/clusters`は、データセンター内のクラスタの詳細を取得します。操作によって返されるレコードの最大数 `GET`は1000です。
+
[NOTE]
====
APIを使用すると、サポートされている属性に基づいてレコードをフィルタリング、ソート、および順序付けできます。

====
* POSTの例：は、 `POST /datacenter/svm/svms`カスタムのStorage Virtual Machine（SVM）を作成します。
* PATCHの例：は、 `PATCH /datacenter/svm/svms/{key}`一意のキーを使用してSVMのプロパティを変更します。
* DELETEの例：は `DELETE /storage-provider/access-endpoints/{key}`、一意のキーを使用して、LUN、SVM、またはファイル共有からアクセスエンドポイントを削除します。


APIを使用して実行できるREST処理は、オペレータ、ストレージ管理者、またはアプリケーション管理者のユーザロールによって異なります。

[cols="2*"]
|===
| ユーザロール | サポートされている REST メソッド 


 a| 
運用者
 a| 
データへの読み取り専用アクセス。このロールのユーザは、すべてのGET要求を実行できます。



 a| 
ストレージ管理者
 a| 
すべてのデータへの読み取りアクセス。このロールのユーザは、すべてのGET要求を実行できます。

また、管理、ストレージサービスオブジェクト、ストレージ管理オプションなどの特定のアクティビティを実行するための書き込みアクセス（PATCH、POST、DELETE要求を実行するため）があります。



 a| 
アプリケーション管理者
 a| 
すべてのデータへの読み取りおよび書き込みアクセス。このロールのユーザは、すべての機能に対してGET、PATCH、POST、DELETEの各要求を実行できます。

|===
すべての REST 処理の詳細については、 _ オンラインの API ドキュメントを参照してください。
