---
permalink: api-automation/concept_gateway_apis.html 
sidebar: sidebar 
keywords: access, ONTAP, APIs, proxy, access 
summary: ゲートウェイAPIには、Active IQ Unified Managerクレデンシャルを使用してONTAP REST APIを実行したり、ストレージオブジェクトを管理したりできるという利点があります。これらのAPIは、Unified Manager Web UIからAPIゲートウェイ機能を有効にした場合に使用できます。 
---
= プロキシアクセスによるONTAP APIへのアクセス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ゲートウェイAPIには、Active IQ Unified Managerクレデンシャルを使用してONTAP REST APIを実行したり、ストレージオブジェクトを管理したりできるという利点があります。これらのAPIは、Unified Manager Web UIからAPIゲートウェイ機能を有効にした場合に使用できます。

Unified Manager REST APIでは、Unified Managerデータソース（ONTAPクラスタ）に対して実行される一連の操作のみがサポートされます。その他の機能は、ONTAP APIを使用して利用できます。ゲートウェイAPIを使用すると、Unified Managerをパススルーインターフェイスとして使用して、Unified Managerが管理するONTAPクラスタで実行されるすべてのAPI要求をトンネリングできます。各データセンタークラスタに個別にログインする必要はありません。Unified Managerインスタンスで管理されるONTAPクラスタ間でAPIを実行するための単一の管理ポイントとして機能します。APIゲートウェイ機能を使用すると、Unified Managerを単一のコントロールプレーンとして使用して、複数のONTAPクラスタに個別にログインすることなく管理できます。ゲートウェイAPIを使用すると、ONTAP REST API処理を実行してUnified ManagerにログインしたままONTAPクラスタを管理できます。

[NOTE]
====
すべてのユーザがGET処理を使用してクエリを実行できます。アプリケーション管理者は、ONTAP RESTのすべての処理を実行できます。

====
ゲートウェイは、ヘッダーと本文の要求をONTAP APIと同じ形式で維持することで、API要求をトンネリングするプロキシとして機能します。Unified Managerのクレデンシャルを使用して特定の処理を実行すると、個 々 のクラスタのクレデンシャルを渡すことなくONTAPクラスタにアクセスして管理できます。クラスタ認証とクラスタ管理は引き続き管理されますが、API要求は特定のクラスタで直接実行されるようにリダイレクトされます。APIから返される応答は、ONTAPから直接実行された対応するONTAP REST APIから返される応答と同じです。

[cols="3*"]
|===
| HTTP動詞 | パス（ URL ） | 製品説明 


 a| 
`GET`
 a| 
`/gateways`
 a| 
このGETメソッドは、ONTAP REST呼び出しをサポートするUnified Managerで管理されているすべてのクラスタのリストを取得します。クラスタの詳細を確認し、クラスタUUIDまたはUniversal Unique Identifier（UUID）に基づいて他の方法を実行するように選択できます。

[NOTE]
====
ゲートウェイAPIは、ONTAP 9 .5以降でサポートされていて、HTTPS経由でUnified Managerに追加されたクラスタのみを取得します。

====


 a| 
`GET`

`POST`

`DELETE`

`PATCH`

`OPTIONS`（Swaggerでは使用できません）

`HEAD`（Swaggerでは使用できません）
 a| 
`/gateways/\{uuid}/\{path}`

[NOTE]
====
「 ｛ uuid ｝ 」の値を、 REST 処理を実行するクラスタ UUID に置き換える必要があります。また、ONTAP 9 .5以降でサポートされているクラスタのUUIDで、HTTPS経由でUnified Managerに追加されていることを確認してください。\｛ path ｝ を ONTAP REST URL に置き換える必要があります。URLからを削除する必要があり `/api/`ます。

==== a| 
これはシングルポイントプロキシAPIであり、すべてのONTAP REST APIでPOST、DELETE、PATCH操作、GETをサポートしています。ONTAPでサポートされている限り、どのAPIにも制限はありません。トンネリング機能またはプロキシ機能はディセーブルにできません。

 `OPTIONS`メソッドは、ONTAP REST APIでサポートされるすべての処理を返します。たとえば、ONTAP APIが処理のみをサポートしている場合 `GET`は、このゲートウェイAPIを使用してメソッドを実行すると、 `OPTIONS`が応答として返されます `GET`。このメソッドはSwaggerではサポートされていませんが、他のAPIツールでも実行できます。

メソッドは、 `OPTIONS`リソースが使用可能かどうかを判断します。この処理を使用すると、HTTP応答ヘッダー内のリソースに関するメタデータを表示できます。このメソッドはSwaggerではサポートされていませんが、他のAPIツールでも実行できます。

|===


== APIゲートウェイトンネリングの概要

ゲートウェイAPIを使用すると、Unified ManagerでONTAPオブジェクトを管理できます。Unified Managerは、クラスタと認証の詳細を管理し、要求をONTAP RESTエンドポイントにリダイレクトします。ゲートウェイAPIは、ヘッダーと応答の本文にあるアプリケーション状態のエンジン(HATEOAS)リンクとしてURLとHypermediaをAPIゲートウェイベースURLで変換します。ゲートウェイAPIは、ONTAP REST URLを追加して必要なONTAP RESTエンドポイントを実行するプロキシベースURLとして機能します。


NOTE: APIゲートウェイ経由でONTAP APIを正常に実行するには、APIが実行されているONTAPクラスタのバージョンでサポートされている必要があります。ONTAPクラスタでサポートされていないAPIを実行しても結果は返されません。

この例では、ゲートウェイAPI（プロキシベースURL）は次のとおりです。 `+/gateways/{uuid}/+`

取得されるONTAP APIは次のとおりです。 `/storage/volumes`PATHパラメータの値としてONTAP API REST URLを追加する必要があります。

[NOTE]
====
パスを追加する際には、"`add/`" symbol at the beginning of the URL. For the API `/storage/volumes,` `storage/volumes.`

====
追加されるURLは次のとおりです。 `+/gateways/{uuid}/storage/volumes+`

処理の実行時に `GET`生成されるURLは次のとおりです。 `GEThttps://<hostname\>/api/gateways/<cluster_UUID\>/storage/volumes`

 `/api`ONTAP REST URLのタグは追加されたURLから削除され、ゲートウェイAPIのタグは保持されます。

* cURL コマンドの例 *

[listing]
----
curl -X GET "https://<hostname>/api/gateways/1cd8a442-86d1-11e0-ae1c-9876567890123/storage/volumes" -H "accept: application/hal+json" -H "Authorization: Basic <Base64EncodedCredentials>"
----
APIは、そのクラスタ内のストレージボリュームのリストを返します。応答形式は、ONTAPから同じAPIを実行したときに受け取る形式と同じです。返されるステータスコードは、ONTAP RESTステータスコードです。



== APIスコープノセッテイ

すべてのAPIには、クラスタのスコープ内にコンテキストが設定されています。Storage VMを基に動作するAPIには、スコープとしてクラスタも含まれます。つまり、API処理は管理対象クラスタ内の特定のStorage VMに対して実行されます。APIを実行するときは `/gateways/\{uuid}/\{path}`、処理を実行するクラスタのクラスタUUID（Unified ManagerデータソースUUID）を入力してください。クラスタ内の特定のStorage VMにコンテキストを設定するには、X-Dot-svm-UUIDパラメータにStorage VMキーを入力するか、X-Dot-svm-NameパラメータにStorage VM名を入力します。パラメータが文字列ヘッダーにフィルタとして追加され、そのクラスタ内のそのStorage VMの範囲内で処理が実行されます。

* cURL コマンドの例 *

[listing]
----
curl -X GET "https://<hostname>/api/gateways/e4f33f90-f75f-11e8-9ed9-00a098e3215f/storage/volume" -H "accept: application/hal+json" -H "X-Dot-SVM-UUID: d9c33ec0-5b61-11e9-8760-00a098e3215f"
-H "Authorization: Basic <Base64EncodedCredentials>"
----
ONTAP REST APIの使用の詳細については、を参照してください。https://docs.netapp.com/us-en/ontap-automation/index.html["ONTAP REST API自動化"]
