---
permalink: api-automation/concept_metrics_apis.html 
sidebar: sidebar 
keywords: view, performance, metrics 
summary: Active IQ Unified Manager には、データセンターカテゴリ下の一連の API が用意されており、データセンター内のクラスタおよびストレージオブジェクトのパフォーマンスデータを表示できます。これらの API は、クラスタ、ノード、 LUN 、ボリュームなどのさまざまなストレージオブジェクトのパフォーマンスデータを取得します。 アグリゲート、 Storage VM 
---
= APIを使用したパフォーマンス指標の表示
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Managerには、カテゴリの一連のAPIが用意されています。このAPIを `/datacenter`使用して、データセンター内のクラスタおよびストレージオブジェクトのパフォーマンスデータを表示できます。これらのAPIは、クラスタ、ノード、LUN、ボリューム、アグリゲート、Storage VM、FCインターフェイス、FCポート、イーサネットポート、IPインターフェイスなど、さまざまなストレージオブジェクトのパフォーマンスデータを取得します。

 `/metrics`APIと `/analytics`APIでは、パフォーマンス指標がさまざまに表示されます。これを使用すると、データセンター内の次のストレージオブジェクトについて、さまざまなレベルの詳細にドリルダウンできます。

* クラスタ
* ノード
* Storage VM
* アグリゲート
* ボリューム
* LUN
* FCインターフェイス
* FCポート
* イーサネットポート
* IPインターフェイス


次の表に、取得したパフォーマンスデータの詳細に関するAPIと `/analytics`APIの比較を示します `/metrics`。

[cols="2*"]
|===
| 指標 | 分析 


 a| 
単一オブジェクトのパフォーマンスの詳細。たとえば、APIで `/datacenter/cluster/clusters/\{key}/metrics`は、その特定のクラスタの指標を取得するためのパスパラメータとしてclusterキーを入力する必要があります。
 a| 
データセンター内の同じタイプの複数のオブジェクトのパフォーマンスの詳細。たとえば、 `/datacenter/cluster/clusters/analytics`APIはデータセンター内のすべてのクラスタの総合的な指標を取得します。



 a| 
読み出しの時間間隔パラメータに基づく、ストレージオブジェクトのパフォーマンス指標のサンプル。
 a| 
特定のタイプのストレージオブジェクトの一定期間（72時間以上）のパフォーマンスの集計値の概要。



 a| 
オブジェクトの基本的な詳細（ノードやクラスタの詳細など）が読み出されます。
 a| 
特定の詳細は取得されません。



 a| 
1つのオブジェクトについて、最小値、最大値、95パーセンタイル値、一定期間の平均パフォーマンス値などの累積カウンタ（読み取り、書き込み、合計、その他のカウンタなど）が読み出されます。
 a| 
同じタイプのすべてのオブジェクトについて、集約された単一の値が表示されます。



 a| 
時間範囲とサンプルデータは、次のスケジュールに基づいています。データの時間範囲。例としては、1h、12h、1d、2d、3d、15d、1w、1m、2m、3m、6mがあります。範囲が3日（72時間）を超える場合は、1時間のサンプルが取得されます。それ以外の場合は、5分のサンプルが取得されます。各時間範囲の期間は次のとおりです。

* 1H ：直近 1 時間の測定値が 5 分以上にわたってサンプリングされます。
* 12 時間： 5 分以上にわたってサンプリングされた最新の 12 時間のメトリック。
* 1D ：直近の 1 日の測定値が 5 分以上にわたってサンプリングされます。
* 2D ：直近 2 日間の測定値が 5 分を超えてサンプリングされます。
* 3D ：直近 3 日間の測定値が 5 分を超えてサンプリングされます。
* 15D ： 1 時間にわたってサンプリングされた最新の 15 日間のメトリック。
* 1W ： 1 時間以上サンプリングされた最新の週のメトリック。
* 1M ：最近 1 時間でサンプリングされた月のメトリックス。
* 2M ：直近 2 カ月間の測定値が 1 時間以上にわたってサンプリングされます。
* 3M ：最近 3 カ月間の測定値が 1 時間以上サンプリングされています。
* 6M ：直近 6 カ月間の測定値が 1 時間以上にわたってサンプリングされます。
+
使用可能な値は、 1h 、 12h 、 1d 、 2d 、 3d です。 15D 、 1w 、 1m 、 2m 、 3m 、 6M

+
デフォルト値： 1h


 a| 
72時間以上。このサンプルが計算される期間は、ISO-8601標準形式で表されます。

|===


== 指標APIの出力例

たとえば、 `/datacenter/cluster/nodes/\{key}/metrics`APIは（特に）ノードについて次の詳細を取得します。


NOTE: 要約値の95パーセンタイルは、その期間に収集されたサンプルの95%が、95パーセンタイルとして指定された値よりも小さいカウンタ値を持っていることを示します。

[listing]
----
{
     "iops": {
       "local": {
         "other": 100.53,
         "read": 100.53,
         "total": 100.53,
         "write": 100.53
       },
       "other": 100.53,
       "read": 100.53,
       "total": 100.53,
       "write": 100.53
     },
     "latency": {
       "other": 100.53,
       "read": 100.53,
       "total": 100.53,
       "write": 100.53
     },
     "performance_capacity": {
       "available_iops_percent": 0,
       "free_percent": 0,
       "system_workload_percent": 0,
       "used_percent": 0,
       "user_workload_percent": 0
     },
     "throughput": {
       "other": 100.53,
       "read": 100.53,
       "total": 100.53,
       "write": 100.53
     },
     "timestamp": "2018-01-01T12:00:00-04:00",
     "utilization_percent": 0
   }
 ],
 "start_time": "2018-01-01T12:00:00-04:00",
 "summary": {
   "iops": {
     "local_iops": {
       "other": {
         "95th_percentile": 28,
         "avg": 28,
         "max": 28,
         "min": 5
       },
       "read": {
         "95th_percentile": 28,
         "avg": 28,
         "max": 28,
         "min": 5
       },
       "total": {
         "95th_percentile": 28,
         "avg": 28,
         "max": 28,
         "min": 5
       },
       "write": {
         "95th_percentile": 28,
         "avg": 28,
         "max": 28,
         "min": 5
       }
     },
----


== 分析APIの出力例

たとえば `/datacenter/cluster/nodes/analytics`、すべてのノードについて（とりわけ）次の値が取得されます。

[listing]
----
{     "iops": 1.7471,
     "latency": 60.0933,
     "throughput": 5548.4678,
     "utilization_percent": 4.8569,
     "period": 72,
     "performance_capacity": {
       "used_percent": 5.475,
       "available_iops_percent": 168350
     },
     "node": {
       "key": "37387241-8b57-11e9-8974-00a098e0219a:type=cluster_node,uuid=95f94e8d-8b4e-11e9-8974-00a098e0219a",
       "uuid": "95f94e8d-8b4e-11e9-8974-00a098e0219a",
       "name": "ocum-infinity-01",
       "_links": {
         "self": {
           "href": "/api/datacenter/cluster/nodes/37387241-8b57-11e9-8974-00a098e0219a:type=cluster_node,uuid=95f94e8d-8b4e-11e9-8974-00a098e0219a"
         }
       }
     },
     "cluster": {
       "key": "37387241-8b57-11e9-8974-00a098e0219a:type=cluster,uuid=37387241-8b57-11e9-8974-00a098e0219a",
       "uuid": "37387241-8b57-11e9-8974-00a098e0219a",
       "name": "ocum-infinity",
       "_links": {
         "self": {
           "href": "/api/datacenter/cluster/clusters/37387241-8b57-11e9-8974-00a098e0219a:type=cluster,uuid=37387241-8b57-11e9-8974-00a098e0219a"
         },
     "_links": {
       "self": {
         "href": "/api/datacenter/cluster/nodes/analytics"
       }
     }
   },
----


== 使用可能なAPIのリスト

次の表に、と `/analytics`のAPIの詳細を示し `/metrics`ます。

[NOTE]
====
これらのAPIから返されるIOPSとパフォーマンスの指標は、のように2倍の値です `100.53`。これらの浮動小数点値をパイプ（ | ）およびワイルドカード（ * ）文字でフィルタリングすることはできません。

====
[cols="3*"]
|===
| HTTP動詞 | パス | 製品説明 


 a| 
`GET`
 a| 
`/datacenter/cluster/clusters/\{key}/metrics`
 a| 
クラスタキーの入力パラメータで指定されたクラスタのパフォーマンスデータ（サンプルと概要）を取得します。クラスタキーとUUID、時間範囲、IOPS、スループット、サンプル数などの情報が返されます。



 a| 
`GET`
 a| 
`/datacenter/cluster/clusters/analytics`
 a| 
データセンター内のすべてのクラスタのパフォーマンス指標の概要を取得します。必要な条件に基づいて結果をフィルタリングできます。集計されたIOPS、スループット、収集期間（時間）などの値が返されます。



 a| 
`GET`
 a| 
`/datacenter/cluster/nodes/\{key}/metrics`
 a| 
ノードキーの入力パラメータで指定されたノードのパフォーマンスデータ（サンプルと概要）を取得します。ノードUUID、時間範囲、IOPS、スループット、レイテンシ、パフォーマンスの概要、収集されたサンプル数、使用率などの情報が返されます。



 a| 
`GET`
 a| 
`/datacenter/cluster/nodes/analytics`
 a| 
データセンター内のすべてのノードのパフォーマンス指標の概要を取得します。必要な条件に基づいて結果をフィルタリングできます。ノードキーやクラスタキーなどの情報と、IOPS、スループット、収集期間（時間数）などの値が返されます。



 a| 
`GET`
 a| 
`/datacenter/storage/aggregates/\{key}/metrics`
 a| 
アグリゲートキーの入力パラメータで指定されたアグリゲートのパフォーマンスデータ（サンプルと概要）を取得します。期間、IOPS、レイテンシ、スループット、パフォーマンス容量の概要、各カウンタで収集されたサンプル数、使用率などの情報が返されます。



 a| 
`GET`
 a| 
`/datacenter/storage/aggregates/analytics`
 a| 
データセンター内のすべてのアグリゲートのパフォーマンス指標の概要を取得します。必要な条件に基づいて結果をフィルタリングできます。アグリゲートキーやクラスタキーなどの情報と、IOPS、スループット、収集期間（時間数）などの値が返されます。



 a| 
`GET`
 a| 
`/datacenter/storage/luns/\{key}/metrics`

`/datacenter/storage/volumes/\{key}/metrics`
 a| 
LUNまたはボリュームキーの入力パラメータで指定されたLUNまたはファイル共有（ボリューム）のパフォーマンスデータ（サンプルと概要）を取得します。読み取り、書き込み、合計のIOPS、レイテンシ、スループットの最小値、最大値、平均値の概要、各カウンタで収集されたサンプル数などの情報が返されます。



 a| 
`GET`
 a| 
`/datacenter/storage/luns/analytics`

`/datacenter/storage/volumes/analytics`
 a| 
データセンター内のすべてのLUNまたはボリュームのパフォーマンス指標の概要を取得します。必要な条件に基づいて結果をフィルタリングできます。Storage VMやクラスタのキーなどの情報と、IOPS、スループット、収集期間（時間数）などの値が返されます。



 a| 
`GET`
 a| 
`/datacenter/svm/svms/{key}/metrics`
 a| 
Storage VMキーの入力パラメータで指定されたStorage VMのパフォーマンスデータ（サンプルと概要）を取得します。サポートされる各プロトコルに基づくIOPSの概要（や、 `nfs`スループット、レイテンシ、収集されたサンプル数など） `nvmf, fcp, iscsi,`が返されます。



 a| 
`GET`
 a| 
`/datacenter/svm/svms/analytics`
 a| 
データセンター内のすべてのStorage VMのパフォーマンス指標の概要を取得します。必要な条件に基づいて結果をフィルタリングできます。Storage VM UUID、集約IOPS、レイテンシ、スループット、収集期間（時間数）などの情報が返されます。



 a| 
`GET`
 a| 
`/datacenter/network/ethernet/ports/{key}/metrics`
 a| 
ポートキーの入力パラメータで指定された特定のイーサネットポートのパフォーマンス指標を取得します。サポートされている範囲から間隔（時間範囲）を指定すると、APIは一定期間のパフォーマンスの最小値、最大値、平均値などの累積カウンタを返します。



 a| 
`GET`
 a| 
`/datacenter/network/ethernet/ports/analytics`
 a| 
データセンター環境内のすべてのイーサネットポートについて、パフォーマンス指標の概要を取得します。クラスタとノードのキーとUUID、スループット、収集期間、ポートの利用率などの情報が返されます。ポートキー、利用率、クラスタとノードの名前とUUIDなど、使用可能なパラメータで結果をフィルタリングできます。



 a| 
`GET`
 a| 
`/datacenter/network/fc/interfaces/{key}/metrics`
 a| 
インターフェイスキーの入力パラメータで指定された特定のネットワークFCインターフェイスのパフォーマンス指標を取得します。サポートされている範囲から間隔（時間範囲）を指定すると、APIは一定期間のパフォーマンスの最小値、最大値、平均値などの累積カウンタを返します。



 a| 
`GET`
 a| 
`/datacenter/network/fc/interfaces/analytics`
 a| 
データセンター環境内のすべてのイーサネットポートについて、パフォーマンス指標の概要を取得します。クラスタとFCインターフェイスキーとUUID、スループット、IOPS、レイテンシ、Storage VMなどの情報が返されます。クラスタとFCインターフェイスの名前とUUID、Storage VM、スループットなど、使用可能なパラメータで結果をフィルタリングできます。



 a| 
`GET`
 a| 
`/datacenter/network/fc/ports/{key}/metrics`
 a| 
ポートキーの入力パラメータで指定された特定のFCポートのパフォーマンス指標を取得します。サポートされている範囲から間隔（時間範囲）を指定すると、APIは一定期間のパフォーマンスの最小値、最大値、平均値などの累積カウンタを返します。



 a| 
`GET`
 a| 
`/datacenter/network/fc/ports/analytics`
 a| 
データセンター環境内のすべてのFCポートについて、パフォーマンス指標の概要を取得します。クラスタとノードのキーとUUID、スループット、収集期間、ポートの利用率などの情報が返されます。ポートキー、利用率、クラスタとノードの名前とUUIDなど、使用可能なパラメータで結果をフィルタリングできます。



 a| 
`GET`
 a| 
`/datacenter/network/ip/interfaces/{key}/metrics`
 a| 
インターフェイスキーの入力パラメータで指定したネットワークIPインターフェイスのパフォーマンス指標を取得します。サポートされている範囲から間隔（時間範囲）を指定すると、サンプル数、累積カウンタ、スループット、送受信されたパケット数などの情報が返されます。



 a| 
`GET`
 a| 
`/datacenter/network/ip/interfaces/analytics`
 a| 
データセンター環境内のすべてのネットワークIPインターフェイスについて、パフォーマンス指標の概要を取得します。クラスタとIPインターフェイスキーとUUID、スループット、IOPS、レイテンシなどの情報が返されます。クラスタとIPインターフェイスの名前とUUID、IOPS、レイテンシ、スループットなど、使用可能なパラメータで結果をフィルタリングできます。

|===