---
permalink: api-automation/reference_recommendations_to_use_um_apis.html 
sidebar: sidebar 
keywords: recommendations, apis, active iq, unified, manager 
summary: Active IQ Unified Manager で API を使用するときは、特定の推奨される方法に従ってください。 
---
= Active IQ Unified Manager で API を使用する際の推奨事項です
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager で API を使用するときは、特定の推奨される方法に従ってください。

* 有効な実行を行うには、すべての応答コンテンツタイプが次の形式である必要があります。
+
[listing]
----
application/json
----
* APIのバージョン番号は製品のバージョン番号とは関係ありません。Unified Manager インスタンスで使用可能な最新バージョンの API を使用する必要があります。Unified Manager API のバージョンの詳細については、「 Active IQ Unified Manager での ST API のバージョン管理」を参照してください。
* Unified Manager APIを使用してアレイ値を更新する場合は、値の文字列全体を更新する必要があります。配列に値を付加することはできません。既存のアレイのみを交換できます。
* パイプ（ | ）やワイルドカード（ + * + ）などのフィルタ演算子をすべてのクエリパラメータに使用できます。ただし、指標 API の IOPS やパフォーマンスなど、二重値は除きます。
* フィルタ演算子のワイルドカード（ +*+ ）とパイプ（ | ）を組み合わせてオブジェクトを照会しないでください。間違った数のオブジェクトが取得される可能性があります。
* フィルタに値を使用する場合は、値に文字が含まれていないことを確認して `?`ください。これは、SQLインジェクションのリスクを軽減するためです。
* すべてのAPIの(all)要求は、最大1000レコードを返すことに注意してください `GET`。パラメータを1000より大きい値に設定してクエリを実行しても、 `max_records`1000レコードだけが返されます。
* 管理機能を実行する場合は、 Unified Manager UI を使用することを推奨します。

