---
permalink: api-automation/reference_authentication_errors.html 
sidebar: sidebar 
keywords: http, status, code, active iq, unified manager 
summary: API の実行時や問題のトラブルシューティング時には、 Active IQ Unified Manager API で使用されるさまざまな HTTP ステータスコードとエラーコードについて理解しておく必要があります。 
---
= Active IQ Unified Manager で使用される HTTP ステータスコード
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
API の実行時や問題のトラブルシューティング時には、 Active IQ Unified Manager API で使用されるさまざまな HTTP ステータスコードとエラーコードについて理解しておく必要があります。

次の表に、認証に関連するエラーコードを示します。

[cols="3*"]
|===
| HTTPステータスコード | ステータスコードタイトル | 製品説明 


 a| 
200
 a| 
OK
 a| 
同期API呼び出しの実行が成功した場合に返されます。



 a| 
201
 a| 
作成済み
 a| 
Active Directoryの設定など、同期呼び出しによる新しいリソースの作成。



 a| 
202
 a| 
承認済み
 a| 
LUNやファイル共有の作成など、プロビジョニング機能の非同期呼び出しが正常に実行された場合に返されます。



 a| 
400
 a| 
無効な要求
 a| 
入力検証に失敗したことを示します。ユーザは、要求の本文に有効なキーなど、入力を修正する必要があります。



 a| 
401
 a| 
未許可の要求
 a| 
リソースを表示する権限がありません/権限がありません。



 a| 
403
 a| 
禁止されている要求
 a| 
アクセスしようとしているリソースへのアクセスは禁止されています。



 a| 
404
 a| 
リソースが見つかりません
 a| 
アクセスしようとしていたリソースが見つかりません。



 a| 
405
 a| 
許可されていないメソッド
 a| 
許可されていないメソッドです。



 a| 
429
 a| 
要求が多すぎます
 a| 
ユーザが特定の時間内に大量の要求を送信した場合に返されます。



 a| 
500
 a| 
内部サーバエラー
 a| 
内部サーバエラー。サーバから応答を取得できませんでした。この内部サーバエラーは永続的な場合とそうでない場合があります。たとえば、処理または `GET ALL`処理を実行してこのエラーが表示された場合は `GET`、この処理を5回以上繰り返すことを推奨します。永続的なエラーの場合は、ステータスコード500が引き続き返されます。処理が成功すると、ステータスコード200が返されます。

|===