---
permalink: api-automation/task_modify_fileshare_to_include_cifs_and_nfs.html 
sidebar: sidebar 
keywords: modify, nfs, file, share, support, cifs 
summary: CIFSプロトコルをサポートするようにNFSファイル共有を変更できます。ファイル共有の作成時に、アクセス制御リスト（ACL）パラメータとエクスポートポリシールールの両方を同じファイル共有に指定できます。ただし、NFSファイル共有を作成したボリュームでCIFSを有効にする場合は、CIFSをサポートするようにそのファイル共有のACLパラメータを更新できます。 
---
= CIFSをサポートするためのAPIを使用したNFSファイル共有の変更
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
CIFSプロトコルをサポートするようにNFSファイル共有を変更できます。ファイル共有の作成時に、アクセス制御リスト（ACL）パラメータとエクスポートポリシールールの両方を同じファイル共有に指定できます。ただし、NFSファイル共有を作成したボリュームでCIFSを有効にする場合は、CIFSをサポートするようにそのファイル共有のACLパラメータを更新できます。

* 必要なもの *

. エクスポートポリシーの詳細のみを指定してNFSファイル共有を作成しておく必要があります。詳細については、「ファイル共有の管理」および「ストレージワークロードの変更」を参照してください。
. この処理を実行するには、ファイル共有キーが必要です。ファイル共有の詳細の表示とジョブ ID を使用したファイル共有キーの取得については、 _ CIFS および NFS ファイル共有のプロビジョニング _ を参照してください。


これは、ACLパラメータではなく、エクスポートポリシールールのみを追加して作成したNFSファイル共有に該当します。ACLパラメータを追加するようにNFSファイル共有を変更します。

.手順
. NFSファイル共有で、CIFSアクセスを許可するACLの詳細を指定して処理を実行し `PATCH`ます。
+
[cols="3*"]
|===
| カテゴリ | HTTP動詞 | パス 


 a| 
ストレージプロバイダ
 a| 
パッチ
 a| 
`/storage-provider/file-shares`

|===
+
* cURL の例 *

+
次の例に示すように、ユーザグループに割り当てたアクセスPrivilegesに基づいてACLが作成され、ファイル共有に割り当てられます。

+
[listing]
----
{
  "access_control": {
    "acl": [
      {
        "permission": "read",
        "user_or_group": "everyone"
      }
    ],
    "active_directory_mapping": {
      "key": "3b648c1b-d965-03b7-20da-61b791a6263c"
    }
----
+
* JSON 出力の例 *

+
更新を実行するジョブのジョブIDが返されます。

. 同じファイル共有に対して詳細を照会し、パラメータが正しく追加されているかどうかを確認します。
+
[cols="3*"]
|===
| カテゴリ | HTTP動詞 | パス 


 a| 
ストレージプロバイダ
 a| 
取得
 a| 
`/storage-provider/file-shares/\{key}`

|===
+
* JSON 出力の例 *

+
[listing]
----
"access_control": {
        "acl": [
            {
                "user_or_group": "everyone",
                "permission": "read"
            }
        ],
        "export_policy": {
            "id": 1460288880641,
            "key": "7d5a59b3-953a-11e8-8857-00a098dcc959:type=export_policy,uuid=1460288880641",
            "name": "default",
            "rules": [
                {
                    "anonymous_user": "65534",
                    "clients": [
                        {
                            "match": "0.0.0.0/0"
                        }
                    ],
                    "index": 1,
                    "protocols": [
                        "nfs3",
                        "nfs4"
                    ],
                    "ro_rule": [
                        "sys"
                    ],
                    "rw_rule": [
                        "sys"
                    ],
                    "superuser": [
                        "none"
                    ]
                },
                {
                    "anonymous_user": "65534",
                    "clients": [
                        {
                            "match": "0.0.0.0/0"
                        }
                    ],
                    "index": 2,
                    "protocols": [
                        "cifs"
                    ],
                    "ro_rule": [
                        "ntlm"
                    ],
                    "rw_rule": [
                        "ntlm"
                    ],
                    "superuser": [
                        "none"
                    ]
                }
            ],
            "_links": {
                "self": {
                    "href": "/api/datacenter/protocols/nfs/export-policies/7d5a59b3-953a-11e8-8857-00a098dcc959:type=export_policy,uuid=1460288880641"
                }
            }
        }
    },
    "_links": {
        "self": {
            "href": "/api/storage-provider/file-shares/7d5a59b3-953a-11e8-8857-00a098dcc959:type=volume,uuid=e581c23a-1037-11ea-ac5a-00a098dcc6b6"
        }
    }
----
+
同じファイル共有にエクスポートポリシーと一緒にACLが割り当てられていることを確認できます。


