---
permalink: reporting/concept_unified_manager_reporting.html 
sidebar: sidebar 
keywords: unified, manager, reporting 
summary: Active IQ Unified Manager （旧 OnCommand Unified Manager ）では、 ONTAP ストレージシステムのレポートを表示、カスタマイズ、ダウンロード、およびスケジュール設定できます。このレポートには、ストレージシステムの容量、健全性、パフォーマンス、保護関係に関する詳細が表示されます。 
---
= Unified Manager のレポート機能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager （旧 OnCommand Unified Manager ）では、 ONTAP ストレージシステムのレポートを表示、カスタマイズ、ダウンロード、およびスケジュール設定できます。このレポートには、ストレージシステムの容量、健全性、パフォーマンス、セキュリティ、保護関係に関する詳細が表示されます。

Active IQ Unified Manager 9.6 で導入された新しい Unified Manager レポート作成機能およびスケジュール設定機能は、 Unified Manager バージョン 9.5 で廃止された以前のレポート作成エンジンに代わるものです。

レポート機能は、ネットワークのさまざまなビューを提供し、容量、健全性、パフォーマンス、セキュリティ、保護データに関する実用的な情報を提供します。列の表示、非表示、再配置、データのフィルタリング、データのソート、結果の検索を行うことで、ビューをカスタマイズできます。カスタムビューを保存して再利用したり、レポートとしてダウンロードしたり、定期的なレポートとしてスケジュール設定してEメールで配信したりできます。

Microsoft®Excel形式のビューをダウンロードしてカスタマイズできます。複雑な並べ替え、レイヤーフィルター、ピボットテーブル、グラフなどの高度なExcel機能を使用できます。結果のExcelレポートに問題がなければ、レポートをスケジュールして共有するたびにExcelファイルをアップロードして使用できます。

ユーザインターフェイスからレポートを生成するだけでなく、次の方法を使用してUnified Managerから健全性、セキュリティ、パフォーマンスのデータを抽出することもできます。

* Open Database Connectivity（ODBC）およびODBCツールを使用してデータベースに直接アクセスし、クラスタ情報を取得する
* Unified Manager REST API を使用して確認したい情報を取得する


このリリースのActive IQ Unified Managerでは、レポートに次の機能拡張が加えられています。

* 設定したスケジュールに従ってレポートのEメールが送信されます。オンデマンドレポートを生成した場合でも、Eメールが送信されます。
* レポートのファイル名とメタデータには、レポートの生成元のホスト名が含まれます。ファイル名が変更された場合でも、この機能拡張によりレポートの生成元のホスト名を特定できます。

