---
permalink: reporting/reference_reporting_limitations.html 
sidebar: sidebar 
keywords: reporting, limitations 
summary: Active IQ Unified Manager の新しいレポート機能には、注意が必要な制限事項があります。 
---
= レポート機能の制限事項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager の新しいレポート機能には、注意が必要な制限事項があります。



== 以前のバージョンの Unified Manager で作成した既存のレポート

スケジュールと受信者を編集できるのは、Unified Manager 9.5以前のリリースで作成およびインポートされた既存のレポート（.rptdesignファイル）のみです。Unified Manager 9.5以前に付属の標準レポートをカスタマイズした場合、それらのカスタムレポートは新しいレポートツールにインポートされません。

.rptdesignファイルからインポートした既存のレポートを編集する必要がある場合は、次のいずれかの操作を行い、インポートしたレポートを削除します。

* 新しいビューを作成し、そのビューからレポートをスケジュールする（推奨）
* レポートにカーソルを合わせてSQLをコピーし、外部ツールを使用してデータを取得します。


デフォルトビューは、カスタマイズを必要とせずにレポートとして生成できます。新しいレポートソリューションを使用して、カスタムレポートを再作成できます。



== スケジュールとレポートの関係

保存したレポートごとに、受信者を任意に組み合わせて複数のスケジュールを作成できます。ただし、複数のレポートでスケジュールを再利用することはできません。



== レポートの保護

適切な権限を持つユーザは、レポートを編集または削除できます。保存したビューやスケジュールを他のユーザが削除または変更できないようにする方法はありません。



== イベントレポート

イベントビューをカスタマイズしてレポートをCSV形式でダウンロードすることはできますが、定期的なイベントレポートを生成して配信するようにスケジュールを設定することはできません。



== レポートの添付

レポートをEメールの本文として送信することはできません。代わりに、レポートはPDF、Excel、またはCSVの添付ファイルとしてのみ送信されます。
