---
permalink: performance-checker/concept_use_performance_capacity_used_counter.html 
sidebar: sidebar 
keywords: performance, capacity, counter, manage, performance 
summary: 通常、組織は、使用済みパフォーマンス容量の割合を100未満に抑えて、リソースを効率的に使用しながら、ピーク時の需要に対応するためにパフォーマンス容量を追加で確保したいと考えています。しきい値ポリシーを使用して、使用済みパフォーマンス容量の値が高い場合にアラートを送信するタイミングを設定できます。 
---
= [使用済みパフォーマンス容量]カウンタを使用したパフォーマンスの管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
通常、組織は、使用済みパフォーマンス容量の割合を100未満に抑えて、リソースを効率的に使用しながら、ピーク時の需要に対応するためにパフォーマンス容量を追加で確保したいと考えています。しきい値ポリシーを使用して、使用済みパフォーマンス容量の値が高い場合にアラートを送信するタイミングを設定できます。

パフォーマンス要件に基づいて具体的な目標を設定できます。たとえば、金融機関では、取り引きをタイミングよく実行するために、より多くのパフォーマンス容量を確保することが考えられます。このような企業では、使用済みパフォーマンス容量のしきい値を70~80%の範囲に設定する必要があります。マージンが小さい製造企業では、ITコストをより適切に管理するためにパフォーマンスを犠牲にしても構わない場合、確保するパフォーマンス容量を少なくすることを選択することがあります。このような企業では、使用済みパフォーマンス容量のしきい値を85~95%の範囲に設定する可能性があります。

使用済みパフォーマンス容量の値がユーザ定義のしきい値ポリシーで設定された割合を超えると、Unified ManagerはアラートEメールを送信し、[イベントインベントリ]ページにイベントを追加します。これにより、パフォーマンスに影響が及ぶ前に潜在的な問題に対処できます。これらのイベントは、ノードやアグリゲート内でワークロードの移動や変更を行う際に必要な指標としても使用できます。
