---
permalink: performance-checker/concept_sources_of_performance_events.html 
sidebar: sidebar 
keywords: sources, performance, events 
summary: パフォーマンスイベントは、クラスタでのワークロードパフォーマンスに関連する問題です。応答時間が長い（レイテンシが高い）ストレージオブジェクトを特定するのに役立ちます。同時に発生した他の健全性イベントと一緒に確認することで、応答時間の低下の原因となった、または原因となった問題を特定できます。 
---
= パフォーマンスイベントのソース
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
パフォーマンスイベントは、クラスタでのワークロードパフォーマンスに関連する問題です。応答時間が長い（レイテンシが高い）ストレージオブジェクトを特定するのに役立ちます。同時に発生した他の健全性イベントと一緒に確認することで、応答時間の低下の原因となった、または原因となった問題を特定できます。

Unified Manager は、次のソースからパフォーマンスイベントを受け取ります。

* * ユーザ定義のパフォーマンスしきい値ポリシーイベント *
+
独自に設定したしきい値に基づいたパフォーマンスの問題。アグリゲートやボリュームなどのストレージオブジェクトに対してパフォーマンスしきい値ポリシーを設定し、パフォーマンスカウンタのしきい値を超えたときにイベントが生成されるようにします。

+
これらのイベントを受け取るには、パフォーマンスしきい値ポリシーを定義してストレージオブジェクトに割り当てる必要があります。

* * システム定義のパフォーマンスしきい値ポリシーイベント *
+
システム定義のしきい値に基づいたパフォーマンスの問題。このしきい値ポリシーはUnified Managerに含まれており、一般的なパフォーマンスの問題に対処します。

+
このしきい値はデフォルトで有効化されており、クラスタの追加後すぐにイベントが生成される場合があります。

* * 動的なパフォーマンスしきい値イベント *
+
ITインフラの障害やエラー、またはクラスタリソースを過剰に消費しているワークロードに起因するパフォーマンスの問題。これらのイベントの原因は、時間が経つと修復される単純な問題や、修理や設定の変更によって解決できる単純な問題である可能性があります。動的しきい値イベントは、他のワークロードが共有のクラスタコンポーネントを利用していることが原因で、 ONTAP システムのワークロードの処理速度が低下した場合に生成されます。

+
これらのしきい値はデフォルトで有効になっており、新しいクラスタからデータを収集してから3日後にイベントが表示されることがあります。


