---
permalink: performance-checker/concept_performance_threshold_policies_when_object_is_moved.html 
sidebar: sidebar 
keywords: happens, performance, threshold, policies, object, moved 
summary: パフォーマンスしきい値ポリシーはストレージオブジェクトに割り当てられているため、オブジェクトを移動した場合、割り当てられているすべてのしきい値ポリシーが移動の完了後もオブジェクトに関連付けられたままになります。たとえば、ボリュームまたはLUNを別のアグリゲートに移動した場合でも、しきい値ポリシーは新しいアグリゲートのボリュームまたはLUNで引き続きアクティブです。 
---
= オブジェクトの移動によるパフォーマンスしきい値ポリシーへの影響
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
パフォーマンスしきい値ポリシーはストレージオブジェクトに割り当てられているため、オブジェクトを移動した場合、割り当てられているすべてのしきい値ポリシーが移動の完了後もオブジェクトに関連付けられたままになります。たとえば、ボリュームまたはLUNを別のアグリゲートに移動した場合でも、しきい値ポリシーは新しいアグリゲートのボリュームまたはLUNで引き続きアクティブです。

アグリゲートやノードに追加の条件が割り当てられている場合など、しきい値ポリシー（組み合わせポリシー）のセカンダリカウンタ条件が存在する場合は、ボリュームまたはLUNの移動先である新しいアグリゲートまたはノードにセカンダリカウンタ条件が適用されます。

変更されたしきい値ポリシーを使用しているオブジェクトに対して新しいアクティブなイベントが発生すると、イベントは廃止とマークされ、新たに定義されたしきい値ポリシーとしてカウンタの監視が開始されます。

ボリューム移動処理を実行すると、ONTAPは情報変更イベントを送信します。[パフォーマンスエクスプローラ]ページと[ワークロード分析]ページの[イベントタイムライン]に変更イベントアイコンが表示され、移動処理が完了した時刻が示されます。

[NOTE]
====
オブジェクトを別のクラスタに移動した場合、ユーザ定義のしきい値ポリシーはオブジェクトから削除されます。必要に応じて、移動処理の完了後にしきい値ポリシーをオブジェクトに割り当てる必要があります。ただし、動的なしきい値ポリシーとシステム定義のしきい値ポリシーは、新しいクラスタへの移動後にオブジェクトに自動的に適用されます。

====


== HAのテイクオーバーおよびギブバック時のしきい値ポリシーの機能

ハイアベイラビリティ（HA）構成でテイクオーバー処理やギブバック処理が発生した場合、1つのノードから別のノードに移動されたオブジェクトのしきい値ポリシーは、手動の移動処理と同じ方法で保持されます。Unified Manager ではクラスタの構成に変更がないかどうかを 15 分間隔でチェックするため、スイッチオーバーによる新しいノードへの影響は、クラスタの構成のポーリングが次に行われるときまで特定されません。

[NOTE]
====
15分間の設定変更の収集期間内にテイクオーバー処理とギブバック処理の両方が発生した場合、一方のノードからもう一方のノードへの移動に関するパフォーマンス統計が表示されないことがあります。

====


== アグリゲートの再配置時のしきい値ポリシーの機能

コマンドを使用してあるノードから別のノードにアグリゲートを移動した場合は `aggregate relocation start`、単一のしきい値ポリシーと組み合わせのしきい値ポリシーの両方がすべてのオブジェクトで保持され、しきい値ポリシーのノード部分が新しいノードに適用されます。



== MetroClusterスイッチオーバー時のしきい値ポリシーの機能

MetroCluster構成でクラスタ間を移動したオブジェクトの場合、ユーザ定義のしきい値ポリシーの設定は保持されません。必要に応じて、パートナークラスタに移動したボリュームとLUNにしきい値ポリシーを適用できます。オブジェクトが元のクラスタに戻ると、それらのユーザ定義のしきい値ポリシーが自動的に再適用されます。

詳細については、を参照してください link:../storage-mgmt/concept_volume_behavior_during_switchover_and_switchback.html["スイッチオーバーおよびスイッチバックの発生時のボリュームの動作"]。
