---
permalink: performance-checker/concept_performance_capacity_used_threshold_conditions.html 
sidebar: sidebar 
keywords: performance, capacity, threshold, conditions 
summary: ユーザ定義のパフォーマンスしきい値ポリシーを作成して、ノードまたはアグリゲートの使用済みパフォーマンス容量の値が定義されている使用済みパフォーマンス容量しきい値の設定を超えたときにイベントがトリガーされるようにすることができます。 
---
= 使用済みパフォーマンス容量のパフォーマンスしきい値条件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ユーザ定義のパフォーマンスしきい値ポリシーを作成して、ノードまたはアグリゲートの使用済みパフォーマンス容量の値が定義されている使用済みパフォーマンス容量しきい値の設定を超えたときにイベントがトリガーされるようにすることができます。

また、ノードには「 Performance capacity used takeover 」しきい値ポリシーを設定することもできます。このしきい値ポリシーは、 HA ペアの両方のノードの使用済みパフォーマンス容量の統計を合計して、一方のノードで障害が発生した場合にもう一方のノードの容量が不足するかどうかを判断します。フェイルオーバー中のワークロードは 2 つのパートナーノードのワークロードの組み合わせであるため、両方のノードに同じ使用済みパフォーマンス容量のテイクオーバーポリシーを適用できます。

[NOTE]
====
ノード間では、一般に使用済みパフォーマンス容量は同等になります。ただし、フェイルオーバーパートナー経由で一方のノードを宛先とするノード間トラフィックが大幅に多い場合は、一方のパートナーノードですべてのワークロードを実行したときともう一方のパートナーノードで実行したときの合計パフォーマンス容量は、障害が発生したノードによって多少異なる可能性があります。

====
LUNやボリュームのしきい値を定義する際に、使用済みパフォーマンス容量の条件をセカンダリパフォーマンスしきい値の設定として使用して組み合わせしきい値ポリシーを作成することもできます。使用済みパフォーマンス容量の条件は、ボリュームまたはLUNが配置されているアグリゲートまたはノードに適用されます。たとえば、次の条件を使用して組み合わせしきい値ポリシーを作成できます。

|===
| ストレージオブジェクト | パフォーマンスカウンタ | 警告しきい値 | 重大のしきい値 | 期間 


 a| 
ボリューム
 a| 
レイテンシ
 a| 
15ミリ秒/処理
 a| 
25ミリ秒/処理
 a| 
20分



 a| 
アグリゲート
 a| 
使用済みパフォーマンス容量
 a| 
80%
 a| 
95%
 a| 

|===
組み合わせしきい値ポリシーを使用すると、期間全体にわたって両方の条件に違反した場合にのみイベントが生成されます。
