---
permalink: performance-checker/concept_cluster_components_and_why_they_can_be_in_contention.html 
sidebar: sidebar 
keywords: cluster, components, why, contention 
summary: クラスタコンポーネントが競合状態になった場合のクラスタパフォーマンスの問題を特定できます。コンポーネントを使用するワークロードのパフォーマンスが低下し、クライアント要求に対する応答時間（レイテンシ）が長くなると、 Unified Manager でイベントがトリガーされます。 
---
= クラスタコンポーネントと競合する理由
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラスタコンポーネントが競合状態になった場合のクラスタパフォーマンスの問題を特定できます。コンポーネントを使用するワークロードのパフォーマンスが低下し、クライアント要求に対する応答時間（レイテンシ）が長くなると、 Unified Manager でイベントがトリガーされます。

競合状態のコンポーネントは、最適なレベルのパフォーマンスを提供できません。パフォーマンスが低下し、 _Victim _ と呼ばれる他のクラスタコンポーネントやワークロードのパフォーマンスによってレイテンシが増大する可能性があります。コンポーネントの競合を解消するには、パフォーマンスを通常のレベルに戻すために、ワークロードを減らすか処理能力を高める必要があります。Unified Managerはワークロードのパフォーマンスの収集と分析を5分間隔で行うため、クラスタコンポーネントの利用率が一貫して高い場合にのみ検出します。5分インターバルの間に短時間しか続かない過剰使用の一時的な急増は検出されません。

たとえば、ストレージアグリゲート上の1つ以上のワークロードがそれぞれのI/O要求に対応するために競合しているために、ストレージアグリゲートが競合状態になっている可能性があります。アグリゲートの他のワークロードに影響し、それらのワークロードのパフォーマンスが低下する可能性があります。アグリゲートのアクティビティを減らすには、いくつかの手順を実行します。たとえば、1つ以上のワークロードを負荷の低いアグリゲートまたはノードに移動して、現在のアグリゲートに対する全体的なワークロードの負荷を軽減するなどです。QoSポリシーグループの場合は、スループット制限を調整したり、ワークロードを別のポリシーグループに移動して、ワークロードが調整されないようにすることができます。

Unified Manager では、次のクラスタコンポーネントを監視して、これらのコンポーネントが競合状態になるとアラートを生成します。

* * ネットワーク *
+
クラスタ上の外部ネットワークプロトコルによるI/O要求の待機時間を表します。待機時間とは、クラスタが I/O 要求に応答できるようになるまで「 transfer ready 」トランザクションが完了するのを待機する時間です。ネットワークコンポーネントが競合状態にある場合は、プロトコルレイヤでの長い待機時間が1つ以上のワークロードのレイテンシに影響していることを意味します。

* * ネットワーク処理 *
+
プロトコルレイヤとクラスタ間のI/O処理に関与する、クラスタ内のソフトウェアコンポーネントを表します。ネットワーク処理を処理するノードがイベント検出後に変更された可能性があります。ネットワーク処理コンポーネントが競合状態にある場合、ネットワーク処理ノードでの高利用率が1つ以上のワークロードのレイテンシに影響していることを意味します。

+
オールSANアレイクラスタをアクティブ/アクティブ構成で使用している場合は、両方のノードのネットワーク処理のレイテンシの値が表示され、ノードで負荷を均等に共有していることを確認できます。

* * 最大 QoS
+
ワークロードに割り当てられたストレージQoSポリシーグループの最大スループット（ピーク）を表します。ポリシーグループコンポーネントが競合状態にある場合は、ポリシーグループ内のすべてのワークロードがスループット制限によって調整されており、1つ以上のワークロードのレイテンシに影響しています。

* * 最小 QoS
+
他のワークロードに割り当てられた QoS スループットの下限（想定）設定によって引き起こされている、ワークロードへのレイテンシを表します。設定されている QoS の下限に応じて特定のワークロードが保証されたスループットを確保するために帯域幅の大部分を使用すると、他のワークロードは調整されてレイテンシが増大します。

* * クラスタインターコネクト *
+
クラスタノードを物理的に接続するケーブルとアダプタを表します。クラスタインターコネクトコンポーネントが競合状態にある場合は、クラスタインターコネクトでのI/O要求の長い待機時間が1つ以上のワークロードのレイテンシに影響していることを意味します。

* * データ処理 *
+
クラスタとワークロードを含むストレージアグリゲート間のI/O処理に関与する、クラスタ内のソフトウェアコンポーネントを表します。Data Processingを処理するノードは、イベント検出後に変更された可能性があります。Data Processingコンポーネントが競合状態にある場合は、Data Processingノードでの高利用率が1つ以上のワークロードのレイテンシに影響していることを意味します。

* * ボリュームアクティベーション *
+
すべてのアクティブボリュームの使用状況を追跡するプロセスを表します。1000 を超えるアクティブボリュームを擁する大規模な環境で、ノード経由で同時にリソースにアクセスする必要がある重要なボリュームの数を追跡します。同時アクティブボリュームの数が推奨される最大しきい値を超えると、重要でない一部のボリュームでレイテンシが発生します。

* * MetroCluster リソース *
+
NVRAMとインタースイッチリンク（ISL）を含むMetroClusterリソースを表します。MetroCluster構成のクラスタ間でデータをミラーリングするために使用されます。MetroClusterコンポーネントが競合状態にある場合は、ローカルクラスタのワークロードによる高書き込みスループットまたはリンクの健常性の問題が、ローカルクラスタの1つ以上のワークロードのレイテンシに影響していることを意味します。クラスタがMetroCluster構成に含まれていない場合、このアイコンは表示されません。

* * アグリゲートまたは SSD アグリゲートの処理 *
+
ワークロードが実行されているストレージアグリゲートを表します。アグリゲートコンポーネントが競合状態にある場合は、アグリゲートの高利用率が1つ以上のワークロードのレイテンシに影響していることを意味します。アグリゲートは、HDDのみ、HDDとSSD（Flash Poolアグリゲート）、またはHDDとクラウド階層（FabricPoolアグリゲート）で構成されます。「 SD アグリゲート」は、すべての SSD （オールフラッシュアグリゲート）、または SSD とクラウド階層（ FabricPool アグリゲート）が混在しています。

* * クラウドレイテンシ *
+
クラスタとユーザデータが格納されているクラウド階層間のI/O処理に関与する、クラスタ内のソフトウェアコンポーネントを表します。クラウドレイテンシコンポーネントが競合状態にある場合、クラウド階層でホストされたボリュームからの大量の読み取りが1つ以上のワークロードのレイテンシに影響していることを意味します。

* * 同期 SnapMirror *
+
SnapMirror同期関係でのプライマリボリュームからセカンダリボリュームへのユーザデータのレプリケートに関連するクラスタ内のソフトウェアコンポーネントを表します。同期SnapMirrorコンポーネントが競合状態にある場合は、SnapMirror同期処理のアクティビティが1つ以上のワークロードのレイテンシに影響しています。


