---
permalink: performance-checker/concept_cluster_configuration_and_performance_data_collection_activity.html 
sidebar: sidebar 
keywords: cluster, configuration, performance, data, collection, activity 
summary: クラスタの構成データの収集間隔は 15 分です。たとえば、クラスタを追加したあと、そのクラスタの詳細が Unified Manager の UI に表示されるまでに 15 分かかります。クラスタに対する変更を行った場合にも同じ間隔が適用されます。 
---
= クラスタの構成とパフォーマンスのデータの収集アクティビティ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラスタ構成 data_is の収集間隔は 15 分です。たとえば、クラスタを追加したあと、そのクラスタの詳細が Unified Manager の UI に表示されるまでに 15 分かかります。クラスタに対する変更を行った場合にも同じ間隔が適用されます。

たとえば、クラスタ内の SVM に 2 つの新しいボリュームを追加した場合、それらの新しいオブジェクトが UI に表示されるのは次回のポーリング間隔のあとであるため、最大で 15 分後になります。

Unified Manager は、監視対象のすべてのクラスタから 5 分間隔で current_performance statistics _ を収集します。このデータを分析して、パフォーマンスイベントと潜在的な問題を特定します。5 分ごとのパフォーマンスデータについては 30 日分、 1 時間ごとのパフォーマンスデータについては 180 日分のデータが履歴として保持されます。これにより、現在の月の非常に詳細なパフォーマンスの詳細と、最大1年間の一般的なパフォーマンスの傾向を表示できます。

収集のポーリングは、各クラスタからのデータが同時に送信されてパフォーマンスに影響することがないように数分ずつオフセットされます。

次の表に、 Unified Manager で実行される収集アクティビティを示します。

|===
| アクティビティ | 時間間隔 | 製品説明 


 a| 
パフォーマンス統計のポーリング
 a| 
5分ごと
 a| 
各クラスタからリアルタイムのパフォーマンスデータを収集します。



 a| 
統計分析
 a| 
5分ごと
 a| 
Unified Manager では、統計のポーリングが完了するたびに、収集したデータをユーザ定義のしきい値、システム定義のしきい値、および動的なしきい値と比較します。

パフォーマンスしきい値の違反が見つかると、 Unified Manager はイベントを生成し、設定されている場合は該当のユーザに E メールを送信します。



 a| 
構成のポーリング
 a| 
15分ごと
 a| 
各クラスタから詳細なインベントリ情報を収集して、すべてのストレージオブジェクト（ノード、 SVM 、ボリュームなど）を特定します。



 a| 
要約
 a| 
1時間ごと
 a| 
5分ごとに収集された最新12件のパフォーマンスデータを1時間の平均にまとめたものです。

1 時間の平均値は UI のいくつかのページで使用され、 180 日間保持されます。



 a| 
予測分析とデータの削除
 a| 
毎日午前0時以降
 a| 
クラスタのデータを分析して、次の24時間のボリュームレイテンシとIOPSの動的なしきい値を設定します。

30日を経過した5分ごとのパフォーマンスデータをデータベースから削除します。



 a| 
データの削除
 a| 
毎日午前2時から
 a| 
180 日を経過したイベントおよび 180 日を経過した動的しきい値をデータベースから削除します。



 a| 
データの削除
 a| 
毎日午前3時半から
 a| 
180 日を経過した 1 時間ごとのパフォーマンスデータをデータベースから削除します。

|===