---
permalink: performance-checker/concept_types_of_workloads_monitored_by_unified_manager.html 
sidebar: sidebar 
keywords: types, workloads, monitored, unified manager 
summary: Unified Manager では、ユーザ定義とシステム定義の 2 種類のワークロードのパフォーマンスを監視できます。 
---
= Unified Managerで監視されるワークロードのタイプ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager では、ユーザ定義とシステム定義の 2 種類のワークロードのパフォーマンスを監視できます。

* * _ ユーザ定義のワークロード _ *
+
アプリケーションからクラスタへのI/Oスループット。読み取り要求と書き込み要求に関連するプロセスです。ボリューム、LUN、NFS共有、SMB / CIFS共有、およびワークロードはユーザ定義のワークロードです。

+
[NOTE]
====
Unified Managerは、クラスタ上のワークロードアクティビティのみを監視します。アプリケーションやクライアント、アプリケーションとクラスタ間のパスは監視されません。

====
+
次の条件が 1 つ以上該当するワークロードは、 Unified Manager で監視できません。

+
** 読み取り専用モードのデータ保護（DP）コピーです。（DPボリュームはユーザ生成のトラフィックについて監視されます）。
** オフラインデータクローンである。
** MetroCluster構成のミラーボリュームである。


* * _ システム定義のワークロード _ *
+
ストレージ効率化、データレプリケーション、およびシステム健全性に関連する内部プロセス。次のプロセスが含まれます。

+
** ストレージ効率化（重複排除など）
** ディスクの健全性（RAIDの再構築、ディスクスクラビングなど）
** データレプリケーション（SnapMirrorコピーなど）
** 管理アクティビティ
** ファイルシステムの健全性（WAFLのさまざまなアクティビティなど）
** ファイルシステムスキャナ（WAFLスキャンなど）
** コピーオフロード（VMwareホストからオフロードされたStorage Efficiency処理など）
** システム健全性（ボリューム移動、データ圧縮など）
** 監視対象外のボリューム




システム定義のワークロードのパフォーマンスデータは、これらのワークロードで使用されているクラスタコンポーネントが競合状態にある場合にのみGUIに表示されます。たとえば、システム定義のワークロードの名前を検索して、そのパフォーマンスデータをGUIで表示することはできません。
