---
permalink: performance-checker/concept_what_expected_range_of_performance_is.html 
sidebar: sidebar 
keywords: expected, range, performance, latency, forecast, formed 
summary: レイテンシ予測は、特定の時点で想定されるパフォーマンスの上限値と下限値を予測したものです。ワークロードのレイテンシについては、パフォーマンスしきい値を上回る値が表示されます。実測値がパフォーマンスしきい値を超えると、Unified Managerは動的なパフォーマンスイベントをトリガーします。 
---
= パフォーマンスの想定範囲とは
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
レイテンシ予測は、特定の時点で想定されるパフォーマンスの上限値と下限値を予測したものです。ワークロードのレイテンシについては、パフォーマンスしきい値を上回る値が表示されます。実測値がパフォーマンスしきい値を超えると、Unified Managerは動的なパフォーマンスイベントをトリガーします。

たとえば、午前9時から午後5時までの通常の営業時間には、ほとんどの従業員が午前9時から午前10時30分までの間にEメールをチェックする場合があります。Eメールサーバへの需要の増加は、この間にバックエンドストレージでのワークロードアクティビティが増加することを意味します。従業員は、電子メールクライアントからの応答時間が遅いことに気付く場合があります。

午後12時から午後1時までのランチタイム、および午後5時以降の営業日の終わりには、ほとんどの従業員がコンピュータから離れている可能性があります。通常、Eメールサーバの需要は減少し、バックエンドストレージの需要も減少します。また、ストレージのバックアップやウィルススキャンなどのワークロード処理を午後5時以降に開始し、バックエンドストレージのアクティビティが増加するようにスケジュール設定することもできます。

ワークロードアクティビティの増減から数日間にわたるアクティビティの想定範囲（レイテンシ予測）が特定され、ワークロードの上限と下限が決まります。オブジェクトの実際のワークロードアクティビティが上限と下限の外側にあり、その外側にある期間がある場合は、オブジェクトの使用率が高すぎるか低すぎる可能性があります。



== レイテンシ予測の生成方法

Unified Managerでは、少なくとも3日分のワークロードアクティビティを収集して分析してから、GUIに表示するI/O応答時間のレイテンシ予測を決定する必要があります。最小限必要なデータ収集には、ワークロードアクティビティで発生するすべての変更が反映されるわけではありません。最初の3日間のアクティビティを収集したあと、Unified Managerはレイテンシ予測を24時間ごとに午前12時に調整し、ワークロードアクティビティの変化を反映して、より正確な動的なパフォーマンスしきい値を設定します。

[NOTE]
====
システム時間が夏時間（DST）に切り替わると、監視対象のワークロードのパフォーマンス統計のレイテンシ予測が変わります。Unified Managerはレイテンシ予測の修正を即座に開始しますが、完了までに約15日かかります。その間もUnified Managerの使用は継続できますが、Unified Managerはレイテンシ予測を使用して動的なイベントを検出するため、一部のイベントは正確でなくなる可能性があります。時間の変更前に検出されたイベントは影響を受けません。

====