---
permalink: performance-checker/concept_how_storage_qos_can_control_workload_throughput.html 
sidebar: sidebar 
keywords: storage, qos, control, workload, throughput 
summary: QoSポリシーグループを作成して、ポリシーグループに含まれるワークロードの1秒あたりのI/O処理数（IOPS）やスループット（MBps）の上限を制御できます。ワークロードが属するポリシーグループに上限が設定されていない場合（デフォルトのポリシーグループなど）や、設定された上限がニーズに合わない場合は、上限を引き上げるか、適切な上限が設定された新規または既存のポリシーグループにワークロードを移動できます。 
---
= ストレージQoSがワークロードスループットを制御する仕組み
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
QoSポリシーグループを作成して、ポリシーグループに含まれるワークロードの1秒あたりのI/O処理数（IOPS）やスループット（MBps）の上限を制御できます。ワークロードが属するポリシーグループに上限が設定されていない場合（デフォルトのポリシーグループなど）や、設定された上限がニーズに合わない場合は、上限を引き上げるか、適切な上限が設定された新規または既存のポリシーグループにワークロードを移動できます。

「従来の」 QoS ポリシーグループは、単一のボリュームや LUN など、個々のワークロードに割り当てることができます。この場合、ワークロードはスループットの上限をすべて使用できます。また、 QoS ポリシーグループを複数のワークロードに割り当てることもできます。この場合、ワークロードのスループットの上限は「「「赤」です。たとえば、3つのワークロードに9、000 IOPSのQoS制限を割り当てると、IOPSの合計が9、000 IOPSを超えないように制限されます。

アダプティブ QoS ポリシーグループは、個々のワークロードまたは複数のワークロードに割り当てることもできます。ただし、複数のワークロードに割り当てられている場合も、スループットの値を他のワークロードと共有するのではなく、各ワークロードでスループットが上限まで使用されます。さらに、アダプティブQoSポリシーは、スループットの設定をワークロードごとにボリュームサイズに基づいて自動的に調整し、ボリュームサイズが変わっても容量に対するIOPSの比率を維持します。たとえば、アダプティブQoSポリシーでピークが5、000 IOPS/TBに設定されている場合、10TBのボリュームの最大スループットは50、000 IOPSになります。ボリュームのサイズが20TBに変更されると、アダプティブQoSによって最大値が100、000 IOPSに調整されます。

ONTAP 9 .5以降では、アダプティブQoSポリシーを定義する際にブロックサイズを含めることができます。これにより、ワークロードが非常に大きなブロックサイズを使用しており、最終的にスループットの大部分を使用しているケースでは、ポリシーのしきい値がIOPS/TBからMBpsに変換されます。

グループでQoSポリシーを共有している場合、ポリシーグループ内のすべてのワークロードのIOPSまたはMBpsが設定された上限を超えると、ワークロードが調整されてそのアクティビティが制限されます。これにより、ポリシーグループ内のすべてのワークロードのパフォーマンスが低下することがあります。ポリシーグループの調整によって動的なパフォーマンスイベントが生成されると、イベントの説明に関係するポリシーグループの名前が表示されます。

パフォーマンス：すべてのボリュームビューで、影響を受けたボリュームを IOPS と MBps でソートすると、イベントの原因となった可能性がある使用率が最も高いワークロードを確認できます。Performance/Volumes Explorer ヘエシでは、ボリューム上の他のボリュームまたは LUN を選択して、影響を受けるワークロードの IOPS または MBps スループットの使用率と比較できます。

ノードリソースを過剰に消費しているワークロードをより制限の厳しいポリシーグループに割り当てることで、ポリシーグループによる調整でワークロードのアクティビティが制限され、そのノードでのリソースの使用が削減されます。ただし、ワークロードがより多くのノードリソースを使用できるようにするには、ポリシーグループの値を大きくします。

System Manager、ONTAPコマンド、またはUnified Managerのパフォーマンスサービスレベルを使用してポリシーグループを管理できます。これには次のタスクが含まれます。

* ポリシーグループの作成
* ポリシーグループ内のワークロードの追加または削除
* ポリシーグループ間でのワークロードの移動
* ポリシーグループのスループット制限の変更
* 別のアグリゲートやノードへのワークロードの移動

