---
permalink: performance-checker/concept_add_disks_and_reallocate_data.html 
sidebar: sidebar 
keywords: add, disks, reallocate, data 
summary: アグリゲートにディスクを追加して、ストレージ容量とそのアグリゲートのパフォーマンスを向上させることができます。ディスクを追加したあと、追加したディスクにデータを再配置するまでは読み取りパフォーマンスは向上しません。 
---
= ディスクの追加とデータの再割り当て
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アグリゲートにディスクを追加して、ストレージ容量とそのアグリゲートのパフォーマンスを向上させることができます。ディスクを追加したあと、追加したディスクにデータを再配置するまでは読み取りパフォーマンスは向上しません。

この手順は、 Unified Manager で動的しきい値またはシステム定義のパフォーマンスしきい値に基づいてトリガーされたアグリゲートイベントを受信したときに使用できます。

* 動的しきい値のイベントを受信した場合は、[イベントの詳細]ページで、競合状態にあるアグリゲートを表すクラスタコンポーネントのアイコンが赤で強調表示されます。
+
アイコンの下には、ディスクを追加できるアグリゲートの名前がかっこ内に表示されます。

* システム定義のしきい値イベントを受信した場合は、[イベントの詳細]ページでイベントの説明テキストに問題があるアグリゲートの名前が表示されます。
+
このアグリゲートにディスクを追加してデータを再割り当てできます。



アグリゲートに追加できるのは、クラスタにすでに存在しているディスクだけです。クラスタに使用可能なディスクが残っていない場合は、必要に応じて管理者に問い合わせるか追加のディスクを購入してください。アグリゲートにディスクを追加するには、ONTAP System ManagerまたはONTAPコマンドを使用します。

[NOTE]
====
データの再割り当ては、HDDアグリゲートおよびFlash Poolアグリゲートを使用している場合にのみ行ってください。SSDアグリゲートまたはFabricPoolアグリゲートにはデータを再割り当てしないでください。

====