---
permalink: performance-checker/concept_metrocluster_configuration_verification.html 
sidebar: sidebar 
keywords: metrocluster, configuration, verification 
summary: MetroCluster 構成でミラーされたワークロードにパフォーマンスの問題が発生しないようにするには、 MetroCluster 構成が正しくセットアップされていることを確認します。また、構成を変更したり、ソフトウェアまたはハードウェアコンポーネントをアップグレードしたりして、ワークロードのパフォーマンスを向上させることもできます。 
---
= MetroCluster構成の検証
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MetroCluster over FC / IP構成でミラーされたワークロードでパフォーマンスの問題が発生しないようにするには、MetroCluster構成を正しく設定します。また、構成を変更したり、ソフトウェアまたはハードウェアコンポーネントをアップグレードしたりして、ワークロードのパフォーマンスを向上させることもできます。

Fibre Channel（FC；ファイバチャネル）スイッチ、ケーブル、スイッチ間リンク（ISL）など、MetroCluster構成でクラスタをセットアップする手順については、を参照してください https://docs.netapp.com/us-en/ontap-metrocluster/index.html["MetroClusterのドキュメント"]。また、ローカルクラスタとリモートクラスタがミラーボリュームのデータと通信できるようにMetroClusterソフトウェアを設定する際にも役立ちます。MetroCluster over IP設定に固有の情報については、を参照してください https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/index.html["MetroCluster IP設定のインストール"]。

MetroCluster構成をの要件と比較して、MetroCluster構成のコンポーネントを変更またはアップグレードすることでワークロードのパフォーマンスが向上するかどうかを判断できます https://docs.netapp.com/us-en/ontap-metrocluster/index.html["MetroClusterのドキュメント"]。この比較は、次の点を確認するのに役立ちます。

* コントローラはワークロードに適していますか？
* スループットを向上させるために、ISLバンドルをより広い帯域幅にアップグレードする必要がありますか。
* 帯域幅を増やすために、スイッチのバッファ間クレジット（BBC）を調整できますか。
* ワークロードのソリッドステートドライブ（SSD）ストレージへの書き込みスループットが高い場合、スループットに対応するためにFC-to-SASブリッジをアップグレードする必要がありますか？


* 関連情報 *

* MetroClusterコンポーネントの交換またはアップグレードの詳細については、を参照して https://docs.netapp.com/us-en/ontap-metrocluster/index.html["MetroClusterのドキュメント"]ください。
* コントローラのアップグレードについては、および https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_upgrade_controllers_in_a_four_node_ip_mcc_us_switchover_and_switchback_mcc_ip.html["スイッチオーバーとスイッチバックを使用したMetroCluster IP構成のコントローラのアップグレード"]を参照してください。 https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_upgrade_controllers_in_a_four_node_fc_mcc_us_switchover_and_switchback_mcc_fc_4n_cu.html["スイッチオーバーとスイッチバックを使用したMetroCluster FC構成のコントローラのアップグレード"]

