---
permalink: performance-checker/concept_understand_events_from_adaptive_qos_policies.html 
sidebar: sidebar 
keywords: understand, events, adaptive, qos, policies, defined, block, size 
summary: アダプティブQoSポリシーグループでは、ボリュームサイズに基づいてスループットの上限と下限が自動的に調整され、TBあたりのIOPSが一定に維持されます。ONTAP 9 .5以降では、QoSポリシーにブロックサイズを指定してMBpsのしきい値を同時に適用できます。 
---
= ブロックサイズの定義を含むアダプティブ QoS ポリシーによるイベントの概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アダプティブQoSポリシーグループでは、ボリュームサイズに基づいてスループットの上限と下限が自動的に調整され、TBあたりのIOPSが一定に維持されます。ONTAP 9 .5以降では、QoSポリシーにブロックサイズを指定してMBpsのしきい値を同時に適用できます。

アダプティブQoSポリシーにIOPSのしきい値を割り当てると、各ワークロードで発生する処理数のみが制限されます。ワークロードを生成するクライアントに設定されているブロックサイズによっては、一部のIOPSにはるかに多くのデータが含まれるため、処理を処理するノードの負荷がはるかに大きくなります。

ワークロードのMBpsの値は次の式を使用して生成されます。

[listing]
----
MB/s = (IOPS * Block Size) / 1000
----
平均IOPSが3、000のワークロードについて、クライアントのブロックサイズが32KBに設定されている場合、このワークロードの実効MBpsは96です。平均IOPSが3、000の同じワークロードについて、クライアントのブロックサイズが48KBに設定されている場合、このワークロードの実効MBpsは144です。ブロックサイズが大きいほど、ノードで処理されるデータが50%多くなっていることがわかります。

次に、ブロックサイズが定義されたアダプティブQoSポリシーを示し、クライアントに設定されているブロックサイズに基づいてイベントがどのようにトリガーされるかを確認します。

ポリシーを作成し、最大スループットを2、500 IOPS/TB、ブロックサイズを32KBに設定します。これにより、使用済み容量が1TBのボリュームのMBpsのしきい値が80MB/s（（（2500 IOPS * 32KB）/ 1000）に設定されます。Unified Managerでは、スループットの値が定義されたしきい値を10%下回ると警告イベントが生成されます。イベントは次の状況で生成されます。

|===
| 使用済み容量 2+| イベントが生成されるスループットのしきい値 


|  | IOPS | MB/秒 


 a| 
1TB
 a| 
2、250 IOPS
 a| 
72 MB/秒



 a| 
2TB
 a| 
4、500 IOPS
 a| 
144 MB/秒



 a| 
5TB
 a| 
11、250 IOPS
 a| 
360 MB/秒

|===
ボリュームの使用可能なスペースが2TB、IOPSが4、000、クライアントで設定されているQoSブロックサイズが32KBである場合、スループットは128MB/秒（（（4、000 IOPS * 32KB）/ 1000）になります。このシナリオでは、4、000 IOPSと128MB/秒のどちらも、ボリュームで2TBのスペースを使用する場合のしきい値を下回っているため、イベントは生成されません。

ボリュームの使用可能なスペースが2TB、IOPSが4、000、クライアントで設定されているQoSブロックサイズが64KBである場合、スループットは256MB/秒（（（4、000 IOPS * 64KB）/ 1000）になります。この場合、4、000 IOPSについてはイベントは生成されませんが、MB/sの値については256MB/sのしきい値である144MB/sを超えているためイベントが生成されます。

このため、ブロックサイズを含むアダプティブQoSポリシーに対するMBpsの違反に基づいてイベントがトリガーされた場合は、[イベントの詳細]ページの[システム診断]セクションにMBpsのグラフが表示されます。アダプティブ QoS ポリシーに対する IOPS の違反に基づいてイベントがトリガーされると、システム診断セクションに IOPS チャートが表示されます。IOPSとMBpsの両方に違反が発生すると、2つのイベントが表示されます。

QoS設定の調整の詳細については、を参照してください https://docs.netapp.com/us-en/ontap/performance-admin/index.html["パフォーマンス管理の概要"]。
