---
permalink: performance-checker/concept_understand_counter_charts.html 
sidebar: sidebar 
keywords: understand, counter, charts 
summary: カウンタグラフペインのグラフでは、ルートオブジェクトのパフォーマンスデータと、関連オブジェクトグリッドから追加したオブジェクトのパフォーマンスデータを表示および比較できます。これは、パフォーマンスの傾向を把握し、パフォーマンスの問題を切り分けて解決するのに役立ちます。 
---
= カウンタグラフの概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
カウンタグラフペインのグラフでは、ルートオブジェクトのパフォーマンスデータと、関連オブジェクトグリッドから追加したオブジェクトのパフォーマンスデータを表示および比較できます。これは、パフォーマンスの傾向を把握し、パフォーマンスの問題を切り分けて解決するのに役立ちます。

デフォルトで表示されるカウンタグラフは、イベント、レイテンシ、 IOPS 、および MBps です。オプションで表示できるグラフは、利用率、使用済みパフォーマンス容量、使用可能な IOPS 、 IOPS/TB 、キャッシュミス率です。また、レイテンシ、 IOPS 、 MBps 、および使用済みパフォーマンス容量の各グラフの合計値と内訳値を表示することもできます。

パフォーマンスエクスプローラには、デフォルトで特定のカウンタグラフが表示されます。それらがすべてサポートされているかどうかは関係ありません。サポートされていないカウンタの場合、カウンタグラフは空になり、メッセージが表示されます。 `Not applicable for <object>`

チャートには、ルートオブジェクトと、比較ペインで選択したすべてのオブジェクトのパフォーマンスの傾向が表示されます。各グラフのデータは次のように配置されます。

* * X 軸 *
+
指定した期間が表示されます。期間を指定しなかった場合のデフォルトの期間は過去72時間です。

* * Y 軸 *
+
選択したオブジェクトに固有のカウンタ単位が表示されます。



傾向線の色は、比較ペインに表示されるオブジェクト名の色と一致します。任意のトレンドライン上のポイントにカーソルを合わせると、そのポイントの時間と値の詳細が表示されます。

グラフ内の特定の期間を調査するには、次のいずれかの方法を使用します。

* 「 * < * 」ボタンを使用して、カウンタチャートペインを展開し、ページの幅を広げます。
* カーソルを使用して（虫眼鏡に変わる）チャート内の一部の期間を選択し、拡大する。[Reset Chart Zoom]をクリックすると、グラフをデフォルトの期間に戻すことができます。
* 拡大した詳細やしきい値インジケータを含む大きなカウンタチャートを表示するには、 * Zoom View * ボタンを使用します。


[NOTE]
====
トレンドラインにギャップが表示されることがあります。その期間は Unified Manager がストレージシステムからパフォーマンスデータを収集できなかったか、 Unified Manager が停止していた可能性があります。

====