---
permalink: performance-checker/concept_roles_of_workloads_involved_in_performance_incident.html 
sidebar: sidebar 
keywords: roles, workloads, involved, performance, event 
summary: Unified Manager では、ロールを使用して、パフォーマンスイベントにワークロードがどのように関連しているかを特定します。役割にはVictim、Bully、Sharkがあります。ユーザ定義のワークロードは、同時にVictim、Bully、Sharkにすることができます。 
---
= パフォーマンスイベントに関連したワークロードの役割
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager では、ロールを使用して、パフォーマンスイベントにワークロードがどのように関連しているかを特定します。役割にはVictim、Bully、Sharkがあります。ユーザ定義のワークロードは、同時にVictim、Bully、Sharkにすることができます。

|===
| ロール | 製品説明 


 a| 
被害者
 a| 
クラスタコンポーネントを過剰に消費している他のワークロード（Bully）のためにパフォーマンスが低下しているユーザ定義のワークロード。Victimとみなされるのはユーザ定義のワークロードだけです。Unified Manager はレイテンシの偏差に基づいて、イベント中のレイテンシの実測値がレイテンシ予測（想定範囲）から大幅に増加しているワークロードを Victim ワークロードとして特定します。



 a| 
Bully
 a| 
クラスタコンポーネントの過剰な消費によって他のワークロード（Victim）のパフォーマンスが低下するユーザ定義またはシステム定義のワークロード。Unified Manager はクラスタコンポーネントの使用量の偏差に基づいて、イベント中の使用量の実測値が想定範囲から大幅に増加しているワークロードを Bully ワークロードとして特定します。



 a| 
シャーク
 a| 
イベントに関連するすべてのワークロードと比較してクラスタコンポーネントの使用量が最も多いユーザ定義のワークロード。Unified Manager はイベント中のクラスタコンポーネントの使用量に基づいて Shark ワークロードを特定します。

|===
クラスタのワークロードは、アグリゲートやネットワーク用のCPUやData Processingなど、クラスタコンポーネントの多くを共有できます。ボリュームなどのワークロードが、クラスタコンポーネントの使用量を増やしてワークロードの要求を効率的に満たせなくなると、そのコンポーネントは競合状態になります。クラスタコンポーネントを過剰に消費しているワークロードはBullyです。これらのコンポーネントを共有しており、Bullyによってパフォーマンスに影響が出ている他のワークロードがVictimです。重複排除や Snapshot コピーなど、システム定義のワークロードのアクティビティも、「いじめ」にエスカレーションできます。

Unified Manager はイベントを検出すると、関連するすべてのワークロードとクラスタコンポーネントを特定します。これには、イベントの原因となった Bully ワークロード、競合状態のクラスタコンポーネント、および Bully ワークロードのアクティビティが増加したためにパフォーマンスが低下した Victim ワークロードが含まれます。

[NOTE]
====
Unified Manager が Bully ワークロードを特定できない場合は、 Victim ワークロードと関連するクラスタコンポーネントに関するアラートだけが生成されます。

====
Unified Manager は Bully ワークロードの Victim ワークロードを特定でき、同じワークロードが Bully ワークロードになった場合にも特定できます。ワークロードが自身の影響源になる可能性があります。たとえば、負荷の高いワークロードがポリシーグループの制限によって調整されている場合、そのワークロードも含めて、ポリシーグループ内のすべてのワークロードが調整されます。継続的なパフォーマンスイベントでBullyまたはVictimであるワークロードは、ロールが変更されたり、イベントに参加しなくなったりする可能性があります。
