---
permalink: performance-checker/concept_understand_um_recommendations_to_tier_data_to_cloud.html 
sidebar: sidebar 
keywords: understand, unified manager, recommendations, tier, data, cloud 
summary: Performance ： All Volumes ビューには、ボリュームに格納されているアクセス頻度の低いユーザデータ（コールドデータ）のサイズに関する情報が表示されます。Unified Manager が、特定のボリュームについて、アクセス頻度の低いデータを FabricPool 対応アグリゲートのクラウド階層（クラウドプロバイダまたは StorageGRID ）に階層化することを推奨することがあります。 
---
= Unified Managerによるクラウドへのデータ階層化の推奨事項の概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Performance ： All Volumes ビューには、ボリュームに格納されているアクセス頻度の低いユーザデータ（コールドデータ）のサイズに関する情報が表示されます。Unified Manager が、特定のボリュームについて、アクセス頻度の低いデータを FabricPool 対応アグリゲートのクラウド階層（クラウドプロバイダまたは StorageGRID ）に階層化することを推奨することがあります。

[NOTE]
====
FabricPool は ONTAP 9.2 で導入されたため、 9.2 より前のバージョンの ONTAP ソフトウェアを使用している場合、 Unified Manager によるデータの階層化の推奨を有効にするには、 ONTAP ソフトウェアのアップグレードが必要になります。また `*auto*`、階層化ポリシーはONTAP 9 .4、階層化ポリシーはONTAP 9 .6でも導入され `*all*`たため、auto階層化ポリシーの使用が推奨される場合は、ONTAP 9 .4以降にアップグレードする必要があります。

====
Performance ： All Volumes ビューの次の 3 つのフィールドは、アクセス頻度の低いデータをクラウド階層に移動することでストレージシステムのディスク使用率の改善やパフォーマンス階層のスペースの削減が可能かどうかに関する情報を提供します。

* * 階層化ポリシー *
+
階層化ポリシーによって、ボリュームのデータを高パフォーマンス階層に残すか、あるいは一部のデータをパフォーマンス階層からクラウド階層に移動するかが決まります。

+
このフィールドの値は、ボリュームに対して設定されている階層化ポリシーを示します。ボリュームが現在FabricPoolアグリゲートにない場合も同様です。階層化ポリシーが適用されるのは、ボリュームがFabricPoolアグリゲートにある場合のみです。

* * コールドデータ *
+
ボリュームに格納されているアクセス頻度の低いユーザデータ（コールドデータ）のサイズが表示されます。

+
ここには、ONTAP 9 .4以降のソフトウェアを使用している場合にのみ値が表示されます。これは、ボリュームを導入するアグリゲートでがに設定されて `*enabled*`いる必要があり、最小クーリング日数のしきい値（または `*auto*`階層化ポリシーを使用するボリュームの場合）に達している `*snapshot-only*`必要があるためです。 `*inactive data reporting parameter*`それ以外の場合、値は「 N/A 」と表示されます。

* * クラウドの推奨事項 *
+
ボリュームのデータアクティビティに関して十分な情報が収集されると、 Unified Manager は、対処が不要か、またはアクセス頻度の低いデータをクラウド階層に移動することでパフォーマンス階層のスペースを削減できるかを判断することができます。



[NOTE]
====
[コールドデータ]フィールドは15分ごとに更新されますが、[クラウドの推奨事項]フィールドは7日ごとに更新され、ボリュームに対してコールドデータ分析が実行されます。そのため、コールドデータの正確な量はフィールド間で異なる可能性があります。[クラウドの推奨事項]フィールドには、分析が実行された日付が表示されます。

====
Inactive Data Reportingが有効になっている場合は、コールドデータフィールドにアクセス頻度の低いデータの正確な量が表示されます。Inactive Data Reporting 機能を使用できない場合、 Unified Manager はパフォーマンス統計に基づいてアクセス頻度の低いデータがボリュームにあるかどうかを判断します。アクセス頻度の低いデータの量はこの場合のコールドデータフィールドには表示されませんが、クラウドに関する推奨事項を表示するために「 * ティア * 」という単語にカーソルを合わせると表示されます。

クラウドに関する推奨事項は次のとおりです。

* * 学習中 * 。推奨事項を利用できるだけの十分なデータが収集されていません。
* * 階層 * 。分析の結果、アクセス頻度の低いコールドデータがボリュームに含まれているため、そのデータをクラウド階層に移動するようにボリュームを設定する必要があると判断されました。場合によっては、まずボリュームをFabricPool対応アグリゲートに移動しなければならないことがあります。ボリュームがすでにFabricPoolアグリゲートにある場合は、階層化ポリシーを変更するだけで済みます。
* * アクションなし * 。ボリュームにアクセス頻度の低いデータがほとんどないか、ボリュームが FabricPool アグリゲートですでに「 auto 」階層化ポリシーに設定されているか、ボリュームがデータ保護ボリュームです。この値は、ボリュームがオフラインの場合やMetroCluster構成で使用されている場合にも表示されます。


ボリュームを移動したり、ボリュームの階層化ポリシーやアグリゲートの Inactive Data Reporting の設定を変更するには、 ONTAP System Manager 、 ONTAP の CLI コマンド、またはこの 2 つを組み合わせて使用します。

アプリケーション管理者またはストレージ管理者のロールで Unified Manager にログインしている場合は、「 * 階層 * 」にカーソルを合わせるとクラウドに関する推奨事項の「ボリュームの設定 * 」リンクが表示されます。このボタンをクリックすると、 System Manager の Volumes （ボリューム）ページが開き、推奨される変更が行われます。
