---
permalink: performance-checker/concept_use_threshold_policy_with_node_failover_planning_page.html 
sidebar: sidebar 
keywords: threshold, policy, node, failover, planning page 
summary: 'ノードしきい値ポリシーを作成すると、フェイルオーバーによってテイクオーバーノードのパフォーマンスが許容できないレベルに低下する可能性がある場合に、[Performance/Node Failover Planning]ページで通知を受け取ることができます。' 
---
= [Node Failover Planning]ページでのしきい値ポリシーの使用
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ノードしきい値ポリシーを作成すると、フェイルオーバーによってテイクオーバーノードのパフォーマンスが許容できないレベルに低下する可能性がある場合に、[Performance/Node Failover Planning]ページで通知を受け取ることができます。

「 Node HA pair over-utilized 」という名前のシステム定義のパフォーマンスしきい値ポリシーは、 6 回の収集期間（ 30 分）に連続してしきい値を超えた場合に警告イベントを生成します。HA ペアのノードの使用済みパフォーマンス容量の合計が 200% を超えると、しきい値を超えたと認識されます。

システム定義のしきい値ポリシーのイベントは、フェイルオーバーによってテイクオーバーノードのレイテンシが許容できないレベルに上昇することを警告します。特定のノードについてこのポリシーで生成されたイベントが表示された場合は、そのノードの[Performance/Node Failover Planning]ページに移動して、フェイルオーバーによるレイテンシの予測値を確認できます。

このシステム定義のしきい値ポリシーの使用に加えて、「 Performance Capacity Used - Takeover 」カウンタを使用してしきい値ポリシーを作成し、選択したノードにそのポリシーを適用できます。200%を下回るしきい値を指定すると、システム定義のポリシーのしきい値を超える前にイベントを受け取ることができます。システム定義のポリシーイベントが生成される前に通知を受け取る場合は、しきい値を超えた最小期間を30分未満に指定することもできます。

たとえば、 HA ペアのノードの使用済みパフォーマンス容量の合計が 10 分以上にわたって 175% を超えた場合に警告イベントが生成されるようにしきい値ポリシーを定義できます。このポリシーは、HAペアを形成するノード1とノード2に適用できます。ノード1またはノード2のいずれかについて警告イベント通知を受信したら、そのノードの[Performance/Node Failover Planning]ページを表示して、テイクオーバーノードへのパフォーマンスへの影響を評価できます。フェイルオーバーが発生した場合にテイクオーバーノードが過負荷にならないように対処することができます。ノードの使用済みパフォーマンス容量の合計が200%未満のときに対処すると、この間にフェイルオーバーが発生しても、テイクオーバーノードのレイテンシは許容できないレベルに達しません。
