---
permalink: performance-checker/concept_remove_inactive_volumes_and_luns.html 
sidebar: sidebar 
keywords: remove, inactive, volumes, luns 
summary: アグリゲートの空きスペースに問題が見つかった場合は、未使用のボリュームとLUNを検索してアグリゲートから削除できます。これは、ディスク容量不足の問題を軽減するのに役立ちます。 
---
= 非アクティブなボリュームとLUNの削除
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アグリゲートの空きスペースに問題が見つかった場合は、未使用のボリュームとLUNを検索してアグリゲートから削除できます。これは、ディスク容量不足の問題を軽減するのに役立ちます。

アグリゲートのパフォーマンスイベントの原因がディスクスペースの不足である場合は、使用されなくなったボリュームやLUNをいくつかの方法で確認できます。

未使用のボリュームを特定するには：

* イベントの詳細ページの * 影響を受けるオブジェクト数 * フィールドには、影響を受けるボリュームのリストを示すリンクが表示されます。
+
リンクをクリックすると、 Performance ： All Volumes ビューにボリュームが表示されます。このページで関連するボリュームを * IOPS * でソートすると、アクティブでないボリュームがわかります。



未使用のLUNを特定するには：

. [Event Details]ページで、イベントが発生したアグリゲートの名前を書き留めます。
. 左側のナビゲーションペインで、 * Storage * > * LUNs * をクリックし、表示メニューから * Performance * > * All LUNs * を選択します。
. [*Filtering*] をクリックし、左側のドロップダウンメニューから [*Aggregate*] を選択して、テキストフィールドにアグリゲートの名前を入力し、 [*Apply Filter*] をクリックします。
. 表示された影響を受ける LUN のリストを * IOPS * でソートして、アクティブでない LUN を確認します。


未使用のボリュームとLUNを特定したら、ONTAP System ManagerまたはONTAPコマンドを使用してそれらのオブジェクトを削除できます。
