---
permalink: performance-checker/concept_understand_performance_panels_on_dashboard.html 
sidebar: sidebar 
keywords: understand, performance, panels, dashboard 
summary: Unified Manager のダッシュボードには、環境内の監視対象のすべてのクラスタのパフォーマンスステータスの概要が、複数のパネルに分けて表示されます。すべてのクラスタまたは個々のクラスタのステータスを表示できます。 
---
= ダッシュボードのパフォーマンスパネルの概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager のダッシュボードには、環境内の監視対象のすべてのクラスタのパフォーマンスステータスの概要が、複数のパネルに分けて表示されます。すべてのクラスタまたは個々のクラスタのステータスを表示できます。

ほとんどのパネルには、パフォーマンス情報のほかに、そのカテゴリのアクティブなイベントの数や、過去24時間に追加された新しいイベントの数も表示されます。この情報から、報告されたイベントを解決するために詳細な分析が必要なクラスタを決定できます。イベントをクリックすると上位数件のイベントが表示され、そのカテゴリのイベントだけを表示するようにフィルタリングされた[イベント管理]インベントリページへのリンクが表示されます。

次のパネルにパフォーマンスステータスが表示されます。

* * パフォーマンス容量パネル *
+
すべてのクラスタを表示している場合、このパネルには、各クラスタのパフォーマンス容量（過去1時間の平均）とパフォーマンス容量が上限に達するまでの日数（日次増加率に基づく）が表示されます。棒グラフをクリックすると、そのクラスタの[Nodes]インベントリページが表示されます。ノードのインベントリページには過去 72 時間のパフォーマンス容量の平均が表示されるため、この値がダッシュボードの値と一致しないことがあります。

+
単一のクラスタを表示している場合、このパネルには、クラスタのパフォーマンス容量、合計IOPS、合計スループットの値が表示されます。

* * ワークロード IOPS パネル *
+
ワークロードのアクティブ管理が有効になっていて、単一のクラスタを表示している場合、このパネルには、特定の範囲のIOPSで現在実行されているワークロードの総数が表示されます。

* * ワークロードパフォーマンスパネル *
+
ワークロードのアクティブ管理が有効になっている場合、このパネルには、定義されている各パフォーマンスサービスレベルに割り当てられている準拠ワークロードと非準拠ワークロードの合計数が表示されます。棒グラフをクリックすると、[ワークロード]ページでそのポリシーに割り当てられているワークロードが表示されます。

* * 使用状況の概要パネル *
+
すべてのクラスタを表示している場合は、クラスタをIOPSまたはスループット（MBps）が高い順に表示できます。

+
単一のクラスタを表示している場合は、そのクラスタのワークロードをIOPSまたはスループット（MBps）が高い順に表示できます。


