---
permalink: performance-checker/concept_options_for_improving_workload_performance_from_client.html 
sidebar: sidebar 
keywords: options, improving, workload, performance, client-side 
summary: パフォーマンスイベントに関連したボリュームにI/Oを送信しているクライアントワークロード（アプリケーションやデータベースなど）を確認することで、クライアント側の変更によってイベントが修正されたかどうかを判断できます。 
---
= クライアント側からワークロードパフォーマンスを向上させるためのオプション
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
パフォーマンスイベントに関連したボリュームにI/Oを送信しているクライアントワークロード（アプリケーションやデータベースなど）を確認することで、クライアント側の変更によってイベントが修正されたかどうかを判断できます。

クラスタ上のボリュームに接続されているクライアントのI/O要求が増加すると、その要求を満たすためにクラスタの負荷が増大します。クラスタ上の特定のボリュームに対するI/O要求数が多いクライアントがわかっている場合は、そのボリュームにアクセスするクライアントの数を調整するか、ボリュームに対するI/Oの量を減らすことで、クラスタのパフォーマンスを向上できます。ボリュームが属しているQoSポリシーグループに対して、制限を適用または増やすこともできます。

クライアントとそのアプリケーションを調査して、クライアントが通常よりも多くのI/Oを送信しており、クラスタコンポーネントの競合を引き起こしている可能性があるかどうかを確認できます。[イベントの詳細]ページの[システム診断]セクションには、競合状態のコンポーネントを使用している上位のボリュームワークロードが表示されます。特定のボリュームにアクセスしているクライアントがわかった場合は、そのクライアントに移動して、クライアントのハードウェアまたはアプリケーションが正常に動作しているか、あるいは通常より負荷が増えていないかを確認できます。

MetroCluster構成では、ローカルクラスタ上のボリュームへの書き込み要求は、リモートクラスタ上のボリュームにミラーリングされます。ローカルクラスタのソースボリュームとリモートクラスタのデスティネーションボリュームの同期を維持すると、MetroCluster構成での両方のクラスタの要求が増加する可能性もあります。これらのミラーボリュームへの書き込み要求を減らすことで、クラスタが実行する同期処理が減り、他のワークロードのパフォーマンスへの影響が軽減されます。
