---
permalink: performance-checker/concept_what_data_continuity_collection_cycle_is.html 
sidebar: sidebar 
keywords: data, continuity, collection, cycle 
summary: データの継続性収集サイクルは、リアルタイムのクラスタパフォーマンス収集サイクル（デフォルトでは5分間隔）以外のパフォーマンスデータを収集します。データの継続性収集により、 Unified Manager がリアルタイムのデータを収集できなかった期間の統計データを補完することができます。 
---
= データの継続性収集サイクルとは
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
データの継続性収集サイクルは、リアルタイムのクラスタパフォーマンス収集サイクル（デフォルトでは5分間隔）以外のパフォーマンスデータを収集します。データの継続性収集により、 Unified Manager がリアルタイムのデータを収集できなかった期間の統計データを補完することができます。

Unified Manager は、次のイベントが発生したときにデータの継続性収集による履歴パフォーマンスデータのポーリングを実行します。

* クラスタが最初に Unified Manager に追加されたとき。
+
Unified Manager は、過去 15 日間の履歴パフォーマンスデータを収集します。これにより、クラスタが追加されてから数時間後に、2週間分の履歴パフォーマンス情報を表示できます。

+
また、前の期間にシステム定義のしきい値イベントがある場合は報告されます。

* 現在のパフォーマンスデータ収集サイクルが時間どおりに終了しません。
+
リアルタイムのパフォーマンスポーリングが5分間の収集期間を超えた場合は、不足している情報を収集するためにデータの継続性収集サイクルが開始されます。データの継続性収集が実行されなかった場合、次の収集期間がスキップされます。

* 次の状況により、 Unified Manager に一時的にアクセスできなくなり、そのあとオンラインに戻ったとき。
+
** 再起動されました。
** ソフトウェアのアップグレード中またはバックアップファイルの作成中にシャットダウンされました。
** ネットワーク停止から復旧した。


* 次の状況により、クラスタに一時的にアクセスできなくなり、そのあとオンラインに戻ったとき。
+
** ネットワーク停止から復旧した。
** 低速のワイドエリアネットワーク接続が原因で、通常のパフォーマンスデータの収集が遅れました。




データの継続性収集サイクルでは、最大24時間の履歴データを収集できます。Unified Manager が停止した状態が 24 時間以上続くと、 UI のページにパフォーマンスデータが表示されない期間が発生します。

データの継続性収集サイクルとリアルタイムのデータ収集サイクルを同時に実行することはできません。データの継続性収集サイクルが完了してから、リアルタイムのパフォーマンスデータ収集が開始される必要があります。1 時間以上の履歴データを収集するためにデータの継続性収集が必要な場合は、 Notifications ペインの上部に、そのクラスタのバナーメッセージが表示されます。
