---
permalink: performance-checker/concept_use_qos_policy_settings_to_prioritize_work_on_this_node.html 
sidebar: sidebar 
keywords: qos, policy, settings, prioritize, work, node 
summary: QoSポリシーグループに上限を設定して、ポリシーグループに含まれるワークロードの1秒あたりのI/O処理数（IOPS）やスループット（MBps）の上限を制御できます。ワークロードが属するポリシーグループに上限が設定されていない場合（デフォルトのポリシーグループなど）や、設定された上限がニーズに合わない場合は、設定された上限を引き上げるか、適切な上限が設定された新規または既存のポリシーグループにワークロードを移動できます。 
---
= QoSポリシーの設定を使用してこのノードでの作業の優先順位を決定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
QoSポリシーグループに上限を設定して、ポリシーグループに含まれるワークロードの1秒あたりのI/O処理数（IOPS）やスループット（MBps）の上限を制御できます。ワークロードが属するポリシーグループに上限が設定されていない場合（デフォルトのポリシーグループなど）や、設定された上限がニーズに合わない場合は、設定された上限を引き上げるか、適切な上限が設定された新規または既存のポリシーグループにワークロードを移動できます。

ノードのパフォーマンスイベントの原因がノードリソースを過剰に消費しているワークロードである場合は、[イベントの詳細]ページのイベントの説明に関連するボリュームのリストへのリンクが表示されます。パフォーマンス / ボリュームページで、影響を受けたボリュームを IOPS と MBps でソートすると、イベントの原因となった可能性がある使用率が最も高いワークロードを確認できます。

ノードリソースを過剰に消費しているボリュームをより制限の厳しいポリシーグループに割り当てることで、ポリシーグループによる調整でワークロードのアクティビティが制限され、そのノードでのリソースの使用が削減されます。

ONTAP System ManagerまたはONTAPコマンドを使用してポリシーグループを管理できます。これには次のタスクが含まれます。

* ポリシーグループの作成
* ポリシーグループ内のワークロードの追加または削除
* ポリシーグループ間でのワークロードの移動
* ポリシーグループのスループット制限の変更

