---
permalink: performance-checker/concept_unified_manager_performance_monitoring_features.html 
sidebar: sidebar 
keywords: unified manager, performance, monitoring, features 
summary: Unified Manager は、 ONTAP ソフトウェアを実行しているシステムからパフォーマンス統計を収集して分析します。動的なパフォーマンスしきい値とユーザ定義のパフォーマンスしきい値を使用して、多くのクラスタコンポーネントのさまざまなパフォーマンスカウンタを監視します。 
---
= Unified Managerのパフォーマンス監視機能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager は、 ONTAP ソフトウェアを実行しているシステムからパフォーマンス統計を収集して分析します。動的なパフォーマンスしきい値とユーザ定義のパフォーマンスしきい値を使用して、多くのクラスタコンポーネントのさまざまなパフォーマンスカウンタを監視します。

応答時間（レイテンシ）が長い場合は、ストレージオブジェクト（ボリュームなど）の処理速度が通常よりも遅いことを示しています。この問題は、ボリュームを使用しているクライアントアプリケーションのパフォーマンスが低下していることも示しています。Unified Manager はパフォーマンス問題が存在するストレージコンポーネントを特定し、そのパフォーマンス問題に対処するための推奨される対処策を提示します。

Unified Manager には次の機能があります。

* ONTAPソフトウェアを実行しているシステムからワークロードのパフォーマンス統計を監視および分析します。
* クラスタ、ノード、アグリゲート、ポート、 SVM のパフォーマンスカウンタを追跡します。 ボリューム、 LUN 、 NVMe ネームスペース、およびネットワークインターフェイス（ LIF ）。
* IOPS（処理数）、MBps（スループット）、レイテンシ（応答時間）、利用率、パフォーマンス容量、キャッシュ比率など、ワークロードのアクティビティの推移を示す詳細なグラフが表示されます。
* しきい値を超えたときにイベントをトリガーしてEメールアラートを送信する、ユーザ定義のパフォーマンスしきい値ポリシーを作成できます。
* システム定義のしきい値とワークロードのアクティビティを学習する動的なパフォーマンスしきい値を使用して、パフォーマンスの問題を特定してアラートを送信します。
* ボリュームやLUNに適用されているサービス品質（QoS）ポリシーとパフォーマンスサービスレベルポリシー（PSL）を特定します。
* 競合状態にあるクラスタコンポーネントを特定します。
* クラスタコンポーネントを過剰に消費しているワークロードと、アクティビティの増加によってパフォーマンスが影響を受けたワークロードを特定します。

