---
permalink: performance-checker/reference_components_of_node_failover_planning_page.html 
sidebar: sidebar 
keywords: components, node, failover, planning page, performance, statistics, grid 
summary: Performance / Node Failover Planning ページのコンポーネントが、グリッドと Comparing ペインに表示されます。これらのセクションでは、ノードフェイルオーバーがテイクオーバーノードのパフォーマンスに与える影響を評価できます。 
---
= [Node Failover Planning]ページのコンポーネント
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Performance / Node Failover Planning ページのコンポーネントが、グリッドと Comparing ペインに表示されます。これらのセクションでは、ノードフェイルオーバーがテイクオーバーノードのパフォーマンスに与える影響を評価できます。



== パフォーマンス統計グリッド

Performance/NodeFailover Planning ヘエシには、レイテンシ、 IOPS 、利用率、使用済みパフォーマンス容量の統計を含むグリッドが表示されます。

[NOTE]
====
このページおよび Performance/NodePerformance Explorer ページに表示されるレイテンシと IOPS の値は一致しないことがあります。異なるパフォーマンスカウンタを使用してノードフェイルオーバーを予測するために値が計算されるためです。

====
グリッドでは、各ノードに次のいずれかのロールが割り当てられます。

* プライマリ
+
HAパートナーで障害が発生した場合にパートナーをテイクオーバーするノード。ルートオブジェクトは常にプライマリノードです。

* パートナー
+
フェイルオーバーシナリオで障害が発生したノード。

* 推定テイクオーバー
+
プライマリノードと同じ。このノードについて表示されるパフォーマンス統計には、障害が発生したパートナーをテイクオーバーしたあとのテイクオーバーノードのパフォーマンスが表示されます。



[NOTE]
====
テイクオーバーノードのワークロードはフェイルオーバー後の両方のノードのワークロードの合計に相当しますが、推定テイクオーバーノードの統計はプライマリノードとパートナーノードの統計の合計にはなりません。たとえば、プライマリノードのレイテンシが2ミリ秒/処理でパートナーノードのレイテンシが3ミリ秒/処理の場合、推定テイクオーバーノードのレイテンシが4ミリ秒/処理になることがあります。この値は Unified Manager で計算されます。

====
パートナーノードをルートオブジェクトにする場合は、パートナーノードの名前をクリックします。Performance/NodePerformance Explorer ヘエシが表示されたら、 * Failover Planning * タブをクリックして、このノード障害シナリオにおけるパフォーマンスの変化を確認できます。たとえば、Node1がプライマリノードでNode2がパートナーノードの場合、Node2をクリックしてプライマリノードにすることができます。これにより、障害が発生したノードに応じて推定パフォーマンスがどのように変化するかを確認できます。



== 比較ペイン

デフォルトでは ' 比較ペインに表示される構成部品は次のとおりです

* * イベントチャート *
+
これらの値は、 Performance/NodePerformance Explorer ページと同じ形式で表示されます。プライマリノードのみに関係します。

* * カウンタチャート *
+
グリッドに表示されるパフォーマンスカウンタの履歴統計が表示されます。各チャートの推定テイクオーバーノードのグラフには、ある時点でフェイルオーバーが発生した場合の推定パフォーマンスが表示されます。

+
たとえば、利用率のグラフに、推定テイクオーバー ノードの2月8日午前11時の利用率が73%と表示されているとします。この時点でフェイルオーバーが発生していた場合、テイクオーバーノードの利用率は73%になります。

+
過去の統計は、フェイルオーバーを開始する最適な時間を特定するのに役立ち、テイクオーバーノードに過剰な負荷がかかる可能性を最小限に抑えることができます。フェイルオーバーのスケジュールは、テイクオーバーノードの予測パフォーマンスが許容範囲内である場合にのみ設定できます。



デフォルトでは、ルートオブジェクトとパートナーノードの両方の統計情報が比較ペインに表示されます。Performance/NodePerformance Explorer ページとは異なり、このページには統計比較用のオブジェクトを追加するための *Add* ボタンは表示されません。

[Performance/Node Performance Explorer] ページで行うのと同じ方法で、 [Comparing （比較） ] ペインをカスタマイズできます。グラフのカスタマイズ例を次に示します。

* ノード名をクリックすると、カウンタグラフでノードの統計の表示と非表示が切り替わります。
* 特定のカウンタの詳細なグラフを新しいウィンドウに表示するには、 * Zoom View * をクリックします。

