---
permalink: performance-checker/reference_performance_event_analysis_and_notification.html 
sidebar: sidebar 
keywords: performance, event, analysis, notification 
summary: パフォーマンスイベントは、クラスタコンポーネントの競合に起因するワークロードのI/Oパフォーマンスの問題を通知します。Unified Manager はイベントを分析して、関連するすべてのワークロード、競合状態のコンポーネント、および解決する必要のある問題かどうかを特定します。 
---
= パフォーマンスイベントの分析と通知
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
パフォーマンスイベントは、クラスタコンポーネントの競合に起因するワークロードのI/Oパフォーマンスの問題を通知します。Unified Manager はイベントを分析して、関連するすべてのワークロード、競合状態のコンポーネント、および解決する必要のある問題かどうかを特定します。

Unified Manager は、クラスタ上のボリュームの I/O レイテンシ（応答時間）と IOPS （処理数）を監視します。たとえば、他のワークロードがクラスタコンポーネントを過剰に使用している場合、そのコンポーネントは競合状態にあり、ワークロードの要件を満たす最適なレベルのパフォーマンスを提供できません。同じコンポーネントを使用している他のワークロードのパフォーマンスに影響が生じ、レイテンシが増大する可能性があります。レイテンシが動的なパフォーマンスしきい値を超えると、Unified Managerはパフォーマンスイベントをトリガーしてユーザに通知します。



== イベント分析

Unified Manager は、過去 15 日間のパフォーマンス統計を使用して次の分析を実行し、 Victim ワークロード、 Bully ワークロード、およびイベントに関連するクラスタコンポーネントを特定します。

* レイテンシがレイテンシ予測の上限である動的なパフォーマンスしきい値を超えたVictimワークロードを特定します。
+
** HDD または Flash Pool のハイブリッドアグリゲート（ローカル階層）のボリュームの場合、レイテンシが 5 ミリ秒を超え、かつ IOPS が 1 秒あたり 10 件（ ops/sec ）を超えた場合にのみイベントがトリガーされます。
** オールSSDアグリゲートまたはFabricPoolアグリゲート（クラウド階層）のボリュームの場合、レイテンシが1ミリ秒を超え、かつIOPSが100ops/秒を超えた場合にのみイベントがトリガーされます。


* 競合状態のクラスタコンポーネントを特定します。
+
[NOTE]
====
クラスタインターコネクトで Victim ワークロードのレイテンシが 1 ミリ秒を超えた場合、 Unified Manager はこれを重大な状況とみなしてクラスタインターコネクトのイベントをトリガーします。

====
* クラスタコンポーネントを過剰に消費して競合状態にしているBullyワークロードを特定します。
* クラスタコンポーネントの利用率またはアクティビティの偏差に基づいて関連するワークロードをランク付けし、クラスタコンポーネントの使用量の変化が最も大きいBullyワークロードと最も影響が大きいVictimワークロードを特定します。


ごく短時間しか発生せず、コンポーネントの競合状態が解消した時点で自己修復されるイベントもあります。継続的なイベントとは、同じクラスタコンポーネントについて5分以内に再発生し、アクティブな状態のままのイベントです。Unified Manager は、連続する 2 つの分析期間に同じイベントを検出するとアラートをトリガーします。

解決されたイベントは、ボリュームの過去のパフォーマンス問題の記録として Unified Manager で引き続き参照できます。各イベントには、イベントタイプ、およびボリューム、クラスタ、および関連するクラスタコンポーネントを識別する一意のIDが割り当てられます。

[NOTE]
====
1つのボリュームが同時に複数のイベントに関与している可能性があります。

====


== イベントの状態

イベントは次のいずれかの状態になります。

* * アクティブ *
+
現在アクティブなパフォーマンスイベント（新規または確認済み）を示します。自己修復または解決されていないイベントです。ストレージオブジェクトのパフォーマンスカウンタがパフォーマンスしきい値を超えたままになっている。

* * 廃止 *
+
アクティブではなくなったイベントを示します。自己修復または解決されたイベント。ストレージオブジェクトのパフォーマンスカウンタがパフォーマンスしきい値を超えなくなりました。





== イベント通知

イベントは[ダッシュボード]ページおよびユーザインターフェイスの他の多くのページに表示され、それらのイベントに関するアラートが指定したEメールアドレスに送信されます。[イベントの詳細]ページおよび[ワークロード分析]ページでは、イベントに関する詳細な分析情報を表示し、推奨される解決方法を確認できます。



== イベントの相互作用

[イベントの詳細]ページおよび[ワークロード分析]ページでは、次の方法でイベントを操作できます。

* イベントの上にマウスを移動すると、イベントが検出された日時を示すメッセージが表示されます。
+
同じ期間に複数のイベントがある場合は、イベントの数がメッセージに表示されます。

* 単一のイベントをクリックすると、関連するクラスタコンポーネントなど、イベントの詳細情報を示すダイアログボックスが表示されます。
+
競合状態のコンポーネントは赤い丸で囲んで表示されます。[ 完全な解析を表示（ View full analysis ） ] をクリックすると、 [ イベントの詳細（ Event details ） ] ページに完全な解析を表示できます。同じ期間に複数のイベントがある場合は、最新の3つのイベントの詳細がダイアログボックスに表示されます。イベントをクリックすると、[イベントの詳細]ページでイベント分析を確認できます。


