---
permalink: performance-checker/reference_types_of_performance_counter_charts.html 
sidebar: sidebar 
keywords: types, performance, counter, charts 
summary: 標準のパフォーマンスチャートには、選択したストレージオブジェクトのカウンタの値が表示されます。内訳カウンタグラフには、合計値が読み取り、書き込み、その他のカテゴリに分けて表示されます。さらに、一部の内訳カウンタグラフには、その他の詳細情報が表示されます（グラフがズームビューに表示される場合）。 
---
= パフォーマンスカウンタグラフのタイプ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
標準のパフォーマンスチャートには、選択したストレージオブジェクトのカウンタの値が表示されます。内訳カウンタグラフには、合計値が読み取り、書き込み、その他のカテゴリに分けて表示されます。さらに、一部の内訳カウンタグラフには、その他の詳細情報が表示されます（グラフがズームビューに表示される場合）。

次の表に、使用可能なパフォーマンスカウンタグラフを示します。

|===
| 使用可能なチャート | Chart 概要（チャート） 


 a| 
イベント
 a| 
ルートオブジェクトの統計グラフに関連して、重大、エラー、警告、および情報のイベントが表示されます。パフォーマンスイベントに加えて健全性イベントが表示され、パフォーマンスに影響を及ぼす可能性がある理由の全体像が示されます。



 a| 
レイテンシ - 合計
 a| 
アプリケーションの要求に応答するまでのミリ秒数。平均レイテンシの値はI/Oの加重値です。



 a| 
レイテンシ - 内訳
 a| 
[レイテンシ-合計]と同じ情報が表示されますが、パフォーマンスデータが読み取り、書き込み、その他のレイテンシに分けて表示されます。このグラフは、選択したオブジェクトが SVM 、ノード、アグリゲート、ボリューム、 LUN である場合にのみ表示されます。 またはネームスペースです。



 a| 
レイテンシ-クラスタコンポーネント
 a| 
[レイテンシ-合計]と同じ情報が表示されますが、パフォーマンスデータがクラスタコンポーネント別のレイテンシに分けて表示されます。このグラフは、選択したオブジェクトがボリュームの場合にのみ表示されます。



 a| 
IOPS - 合計
 a| 
1秒あたりの入出力処理数ノードに対して表示される場合、「 Total 」を選択すると、そのノードを経由する（ローカルノードまたはリモートノード上の）データの IOPS が表示されます。「 Total （ Local ）」を選択すると、現在のノード上のデータの IOPS が表示されます。



 a| 
IOPS - 内訳
 a| 
[IOPS -合計]と同じ情報が表示されますが、パフォーマンスデータが読み取りIOPS、書き込みIOPS、その他のIOPSに分けて表示されます。このグラフは、選択したオブジェクトが SVM 、ノード、アグリゲート、ボリューム、 LUN である場合にのみ表示されます。 またはネームスペースです。

ズームビューに表示される場合、ボリュームのグラフにはQoS最小/最大スループット値が表示されます（ONTAPで設定されている場合）。

ノードに対して表示される場合、「内訳」を選択すると、そのノードを経由する（ローカルノードまたはリモートノード上の）データの IOPS の内訳が表示されます。「内訳（ローカル）」を選択すると、現在のノード上のデータの IOPS の内訳が表示されます。



 a| 
IOPS - プロトコル
 a| 
[IOPS -合計]と同じ情報が表示されますが、パフォーマンスデータがCIFS、NFS、FCP、NVMe、iSCSIのプロトコルトラフィックの個 々 のグラフに分けて表示されます。このグラフは、選択したオブジェクトが SVM の場合にのみ表示されます。



 a| 
IOPS/TB - 合計
 a| 
ワークロードで消費される合計スペース（TB）に基づく、1秒あたりの入出力処理数。I/O密度とも呼ばれます。このカウンタは、所定のストレージ容量で提供できるパフォーマンスを測定します。ズームビューに表示される場合、ボリュームのグラフにはQoS想定/最大スループット値が表示されます（ONTAPで設定されている場合）。

このグラフは、選択したオブジェクトがボリュームの場合にのみ表示されます。



 a| 
MBps - 合計
 a| 
オブジェクトとの間で転送される1秒あたりのデータ量（MB）。



 a| 
MBps - 内訳
 a| 
[MBps]グラフと同じ情報が表示されますが、スループットデータがディスク読み取り、Flash Cache読み取り、書き込み、その他に分けて表示されます。ズームビューに表示される場合、ボリュームのグラフにはQoS最大スループット値が表示されます（ONTAPで設定されている場合）。

このグラフは、選択したオブジェクトが SVM 、ノード、アグリゲート、ボリューム、 LUN である場合にのみ表示されます。 またはネームスペースです。

[NOTE]
====
Flash Cacheのデータは、ノードにFlash Cacheモジュールがインストールされている場合にのみ表示されます。

====


 a| 
使用済みパフォーマンス容量 - 合計
 a| 
ノードまたはアグリゲートによるパフォーマンス容量の消費率。



 a| 
使用済みパフォーマンス容量 - 内訳
 a| 
使用済みパフォーマンス容量のデータをユーザプロトコルとシステムのバックグラウンドプロセスに分けて表示します。また、空きパフォーマンス容量が表示されます。



 a| 
使用可能な IOPS - 合計
 a| 
このオブジェクトで現在使用可能な（空き）1秒あたりの入出力処理数。この数値は、 Unified Manager がオブジェクトで実行可能と計算する合計 IOPS から現在使用されている IOPS を引いた結果です。このグラフは、選択したオブジェクトがノードまたはアグリゲートの場合にのみ表示されます。



 a| 
利用率-合計
 a| 
オブジェクトの使用可能なリソースの使用率。利用率は、ノードの利用率（ノードの場合）、ディスクの利用率（アグリゲートの場合）、帯域幅の利用率（ポートの場合）です。このグラフは、選択したオブジェクトがノード、アグリゲート、またはポートの場合にのみ表示されます。



 a| 
キャッシュミス率-合計
 a| 
クライアントアプリケーションからの読み取り要求のうち、キャッシュからではなくディスクからデータが返される割合。このグラフは、選択したオブジェクトがボリュームの場合にのみ表示されます。

|===