---
permalink: performance-checker/reference_managed_objects_pane.html 
sidebar: sidebar 
keywords: managed, objects, pane 
summary: Performance Summary タブの Managed Objects ペインには、クラスタのストレージオブジェクトタイプと数の概要が表示されます。このペインでは、各クラスタ内のオブジェクトのステータスを追跡できます。 
---
= [管理対象オブジェクト]ペイン
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Performance Summary タブの Managed Objects ペインには、クラスタのストレージオブジェクトタイプと数の概要が表示されます。このペインでは、各クラスタ内のオブジェクトのステータスを追跡できます。

管理オブジェクト数は、前回の収集期間におけるポイントインタイムデータです。新しいオブジェクトは15分間隔で検出されます。

オブジェクトタイプの数をクリックすると、そのオブジェクトタイプのオブジェクトパフォーマンスインベントリページが表示されます。オブジェクトのインベントリページには、このクラスタ上のオブジェクトだけが表示されます。

管理対象オブジェクトは次のとおりです。

* * ノード * ：
+
クラスタ内の物理システム。

* * アグリゲート *
+
保護とプロビジョニングのために1つのユニットとして管理できる、複数のRedundant Array of Independent Disks（RAID）グループのセット。

* * ポート * ：
+
ネットワーク上の他のデバイスへの接続に使用されるノード上の物理接続ポイント。

* * ストレージ VMs *
+
一意のネットワークアドレスを使用してネットワークアクセスを提供する仮想マシン。SVM は、固有のネームスペースからデータを提供でき、クラスタの残りのエンティティとは別に管理することができます。

* * ボリューム *
+
サポートされている1つ以上のアクセスプロトコルを使用してアクセス可能なユーザデータを保持する論理エンティティ。この数には、FlexVolとFlexGroupの両方が含まれます。FlexGroupコンスティチュエントは含まれません。

* * LUN*
+
Fibre Channel（FC；ファイバチャネル）論理ユニットまたはiSCSI論理ユニットの識別子。論理ユニットは通常ストレージボリュームに対応し、コンピュータオペレーティングシステム内ではデバイスとして表されます。

* * ネットワーク・インターフェイス *
+
ノードへのネットワークアクセスポイントを表す論理ネットワークインターフェイス。この数には、すべてのインターフェイスタイプが含まれます。


