---
permalink: performance-checker/reference_what_data_does_workload_analyzer_display.html 
sidebar: sidebar 
keywords: workload analyzer, charts, display, data 
summary: '[Workload Analyzer]ページには、ワークロードに影響している可能性があるイベントの情報、イベントの原因となっている問題を修正するための推奨事項、およびパフォーマンスと容量の履歴を分析するためのグラフが表示されます。' 
---
= Workload Analyzerで表示されるデータ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
[Workload Analyzer]ページには、ワークロードに影響している可能性があるイベントの情報、イベントの原因となっている問題を修正するための推奨事項、およびパフォーマンスと容量の履歴を分析するためのグラフが表示されます。

ページの上部では、分析するワークロード（ボリュームまたはLUN）の名前と、統計を表示する期間を指定します。表示する期間はいつでも短縮または延長することができます。

ページの他の領域には、分析結果およびパフォーマンスと容量のグラフが表示されます。

[NOTE]
====
LUNのワークロードグラフには、ボリュームのワークロードグラフと同じレベルの統計が表示されないため、この2つのタイプのワークロードで異なる値が表示されることがあります。

====
* * イベントサマリ領域 *
+
期間内に発生したイベントの数とタイプの概要が表示されます。複数の領域（パフォーマンスと容量など）に影響するイベントがある場合は、ここから必要なイベント タイプの詳細を選択できます。イベント タイプをクリックすると、イベント名のリストが表示されます。

+
期間中にイベントが1つしか発生しなかった場合は、一部のイベントについて問題を解決するための推奨事項のリストが表示されます。

* * イベントタイムライン *
+
指定した期間内に発生したすべてのイベントが表示されます。各イベントにカーソルを合わせると、イベント名が表示されます。

+
イベントの詳細ページから * ワークロードの分析 * ボタンをクリックしてこのページを表示した場合は、選択したイベントのアイコンが大きく表示され、イベントを特定できます。

* * パフォーマンスチャート領域 *
+
選択した期間のレイテンシ、スループット（IOPSとMBpsの両方）、利用率（ノードとアグリゲートの両方）のグラフが表示されます。さらに分析を行う場合は、 View performance details リンクをクリックしてワークロードの Performance Explorer ページを表示できます。

+
** * Latency * は選択した期間のワークロードのレイテンシを表示します。グラフには次の3つのビューがあります。
+
*** * 合計 * レイテンシ
*** * 内訳 * レイテンシ（読み取り、書き込み、その他のプロセスによる内訳）
*** * クラスタコンポーネント * レイテンシ（クラスタコンポーネント別）






ここに表示されるクラスタコンポーネントの説明については、を参照してくださいlink:concept_cluster_components_and_why_they_can_be_in_contention.html["クラスタコンポーネントと競合する理由"]。** * Throughput * には、選択した期間におけるワークロードの IOPS と MBps の両方のスループットが表示されます。このグラフには 4 つのビューがあり、それぞれ以下を確認できます。 *** * 合計スループット *** * 内訳 * スループット（読み取り、書き込み、その他のプロセスで内訳） *** クラウドスループット * （クラウドへのデータの書き込みとクラウドからのデータの読み取りに使用される MBps 。 容量をクラウドに階層化しているワークロードの場合） *** 予測付き IOPS * （ IOPS スループットの上限と下限の値が時間枠を超えて想定される予測）このチャートには、サービス品質（ QoS ）の最大スループットと最小スループットのしきい値の設定も表示されます（設定されている場合）。 そのため、 QoS ポリシーによって意図的にスループットが制限されているかどうかを確認することができます。** * Utilization * には、選択した期間にワークロードが実行されているアグリゲートとノードの両方の利用率が表示されます。ここから、アグリゲートまたはノードが過剰に使用され、レイテンシが高くなっていないかどうかを確認できます。FlexGroupボリュームを分析している場合は、利用率グラフに複数のノードと複数のアグリゲートが表示されます。

* * 容量チャート領域 *
+
過去1カ月のワークロードのデータ容量とSnapshot容量のグラフが表示されます。

+
ボリュームについては、容量の詳細の表示リンクをクリックして、詳細な分析を行う場合に備えてワークロードの健全性の詳細ページを表示できます。LUN の健全性の詳細ページがないため、 LUN ではこのリンクは表示されません。

+
** * 容量ビュー * ：ワークロードに割り当てられている使用可能な合計スペースと使用済みの論理スペースが表示されます（ネットアップによるすべての最適化の完了後）。
** * Snapshot ビュー * には、 Snapshot コピー用にリザーブされているスペースの合計と、現在使用されているスペースの量が表示されます。LUNにはSnapshotビューはありません。
** * クラウド階層ビュー * には、ローカルのパフォーマンス階層で使用されている容量とクラウド階層で使用されている容量が表示されます。これらのグラフには、このワークロードの容量がフルになるまでの推定残り時間が表示されます。この情報は過去の使用状況に基づいており、最低10日分のデータが必要です。Unified Manager は、容量が 30 日未満になるとストレージを「ほぼフル」とみなします。



