---
permalink: performance-checker/reference_performance_event_severity_types.html 
sidebar: sidebar 
keywords: performance, event, severity, types 
summary: パフォーマンスイベントには、対処する際の優先度を判別できるように、それぞれ重大度タイプが関連付けられています。 
---
= パフォーマンスイベントの重大度タイプ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
パフォーマンスイベントには、対処する際の優先度を判別できるように、それぞれ重大度タイプが関連付けられています。

* * 重要 *
+
パフォーマンスイベントが発生しました。すぐに対処しないとサービスが停止する可能性があります。

+
重大イベントは、ユーザ定義のしきい値からのみ生成されます。

* * 警告 *
+
クラスタオブジェクトのパフォーマンスカウンタが正常な範囲外であるため、重大な重大度に達しないように監視する必要があります。この重大度のイベントではサービスは停止しないため、すぐに対処する必要はありません。

+
警告イベントは、システムまたはユーザ定義のしきい値、あるいは動的なしきい値から生成されます。

* * 情報 *
+
新しいオブジェクトが検出されたときやユーザ操作が実行されたときに発生します。たとえば、ストレージオブジェクトが削除された場合や設定が変更された場合は、重大度タイプが「情報」のイベントが生成されます。

+
情報イベントは、設定の変更を検出すると、ONTAPから直接送信されます。



詳細については、次のリンクを参照してください。

* link:../events/concept_what_happens_when_an_event_is_received.html["イベント受信時の動作"]
* link:../events/concept_what_information_is_contained_in_an_alert_email.html["アラートEメールに含まれる情報"]
* link:../events/task_add_alerts.html["アラートの追加"]
* link:../events/task_add_alerts_for_performance_events.html["パフォーマンスイベントのアラートの追加"]

