---
permalink: performance-checker/reference_what_performance_metrics_can_be_monitored_using_thresholds.html 
sidebar: sidebar 
keywords: performance, counters, tracked, thresholds 
summary: IOPSやMBpsなど、一部の共通のパフォーマンスカウンタでは、すべてのストレージオブジェクトに対してしきい値を設定できます。他にも、特定のストレージオブジェクトに対してのみしきい値を設定できるカウンタがあります。 
---
= しきい値を使用して追跡できるパフォーマンスカウンタ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
IOPSやMBpsなど、一部の共通のパフォーマンスカウンタでは、すべてのストレージオブジェクトに対してしきい値を設定できます。他にも、特定のストレージオブジェクトに対してのみしきい値を設定できるカウンタがあります。



== 使用可能なパフォーマンスカウンタ

|===
| ストレージオブジェクト | パフォーマンスカウンタ | 製品説明 


 a| 
クラスタ
 a| 
IOPS
 a| 
クラスタで処理される1秒あたりの平均入出力処理数



 a| 
MB/秒
 a| 
このクラスタとの間で転送される1秒あたりの平均データ量（MB）



 a| 
ノード
 a| 
IOPS
 a| 
ノードで処理される1秒あたりの平均入出力処理数



 a| 
MB/秒
 a| 
このノードとの間で転送される1秒あたりの平均データ量（MB）



 a| 
レイテンシ
 a| 
ノードがアプリケーションの要求に応答するまでの平均時間（ミリ秒）



 a| 
利用率
 a| 
ノードのCPUとRAMの平均使用率。



 a| 
使用済みパフォーマンス容量
 a| 
ノードによるパフォーマンス容量の平均消費率



 a| 
使用済みパフォーマンス容量 - テイクオーバー
 a| 
ノードによるパフォーマンス容量の平均消費率とパートナーノードのパフォーマンス容量



 a| 
アグリゲート
 a| 
IOPS
 a| 
アグリゲートで処理される1秒あたりの平均入出力処理数



 a| 
MB/秒
 a| 
このアグリゲートとの間で転送される1秒あたりの平均データ量（MB）



 a| 
レイテンシ
 a| 
アグリゲートがアプリケーションの要求に応答するまでの平均時間（ミリ秒）



 a| 
利用率
 a| 
アグリゲートのディスクの平均使用率



 a| 
使用済みパフォーマンス容量
 a| 
アグリゲートによるパフォーマンス容量の平均消費率



 a| 
Storage VM
 a| 
IOPS
 a| 
SVMで処理される1秒あたりの平均入出力処理数



 a| 
MB/秒
 a| 
このSVMとの間で転送される1秒あたりの平均データ量（MB）



 a| 
レイテンシ
 a| 
SVMがアプリケーションの要求に応答するまでの平均時間（ミリ秒）



 a| 
ボリューム
 a| 
IOPS
 a| 
ボリュームで処理される1秒あたりの平均入出力処理数



 a| 
MB/秒
 a| 
このボリュームとの間で転送される1秒あたりの平均データ量（MB）



 a| 
レイテンシ
 a| 
ボリュームがアプリケーションの要求に応答するまでの平均時間（ミリ秒）



 a| 
キャッシュミス率
 a| 
クライアントアプリケーションからの読み取り要求に対してキャッシュからではなくボリュームからデータが返される割合の平均値



 a| 
LUN
 a| 
IOPS
 a| 
LUNで処理される1秒あたりの平均入出力処理数



 a| 
MB/秒
 a| 
このLUNとの間で転送される1秒あたりの平均データ量（MB）



 a| 
レイテンシ
 a| 
LUNがアプリケーションの要求に応答するまでの平均時間（ミリ秒）



 a| 
ネームスペース
 a| 
IOPS
 a| 
ネームスペースで処理される1秒あたりの平均入出力処理数



 a| 
MB/秒
 a| 
このネームスペースとの間で転送される1秒あたりの平均データ量（MB）



 a| 
レイテンシ
 a| 
ネームスペースがアプリケーションの要求に応答するまでの平均時間（ミリ秒）



 a| 
ポート
 a| 
帯域幅の使用量
 a| 
ポートの使用可能な帯域幅の平均使用率



 a| 
MB/秒
 a| 
このポートとの間で転送される1秒あたりの平均データ量（MB）



 a| 
ネットワークインターフェイス（LIF）
 a| 
MB/秒
 a| 
このLIFとの間で転送される1秒あたりの平均データ量（MB）

|===