---
permalink: performance-checker/reference_types_of_system_defined_performance_threshold_policies.html 
sidebar: sidebar 
keywords: system-defined, performance, threshold, policies, cluster, node. aggregate, qos 
summary: Unified Manager には、クラスタのパフォーマンスを監視し、イベントを自動生成する標準のしきい値ポリシーがいくつか用意されています。これらのポリシーはデフォルトで有効になっており、監視対象のパフォーマンスしきい値を超えたときに警告イベントまたは情報イベントを生成します。 
---
= システム定義のパフォーマンスしきい値ポリシーのタイプ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager には、クラスタのパフォーマンスを監視し、イベントを自動生成する標準のしきい値ポリシーがいくつか用意されています。これらのポリシーはデフォルトで有効になっており、監視対象のパフォーマンスしきい値を超えたときに警告イベントまたは情報イベントを生成します。

[NOTE]
====
システム定義のパフォーマンスしきい値ポリシーは、 Cloud Volumes ONTAP 、 ONTAP Edge 、 ONTAP Select の各システムでは無効です。

====
システム定義のパフォーマンスしきい値ポリシーから不要なイベントが送られてくる場合は、[イベントセットアップ]ページで個 々 のポリシーのイベントを無効にすることができます。



== クラスタのしきい値ポリシー

システム定義のクラスタパフォーマンスしきい値ポリシーは、 Unified Manager で監視されている各クラスタにデフォルトで割り当てられます。

* * クラスタ負荷の不均衡 *
+
クラスタ内の1つのノードの負荷が他のノードよりもはるかに高く、ワークロードのレイテンシに影響を及ぼしている可能性がある状況を特定します。

+
これは、クラスタ内のすべてのノードの使用済みパフォーマンス容量の値を比較して、24時間以上にわたって30%のしきい値を超えていないノードがないかどうかを確認することで行われます。これは警告イベントです。

* * クラスタ容量の不均衡 *
+
1つのアグリゲートの使用済み容量がクラスタ内の他のアグリゲートよりもはるかに多く、処理に必要なスペースに影響を及ぼす可能性がある状況を特定します。

+
クラスタ内のすべてのアグリゲートの使用済み容量の値が比較され、70%の差があるかどうかが確認されます。これは警告イベントです。





== ノードのしきい値ポリシー

システム定義のノードパフォーマンスしきい値ポリシーは、 Unified Manager で監視されているクラスタ内の各ノードにデフォルトで割り当てられます。

* * 使用済みパフォーマンス容量しきい値を超過 *
+
単一のノードが運用効率の上限を超えて稼働しており、ワークロードのレイテンシに影響を及ぼしている可能性がある状況を特定します。

+
100%以上のパフォーマンス容量を12時間以上使用しているノードが特定されます。これは警告イベントです。

* * 利用率の高いノード HA ペア *
+
HA ペアのノードが HA ペアの運用効率の上限を超えて稼働している状況を特定します。

+
HA ペアの 2 つのノードの使用済みパフォーマンス容量の値が確認されます。2つのノードの使用済みパフォーマンス容量の合計が12時間以上にわたって200%を超えると、コントローラフェイルオーバーがワークロードのレイテンシに影響します。これは情報イベントです。

* * ノードディスクの断片化 *
+
アグリゲート内の1つまたは複数のディスクが断片化されており、主要なシステムサービスの速度が低下し、ノード上のワークロードのレイテンシに影響を及ぼしている可能性がある状況を特定します。

+
ノード上のすべてのアグリゲートで特定の読み取り / 書き込み処理の比率が確認されます。このポリシーは、SyncMirrorの再同期中やディスクスクラビング処理中にエラーが検出された場合にもトリガーされることがあります。これは警告イベントです。

+
[NOTE]
====
「ノードディスクの断片化」ポリシーは、 HDD のみのアグリゲートを分析します。 Flash Pool 、 SSD 、および FabricPool の各アグリゲートは分析しません。

====




== アグリゲートのしきい値ポリシー

システム定義のアグリゲートパフォーマンスしきい値ポリシーは、 Unified Manager で監視されているクラスタ内の各アグリゲートにデフォルトで割り当てられます。

* * 利用率の高いアグリゲートディスク *
+
アグリゲートが運用効率の上限を超えて稼働していて、ワークロードのレイテンシに影響を及ぼしている可能性がある状況を特定します。このような状況では、アグリゲート内のディスクの利用率が30分以上95%を超えているアグリゲートが検索されます。この複数条件ポリシーは、次の分析を実行して問題の原因を特定します。

+
** アグリゲート内のディスクがバックグラウンドでメンテナンス作業を実行中かどうか。
+
ディスクでバックグラウンドで実行されるメンテナンス作業には、ディスクの再構築、ディスクスクラビング、SyncMirrorの再同期、再パリティ化などがあります。

** ディスクシェルフのFibre Channelインターコネクトに通信のボトルネックはありますか。
** アグリゲートの空きスペースが不足しているか。3つの下位ポリシーのうち1つ（または複数）にも違反しているとみなされた場合にのみ、このポリシーに対して警告イベントが発行されます。アグリゲート内のディスクの利用率が95%を超えている場合のみ、パフォーマンスイベントはトリガーされません。




[NOTE]
====
「利用率の高いディスクを集約」ポリシーは、 HDD のみのアグリゲートと Flash Pool （ハイブリッド）アグリゲートを分析します。 SSD アグリゲートと FabricPool アグリゲートは分析しません。

====


== ワークロードレイテンシのしきい値ポリシー

システム定義のワークロード遅延しきい値ポリシーは、「想定レイテンシ」の値が定義されたパフォーマンスサービスレベルポリシーが設定されているワークロードに割り当てられます。

* * パフォーマンスサービスレベル * に定義されたワークロードのボリューム / LUN レイテンシしきい値を超過
+
ボリューム（ファイル共有）と LUN のうち、「想定レイテンシ」の制限を超えていて、ワークロードのパフォーマンスに影響を及ぼしているものを特定します。これは警告イベントです。

+
想定レイテンシの値を超えた過去1時間のうちに30%の時間が経過したワークロードが検索されます。





== QoSのしきい値ポリシー

システム定義のQoSパフォーマンスしきい値ポリシーは、ONTAP QoS最大スループットポリシー（IOPS、IOPS/TB、またはMBps）が設定されているワークロードに割り当てられます。ワークロードのスループットの値が設定されたQoS値を15%下回ると、Unified Managerはイベントをトリガーします。

* * QoS 最大 IOPS または MBps しきい値 *
+
IOPSまたはMBpsがQoS最大スループット制限を超えていて、ワークロードのレイテンシに影響を及ぼしているボリュームおよびLUNを特定します。これは警告イベントです。

+
ポリシーグループに割り当てられているワークロードが1つだけの場合、割り当てられているQoSポリシーグループで定義されている最大スループットのしきい値を超えているワークロードが過去1時間の各収集期間に検出されます。

+
複数のワークロードで1つのQoSポリシーを共有している場合は、ポリシーに含まれるすべてのワークロードのIOPSまたはMBpsが加算され、その合計がしきい値を超えていないかどうかが確認されます。

* * QoS ピーク IOPS/TB またはブロックサイズしきい値 *
+
IOPS/TBがアダプティブQoSピークスループット制限（またはブロックサイズ指定のIOPS/TB制限）を超えていて、ワークロードのレイテンシに影響を及ぼしているボリュームを特定します。これは警告イベントです。

+
アダプティブQoSポリシーで定義されているIOPS/TBのピークしきい値を各ボリュームのサイズに基づいてQoS最大IOPSの値に変換し、過去1時間の各パフォーマンス収集期間にQoS最大IOPSを超えているボリュームがないかどうかを確認します。

+
[NOTE]
====
このポリシーは、クラスタにONTAP 9.3以降のソフトウェアがインストールされている場合にのみボリュームに適用されます。

====
+
アダプティブ QoS ポリシーに「 block size 」要素が定義されている場合、しきい値は各ボリュームのサイズに基づいて QoS の最大 MBps の値に変換されます。過去1時間の各パフォーマンス収集期間にこの値を超えているボリュームがないかどうかが確認されます。

+
[NOTE]
====
このポリシーは、クラスタにONTAP 9.5以降のソフトウェアがインストールされている場合にのみボリュームに適用されます。

====

