---
permalink: performance-checker/reference_what_objects_can_be_used_in_threshold_policies.html 
sidebar: sidebar 
keywords: objects, counters, combination, threshold, policies 
summary: 組み合わせポリシーで一緒に使用できるのは、一部のパフォーマンスカウンタだけです。プライマリとセカンダリのパフォーマンスカウンタを指定した場合、イベントが生成される前に両方のパフォーマンスカウンタが最大値を超えている必要があります。 
---
= 組み合わせしきい値ポリシーで使用できるオブジェクトとカウンタ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
組み合わせポリシーで一緒に使用できるのは、一部のパフォーマンスカウンタだけです。プライマリとセカンダリのパフォーマンスカウンタを指定した場合、イベントが生成される前に両方のパフォーマンスカウンタが最大値を超えている必要があります。

|===
| プライマリストレージのオブジェクトとカウンタ | セカンダリストレージのオブジェクトとカウンタ 


 a| 
ボリュームレイテンシ
 a| 
ボリューム IOPS



 a| 
ボリュームMBps



 a| 
アグリゲート利用率



 a| 
アグリゲート-使用済みパフォーマンス容量



 a| 
ノード利用率



 a| 
ノード使用済みパフォーマンス容量



 a| 
ノード使用済みパフォーマンス容量 - テイクオーバー



 a| 
LUN レイテンシ
 a| 
LUN IOPS



 a| 
LUN MBps



 a| 
アグリゲート利用率



 a| 
アグリゲート-使用済みパフォーマンス容量



 a| 
ノード利用率



 a| 
ノード使用済みパフォーマンス容量



 a| 
ノード使用済みパフォーマンス容量 - テイクオーバー

|===
[NOTE]
====
ボリュームの組み合わせポリシーが FlexVol ボリュームではなく FlexGroup ボリュームに適用される場合、セカンダリ・カウンタとして選択できる属性は「ボリューム IOPS 」と「ボリューム MBps 」のみです。しきい値ポリシーにノード属性またはアグリゲート属性のいずれかが含まれている場合、ポリシーはFlexGroupボリュームに適用されず、エラーメッセージが表示されます。これは、FlexGroupボリュームは複数のノードまたはアグリゲートに配置できるためです。

====