---
permalink: performance-checker/reference_performance_data_that_can_be_sent_to_an_external_server.html 
sidebar: sidebar 
keywords: performance, data, external, server 
summary: Unified Managerは、監視しているすべてのクラスタからさまざまなパフォーマンスデータを収集します。特定のデータグループを外部サーバに送信できます。 
---
= 外部サーバに送信可能なパフォーマンスデータ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Managerは、監視しているすべてのクラスタからさまざまなパフォーマンスデータを収集します。特定のデータグループを外部サーバに送信できます。

グラフ化するパフォーマンスデータに応じて、次のいずれかの統計グループを送信できます。

|===
| 統計グループ | データが含まれます | 詳細 


 a| 
パフォーマンスモニタ
 a| 
次のオブジェクトのパフォーマンス統計の概要：

* LUN
* ボリューム

 a| 
このグループは、監視対象のすべてのクラスタ内のすべてのLUNとボリュームの合計IOPSまたはレイテンシを提供します。

提供する統計データが最も少ないグループです。



 a| 
リソース利用率
 a| 
次のオブジェクトのリソース使用率の統計情報。

* ノード
* アグリゲート

 a| 
このグループは、監視対象のすべてのクラスタ内のノードおよびアグリゲートの物理リソースの利用率の統計を提供します。

また、Performance Monitorグループで収集された統計情報も提供します。



 a| 
ドリルダウン
 a| 
追跡対象のすべてのオブジェクトの読み取り/書き込みおよびプロトコルごとの下位レベルの統計情報：

* ノード
* アグリゲート
* LUN
* ボリューム
* ディスク
* LIF
* ポート/ NIC

 a| 
このグループは、監視対象のすべてのクラスタで追跡される7つのオブジェクトタイプすべてについて、読み取り/書き込みおよびプロトコルごとの内訳を提供します。

また、[Performance Monitor]グループおよび[Resource Utilization]グループで収集された統計情報も提供します。

提供する統計データが最も多いグループです。

|===
[NOTE]
====
ストレージシステム上でクラスタまたはクラスタオブジェクトの名前が変更された場合、古いオブジェクトと新しいオブジェクトの両方に外部サーバ上のパフォーマンスデータが含まれます（「両パス」）。2つのオブジェクトは同じオブジェクトとして関連付けられません。たとえば、ボリュームの名前を「 volume1_acct` 」から「 acct_vol1 」に変更した場合は、古いボリュームの古いパフォーマンスデータと、新しいボリュームの新しいパフォーマンスデータが表示されます。

====
外部データプロバイダに送信できるすべてのパフォーマンスカウンタのリストについては、記事30096を参照してください。

https://kb.netapp.com/?title=Advice_and_Troubleshooting%2FData_Infrastructure_Management%2FActive_IQ_Unified_Manager%2FWhat_are_the_ActiveIQ_Unified_Manager_performance_counters_that_can_be_exported_to_an_External_Data_Provider%253F["外部データプロバイダにエクスポート可能なUnified Managerのパフォーマンスカウンタ"]
