---
permalink: performance-checker/task_respond_to_user_defined_performance_threshold_events.html 
sidebar: sidebar 
keywords: user-defined, performance, threshold, events 
summary: Unified Manager を使用して、パフォーマンスカウンタがユーザ定義の警告または重大のしきい値を超えたことに起因するパフォーマンスイベントを調査できます。また、 Unified Manager を使用してクラスタコンポーネントの健常性を確認し、コンポーネントで検出された最近の健常性イベントがパフォーマンスイベントに関与しているかどうかを判断できます。 
---
= ユーザ定義のパフォーマンスしきい値イベントへの対処
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager を使用して、パフォーマンスカウンタがユーザ定義の警告または重大のしきい値を超えたことに起因するパフォーマンスイベントを調査できます。また、 Unified Manager を使用してクラスタコンポーネントの健常性を確認し、コンポーネントで検出された最近の健常性イベントがパフォーマンスイベントに関与しているかどうかを判断できます。

* 必要なもの *

* オペレータ、アプリケーション管理者、またはストレージ管理者のロールが必要です。
* 新規または廃止状態のパフォーマンスイベントが発生している必要があります。


.手順
. イベントの詳細情報を表示するには、イベントの詳細 * ページを表示します。
. イベントの原因となったしきい値違反の説明が記載された * 概要 * を確認します。
+
たとえば、「レイテンシ値 456 ms/op has triggered a WARNING event based on threshold setting of 400 ms/op 」というメッセージは、オブジェクトに対してレイテンシ警告イベントが発生したことを示しています。

. ポリシーの名前にカーソルを合わせると、イベントをトリガーしたしきい値ポリシーの詳細が表示されます。
+
これには、ポリシー名、評価されるパフォーマンスカウンタ、違反して重大イベントまたは警告イベントとみなされるカウンタの値、およびこの値を超える期間が含まれます。

. イベントトリガー時間 * をメモしておき、このイベントの原因となった可能性のある他のイベントが同時に発生したかどうかを調べることができます。
. 次のいずれかのオプションを使用してイベントをさらに詳しく調査し、パフォーマンスの問題を解決するための対処が必要かどうかを判断します。
+
|===
| オプション | 調査方法 


 a| 
ソースオブジェクト名をクリックして'そのオブジェクトのエクスプローラページを表示します
 a| 
このページでは、オブジェクトの詳細を表示し、このオブジェクトを他の同様のストレージオブジェクトと比較して、他のストレージオブジェクトに同時にパフォーマンスの問題が発生していないかどうかを確認できます。たとえば、同じアグリゲート上の他のボリュームにもパフォーマンスの問題が発生していないかどうかを確認できます。



 a| 
クラスタ名をクリックして[Cluster Summary]ページを表示します。
 a| 
このページでは、このオブジェクトが配置されているクラスタの詳細を表示して、同じ時間に他のパフォーマンスの問題が発生していないかどうかを確認できます。

|===

