---
permalink: performance-checker/task_configure_connection_between_um_server_and_external_data_provider.html 
sidebar: sidebar 
keywords: configuring, connection, unified manager, server, external, data, provider 
summary: Unified Manager から外部サーバにクラスタのパフォーマンスデータを送信できます。送信する統計データの種類とデータの送信間隔を指定できます。 
---
= Unified Manager サーバから外部データプロバイダへの接続の設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager から外部サーバにクラスタのパフォーマンスデータを送信できます。送信する統計データの種類とデータの送信間隔を指定できます。

* 必要なもの *

* Unified Managerサーバのメンテナンスコンソールへのログインが許可されているユーザIDが必要です。
* 外部データプロバイダに関する次の情報が必要です。
+
** サーバ名またはIPアドレス（IPv4またはIPv6）
** サーバのデフォルトポート（デフォルトポート2003を使用していない場合）


* Unified Manager サーバから統計データを受信できるようにリモートサーバと他社製ソフトウェアを設定しておく必要があります。
* 送信する統計のグループを把握しておく必要があります。
+
** performion_indicator ：パフォーマンスモニタの統計情報
** RESOURCE_UTILIZATION ：リソース利用率とパフォーマンスモニタの統計データ
** DRILL_DOWN ：すべての統計データ


* 統計情報を送信する間隔を 5 分、 10 分、または 15 分で指定する必要があります
+
デフォルトでは、 Unified Manager は 5 分間隔で統計データを収集します。送信間隔を10分（または15分）に設定すると、各送信で送信されるデータ量は、デフォルトの5分間隔を使用した場合の2倍（または3倍）になります。

+
[NOTE]
====
Unified Manager のパフォーマンス収集間隔を 10 分または 15 分に変更した場合は、送信間隔も Unified Manager の収集間隔以上に変更する必要があります。

====


1 台の Unified Manager サーバと 1 台の外部データプロバイダサーバの間に接続を設定できます。

.手順
. Unified Managerサーバのメンテナンスコンソールに、maintenanceユーザとしてログインします。
+
Unified Managerメンテナンスコンソールのプロンプトが表示されます。

. メンテナンスコンソールで、 * 外部データプロバイダ * メニューオプションの番号を入力します。
+
[External Server Connection]メニューが表示されます。

. [ サーバー接続の追加 / 変更 *] メニューオプションの番号を入力します。
+
現在のサーバ接続情報が表示されます。

. プロンプトが表示されたら、と入力して `*y*`続行します。
. プロンプトが表示されたら、宛先サーバのIPアドレスまたは名前、およびサーバポート情報（デフォルトポート2003と異なる場合）を入力します。
. プロンプトが表示されたら、と入力して、 `*y*`入力した情報が正しいことを確認します。
. 任意のキーを押して、[External Server Connection]メニューに戻ります。
. [ サーバー構成の変更 *] メニューオプションの番号を入力します。
+
現在のサーバ設定情報が表示されます。

. プロンプトが表示されたら、と入力して `*y*`続行します。
. プロンプトが表示されたら、送信する統計のタイプ、統計の送信間隔、および統計の送信を今すぐイネーブルにするかどうかを入力します。
+
|===
| 用途 | 入力するコマンド 


 a| 
統計グループID
 a| 
`*0*`-performance_indicator（デフォルト）

`*1*`-resource_utilization

`*2*`-ドリルダウン



 a| 
ベンダータグ
 a| 
統計情報を外部サーバに保存するフォルダのわかりやすい名前。デフォルト名は「 netapp-performance 」ですが、別の値を入力できます。

ドット付き表記を使用すると、階層的なフォルダ構造を定義できます。たとえば、と入力する `*stats.performance.netapp*`と、* stats *>* performance *>* NetApp *に統計が表示されます。



 a| 
送信間隔
 a| 
`*5*`（デフォルト）、、 `*10*`、または `*15*`分



 a| 
有効化/無効化
 a| 
`*0*`-無効化

`*1*`-有効（デフォルト）

|===
. プロンプトが表示されたら、と入力して、 `*y*`入力した情報が正しいことを確認します。
. 任意のキーを押して、[External Server Connection]メニューに戻ります。
. と入力し `*x*`てメンテナンスコンソールを終了します。


接続の設定が完了すると、選択したパフォーマンスデータが指定した間隔でデスティネーションサーバに送信されます。指標が外部ツールに表示されるまでに数分かかります。新しい指標を表示するには、ブラウザの表示の更新が必要になる場合があります。
