---
permalink: performance-checker/task_create_user_defined_performance_threshold_policies.html 
sidebar: sidebar 
keywords: create, user-defined, performance, threshold, policies 
summary: ストレージオブジェクトのパフォーマンスしきい値ポリシーを作成して、パフォーマンスカウンタが特定の値を超えたときに通知が送信されるようにします。イベント通知から、クラスタでパフォーマンスの問題が発生していることを確認できます。 
---
= ユーザ定義のパフォーマンスしきい値ポリシーの作成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージオブジェクトのパフォーマンスしきい値ポリシーを作成して、パフォーマンスカウンタが特定の値を超えたときに通知が送信されるようにします。イベント通知から、クラスタでパフォーマンスの問題が発生していることを確認できます。

* 必要なもの *

アプリケーション管理者のロールが必要です。

パフォーマンスしきい値ポリシーを作成するには、[パフォーマンスしきい値ポリシーの作成]ページでしきい値の値を入力します。このページでポリシーのすべての値を定義して新しいポリシーを作成できるほか、既存のポリシーのコピー（ _cloning_） を作成して値を変更することもできます。

しきい値の有効な値は、数値については 0.001~10 、 000 、 000 、割合については 0.001~100 、使用済みパフォーマンス容量の割合については 0.001~200 です。

[NOTE]
====
現在のリリースでは、カウンタの値が設定値を超えたときにイベントを送信するしきい値を設定できます。カウンタの値が設定値を下回ったときにイベントを送信するしきい値は設定できません。

====
.手順
. 左側のナビゲーションペインで、 * イベントしきい値 * > * パフォーマンス * を選択します。
+
[Performance Thresholds]ページが表示されます。

. 新しいポリシーを作成するか、類似のポリシーのクローンを作成して変更するかに応じて、該当するボタンをクリックします。
+
|===
| 目的 | クリックする項目 


 a| 
新しいポリシーを作成する
 a| 
* 作成 * 。



 a| 
既存のポリシーのクローンを作成する
 a| 
既存のポリシーを選択し、 * Clone * をクリックします

|===
+
[Create Performance Threshold Policy]ページまたは[Clone Performance Threshold Policy]ページが表示されます。

. 特定のストレージオブジェクトに対して設定するパフォーマンスカウンタのしきい値を指定して、しきい値ポリシーを定義します。
+
.. ストレージオブジェクトのタイプを選択し、ポリシーの名前と説明を指定します。
.. 追跡するパフォーマンスカウンタを選択し、警告イベントと重大イベントの制限値を指定します。
+
警告または重大の制限を少なくとも1つ定義する必要があります。両方のタイプの境界を定義する必要はありません。

.. 必要に応じてセカンダリパフォーマンスカウンタを選択し、警告イベントと重大イベントの制限値を指定します。
+
セカンダリカウンタを含めるには、両方のカウンタが制限値を超えていないとしきい値を超えてイベントが報告されません。組み合わせポリシーを使用して設定できるオブジェクトとカウンタには制限があります。

.. 制限値に違反してイベントを送信する期間を選択します。


+
既存のポリシーをクローニングする場合は、ポリシーの新しい名前を入力する必要があります。

. [ 保存（ Save ） ] をクリックして、ポリシーを保存します。
+
[パフォーマンスしきい値]ページに戻ります。しきい値ポリシーが作成されたことを示すメッセージがページの上部に表示されます。また、新しいポリシーをストレージオブジェクトにすぐに適用できるように、そのオブジェクトタイプのインベントリページへのリンクも表示されます。



この時点で新しいしきい値ポリシーをストレージオブジェクトに適用する場合は、 * Go to object_type Now * リンクをクリックしてインベントリページに移動できます。
