---
permalink: performance-checker/task_analyze_performance_incident_in_metrocluster.html 
sidebar: sidebar 
keywords: analyzing, dynamic, performance, event, remote, cluster, metrocluster, configuration 
summary: Unified Manager を使用して、 MetroCluster 構成のリモートクラスタの動的なパフォーマンスイベントを分析できます。この分析は、リモートクラスタのイベントがパートナークラスタのイベントの原因かどうかを判断するのに役立ちます。 
---
= MetroCluster構成のリモートクラスタの動的なパフォーマンスイベントの分析
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager を使用して、 MetroCluster 構成のリモートクラスタの動的なパフォーマンスイベントを分析できます。この分析は、リモートクラスタのイベントがパートナークラスタのイベントの原因かどうかを判断するのに役立ちます。

* 必要なもの *

* オペレータ、アプリケーション管理者、またはストレージ管理者のロールが必要です。
* MetroCluster構成内のローカルクラスタのパフォーマンスイベントを分析し、イベントの検出時間を確認しておく必要があります。
* パフォーマンスイベントに関連したローカルクラスタとそのパートナークラスタの健常性を確認し、パートナークラスタの名前を取得しておく必要があります。


.手順
. パートナークラスタを監視している Unified Manager インスタンスにログインします。
. 左側のナビゲーションペインで、 * Events * をクリックしてイベントリストを表示します。
. * 時間範囲 * セレクタから * 過去 1 時間 * を選択し、 * 範囲の適用 * をクリックします。
. [*Filtering*selector] で、左ドロップダウンメニューから [*Cluster*] を選択し、テキストフィールドにパートナークラスタの名前を入力して、 [*Apply Filter*] をクリックします。
+
選択したクラスタのイベントが過去1時間にない場合は、パートナーでイベントが検出された時間にクラスタでパフォーマンスの問題が発生していないことを示しています。

. 選択したクラスタで過去1時間にイベントが検出された場合は、イベントの検出時刻をローカルクラスタでのイベントの検出時刻と比較します。
+
これらのイベントにData Processingコンポーネントの競合を引き起こしているBullyワークロードが含まれている場合は、これらのBullyワークロードの一部がローカルクラスタでのイベントの原因となっている可能性があります。イベントをクリックすると、イベントを分析し、推奨される解決方法を[イベントの詳細]ページで確認できます。

+
これらのイベントにBullyワークロードが関係していない場合、ローカルクラスタのパフォーマンスイベントは発生していません。


