---
permalink: performance-checker/task_view_workload_qos_minimum_and_maximum_settings.html 
sidebar: sidebar 
keywords: view, workload, qos, minimum, maximum, settings, performance, explorer 
summary: パフォーマンスエクスプローラのグラフで、ボリュームまたは LUN に対する ONTAP 定義のサービス品質（ QoS ）ポリシーの設定を確認できます。最大スループットを設定すると、競合するワークロードがシステムリソースに与える影響が制限されます。最小スループット設定は、競合するワークロードによる要求に関係なく、重要なワークロードに最小限のスループットを確保するために使用されます。 
---
= [パフォーマンスエクスプローラ]でのワークロードのQoS最小値と最大値の設定の表示
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
パフォーマンスエクスプローラのグラフで、ボリュームまたは LUN に対する ONTAP 定義のサービス品質（ QoS ）ポリシーの設定を確認できます。最大スループットを設定すると、競合するワークロードがシステムリソースに与える影響が制限されます。最小スループット設定は、競合するワークロードによる要求に関係なく、重要なワークロードに最小限のスループットを確保するために使用されます。

QoS スループット「最小」および「最大」 IOPS および MBps の設定は、 ONTAP で設定されている場合にのみカウンタチャートに表示されます。最小スループットの設定は、ONTAP 9 .2以降のソフトウェアを実行しているシステム、AFFシステムでのみ使用でき、現時点ではIOPSに対してのみ設定できます。

アダプティブQoSポリシーはONTAP 9 .3以降で使用でき、IOPSではなくIOPS/TBが使用されます。これらのポリシーは、QoSポリシーの値をワークロードごとにボリュームサイズに基づいて自動的に調整し、ボリュームサイズが変わっても容量に対するIOPSの比率を維持します。アダプティブQoSポリシーグループはボリュームにのみ適用できます。QoS の用語 "expected" と "peak" は、最小と最大ではなくアダプティブ QoS ポリシーに使用されます。

Unified Manager では、定義されている QoS 最大ポリシーの設定を超えるワークロードが過去 1 時間の各パフォーマンス収集期間で見つかった場合に、 QoS ポリシーの違反とみなして警告イベントを生成します。ワークロードのスループットが各収集期間に短時間だけ QoS のしきい値を超えることがありますが、 Unified Manager のグラフには収集期間中の「平均」のスループットが表示されます。そのため、QoSイベントが表示されても、グラフではワークロードのスループットがポリシーのしきい値を超えていない可能性があります。

.手順
. 選択したボリュームまたは LUN の * パフォーマンスエクスプローラ * ページで、次の操作を実行して QoS の上限と下限の設定を表示します。
+
|===
| 状況 | 操作 


 a| 
IOPSの上限（QoS最大）を表示する
 a| 
IOPS の合計または内訳グラフで、 * ズームビュー * をクリックします。



 a| 
MBpsの上限（QoS最大）を表示する
 a| 
MBps の合計または内訳グラフで、 * ズームビュー * をクリックします。



 a| 
IOPSの下限（QoSの最小値）を表示する
 a| 
IOPS の合計または内訳グラフで、 * ズームビュー * をクリックします。



 a| 
IOPS/TBの上限（QoSピーク）を表示する
 a| 
ボリュームの場合は、 IOPS/TB チャートで * Zoom View * をクリックします。



 a| 
IOPS/TBの下限（QoS想定）を表示する
 a| 
ボリュームの場合は、 IOPS/TB チャートで * Zoom View * をクリックします。

|===
+
横の点線は、ONTAPで設定された最大スループットまたは最小スループットを示します。QoS値の変更がいつ実装されたかを確認することもできます。

. IOPSとMBpsの具体的な値をQoS設定と比較して表示するには、グラフ領域にカーソルを合わせてポップアップウィンドウを確認します。


特定のボリュームまたは LUN の IOPS や MBps が非常に高く、システムリソースを圧迫している場合は、 System Manager または ONTAP CLI を使用して、それらのワークロードが他のワークロードのパフォーマンスに影響しないように QoS 設定を調整することができます。

QoS設定の調整の詳細については、を参照してください。 http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-perf-mon/home.html["パフォーマンス管理の概要"]
