---
permalink: performance-checker/task_view_node_iops_based_on_workloads_on_local_node.html 
sidebar: sidebar 
keywords: view, node, iops, workloads, reside, only, local node 
summary: 'ノードのIOPSカウンタグラフでは、リモートノード上のボリュームに対する読み取り/書き込み処理を実行するために、処理がネットワークLIFを使用してローカルノードのみを経由する場所を特定できます。IOPS の「 Total (Local) 」グラフと「 Breakdown (Local) 」グラフには、現在のノード上にあるローカルボリュームに存在するデータの IOPS が表示されます。' 
---
= ローカルノードにのみ存在するワークロードに基づくノードIOPSの表示
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ノードのIOPSカウンタグラフでは、リモートノード上のボリュームに対する読み取り/書き込み処理を実行するために、処理がネットワークLIFを使用してローカルノードのみを経由する場所を特定できます。IOPS の「 Total (Local) 」グラフと「 Breakdown (Local) 」グラフには、現在のノード上のみのローカルボリュームに存在するデータの IOPS が表示されます。

これらのカウンタ・チャートの「ローカル」バージョンは ' ローカル・ボリューム上に存在するデータの統計のみを表示するため ' パフォーマンス容量と使用率のノード・チャートに似ています

これらのカウンタグラフの「ローカル」バージョンと、通常の合計バージョンのカウンタグラフを比較することで、ローカルノードを経由してリモートノード上のボリュームにアクセスしているトラフィックが大量にあるかどうかを確認できます。ローカルノードを経由してリモートノード上のボリュームにアクセスしている処理が多すぎると、パフォーマンスの問題が発生し、ノードでの高利用率が原因となる可能性があります。このような場合は、ボリュームをローカルノードに移動したり、そのボリュームにアクセスするホストからのトラフィックを接続できるリモートノードにLIFを作成したりできます。

.手順
. 選択したノードの * パフォーマンス / ノードエクスプローラ * ページで、 IOPS チャートから、ドロップダウンメニューから * 合計 * を選択します。
+
[IOPS -合計]グラフが表示されます。

. [* ズームビュー * ] をクリックすると、新しいブラウザタブにグラフのより大きなバージョンが表示されます。
. パフォーマンス / ノードエクスプローラ * ページに戻り、 IOPS チャートから、ドロップダウンメニューから * 合計（ローカル） * を選択します。
+
[IOPS -合計（ローカル）]グラフが表示されます。

. [* ズームビュー * ] をクリックすると、新しいブラウザタブにグラフのより大きなバージョンが表示されます。
. 両方のグラフを横に表示して、IOPS値が大きく異なる領域を特定します。
. これらの領域にカーソルを合わせて、特定の時点におけるローカルIOPSと合計IOPSを比較します。

