---
permalink: performance-checker/task_move_workloads_to_different_aggregate.html 
sidebar: sidebar 
keywords: move, workloads, different, aggregate 
summary: ワークロードが現在配置されているアグリゲートよりも負荷の低いアグリゲートを Unified Manager で特定し、選択したボリュームまたは LUN をそのアグリゲートに移動できます。負荷の高いワークロードを負荷の低いアグリゲートまたはフラッシュストレージが有効なアグリゲートに移動すると、ワークロードの効率が向上します。 
---
= 別のアグリゲートへのワークロードの移動
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ワークロードが現在配置されているアグリゲートよりも負荷の低いアグリゲートを Unified Manager で特定し、選択したボリュームまたは LUN をそのアグリゲートに移動できます。負荷の高いワークロードを負荷の低いアグリゲートまたはフラッシュストレージが有効なアグリゲートに移動すると、ワークロードの効率が向上します。

* 必要なもの *

* オペレータ、アプリケーション管理者、またはストレージ管理者のロールが必要です。
* 現在パフォーマンスに問題があるアグリゲートの名前を記録しておく必要があります。
* アグリゲートがイベントを受け取った日時を記録しておく必要があります。
* Unified Manager で 1 カ月分以上のパフォーマンスデータの収集と分析が行われている必要があります。


負荷の高いワークロードを利用率の低いアグリゲートに移動するには、以下に示す手順で次のリソースを特定します。

* 同じクラスタ上の利用率の低いアグリゲート
* 現在のアグリゲートで最も負荷の高いボリューム


.手順
. クラスタ内で最も利用率の低いアグリゲートを特定します。
+
.. イベント * の詳細ページで、アグリゲートが配置されているクラスタの名前をクリックします。
+
パフォーマンス / クラスタランディングページにクラスタの詳細が表示されます。

.. [* 概要 *] ページで、 [* 管理対象オブジェクト * ] ペインの [* アグリゲート ] をクリックします。
+
このクラスタ上のアグリゲートのリストが表示されます。

.. 利用率 * 列をクリックして、アグリゲートを利用率が低い順にソートします。
+
空き容量が最も多いアグリゲートを特定することもできます。これにより、ワークロードの移動先にするアグリゲートの候補が一覧表示されます。

.. ワークロードの移動先にするアグリゲートの名前を書き留めます。


. イベントを受け取ったアグリゲートで負荷の高いボリュームを特定します。
+
.. パフォーマンスに問題があるアグリゲートをクリックします。
+
[パフォーマンス/アグリゲートエクスプローラ]ページにアグリゲートの詳細が表示されます。

.. * 時間範囲 * セレクタから「 * 過去 30 日間 * 」を選択し、 * 範囲の適用 * をクリックします。
+
これにより、デフォルトの72時間よりも長いパフォーマンス履歴期間を表示できます。過去72時間だけでなく、大量のリソースを使用しているボリュームを移動する必要があります。

.. View and Compare * コントロールから、 * このアグリゲートのボリュームを選択します。
+
このアグリゲート上のFlexVolボリュームとFlexGroupコンスティチュエントボリュームのリストが表示されます。

.. ボリュームをMBpsの高い順にソートし、IOPSの高い順にソートして、最も負荷の高いボリュームを確認します。
.. 別のアグリゲートに移動するボリュームの名前を書き留めます。


. 事前に特定した利用率の低いアグリゲートに負荷の高いボリュームを移動します。
+
移動処理は、ONTAP System Manager、OnCommand Workflow Automation、ONTAPコマンド、またはこれらのツールを組み合わせて実行できます。



数日後に、このノードまたはアグリゲートから同じタイプのイベントを受け取っていないかどうかを確認します。
