---
permalink: performance-checker/task_respond_to_system_defined_qos_policy_group_performance_event.html 
sidebar: sidebar 
keywords: qos, policy, group, performance, events 
summary: ワークロードのスループット（ IOPS 、 IOPS/TB 、または MBps ）が定義されている ONTAP QoS ポリシーの設定を超え、ワークロードのレイテンシに影響を及ぼしている場合、 Unified Manager で QoS ポリシー警告イベントが生成されます。これらのシステム定義のイベントを使用すると、多くのワークロードがレイテンシの影響を受ける前に、潜在的なパフォーマンスの問題を修正できます。 
---
= QoSポリシーグループパフォーマンスイベントへの対処
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ワークロードのスループット（ IOPS 、 IOPS/TB 、または MBps ）が定義されている ONTAP QoS ポリシーの設定を超え、ワークロードのレイテンシに影響を及ぼしている場合、 Unified Manager で QoS ポリシー警告イベントが生成されます。これらのシステム定義のイベントを使用すると、多くのワークロードがレイテンシの影響を受ける前に、潜在的なパフォーマンスの問題を修正できます。

* 必要なもの *

* オペレータ、アプリケーション管理者、またはストレージ管理者のロールが必要です。
* 新規、確認済み、または廃止状態のパフォーマンスイベントが発生している必要があります。


Unified Manager では、定義されている QoS ポリシーの設定を超えるワークロードが過去 1 時間の各パフォーマンス収集期間で見つかった場合に、 QoS ポリシーの違反とみなして警告イベントを生成します。ワークロードのスループットが各収集期間に短時間だけ QoS のしきい値を超えることがありますが、 Unified Manager のグラフには収集期間中の「平均」のスループットしか表示されません。そのため、QoSイベントが発生しても、グラフではワークロードのスループットがポリシーのしきい値を超えていない可能性があります。

System Manager または ONTAP コマンドを使用してポリシーグループを管理できます。これには次のタスクが含まれます。

* ワークロードの新しいポリシーグループの作成
* ポリシーグループ内のワークロードの追加または削除
* ポリシーグループ間でのワークロードの移動
* ポリシーグループのスループット制限の変更
* 別のアグリゲートまたはノードへのワークロードの移動


.手順
. イベントの詳細情報を表示するには、イベントの詳細 * ページを表示します。
. イベントの原因となったしきい値違反の説明が記載された * 概要 * を確認します。
+
たとえば、「 vol1_NFS1 の IOPS 値が 1 、 352 IOPS のため、警告イベントがトリガーされました。ワークロードに潜在的なパフォーマンスの問題があります」というメッセージは、ボリューム vol1_NFS1 で QoS 最大 IOPS イベントが発生したことを示しています。

. イベントが発生した日時とイベントがアクティブになっている期間の詳細については、「イベント情報」セクションを参照してください。
+
また、QoSポリシーのスループットを共有しているボリュームやLUNについては、IOPSまたはMBpsが高い上位3つのワークロードの名前を確認できます。

. システム診断 * セクションで、合計平均 IOPS または MBps （イベントに応じて）とレイテンシの 2 つのグラフを確認します。このように配置すると、ワークロードが最大QoSに達したときにレイテンシに最も影響しているクラスタコンポーネントを確認できます。
+
共有QoSポリシーのイベントの場合は、上位3つのワークロードがスループットグラフに表示されます。3 つ以上のワークロードが QoS ポリシーを共有している場合、「 other workloads 」カテゴリに追加されたワークロードが表示されます。また、[レイテンシ]グラフには、QoSポリシーに含まれているすべてのワークロードの平均レイテンシが表示されます。

+
アダプティブQoSポリシーのイベントについては、[IOPS]グラフと[MBps]グラフには、ONTAPがボリュームのサイズに基づいて割り当てられているIOPS/TBしきい値ポリシーから変換したIOPSまたはMBpsの値が表示されます。

. 「推奨される対処方法」セクションで、推奨される対処方法を確認し、ワークロードのレイテンシ増加を回避するために実行する必要がある対処方法を決定します。
+
必要に応じて、ヘルプ * ボタンをクリックして、パフォーマンスイベントの解決方法に関する推奨される操作の詳細を確認します。


