---
permalink: performance-checker/task_view_event_details_in_performance_explorer_events_timeline.html 
sidebar: sidebar 
keywords: view, event, details, timeline 
summary: '[パフォーマンスエクスプローラ]の[イベントタイムライン]ペインで、すべてのイベントと関連する詳細を確認できます。指定した期間内にルートオブジェクトで発生したすべての健常性イベントとパフォーマンスイベントをすばやく効率的に表示できるため、パフォーマンスの問題のトラブルシューティングに役立ちます。' 
---
= イベントタイムラインでのイベントの詳細の表示
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
[パフォーマンスエクスプローラ]の[イベントタイムライン]ペインで、すべてのイベントと関連する詳細を確認できます。指定した期間内にルートオブジェクトで発生したすべての健常性イベントとパフォーマンスイベントをすばやく効率的に表示できるため、パフォーマンスの問題のトラブルシューティングに役立ちます。

イベントタイムラインペインには、選択した期間中にルートオブジェクトで発生したクリティカル、エラー、警告、および情報イベントが表示されます。イベントの重大度にはそれぞれ独自のタイムラインがあります。単一または複数のイベントは、タイムライン上ではイベントドットで表されます。イベントを示す点にカーソルを合わせると、イベントの詳細を確認できます。複数のイベントをより詳細に表示するには、期間を短くします。これにより、複数のイベントが1つのイベントに分散され、各イベントを個別に表示および調査できます。

イベントタイムラインの各パフォーマンスイベントドットは、イベントタイムラインの下に表示されるカウンタグラフのトレンドラインの急増に対応して縦に並んでいます。イベントと全体的なパフォーマンスの間に直接的な相関関係があることを確認できます。健全性イベントもタイムラインに表示されますが、これらのタイプのイベントはいずれかのパフォーマンスチャートの急増と一致しているとは限りません。

.手順
. [ * イベントタイムライン * ] ペインで、タイムライン上のイベントドットにカーソルを合わせると、そのイベントポイントでのイベントのサマリーが表示されます。
+
ポップアップダイアログに、イベントタイプ、イベントが発生した日時、状態、およびイベント期間に関する情報が表示されます。

. 1つまたは複数のイベントの詳細を表示します。
+
|===
| 作業 | オプション 


 a| 
単一イベントの詳細を表示する
 a| 
* ポップアップダイアログでイベントの詳細を表示 * 。



 a| 
複数のイベントの詳細を表示する
 a| 
* ポップアップダイアログでイベントの詳細を表示 * 。

[NOTE]
====
複数イベントダイアログで 1 つのイベントをクリックすると、該当するイベントの詳細ページが表示されます。

====
|===

