---
permalink: performance-checker/task_respond_to_system_defined_node_resources_overutilized.html 
sidebar: sidebar 
keywords: node, resources, overutilized, performance, events 
summary: 1 つのノードが運用効率の上限を超えて稼働していて、ワークロードのレイテンシに影響を及ぼしている可能性がある場合、 Unified Manager でノードリソース過剰使用警告イベントが生成されます。これらのシステム定義のイベントを使用すると、多くのワークロードがレイテンシの影響を受ける前に、潜在的なパフォーマンスの問題を修正できます。 
---
= ノードリソース過剰使用パフォーマンスイベントへの対処
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
1 つのノードが運用効率の上限を超えて稼働していて、ワークロードのレイテンシに影響を及ぼしている可能性がある場合、 Unified Manager でノードリソース過剰使用警告イベントが生成されます。これらのシステム定義のイベントを使用すると、多くのワークロードがレイテンシの影響を受ける前に、潜在的なパフォーマンスの問題を修正できます。

* 必要なもの *

* オペレータ、アプリケーション管理者、またはストレージ管理者のロールが必要です。
* 新規または廃止状態のパフォーマンスイベントが発生している必要があります。


Unified Manager では、パフォーマンス容量の使用率が 30 分以上にわたって 100% を超えているノードが見つかると、ノードリソース過剰使用ポリシーの違反とみなして警告イベントを生成します。

System Manager または ONTAP コマンドを使用して、このタイプのパフォーマンス問題を修正できます。これには次の作業が含まれます。

* QoSポリシーを作成してシステムリソースを過剰に使用しているボリュームやLUNに適用する
* ワークロードが適用されているポリシーグループのQoS最大スループット制限を引き下げる
* 別のアグリゲートまたはノードへのワークロードの移動
* ノードにディスクを追加するか、高速CPUとRAMを搭載したノードにアップグレードして容量を拡張する


.手順
. イベントの詳細情報を表示するには、イベントの詳細 * ページを表示します。
. イベントの原因となったしきい値違反の説明が記載された * 概要 * を確認します。
+
たとえば、「 Perf 」というメッセージが表示されます。simplicity-02 の使用済み容量が 139% のため、警告イベントがトリガーされました。データ処理装置に潜在的なパフォーマンスの問題があります。」は、ノード simplicity-02 のパフォーマンス容量の使用率が高く、ノードのパフォーマンスに影響を及ぼしていることを示しています。

. システム診断 * セクションで、 3 つのグラフを確認します。 1 つはノードで使用されているパフォーマンス容量、 1 つは上位のワークロードで使用されている平均ストレージ IOPS 、もう 1 つは上位のワークロードで使用されているレイテンシです。このように配置すると、ノードのレイテンシの原因となっているワークロードを確認できます。
+
IOPSグラフにカーソルを合わせると、QoSポリシーが適用されているワークロードと適用されていないワークロードを確認できます。

. 「推奨される対処方法」セクションで、推奨される対処方法を確認し、ワークロードのレイテンシ増加を回避するために実行する必要がある対処方法を決定します。
+
必要に応じて、ヘルプ * ボタンをクリックして、パフォーマンスイベントの解決方法に関する推奨される操作の詳細を確認します。


