---
permalink: storage-mgmt/concept_fix_ontap_issues_directly_from_unified_manager.html 
sidebar: sidebar 
keywords: fix, ontap, issues, directly, unified manager, fix it, fix-it, remediation 
summary: ONTAP の一部の問題については、 ONTAP System Manager や ONTAP CLI を使用する代わりに、 Unified Manager ユーザインターフェイスから直接修正することができます。「管理操作」オプションでは、 Unified Manager イベントをトリガーした ONTAP のさまざまな問題を修正できます。 
---
= ONTAPの問題や機能をUnified Managerから直接管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAPの特定の問題を解決したり、特定のONTAP機能をUnified Managerユーザインターフェイスから直接管理したりすることができます。ONTAP System ManagerやONTAP CLIを使用する必要はありません。「管理操作」オプションは、 Unified Manager イベントをトリガーした ONTAP のさまざまな問題に対する修正を提供します。

左側のナビゲーションペインで * 管理操作 * オプションを選択すると、管理操作ページから直接問題を修正できます。管理操作は、ダッシュボードの[管理操作]パネル、[イベントの詳細]ページ、および左側のナビゲーションメニューの[ワークロード分析]からも実行できます。

一部の問題については、Unified Managerの詳細な診断によって単一の解決策が提供されます。ランサムウェア対策の監視など、特定のONTAP機能については、Unified Managerが内部チェックを実行し、特定のアクションを推奨します。解決策がある場合は、 [ 管理アクション ] の [ * 修正 ] ボタンで表示されます。[* Fix it* （修正） ] ボタンをクリックして、問題を修正します。アプリケーション管理者またはストレージ管理者のロールが必要です。

Unified Manager からクラスタに ONTAP コマンドが送信され、要求された修正が実行されます。修正が完了すると、イベントは廃止状態になります。

一部の管理操作では、 * すべて修正 * ボタンを使用して、複数のストレージオブジェクトで同じ問題を修正できます。たとえば、「ボリュームスペースがフル」イベントが発生しているボリュームが 5 つある場合に、「ボリュームの自動拡張を有効にする」の「すべてを修正」管理操作をクリックすると解決できます。この問題は、ワンクリックで5つのボリュームで修正できます。

自動修正を使用して管理できるONTAPの問題と機能の詳細については、を参照してくださいlink:../storage-mgmt/reference_what_ontap_issues_can_unified_manager_fix.html["Unified Managerで解決できる問題"]。
