---
permalink: storage-mgmt/concept_what_options_do_i_have_in_fix_it_button.html 
sidebar: sidebar 
keywords: fix it,fix all 
summary: 管理操作ページの修正またはすべて修正ボタンを使用して、 Unified Manager にイベントを通じて通知された問題を修正できます。 
---
= [修正]または[すべて修正]ボタンが表示されたときのオプション
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Management Actions ページには、 Unified Manager にイベントを通じて通知された問題を修正するための * Fix it * または * Fix All * ボタンが表示されます。

必要に応じて、ボタンをクリックして問題を修正することをお勧めします。ただし、 Unified Manager の推奨事項に従って問題を解決するかどうかが不明な場合は、次の操作を実行できます。

|===
| あなたは何をしたいのですか。 | * アクション * 


 a| 
特定されたすべてのオブジェクトの問題をUnified Managerで修正してもらいます。
 a| 
「 * すべて修正 * 」ボタンをクリックします。



 a| 
この時点では特定されたオブジェクトの問題を修正せず、イベントが再度発生するまでこの管理操作を非表示にします。
 a| 
下矢印をクリックし、 * すべてを却下 * をクリックします。



 a| 
特定された一部のオブジェクトでのみ問題を修正します。
 a| 
管理操作の名前をクリックしてリストを展開し、 * 修正 * アクションをすべて表示します。次に、個々の管理操作を修正または削除する手順を実行します。

|===
|===
| あなたは何をしたいのですか。 | アクション 


 a| 
Unified Manager で問題を修正する。
 a| 
[* Fix it* （修正） ] ボタンをクリックします。



 a| 
この時点では問題を修正せず、イベントが再度発生するまでこの管理操作を非表示にします。
 a| 
下矢印をクリックし、 * Dismiss * （キャンセル）をクリックします。



 a| 
問題を詳しく把握するために、このイベントの詳細を表示します。
 a| 
* [ 修正（ Fix it ） ] ボタンをクリックして、結果のダイアログボックスに適用される修正を確認します。
* 下矢印をクリックし、 * イベントの詳細を表示 * をクリックしてイベントの詳細ページを表示します。


問題を修正する場合は、これらのいずれかの結果ページで [* Fix it* （修正） ] をクリックします。



 a| 
問題を詳しく把握するために、このストレージオブジェクトの詳細を表示します。
 a| 
ストレージオブジェクトの名前をクリックすると、パフォーマンスエクスプローラまたは健全性の詳細ページに詳細が表示されます。

|===
場合によっては、次の15分間の設定ポーリングに修正が反映されることがあります。それ以外の場合は、設定の変更が検証されてイベントが廃止されるまでに最大数時間かかることがあります。

完了または進行中の管理アクションのリストを表示するには、フィルタアイコンをクリックし、 * 完了 * または * 進行中 * を選択します。

すべてのオペレーションがシリアルに実行されるように修正します。このため、 [ 進行中 ] パネルを表示すると、 [ ステータス *- 進行中 ] が表示されるオブジェクトと、 [ ステータス *Scheduled （ステータス * スケジュール済み） ] が表示されるオブジェクトがあります。これは、実装を待機していることを意味します。
