---
permalink: storage-mgmt/concept_provision_and_manage_workloads.html 
sidebar: sidebar 
keywords: provision, manage, workloads 
summary: Active IQ Unified Managerのアクティブ管理機能は、データセンターのストレージワークロードをプロビジョニング、監視、管理するために、パフォーマンスサービスレベル、ストレージ効率化ポリシー、およびストレージプロバイダAPIを提供します。 
---
= ワークロードのプロビジョニングと管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Managerのアクティブ管理機能は、データセンターのストレージワークロードをプロビジョニング、監視、管理するために、パフォーマンスサービスレベル、ストレージ効率化ポリシー、およびストレージプロバイダAPIを提供します。

[NOTE]
====
この機能は Unified Manager にデフォルトで搭載されています。この機能を使用しない場合は、 * Storage Management * > * Feature Settings * で無効にできます。

====
有効にした場合、 Unified Manager のインスタンスで管理される ONTAP クラスタのワークロードをプロビジョニングできます。また、パフォーマンスサービスレベルやストレージ効率化ポリシーなどのポリシーをワークロードに割り当て、それらのポリシーに基づいてストレージ環境を管理することもできます。

この機能により、次の機能が有効になります。

* 追加したクラスタでストレージワークロードを自動検出し、ストレージワークロードの評価と導入を簡易化
* NFSプロトコルとCIFSプロトコルをサポートするNASワークロードのプロビジョニング
* iSCSIプロトコルとFCPプロトコルをサポートするSANワークロードのプロビジョニング
* 同じファイル共有でのNFSプロトコルとCIFSプロトコルの両方のサポート
* パフォーマンスサービスレベルとストレージ効率化ポリシーの管理
* ストレージワークロードへのパフォーマンスサービスレベルとストレージ効率化ポリシーの割り当て


UI の左側のペインで、 * Provisioning * 、 * Storage * > * Workloads * 、 * Policies * の各オプションを使用して、さまざまな設定を変更できます。

これらのオプションを使用して、次の機能を実行できます。

* ストレージワークロードを * Storage * > * Workloads * ページで表示できます
* [ワークロードのプロビジョニング]ページでストレージワークロードを作成
* [ポリシー]からのパフォーマンスサービスレベルの作成と管理
* [ポリシー]からのストレージ効率化ポリシーの作成と管理
* [ワークロード]ページでストレージワークロードにポリシーを割り当てる


* 関連情報 *

link:../config/concept_policy_based_storage_management.html["ポリシーベースのストレージ管理"]
