---
permalink: storage-mgmt/concept_monitor_vms.html 
sidebar: sidebar 
keywords: monitor, virtual, machines, view, summary, topology, expand 
summary: 仮想マシン（VM）アプリケーションでレイテンシの問題が発生した場合は、原因の分析とトラブルシューティングを行うためにVMの監視が必要になることがあります。VMは、vCenter ServerおよびVMストレージをホストするONTAPクラスタがUnified Managerに追加されたときに使用可能になります。 
---
= 仮想マシンの監視
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
仮想マシン（VM）アプリケーションでレイテンシの問題が発生した場合は、原因の分析とトラブルシューティングを行うためにVMの監視が必要になることがあります。VMは、vCenter ServerおよびVMストレージをホストするONTAPクラスタがUnified Managerに追加されたときに使用可能になります。

VM の詳細は、 * vmware * >> * Virtual Machines * ページに表示されます。VM、データストア、ホストの可用性、ステータス、使用容量と割り当て容量、ネットワークレイテンシ、IOPSとレイテンシなどの情報が表示されます。複数のデータストアをサポートしている VM の場合は、最もレイテンシが高いデータストアの指標がグリッドに表示され、追加のデータストアを示すアスタリスクアイコン（ * ）が付きます。アイコンをクリックすると、追加データストアのメトリックが表示されます。これらの列の中には、並べ替えやフィルタリングに使用できないものがあります。

[NOTE]
====
VMとその詳細を表示するには、ONTAPクラスタの検出（ポーリングまたは指標収集）が完了している必要があります。クラスタをUnified Managerから削除すると、次回の検出サイクル後にVMを使用できなくなります。

====
このページからは、VMの詳細なトポロジも表示され、VMに接続されているホスト、仮想ディスク、データストアなど、VMが関連するコンポーネントが表示されます。トポロジビューには、基になるコンポーネントが各レイヤの次の順序で表示されます。 * Virtual Disk * > * VM * > * Host * > * Network * > * Datastore * > * VMDK * 。

I/O パスとコンポーネントレベルのレイテンシをトポロジの観点から確認し、パフォーマンス問題の原因かどうかを判断できます。トポロジのサマリビューには I/O パスが表示され、解決手順を特定できるように IOPS やレイテンシの問題があるコンポーネントが強調表示されます。また、トポロジの展開ビューで、各コンポーネントとそのコンポーネントのレイテンシを個別に確認することもできます。コンポーネントを選択して、レイヤ内で強調表示されているI/Oパスを決定できます。



== トポロジのサマリビューの表示

トポロジの概要でVMを表示してパフォーマンスの問題を特定するには、次の手順を実行します。

. 「 * vmware * > * Virtual Machines * 」に移動します。
. 検索ボックスに名前を入力してVMを検索します。また、 * フィルター * ボタンをクリックして、特定の条件に基づいて検索結果をフィルターすることもできます。ただし、VMが見つからない場合は、対応するvCenter Serverが追加されて検出されていることを確認してください。
+
[NOTE]
====
vCenter Server で使用できる特殊文字（ % 、 & 、 * 、 $ 、 # 、 @ 、！、 \ 、 / 、：、 * 、 ? 、 " 、 < 、 > 、 | 、；、 ' ）を使用して、 VM 、クラスタ、データストア、フォルダ、 または file です。VMware vCenter Server および ESX/ESXi Server では、表示名に使用される特殊文字はエスケープされません。ただし、 Unified Manager で処理される名前は異なって表示されます。たとえば、vCenter Serverでという名前のVM `%$VC_AIQUM_clone_191124%`は、Unified Managerではと表示されます `%25$VC_AIQUM_clone_191124%25`。名前に特殊文字が含まれているVMを照会する場合は、この問題に注意する必要があります。

====
. VMのステータスを確認します。VMのステータスはvCenter Serverから取得されます。ステータスは次のいずれかです。これらのステータスの詳細については、VMwareのドキュメントを参照してください。
+
** 標準
** 警告
** アラート
** 監視対象外
** 不明


. VM の横にある下矢印をクリックすると、コンピューティング、ネットワーク、ストレージの各レイヤにあるコンポーネントのトポロジのサマリビューが表示されます。レイテンシの問題があるノードは強調表示されます。サマリビューには、コンポーネントのワーストレイテンシが表示されます。たとえば、VMに複数の仮想ディスクがある場合は、すべての仮想ディスクの中でレイテンシが最も低い仮想ディスクが表示されます。
. 一定期間にわたるデータストアのレイテンシとスループットを分析するには、データストアオブジェクトアイコンの上にある * Workload Analyzer * ボタンをクリックします。ワークロード分析ページに移動して、期間を選択し、データストアのパフォーマンスチャートを表示できます。Workload Analyzer の詳細については、 Workload Analyzer を使用したワークロードのトラブルシューティング _ を参照してください。




== トポロジの展開ビューの表示

VM のトポロジの展開ビューでは、各コンポーネントにドリルダウンして個別に確認することができます。

.手順
. トポロジのサマリビューで、 [* トポロジの展開 *] をクリックします。各コンポーネントの詳細なトポロジが個別に表示され、各オブジェクトのレイテンシを確認できます。1つのカテゴリに複数のノードがある場合（データストアやVMDKに複数のノードがある場合など）は、レイテンシが最も高いノードが赤で強調表示されます。
. 特定のオブジェクトのIOパスを確認するには、そのオブジェクトをクリックしてIOパスと対応するマッピングを確認します。たとえば、仮想ディスクのマッピングを表示するには、仮想ディスクをクリックして、対応する VMDK への強調表示されたマッピングを表示します。これらのコンポーネントのパフォーマンスが低下した場合は、ONTAPからさらに多くのデータを収集して問題のトラブルシューティングを行うことができます。
+
[NOTE]
====
VMDKについては指標は報告されません。トポロジでは、VMDK名のみが表示され、指標は表示されません。

====


* 関連情報 *

link:../performance-checker/concept_troubleshooting_workloads_using_workload_analyzer.html["Workload Analyzerによるワークロードのトラブルシューティング"]
