---
permalink: storage-mgmt/concept_manage_storage_efficiency_policies.html 
sidebar: sidebar 
keywords: manage, storage, efficiency, policies, guidelines, create, custom 
summary: ストレージ効率化ポリシー（SEP）を使用すると、ワークロードのストレージ効率化特性を定義できます。ワークロードの作成時または作成後にワークロードを編集して、ワークロードにSEPを割り当てることができます。 
---
= ストレージ効率化ポリシーの管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージ効率化ポリシー（SEP）を使用すると、ワークロードのストレージ効率化特性を定義できます。ワークロードの作成時または作成後にワークロードを編集して、ワークロードにSEPを割り当てることができます。

Storage Efficiencyでは、シンプロビジョニング、重複排除、データ圧縮などのテクノロジを使用して、ストレージ利用率を高め、ストレージコストを削減します。SEPの作成時に、これらのスペース削減テクノロジを個別に、または組み合わせて使用することで、ストレージ効率を最大限に高めることができます。ポリシーをストレージワークロードに関連付けると、指定したポリシー設定がストレージワークロードに割り当てられます。Unified Managerでは、システム定義とユーザ定義のSEPを割り当てて、データセンターのストレージリソースを最適化できます。

Unified Manager には、システム定義の 2 つの SEP が「高」と「低」の 2 つあります。これらのSEPはデータセンターのほとんどのストレージワークロードに適用されますが、システム定義のSEPが要件を満たしていない場合は独自のポリシーを作成できます。

システム定義のSEPやワークロードに現在割り当てられているSEPは変更できません。ワークロードに割り当てられているSEPは削除できません。また、使用可能なSEPが他にない場合は削除できません。

[Storage Efficiency Policies]ページには使用可能なSEPが表示され、カスタマイズしたSEPを追加、編集、削除できます。このページには、次の情報が表示されます。

|===
| フィールド | 製品説明 


 a| 
名前
 a| 
SEPの名前。



 a| 
タイプ
 a| 
システム定義のポリシーかユーザ定義のポリシーか。



 a| 
スペースリザベーション
 a| 
ボリュームがシンプロビジョニングされているか、シックプロビジョニングされているか。



 a| 
重複排除
 a| 
ワークロードで重複排除が有効になっているかどうか。

* インライン：ワークロードへの書き込み中に重複排除が実行されます
* バックグラウンド：ワークロードで重複排除が実行されます
* Disable ：ワークロードで重複排除が無効になります




 a| 
圧縮
 a| 
ワークロードでデータ圧縮が有効になっているかどうか。

* Inline ：ワークロードへの書き込み中にデータ圧縮が実行されます
* バックグラウンド：ワークロードでデータ圧縮が実行されます
* disable ：ワークロードでデータ圧縮が無効になります




 a| 
ワークロード
 a| 
SEPが割り当てられているストレージワークロードの数

|===


== カスタムのストレージ効率化ポリシーの作成に関するガイドライン

既存のSEPがストレージワークロードのポリシー要件を満たしていない場合は、カスタムSEPを作成できます。ただし、ストレージワークロードにはシステム定義のSEPを使用し、必要な場合にのみカスタムSEPを作成することを推奨します。

ワークロードに割り当てられているSEPは、[すべてのワークロード]ページと[ボリューム/健全性の詳細]ページで確認できます。これらのStorage Efficiencyに基づいて、ダッシュボードの[容量]パネルと[容量：すべてのクラスタ]ビューで、クラスタレベルのデータ削減率（Snapshotコピーなし）を確認できます。
