---
permalink: storage-mgmt/concept_manage_performance_service_levels.html 
sidebar: sidebar 
keywords: manage, performance service level, PSL, User-defined, system-defined PSL, bursty, Database PSL, extreme PSL, beyond extreme PSL 
summary: パフォーマンスサービスレベルの計算と管理： 
---
= パフォーマンスサービスレベル
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
パフォーマンスサービスレベル（PSL）を使用すると、ワークロードのパフォーマンスとストレージの目標を定義できます。ワークロードの作成時または作成後にワークロードを編集してPSLを割り当てることができます。

ストレージリソースの管理と監視は、サービスレベル目標（SLO）に基づいて行われます。SLOは、必要なパフォーマンスと容量に基づいたサービスレベルアグリーメントによって定義されます。Unified Managerでは、SLOとは、NetAppストレージで実行されているアプリケーションのPSLの定義を指します。ストレージサービスは、基盤となるリソースのパフォーマンスと利用率に基づいて差別化されます。PSLは、ストレージサービスの目標を表したものです。ストレージプロバイダはPSLを使用して、ワークロードの目標とするパフォーマンスと容量を指定できます。ワークロードにPSLを割り当てると、ONTAP上の対応するワークロードがパフォーマンスと容量の目標に基づいて管理されます。各PSLは、ピークIOPS、想定最小IOPS、絶対最小IOPS、想定レイテンシによって決まります。

Unified Managerには次の種類のPSLがあります。

* *システム定義*：Unified Managerには、変更できない組み込みのポリシーがいくつか用意されています。事前定義されたPSLは次のとおりです。
+
** 卓越したパフォーマンス
** パフォーマンス
** 値
+
最高レベルのパフォーマンス、パフォーマンス、バリューの各PSLは、データセンターの一般的なストレージワークロードのほとんどに適用されます。

+
Unified Managerには、データベースアプリケーション用に3つのパフォーマンスサービスレベルも用意されています。これらは、バーストIOPSをサポートする非常にハイパフォーマンスなPSLであり、スループットの要求が最も高いデータベースアプリケーションに適しています。

** 最高レベル（データベースログ用）
** 最高レベル（データベース共有データ用）
** 最高レベル（データベースデータ用）


* *ユーザ定義*：事前定義されたパフォーマンスサービスレベルが要件に合わない場合は、PSLを新たに作成してニーズに対応できます。詳細については、を参照してください link:../storage-mgmt/task_create_and_edit_psls.html["パフォーマンスサービスレベルの作成と編集"]。
* * Extremeを超える場合*：PSLが最高レベルを超えると、PSLがシステム推奨となります。PSLを超えるワークロードには、Extremeよりも高いIOPSが必要です。ワークロードの内部分析はIOPS、容量、レイテンシに基づいて行われ、ストレージ>ワークロード>すべてのワークロード*画面で、これらのワークロードそれぞれについてPSLを超えることが推奨されます。ワークロードにPSLを適用すると、パフォーマンスを最適化できます。
+
ワークロードのIOPSパラメータは、ワークロードの動作に応じて動的に生成され、Beyond Extreme PSLの名前にという形式で付加され `Beyond Extreme <number-(peak IOPS/TB)> <number(expected IOPS/TB)>`ます。たとえば、ピークIOPSと想定IOPSがそれぞれと `37929`になるワークロードが見つかった場合 `106345`、そのワークロードに対して生成されるBeyond Extreme PSLの名前はになります `Beyond Extreme 106345 37929`。これらのPSLはシステムで推奨されますが、ワークロードに割り当てるとタイプが「in」とラベル付けされます `User-defined`。





== PSLの割り当てによるワークロードの管理

PSLには、「* Policies *>* Performance Service Levels *」ページからアクセスできます。また、ストレージプロバイダAPIを使用してアクセスできます。PSLを割り当ててストレージワークロードを管理すると、ストレージワークロードを個別に管理する必要がないため便利です。変更は、個別に管理するのではなく、別のPSLを再割り当てして管理することもできます。Unified Managerでは、内部の評価と推奨事項に基づいてワークロードにPSLを割り当てることができます。

システム推奨のPSLをワークロードに割り当てる方法については、を参照してください。link:..//storage-mgmt/concept_assign_policies_on_workloads.html#assigning-system-recommended-psls-to-workloads["システム推奨のPSLをワークロードに割り当てています"]

[パフォーマンスサービスレベル]ページには使用可能なPSLポリシーが一覧表示され、ポリシーを追加、編集、削除できます。


NOTE: システム定義のPSLやワークロードに現在割り当てられているPSLは変更できません。ワークロードに割り当てられている、または使用可能なPSLが他にない場合、そのPSLは削除できません。

このページには、次の情報が表示されます。

|===
| フィールド | 製品説明 


 a| 
名前
 a| 
PSLの名前。



 a| 
タイプ
 a| 
システム定義のポリシーかユーザ定義のポリシーか。



 a| 
想定IOPS/TB
 a| 
LUNまたはファイル共有でアプリケーションが実行すると予想される最小IOPS。想定IOPSは、ストレージオブジェクトの割り当てサイズに基づいて、割り当てられる最小想定IOPSを指定します。



 a| 
最大IOPS/TB
 a| 
LUNまたはファイル共有でアプリケーションが実行できる最大IOPS。ピークIOPSは、ストレージオブジェクトの割り当てサイズまたは使用済みサイズに基づいて、割り当て可能な最大IOPSを指定します。

ピークIOPSは割り当てポリシーに基づいています。割り当てポリシーは、allocated-spaceまたはused-spaceのいずれかです。割り当てポリシーがallocated-spaceの場合は、ストレージオブジェクトのサイズに基づいてピークIOPSが計算されます。割り当てポリシーがused-spaceの場合は、Storage Efficiency機能の効果を考慮して、ストレージオブジェクトに格納されているデータの量に基づいてピークIOPSが計算されます。デフォルトでは、割り当てポリシーはused-spaceに設定されます。



 a| 
絶対最小IOPS
 a| 
想定IOPSがこの値より小さい場合は、絶対最小IOPSが無視されます。システム定義のPSLのデフォルト値は次のとおりです。

* 最高レベルのパフォーマンス：想定IOPS≧6144/TBの場合、絶対最小IOPS=1000
* パフォーマンス：想定IOPS≧2048/TBで6144/TBの場合、絶対最小IOPS=500
* 値：想定IOPS≧128/TBで2048/TB未満の場合、絶対最小IOPS=75


システム定義のデータベースPSLのデフォルト値は次のとおりです。

* データベースログの最高レベル：想定 IOPS ≧ 22528 の場合、絶対最小 IOPS =4000
* データベース共有データの最大 IOPS ：想定 IOPS ≧ 16384 の場合、絶対最小 IOPS=2000
* データベースデータの最高レベル：想定 IOPS ≧ 12288 の場合、絶対最小 IOPS=2000


カスタムPSLの絶対最小IOPSの値は、最大75000になります。小さい方の値は次のように計算されます。

1000 /想定レイテンシ



 a| 
想定レイテンシ
 a| 
ストレージIOPSの想定レイテンシ（処理あたりのミリ秒（ミリ秒/処理）。



 a| 
容量
 a| 
クラスタ内の使用可能容量と使用済み容量の合計。



 a| 
ワークロード
 a| 
PSLが割り当てられているストレージワークロードの数。

|===
ピークIOPSと想定IOPSを使用して、ONTAPクラスタで一貫した差別化されたパフォーマンスを達成する方法については、次の技術情報アーティクルを参照してください。https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/Active_IQ_Unified_Manager/What_is_Performance_Budgeting%3F["パフォーマンスの予算編成とは"]



=== PSLで定義されたしきい値を超えているワークロードに対して生成されたイベント

過去1時間のうちにワークロードが想定レイテンシ値を30%超えた場合、Unified Managerは次のいずれかのイベントを生成して潜在的なパフォーマンスの問題をユーザに通知します。

* パフォーマンスサービスレベルポリシーに定義されたワークロードのボリュームレイテンシしきい値を超過
* パフォーマンスサービスレベルポリシーに定義されたワークロードのLUNレイテンシしきい値を超過


ワークロードを分析して、レイテンシの値が上昇している原因を確認できます。

詳細については、次のリンクを参照してください。

* link:../events/reference_volume_events.html#impact-area-performance["ボリュームイベント"]
* link:../performance-checker/concept_what_happens_when_performance_threshold_policy_is_breached.html["パフォーマンスしきい値ポリシーを超えた場合の動作"]
* link:..//performance-checker/concept_how_unified_manager_uses_workload_response_time.html["Unified Manager がワークロードのレイテンシを使用してパフォーマンスの問題を特定する仕組み"]
* link:../performance-checker/concept_what_performance_events_are.html["パフォーマンスイベントとは"]




=== システム定義のPSL

次の表に、システム定義のPSLに関する情報を示します。

|===
| パフォーマンスサービスレベル | 概要とユースケース | 想定レイテンシ（ミリ秒 / 処理） | 最大IOPS | 想定 IOPS | 絶対最小IOPS 


 a| 
卓越したパフォーマンス
 a| 
非常に高いスループットを非常に低いレイテンシで実現

レイテンシの影響を受けやすいアプリケーションに最適
 a| 
1
 a| 
12288
 a| 
6144
 a| 
1000



 a| 
パフォーマンス
 a| 
高いスループットを低いレイテンシで実現

データベースおよび仮想アプリケーションに最適
 a| 
2
 a| 
4096
 a| 
2048
 a| 
500



 a| 
値
 a| 
高いストレージ容量と中程度のレイテンシを実現

Eメール、Webコンテンツ、ファイル共有、バックアップターゲットなどの大容量アプリケーションに最適
 a| 
17
 a| 
512
 a| 
128
 a| 
75



 a| 
最高レベル（データベースログ用）
 a| 
最小のレイテンシで最大スループットを実現

データベースログをサポートするデータベースアプリケーションに最適です。データベースログは非常にバースト性が高く、常にロギングが必要であるため、このPSLは最高のスループットを提供します。
 a| 
1
 a| 
45056
 a| 
22528
 a| 
4000



 a| 
最高レベル（データベース共有データ用）
 a| 
非常に高いスループットを最小のレイテンシで実現

共通のデータストアに格納され、データベース間で共有されるデータベースアプリケーションデータに最適です。
 a| 
1
 a| 
32768
 a| 
16384
 a| 
2000



 a| 
最高レベル（データベースデータ用）
 a| 
高いスループットを最小のレイテンシで実現

データベーステーブル情報やメタデータなどのデータベースアプリケーションデータに最適です。
 a| 
1
 a| 
24576
 a| 
12288
 a| 
2000

|===