---
permalink: storage-mgmt/concept_workloads_dashboard.html 
sidebar: sidebar 
keywords: workloads, overview, data center, sections 
summary: ワークロードは、ボリュームやLUNなどのストレージオブジェクトの入出力（I/O）処理を表します。ストレージのプロビジョニング方法は、想定されるワークロード要件に基づいています。Active IQ Unified Manager は、ストレージオブジェクトとの間にトラフィックが発生した時点でワークロードの統計情報の追跡を開始します。たとえば、ワークロードのIOPSとレイテンシの値は、ユーザがデータベースまたはEメールアプリケーションの使用を開始したあとに表示されます。 
---
= ワークロードの概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ワークロードは、ボリュームやLUNなどのストレージオブジェクトの入出力（I/O）処理を表します。ストレージのプロビジョニング方法は、想定されるワークロード要件に基づいています。Active IQ Unified Manager は、ストレージオブジェクトとの間にトラフィックが発生した時点でワークロードの統計情報の追跡を開始します。たとえば、ワークロードのIOPSとレイテンシの値は、ユーザがデータベースまたはEメールアプリケーションの使用を開始したあとに表示されます。

[ワークロード]ページには、Unified Managerで管理されているONTAPクラスタのストレージワークロードの概要が表示されます。パフォーマンスサービスレベルに準拠したストレージワークロードと準拠していないストレージワークロードに関する履歴情報が一目でわかるように表示されます。また、データセンター内のクラスタの合計容量、使用可能容量、使用済み容量、およびパフォーマンス（IOPS）を評価することもできます。

[NOTE]
====
パフォーマンスサービスレベルに準拠していない、利用できない、またはパフォーマンスサービスレベルで管理されていないストレージワークロードの数を評価し、それらのワークロードが準拠していること、使用容量、IOPSが確保されるように必要な措置を講じることを推奨します。

====
[ワークロード]ページには次の2つのセクションがあります。

* ワークロードの概要： Unified Manager で管理されている ONTAP クラスタ上のストレージワークロード数を表示します。
* データセンターの概要：データセンター内のストレージワークロードの容量とIOPSの概要が表示されます。関連するデータは、データセンターレベルと個別に表示されます。




== [ワークロードの概要]セクション

[ワークロードの概要]セクションには、ストレージワークロードの履歴情報が一目でわかるように表示されます。ストレージワークロードのステータスは、割り当てられているパフォーマンスサービスレベルと割り当てられていないパフォーマンスサービスレベルに基づいて表示されます。

* * Assigned * ：パフォーマンスサービスレベルが割り当てられているストレージワークロードについては、次のステータスが報告されます。
+
** * 準拠 * ：ストレージワークロードのパフォーマンスは、割り当てられているパフォーマンスサービスレベルに基づきます。ストレージワークロードが、関連付けられているパフォーマンスサービスレベルで定義されたしきい値レイテンシの範囲内にある場合、「準拠」とマークされます。準拠しているワークロードは青で表示されます。
** * 非準拠 * ：ストレージワークロードのレイテンシが、関連付けられたパフォーマンスサービスレベルで定義されたしきい値遅延を超えた場合、パフォーマンス監視中にストレージワークロードは「不適合」とマークされます。非準拠のワークロードはオレンジで表示されます。
** * 利用不可 *: ストレージワークロードがオフラインの場合、または対応するクラスタに到達できない場合、ストレージワークロードは「利用不可」とマークされます。利用できないワークロードは赤で表示されます。


* * 未割り当て * ：パフォーマンスサービスレベルが割り当てられていないストレージワークロードは「未割り当て」と報告されます。情報アイコンにその数が表示されます。


合計ワークロード数は、割り当て済みのワークロードと割り当てなしのワークロードの合計です。

このセクションに表示されるワークロードの総数をクリックすると、ワークロードのページに表示できます。

「 Conformance by Performance Service Levels 」サブセクションには、使用可能なストレージワークロードの総数が表示されます。

* 各タイプのパフォーマンスサービスレベルへの準拠
* 割り当て済みのパフォーマンスサービスレベルと推奨されるパフォーマンスサービスレベルが一致していない




== [データセンターの概要]セクション

データセンターの概要セクションに、データセンター内のすべてのクラスタの使用可能容量と使用済み容量、および IOPS が図で表示されます。このデータを使用して、ストレージワークロードの容量とIOPSを管理する必要があります。このセクションには、すべてのクラスタのストレージワークロードに関する次の情報も表示されます。

* データセンター内のすべてのクラスタの合計容量、使用可能容量、使用済み容量
* データセンター内のすべてのクラスタの合計IOPS、使用可能IOPS、使用済みIOPS
* 各パフォーマンスサービスレベルに基づく使用可能容量と使用済み容量
* 各パフォーマンスサービスレベルに基づく使用可能IOPSと使用済みIOPS
* パフォーマンスサービスレベルが割り当てられていないワークロードで使用されている合計スペースとIOPS


* パフォーマンスサービスレベル * に基づいて、データセンターの容量とパフォーマンスを計算する方法

使用済み容量と使用済みIOPSは、クラスタ内のすべてのストレージワークロードの合計使用済み容量とパフォーマンスの観点から取得されます。

使用可能IOPSは、ノードの想定レイテンシと推奨されるパフォーマンスサービスレベルに基づいて計算されます。これには、想定レイテンシが独自の想定レイテンシ以下であるすべてのパフォーマンスサービスレベルの使用可能IOPSが含まれます。

使用可能容量は、アグリゲートの想定レイテンシと推奨されるパフォーマンスサービスレベルに基づいて計算されます。これには、想定レイテンシが独自の想定レイテンシ以下であるすべてのパフォーマンスサービスレベルの使用可能容量が含まれます。
