---
permalink: storage-mgmt/concept_all_workloads.html 
sidebar: sidebar 
keywords: view, workloads, add, provision, storage, filter, analyze, performance, capacity, criteria 
summary: すべてのワークロードビューには、データセンター内のクラスタで使用可能なすべてのワークロードのリストが表示されます。 
---
= ワークロードの表示
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Managerにクラスタを追加すると、各クラスタのストレージワークロードが自動的に検出されて[ワークロード]ページに表示されます。

Unified Managerは、ストレージワークロードでI/O処理が開始されたあとに、推奨事項（推奨PSL）についてワークロードの分析を開始します。

FlexGroupボリュームとそのコンスティチュエントは除外されます。



== ワークロードの概要

[ワークロードの概要]ページには、データセンター内のワークロードの概要と、データセンターのスペースとパフォーマンスの概要が表示されます。

* *ワークロードの概要*パネル：ワークロードの総数、およびPSLが割り当てられている/割り当てられていないワークロードの数が表示されます。各PSLのワークロード数の内訳も表示されます。数をクリックすると、「すべてのワークロード」が表示され、フィルタリングされたワークロードが表示されます。また、システム推奨事項に一致しないワークロードの数を表示し、システム推奨のPSLを割り当てても、* Assign System-Recommended PSL *ボタンをクリックすることで、該当するワークロードにPSLを割り当てることができます。
* *データセンターの概要*パネル：データセンターの使用可能スペースと使用済みスペース（TiB）とパフォーマンス（IOPS）が表示されます。各PSLのすべてのワークロードについて、使用可能スペース（TiB）と使用済みスペース（TiB）とパフォーマンス（IOPS）の内訳も表示されます。




== [すべてのワークロード]ビュー

ストレージ>ワークロード>すべてのワークロード*ページには、Unified Managerで管理されているONTAP クラスタに関連付けられているストレージワークロードが表示されます。

新たに検出されたストレージワークロードで I/O 処理が行われていない場合、ステータスは「 I/O を待機中」になります。ストレージワークロードで I/O 処理が開始されると、 Unified Manager が分析を開始し、ワークロードのステータスが「学習中 ... 」に変わります。分析が完了すると（I/O処理の開始から24時間以内）、ストレージワークロードに対して推奨されるPSLが表示されます。

このページでは、ストレージ効率化ポリシー（SEP）とパフォーマンスサービスレベル（PSL）をストレージワークロードに割り当てることもできます。次の複数のタスクを実行できます。

* ストレージワークロードを追加またはプロビジョニングする
* ワークロードのリストを表示してフィルタリングする
* ストレージワークロードにPSLを割り当てる
* システム推奨のPSLを評価してワークロードに割り当てる
* SEPをストレージワークロードに割り当て




=== ストレージワークロードの追加またはプロビジョニング

サポートされる LUN （ iSCSI と FCP の両プロトコルをサポート）、 NFS ファイル共有、 SMB 共有にストレージワークロードを追加またはプロビジョニングできます。

.手順
. ストレージ>ワークロード>すべてのワークロード>作成*をクリックします。
. ワークロードの作成詳細については、を参照してください link:../storage-mgmt/concept_provision_and_manage_workloads.html["ワークロードのプロビジョニングと管理"]。




=== ワークロードの表示とフィルタリング

[すべてのワークロード]画面では、データセンター内のすべてのワークロードを表示したり、PSLまたは名前に基づいて特定のストレージワークロードを検索したりできます。フィルタアイコンを使用して、検索条件を入力できます。ホストクラスタやStorage VMなど、さまざまなフィルタ条件で検索できます。容量の合計 * オプションを使用すると、ワークロードの合計容量（ MB ）でフィルタリングできます。ただし、合計容量がバイトレベルで比較されるため、この場合は返されるワークロードの数が変わる可能性があります。

各ワークロードについて、割り当てられているPSLとSEPに加えて、ホストクラスタやStorage VMなどの情報が表示されます。

また、このページではワークロードのパフォーマンスの詳細を確認することもできます。ワークロードの IOPS 、容量、レイテンシに関する詳細情報を表示するには、「 * 列の選択 / 順序」ボタンをクリックし、表示する列を選択します。パフォーマンスビューの列にはワークロードの平均 IOPS とピーク IOPS が表示され、ワークロードアナライザのアイコンをクリックすると詳細な IOPS 分析を確認できます。



=== ワークロードのパフォーマンスと容量の条件の分析

IOPS分析*ポップアップの*ワークロードの分析*ボタンをクリックすると、ワークロード分析ページが開き、期間を選択して、選択したワークロードのレイテンシ、スループット、容量のトレンドを確認できます。Workload Analyzerの詳細については、を参照してくださいlink:..//performance-checker/concept_troubleshooting_workloads_using_workload_analyzer.html["Workload Analyzerを使用したワークロードのトラブルシューティング"]。

パフォーマンスビュー * 列の棒グラフアイコンをクリックすると、ワークロードに関するパフォーマンス情報を表示してトラブルシューティングに役立てることができます。ワークロードの分析ページにパフォーマンスと容量のグラフを表示してオブジェクトを分析するには、 * ワークロードの分析 * ボタンをクリックします。

詳細については、を参照してください link:../performance-checker/reference_what_data_does_workload_analyzer_display.html["Workload Analyzerで表示されるデータ"]。
