---
permalink: storage-mgmt/concept_assign_policies_on_workloads.html 
sidebar: sidebar 
keywords: assign, policies, workloads, single, multiple, storage, system-recommended, psls 
summary: '[すべてのワークロード]ページで各種のナビゲーションオプションを使用して、ストレージ効率化ポリシー（SEP）とパフォーマンスサービスレベル（PSL）をストレージワークロードに割り当てることができます。' 
---
= ワークロードへのポリシーの割り当て
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
[すべてのワークロード]ページで各種のナビゲーションオプションを使用して、ストレージ効率化ポリシー（SEP）とパフォーマンスサービスレベル（PSL）をストレージワークロードに割り当てることができます。



== 単一のワークロードへのポリシーの割り当て

単一のワークロードにPSL、SEP、またはその両方を割り当てることができます。次の手順を実行します。

. ワークロードを選択します。
. 行の横にある編集アイコンをクリックし、 * 編集 * をクリックします。
+
[ 割り当てられているパフォーマンスサービスレベル * ] フィールドと [ ストレージ効率化ポリシー * ] フィールドが有効になります。

. 必要なPSL、SEP、またはその両方を選択します。
. チェックアイコンをクリックして変更を適用します。


[NOTE]
====
また、ワークロードを選択し、 * その他の操作 * をクリックしてポリシーを割り当てることもできます。

====


== 複数のストレージワークロードへのポリシーの割り当て

PSLまたはSEPを複数のストレージワークロードに同時に割り当てることができます。次の手順を実行します。

. ポリシーを割り当てるワークロードのチェックボックスを選択するか、データセンター内のすべてのワークロードを選択します。
. [ * その他のアクション * ] をクリックします。
. PSL を割り当てるには、「 * パフォーマンスサービスレベルの割り当て」を選択してください。SEP を割り当てる場合は、 * ストレージ効率化ポリシーの割り当て * を選択します。ポリシーを選択するためのポップアップが表示されます。
. 適切なポリシーを選択し、 * 適用 * をクリックします。ポリシーが割り当てられているワークロードの数が表示されます。ポリシーが割り当てられていないワークロードも原因とともに表示されます。
+
[NOTE]
====
選択したワークロードの数によっては、ワークロードに一括でポリシーを適用するのに時間がかかることがあります。[ * バックグラウンドで実行 * ] ボタンをクリックすると、バックグラウンドで処理を実行しながら他のタスクを続行できます。一括割り当てが完了したら、完了ステータスを確認できます。複数のワークロードにPSLを適用している場合、以前の一括割り当てジョブの実行中に別の要求をトリガーすることはできません。

====




== システム推奨のPSLをワークロードに割り当てています

PSLが割り当てられていないデータセンター内のストレージワークロードにシステム推奨のPSLを割り当てることができます。また、割り当てられているPSLがシステム推奨のPSLと一致しない場合もあります。この機能を使用するには、 * Assign System Recommended PSL * ボタンをクリックします。特定のワークロードを選択する必要はありません。

推奨構成はシステム分析によって内部的に決定され、IOPSやその他のパラメータが使用可能なPSLの定義と一致しないワークロードについてはスキップされます。およびラーニングステータスのストレージワークロード `Waiting for I/O`も除外されます。

[NOTE]
====
Unified Managerがシステム分析よりも優先してワークロードに別のPSLを推奨するためにワークロード名に検索する特別なキーワードがあります。ワークロードの名前に「 ora 」という文字が含まれている場合は、 **Extreme Performance ** PSL が推奨されます。ワークロードの名前に「 VM 」という文字が含まれている場合は、 **Performance** PSL を使用することをお勧めします。

====
ナレッジベース（KB）の記事も参照 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/Active_IQ_Unified_Manager/Performance_Service_Level'_is_not_adaptive_to_a_highly_variable_workload["Active IQ Unified Managerの「システム推奨のパフォーマンスサービスレベルの割り当て」が変数の大きいワークロードに適応していません"]
