---
permalink: storage-mgmt/reference_email_notification_format_page.html 
sidebar: sidebar 
keywords: email, notification, format, page 
summary: '[Email Notification Format]ページには、クォータ関連の問題が発生した場合（ソフトリミットを超過した場合、またはハードリミットに達した場合）にユーザまたはユーザグループに送信されるEメールのルールが表示されます。' 
---
= [Email Notification Format]ページ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
[Email Notification Format]ページには、クォータ関連の問題が発生した場合（ソフトリミットを超過した場合、またはハードリミットに達した場合）にユーザまたはユーザグループに送信されるEメールのルールが表示されます。

E メール通知は、次のユーザまたはユーザグループのクォータイベントが生成された場合にのみ送信されます。 ユーザクォータまたはグループクォータのディスクスペースがソフトリミットを超過、ユーザクォータまたはグループクォータのファイル数がソフトリミットを超過、ユーザクォータまたはグループクォータのディスクスペースがハードリミットに達した、またはユーザクォータまたはグループクォータのファイル数がハードリミットを超過しました。

* * から *
+
Eメールの送信元のEメールアドレスが表示されます。このアドレスは変更できます。デフォルトでは、[通知]ページに指定されているEメールアドレスです。

* * 件名 *
+
通知メールの件名が表示されます。

* * 電子メールの詳細 *
+
通知Eメールのテキストが表示されます。必要に応じてテキストを変更できます。たとえば、クォータ属性に関連する情報を指定し、キーワードの数を減らすことができます。ただし、キーワードは変更しないでください。

+
有効なキーワードは次のとおりです。

+
** $イベント名
+
Eメール通知の原因となったイベントの名前を指定します。

** $QUOTA_TARGET
+
クォータが適用されるqtreeまたはボリュームを示します。

** $quota_used_percent
+
ディスクのハードリミット、ディスクのソフトリミット、ファイルのハードリミット、またはファイルのソフトリミットのうち、ユーザまたはユーザグループによって使用されている割合を示します。

** $quota_limit
+
ユーザまたはユーザグループがディスクのハードリミットまたはファイルのハードリミットに達し、次のいずれかのイベントが生成されます。

+
*** ユーザクォータまたはグループクォータのディスクスペースがハードリミットに達しました
*** ユーザクォータまたはグループクォータのディスクスペースがソフトリミットに達しました
*** ユーザクォータまたはグループクォータのファイル数がハードリミットに達しました
*** ユーザクォータまたはグループクォータのファイル数がソフトリミットに達しました


** $quota_used
+
ユーザまたはユーザグループによって使用されているディスクスペース、または作成されたファイル数を示します。

** $quota_user
+
ユーザまたはユーザグループの名前を指定します。







== コマンドボタン

各コマンドボタンを使用して、Eメール通知形式に対する変更をプレビュー、保存、またはキャンセルできます。

* * プレビュー *
+
通知メールのプレビューが表示されます。

* * 工場出荷時のデフォルトに戻します *
+
通知の形式を工場出荷時のデフォルトに戻すことができます。

* * 保存 *
+
通知の形式に対する変更内容を保存します。


