---
permalink: storage-mgmt/reference_dashboard_page.html 
sidebar: sidebar 
keywords: dashboard page, 
summary: 'Dashboard ページには、監視しているクラスタの容量、パフォーマンス、およびセキュリティの健全性の概要を示すパネルがあります。また、このページの[管理操作]パネルには、Unified Managerで特定のイベントを解決するために実行できる修正が表示されます。' 
---
= [ダッシュボード]ページ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
[Dashboard]ページの各パネルには、監視しているクラスタの容量、パフォーマンス、セキュリティの健全性の概要が表示されます。また、このページの[管理操作]パネルには、Unified Managerで特定のイベントを解決するために実行できる修正が表示されます。

ほとんどのパネルには、そのカテゴリのアクティブイベントの数と、過去24時間に追加された新しいイベントの数も表示されます。この情報から、イベントを解決するために詳細な分析が必要なクラスタを決定できます。イベントをクリックすると、上位のイベントが表示され、そのカテゴリのアクティブなイベントだけを表示するようにフィルタリングされた[イベント管理]インベントリページへのリンクが表示されます。

ダッシュボードの上部で、すべての監視対象クラスタ（「すべてのクラスタ」）の情報を表示するか、個 々 のクラスタの情報を表示するかを選択できます。最初にすべてのクラスタのステータスを表示してから、詳細情報を確認する場合は個々のクラスタにドリルダウンできます。

[NOTE]
====
以下に示すパネルの一部は、構成に応じてダッシュボードに表示されます。

====


== [管理操作]パネル

一部の問題については、Unified Managerの詳細な診断によって単一の解決策が提供されます。解決策がある場合は、このパネルに * Fix it * または * Fix All * ボタンで表示されます。これらの問題はUnified Managerからすぐに解決できます。ONTAP System ManagerやONTAP CLIを使用する必要はありません。すべての問題を表示するには、[参照]をクリックして詳細を確認link:concept_fix_ontap_issues_directly_from_unified_manager.html["ONTAPの問題をUnified Managerから直接修正"]してください。



== [容量]パネル

すべてのクラスタを表示している場合、このパネルには、各クラスタの使用済み物理容量（Storage Efficiencyによる削減効果の適用後）と使用可能な物理容量（Storage Efficiencyによる削減効果を除く）、ディスクがフルになるまでの予測日数、およびONTAPのStorage Efficiency設定に基づくデータ削減率（Snapshotコピーなし）が表示されます。また、設定されているクラウド階層の使用済み容量も表示されます。棒グラフをクリックすると、そのクラスタの[アグリゲート]インベントリページが表示されます。「フルまでの日数」というテキストをクリックすると容量の残り日数が最も少ないアグリゲートを示すメッセージが表示され、そのアグリゲート名をクリックすると詳細が表示されます。

単一のクラスタを表示している場合、このパネルには、ローカル階層上の個 々 のディスクタイプ別にソートされたデータアグリゲートおよびクラウド階層について、使用済み物理容量と使用可能物理容量が表示されます。ディスクタイプの棒グラフをクリックすると、そのディスクタイプを使用しているボリュームの[ボリューム]インベントリページが表示されます。



== [パフォーマンス容量]パネル

すべてのクラスタを表示している場合、このパネルには、各クラスタのパフォーマンス容量（過去1時間の平均）とパフォーマンス容量が上限に達するまでの日数（日次増加率に基づく）が表示されます。棒グラフをクリックすると、そのクラスタの[Nodes]インベントリページが表示されます。[ノード]インベントリページには、過去72時間の平均パフォーマンス容量が表示されます。「フルまでの日数」というテキストをクリックすると、パフォーマンス容量の残り日数が最も少ないノードを示すメッセージが表示されます。ノード名をクリックすると詳細が表示されます。

単一のクラスタを表示している場合、このパネルには、クラスタの使用済みパフォーマンス容量、合計IOPS、合計スループット（MBps）の値、およびこれらの3つの指標が上限に達するまでの想定日数が表示されます。



== [ワークロードIOPS]パネル

単一のクラスタを表示している場合、このパネルには、特定の範囲のIOPSで現在実行されているワークロードの総数と、グラフにカーソルを合わせると各ディスクタイプの数が表示されます。



== [ワークロードパフォーマンス]パネル

このパネルには、各パフォーマンスサービスレベル（PSL）ポリシーに割り当てられている準拠ワークロードと非準拠ワークロードの総数が表示されます。また、PSLが割り当てられていないワークロードの数も表示されます。棒グラフをクリックすると、そのポリシーに割り当てられている準拠ワークロードが[ワークロード]ページに表示されます。棒グラフの横にある数値をクリックすると、そのポリシーに割り当てられている準拠ワークロードと非準拠ワークロードが表示されます。



== [セキュリティ]パネル

[Security]パネルには、現在のビューに応じて、すべてのクラスタまたは単一のクラスタのセキュリティステータスの概要が表示されます。このパネルには、

* 過去24時間に受信したセキュリティイベントのリスト。イベントをクリックすると、[イベントの詳細]ページに詳細が表示されます。
* クラスタのセキュリティステータス（準拠クラスタと非準拠クラスタの数）
* Storage VMのセキュリティステータス（準拠Storage VMと非準拠Storage VMの数）
* ボリューム暗号化ステータス（暗号化されているボリュームまたは暗号化されていないボリュームの数）
* ボリュームのランサムウェア対策のステータス（ランサムウェア対策が有効または無効になっているボリュームの数）


準拠クラスタと非準拠クラスタ、Storage VM、暗号化されたボリュームと非暗号化されたボリューム、ボリュームのランサムウェア対策ステータスの棒グラフをクリックすると、対応するページに移動して、フィルタリングされたクラスタ、Storage VM、ボリュームのセキュリティの詳細を確認できます。

準拠はに基づいてい https://www.netapp.com/pdf.html?item=/media/10674-tr4569pdf.pdf["ONTAP 9 セキュリティ設定ガイド"^]ます。パネル上部の右矢印をクリックすると、[セキュリティ]ページにすべてのクラスタのセキュリティの詳細が表示されます。詳細については、を参照してください link:../health-checker/task_view_detailed_security_status_for_clusters_and_svms.html["クラスタと Storage VM の詳細なセキュリティステータスの表示"]。



== [Data Protection]パネル

このパネルには、データセンター内の単一またはすべてのクラスタのデータ保護の概要が表示されます。ONTAPには、データ保護イベント、MetroClusterイベントの総数、および過去24時間に生成されたアクティブなイベントの数が表示されます。これらの各イベントのリンクをクリックすると、[イベントの詳細]ページが表示されます。[ すべて表示 *] リンクをクリックすると、 [ イベント管理 ] インベントリページですべてのアクティブな保護イベントを表示できます。パネルには以下が表示されます

* クラスタ内のボリュームの数、またはSnapshotコピーで保護されているデータセンター内のすべてのクラスタの数。
* クラスタ内のボリュームの数、またはSnapMirror関係で保護されているデータセンター内のすべてのクラスタの数。SnapMirror関係の場合は、ソースクラスタのボリューム数が考慮されます。
* IPまたはFC経由のMetroCluster構成で保護されているデータセンター内のクラスタまたはすべてのクラスタの数。
* 遅延ステータスに基づくSnapMirrorの目標復旧時点（RPO）遅延があるボリューム関係の数。


マウスにカーソルを合わせると、それぞれのカウントと凡例が表示されます。パネル上部の右矢印をクリックすると、[Data Protection]ページで単一またはすべてのクラスタの詳細を確認できます。また、以下をクリックすることもできます。

* 保護されていないボリュームとSnapshotコピーで保護されているボリュームの棒グラフを使用して、[ボリューム]ページに移動して詳細を確認します。
* [Clusters]ページに移動して詳細を表示するには、MetroCluster構成で保護されているクラスタまたは保護されていないクラスタの棒グラフを使用します。
* すべての関係の棒グラフを使用して[Relationships]ページに移動すると、ソースクラスタに基づいて詳細がフィルタリングされます。


詳細については、を参照してください link:../data-protection/view-protection-status.html["ボリュームの保護ステータスの表示"]。



== [使用状況の概要]パネル

すべてのクラスタを表示している場合は、IOPS、スループット（MBps）、または使用済み物理容量が大きい順にクラスタを表示できます。

単一のクラスタを表示している場合は、IOPS、スループット（MBps）、または使用済み論理容量が大きい順にワークロードを表示できます。

* 関連情報 *

link:../events/task_fix_issues_using_um_automatic_remediations.html["Unified Managerの自動修正措置を使用した問題の修正"]

link:../performance-checker/task_display_information_about_performance_event.html["パフォーマンスイベントに関する情報の表示"]

link:../performance-checker/concept_manage_performance_using_perf_capacity_available_iops.html["パフォーマンス容量と使用可能なIOPSの情報を使用したパフォーマンスの管理"]

link:../health-checker/reference_health_volume_details_page.html["[ボリューム/健全性の詳細]ページ"]

link:../performance-checker/reference_performance_event_analysis_and_notification.html["パフォーマンスイベントの分析と通知"]

link:../events/reference_description_of_event_severity_types.html["イベントの重大度タイプの説明"]

link:../performance-checker/concept_sources_of_performance_events.html["パフォーマンスイベントのソース"]

link:../health-checker/concept_manage_cluster_security_objectives.html["クラスタのセキュリティ目標の管理"]

link:../performance-checker/concept_monitor_cluster_performance_from_cluster_landing_page.html["[パフォーマンスクラスタランディング]ページからのクラスタパフォーマンスの監視"]

link:../performance-checker/concept_monitor_performance_using_object_performance.html["[パフォーマンスインベントリ]ページを使用したパフォーマンスの監視"]
