---
permalink: storage-mgmt/reference_what_ontap_issues_can_unified_manager_fix.html 
sidebar: sidebar 
keywords: ontap issues, fix it action, automatic remediation feature, remediation events, fix-it messages, fix-it events 
summary: この表では、 Unified Manager のユーザインターフェイスで Fix it ボタンまたは Fix All ボタンをクリックして直接解決できる ONTAP の問題について説明します。 
---
= Unified Managerで解決できる問題
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Managerの自動修復機能を使用すると、ONTAPの特定の問題を解決するか、ONTAPの特定の機能（ランサムウェア対策の監視など）をUnified Managerで効果的に管理するかを選択できます。

この表では、 Unified Manager Web UI の * Fix it * または * Fix All * ボタンを使用して直接管理できる ONTAP の問題と機能について説明します。

|===
| イベント名と概要 | 管理操作 | 「修正」処理 


 a| 
ボリュームスペースがフル

ボリュームにスペースがほとんど残っておらず、容量の「フル」しきい値を超えています。このしきい値は、デフォルトでボリュームサイズの90%に設定されています。
 a| 
ボリュームの自動拡張を有効にする
 a| 
Unified Managerは、このボリュームにボリュームの自動拡張が設定されていないと判断したため、この機能を有効にして、必要に応じてボリュームの容量を拡張します。



 a| 
inodeがフル

このボリュームでinodeが不足しているため、新しいファイルを受け付けることができません。
 a| 
ボリュームのinode数の増加
 a| 
ボリュームのinodeの数が2%増加します。



 a| 
ストレージ階層のポリシーの不一致を検出

ボリュームにアクセス頻度の低いデータが大量にあり、現在の階層化ポリシーは「snapshot-only」または「none」に設定されています。
 a| 
クラウドの自動階層化を有効化
 a| 
ボリュームはすでにFabricPoolに配置されているため、階層化ポリシーが「auto」に変更され、アクセス頻度の低いデータが低コストのクラウド階層に移動されます。



 a| 
ストレージ階層の不一致を検出

アクセス頻度の低いデータが大量にありますが、クラウド対応のストレージ階層（FabricPool）にはありません。
 a| 
ボリュームのストレージ階層の変更
 a| 
アクセス頻度の低いデータをクラウド階層に移動するには、ボリュームをクラウド対応のストレージ階層に移動し、階層化ポリシーを「自動」に設定します。



 a| 
監査ログが無効

Storage VMの監査ログが有効になっていません
 a| 
Storage VMの監査ログを有効にする
 a| 
Storage VMで監査ログを有効にします。

Storage VMでローカルまたはリモートの監査ログの場所を設定しておく必要があります。



 a| 
ログインバナーが無効

セキュリティを強化するには、アクセス制限を明確にしてクラスタのログインバナーを有効にする必要があります。
 a| 
クラスタのログインバナーの設定
 a| 
クラスタ・ログイン・バナーを「許可されたユーザーにアクセス制限」に設定します。



 a| 
ログインバナーが無効

アクセス制限を明確にしてセキュリティを強化するには、Storage VMのログインバナーを有効にする必要があります。
 a| 
Storage VMのログインバナーの設定
 a| 
Storage VMのログインバナーを「許可されたユーザのみがアクセスできます」に設定します。



 a| 
SSHでセキュアでない暗号が使用されている

サフィックスが「-cbc」の暗号はセキュアでないとみなされます。
 a| 
セキュアでない暗号をクラスタから削除する
 a| 
安全でない暗号（aes192-cbcやaes128-cbcなど）をクラスタから削除します。



 a| 
SSHでセキュアでない暗号が使用されている

サフィックスが「-cbc」の暗号はセキュアでないとみなされます。
 a| 
セキュアでない暗号をStorage VMから削除する
 a| 
安全でない暗号（aes192-cbcやaes128-cbcなど）をStorage VMから削除します。



 a| 
AutoSupport HTTPS転送が無効

テクニカルサポートへのAutoSupportメッセージの送信に使用する転送プロトコルを暗号化する必要があります。
 a| 
HTTPSをAutoSupportメッセージの転送プロトコルとして設定する
 a| 
クラスタでのAutoSupportメッセージの転送プロトコルとしてHTTPSを設定します。



 a| 
クラスタ負荷の不均衡しきい値を超過

クラスタ内のノード間で負荷が不均衡になっています。このイベントは、ノード間の使用済みパフォーマンス容量の差が30%を超えた場合に生成されます。
 a| 
クラスタワークロードを分散
 a| 
Unified Managerは、不均衡を解消するためにノード間で移動するのが最適なボリュームを特定し、ボリュームを移動します。



 a| 
クラスタ容量の不均衡しきい値を超過

クラスタ内のアグリゲート間で容量が不均衡になっていることを示します。このイベントは、アグリゲート間の使用済み容量の差異が70%を超えた場合に生成されます。
 a| 
クラスタ容量を分散
 a| 
Unified Managerは、不均衡を解消するためにアグリゲート間で移動するのが最適なボリュームを特定してから、ボリュームを移動します。



 a| 
使用済みパフォーマンス容量のしきい値を超過

非常にアクティブな1つ以上のワークロードの利用率を下げないと、ノードの負荷が過剰に利用される可能性があることを示します。このイベントは、ノードの使用済みパフォーマンス容量の値が12時間以上100%を超えた場合に生成されます。
 a| 
ノードの高負荷を制限する
 a| 
Unified ManagerはIOPSが高いボリュームを特定し、過去の想定IOPSレベルとピークIOPSレベルを使用してQoSポリシーを適用してノードの負荷を軽減します。



 a| 
動的イベントの警告しきい値を超過

一部のワークロードの負荷が異常に高いため、ノードがすでに過負荷状態で動作していることを示します。
 a| 
ノードの過負荷を軽減
 a| 
Unified ManagerはIOPSが高いボリュームを特定し、過去の想定IOPSレベルとピークIOPSレベルを使用してQoSポリシーを適用してノードの負荷を軽減します。



 a| 
テイクオーバーを実行できません

フェイルオーバーが無効になっているため、停止中またはリブート中のノードが使用可能な状態に戻るまではノードのリソースへのアクセスが失われます。
 a| 
ノードフェイルオーバーを有効にする
 a| 
Unified Manager が該当するコマンドを送信し、クラスタ内のすべてのノードのフェイルオーバーを有効にします。



 a| 
オプションcf.takeover.on_panicがoffに設定されている

ノードシェルオプション「 cf.takeover.on_panic 」が * off * に設定されており、 HA 構成のシステムで問題を原因できます。
 a| 
パニック時のテイクオーバーを有効にする
 a| 
Unified Manager が該当するコマンドを送信し、この設定を * on * に変更します。



 a| 
ノードシェルオプションSnapMirror nfs.enableを無効にします。

古いノードシェルオプション「 snapmirror.enable 」は * on * に設定されており、 ONTAP 9.3 以降へのアップグレード後のブート時に問題を原因することができます。
 a| 
SnapMirror .enableオプションをoffに設定
 a| 
Unified Manager が該当するコマンドを送信し、この設定を * off * に変更します。



 a| 
Telnetが有効

Telnetは安全ではなく、暗号化されていない方法でデータを渡すため、潜在的なセキュリティ上の問題を示します。
 a| 
Telnetを無効にする
 a| 
Unified Managerが該当するコマンドをクラスタに送信し、Telnetを無効にします。



 a| 
Storage VM Anti-Ransomware Learningの設定

ランサムウェア対策監視のために、ライセンスがあるクラスタがないか定期的にチェックする。Storage VMがこのようなクラスタでNFSボリュームとSMBボリュームのどちらのみをサポートするかを検証します。
 a| 
Storage VMをランサムウェア対策監視モードに切り替え `learning`
 a| 
Unified Managerは、クラスタ管理コンソールを使用して、Storage VMのランサムウェア対策の監視を状態に設定します `learning`。Storage VMに作成されたすべての新しいボリュームに対するランサムウェア監視は、自動的にラーニングモードに移行されます。この有効化により、ONTAPはボリューム上のアクティビティのパターンを学習し、潜在的な悪意のある攻撃による異常を検出できます。



 a| 
ボリュームのAnti-Ransomware Learningの設定

ランサムウェア対策監視のために、ライセンスがあるクラスタがないか定期的にチェックする。このようなクラスタでボリュームがNFSサービスまたはSMBサービスのみをサポートするかどうかを検証します。
 a| 
ランサムウェア対策の監視モードにボリュームを配置 `learning`
 a| 
Unified Managerは、クラスタ管理コンソールを使用して、ボリュームのAnti-Ransomware Monitoringを状態に設定します `learning`。この有効化により、ONTAPはボリューム上のアクティビティのパターンを学習し、潜在的な悪意のある攻撃による異常を検出できます。



 a| 
ボリュームのランサムウェア対策を有効化

ランサムウェア対策監視のために、ライセンスがあるクラスタがないか定期的にチェックする。ボリュームが45日以上ランサムウェア対策の監視モードになっているかどうかを検出し `learning`、アクティブモードに移行する可能性を判断します。
 a| 
ランサムウェア対策の監視モードにボリュームを配置 `active`
 a| 
Unified Managerは、クラスタ管理コンソールを使用して、ボリュームに対するランサムウェア対策の監視をに設定します `active`。これにより、ONTAPはボリューム上のアクティビティのパターンを学習し、潜在的な悪意のある攻撃による異常を検出し、データ保護アクションに関するアラートを作成できます。



 a| 
ボリュームAnti-Ransomwareを無効化

ランサムウェア対策監視のために、ライセンスがあるクラスタがないか定期的にチェックする。ボリュームに対するアクティブなランサムウェア対策監視中に繰り返し通知を検出（たとえば、ランサムウェア攻撃の可能性に関する複数の警告が30日間にわたって返されるなど）。
 a| 
ボリュームでランサムウェア対策の監視を無効にする
 a| 
Unified Managerは、クラスタ管理コンソールからボリュームのAnti-Ransomware Monitoringを無効にします。

|===