---
permalink: storage-mgmt/task_add_clusters.html 
sidebar: sidebar 
keywords: add cluster 
summary: Active IQ Unified Managerにクラスタを追加して監視することができます。たとえば、クラスタの健全性、容量、パフォーマンス、構成などの情報を取得して、発生する可能性のある問題を見つけて解決することができます。 
---
= クラスタノツイカ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Managerにクラスタを追加して監視することができます。たとえば、クラスタの健全性、容量、パフォーマンス、構成などの情報を取得して、発生する可能性のある問題を見つけて解決することができます。

* 必要なもの *

* アプリケーション管理者またはストレージ管理者のロールが必要です。
* 次の情報が必要です。
+
** Unified Managerは、オンプレミスのONTAP クラスタ、ONTAP Select 、Cloud Volumes ONTAP をサポートしています。
** クラスタのホスト名またはクラスタ管理IPアドレス（IPv4またはIPv6）が必要です。
+
ホスト名を使用する場合は、クラスタ管理LIFのクラスタ管理IPアドレスに解決される必要があります。ノード管理LIFを使用すると処理に失敗します。

** クラスタにアクセスするためのユーザ名とパスワードが必要です。
+
このアカウントには、アプリケーションアクセスが_ontapi、_console_、および_http_に 設定された_admin_roleが必要です。

** HTTPSプロトコルを使用してクラスタに接続するためのポート番号を確認しておく必要があります（通常はポート443）。
** クラスタでONTAPバージョン9.1以降が実行されている必要があります。
** Unified Managerサーバに十分なスペースが必要です。すでに使用されているスペースが90%を超えている場合、サーバにクラスタを追加することはできません。
** 必要な証明書を用意しておきます。
+
* SSL（HTTPS）証明書*：この証明書の所有者はUnified Managerです。Unified Managerを新規にインストールすると、デフォルトの自己署名SSL（HTTPS）証明書が生成されます。セキュリティを強化するために、NetAppではCA署名証明書にアップグレードすることを推奨しています。サーバ証明書の有効期限が切れた場合は、証明書を再生成し、Unified Managerを再起動してサービスに新しい証明書を組み込む必要があります。SSL証明書の再生成の詳細については、を参照してくださいlink:../config/task_generate_an_https_security_certificate_ocf.html["HTTPSセキュリティ証明書の生成"]。

+
* EMS証明書*：この証明書はUnified Managerが所有しています。ONTAPから受信したEMS通知の認証時に使用されます。

+
*相互TLS通信証明書*：Unified ManagerとONTAP 間の相互TLS通信で使用されます。証明書ベースの認証がONTAPのバージョンに基づいてクラスタに対して有効になっている。ONTAPバージョンが9.5よりも前のクラスタでは、証明書ベースの認証は有効になりません。

+
Unified Managerの古いバージョンを更新する場合、クラスタで証明書ベースの認証は自動的には有効になりません。ただし、クラスタの詳細を変更して保存することで有効にすることができます。証明書の有効期限が切れた場合は、新しい証明書を組み込むために証明書を再生成する必要があります。証明書の表示と再生成の詳細については、を参照してくださいlink:../storage-mgmt/task_edit_clusters.html["クラスタの編集"]。

+
[NOTE]
====
*** Web UIからクラスタを追加すると、証明書ベースの認証が自動的に有効になります。
*** Unified ManagerのCLIを使用してクラスタを追加できますが、証明書ベースの認証はデフォルトでは有効になっていません。Unified Manager CLIを使用してクラスタを追加する場合は、Unified Manager UIを使用してクラスタを編集する必要があります。クラスタを追加するには、link:https://docs.netapp.com/us-en/active-iq-unified-manager/events/reference_supported_unified_manager_cli_commands.html["サポートされるUnified ManagerのCLIコマンド"]Unified Manager CLIを使用します。
*** クラスタで証明書ベースの認証が有効になっている場合に、Unified Managerのバックアップをサーバから作成し、ホスト名またはIPアドレスが変更された別のUnified Managerサーバにリストアすると、クラスタの監視が失敗することがあります。この問題を回避するには、クラスタの詳細を編集して保存します。クラスタの詳細の編集の詳細については、を参照してくださいlink:../storage-mgmt/task_edit_clusters.html["クラスタの編集"]。
*** クラスタレベルでは、Active IQインターフェイスが認証方式「cert」に対して2つの新しいユーザグループエントリを追加します。


====
+
*クラスタ証明書*：この証明書の所有者はONTAP です。証明書の有効期限が切れているクラスタをUnified Managerに追加することはできません。証明書の有効期限が切れている場合は、クラスタを追加する前に証明書を再生成する必要があります。証明書の生成の詳細については、ナレッジベース（KB）の記事を参照して https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_renew_an_SSL_certificate_in_ONTAP_9["System ManagerユーザインターフェイスでONTAP の自己署名証明書を更新する方法"^]ください。



* 1つのUnified Managerインスタンスでサポートできるノードの数には制限があります。サポートされるノード数を超える環境を監視する必要がある場合は、Unified Managerインスタンスを追加でインストールして一部のクラスタを監視する必要があります。サポートされるノード数の一覧については、を参照してください https://www.netapp.com/media/13504-tr4621.pdf["Unified Managerベストプラクティスガイド"^]。


.手順
. 左側のナビゲーションペインで、 * Storage Management * > * Cluster Setup * をクリックします。
. クラスタセットアップページで、 * 追加 * をクリックします。
. [Add Cluster] ダイアログボックスで、必要に応じて値を指定し、 [*Submit*] をクリックします。
. [ ホストの許可 ] ダイアログボックスで、 [ 証明書の表示 *] をクリックして、クラスタに関する証明書情報を表示します。
. 「 * はい * 」をクリックします。
+
クラスタの詳細を保存すると、クラスタの相互TLS通信の証明書を確認できます。

+
証明書ベースの認証が有効になっていない場合、Unified Managerはクラスタを最初に追加したときにのみ証明書をチェックします。Unified Managerでは、ONTAPに対するAPI呼び出しのたびに証明書はチェックされません。



新しいクラスタのオブジェクトがすべて検出されると、Unified Managerは過去15日間の履歴パフォーマンスデータの収集を開始します。これらの統計は、データの継続性収集機能を使用して収集されます。この機能を使用すると、クラスタを追加した直後に2週間分のパフォーマンス情報を取得できます。データの継続性収集サイクルの完了後、リアルタイムのクラスタパフォーマンスデータが収集されます（デフォルトは5分間隔）。

[NOTE]
====
* 15 日間のパフォーマンス データの収集には CPU 負荷がかかります。 NetApp、データ継続性収集ポーリングが同時に多くのクラスターで実行されないように、新しいクラスターの追加を段階的に行うことを推奨しています。さらに、データ継続性収集期間中に Unified Manager を再起動すると、収集が停止し、欠落した期間のパフォーマンス チャートにギャップが表示されます。
* バージョン 9.14.1 以降のONTAPクラスターを追加すると、クラウド エージェント機能を通じて通信が行われます。  ONTAP は、読み取り専用権限を持つ内部サービス アカウント ユーザー (clus-agent-xxxx など) を自動的に作成します。  Unified Managerは、以下の場合、これらのクラスタからのデータ収集を停止します。 `clus-agent`ユーザーは削除されます。


====
[TIP]
====
クラスタを追加できないというエラーメッセージが表示された場合は、次の問題が発生していないかどうかを確認してください。

* 2つのシステムのクロックが同期されておらず、Unified ManagerのHTTPS証明書の開始日がクラスタの日付よりもあとになっている場合。NTPまたは同様のサービスを使用してクロックが同期されていることを確認する必要があります。
* クラスタのEMS通知の送信先が最大数に達している場合は、Unified Managerのアドレスを追加できません。デフォルトでは、クラスタに定義できるEMS通知の送信先は20個までです。


====
* 関連情報 *

link:../config/task_add_users.html["ユーザの追加"]

link:../health-checker/task_view_cluster_list_and_details.html["クラスタリストおよび詳細の表示"]

link:../config/task_install_ca_signed_and_returned_https_certificate.html#example-certificate-chain["CA署名済みおよび返されたHTTPS証明書のインストール"]
