---
permalink: storage-mgmt/task_create_and_edit_seps.html 
sidebar: sidebar 
keywords: create, edit, storage, efficiency, policies 
summary: システム定義のストレージ効率化ポリシーがワークロードの要件と一致しない場合は、ワークロードに最適化された独自のストレージ効率化ポリシーを作成できます。 
---
= ストレージ効率化ポリシーの作成と編集
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
システム定義のストレージ効率化ポリシーがワークロードの要件と一致しない場合は、ワークロードに最適化された独自のストレージ効率化ポリシーを作成できます。

* 必要なもの *

* アプリケーション管理者のロールが必要です。
* ストレージ効率化ポリシーの名前は一意である必要があります。次の予約キーワードは使用できません。
+
`High`、 `Low`、 `Unassigned`、 `Learning`、、 `Idle` `Default`、および `None`。



[ストレージ効率化ポリシー]ページでカスタムのストレージ効率化ポリシーを作成および編集するには、ストレージにアクセスするアプリケーションに必要なストレージ効率化の特性を定義します。

[NOTE]
====
ワークロードに現在割り当てられているストレージ効率化ポリシーは変更できません。

====
.手順
. 左側のナビゲーションペインの * Settings * で、 * Policies * > * Storage Efficiency * を選択します。
. ストレージ効率化ポリシー * ページで、新しいストレージ効率化ポリシーを作成するか既存のストレージ効率化ポリシーを編集するかに応じて、該当するボタンをクリックします。
+
|===
| 目的 | 実行する手順 


 a| 
新しいストレージ効率化ポリシーの作成
 a| 
[ 追加（ Add ） ] をクリックします。



 a| 
既存のストレージ効率化ポリシーを編集する
 a| 
既存のストレージ効率化ポリシーを選択し、 * 編集 * をクリックします

|===
+
ストレージ効率化ポリシーを追加または編集するためのページが表示されます。

. ストレージ効率化の特性を指定してストレージ効率化ポリシーをカスタマイズし、 * Submit * をクリックしてストレージ効率化ポリシーを保存します。


新しいストレージ効率化ポリシーまたは変更したストレージ効率化ポリシーは、[ワークロード]ページから、または新しいワークロードのプロビジョニング時にワークロード（LUN、NFSファイル共有、CIFS共有）に適用できます。
