---
permalink: storage-mgmt/task_create_and_edit_psls.html 
sidebar: sidebar 
keywords: create, edit, performance, service, Levels 
summary: システム定義のパフォーマンスサービスレベルがワークロードの要件と一致しない場合は、ワークロードに最適化された独自のパフォーマンスサービスレベルを作成できます。 
---
= パフォーマンスサービスレベルの作成と編集
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
システム定義のパフォーマンスサービスレベルがワークロードの要件と一致しない場合は、ワークロードに最適化された独自のパフォーマンスサービスレベルを作成できます。

* 必要なもの *

* アプリケーション管理者のロールが必要です。
* パフォーマンスサービスレベル名は一意である必要があります。次の予約キーワードは使用できません。
+
`Prime`、 `Extreme`、 `Performance`、 `Value`、、 `Unassigned` `Learning`、 `Idle` `Default`、、および `None`。



[パフォーマンスサービスレベル]ページでカスタムのパフォーマンスサービスレベルを作成および編集するには、ストレージにアクセスするアプリケーションに必要なサービスレベル目標を定義します。

[NOTE]
====
現在ワークロードに割り当てられているパフォーマンスサービスレベルは変更できません。

====
.手順
. 左側のナビゲーションペインの * Settings * で、 * Policies * > * Performance Service Levels * を選択します。
. パフォーマンスサービスレベル * ページで、新しいパフォーマンスサービスレベルを作成するか既存のパフォーマンスサービスレベルを編集するかに応じて、該当するボタンをクリックします。
+
|===
| 目的 | 実行する手順 


 a| 
新しいパフォーマンスサービスレベルを作成
 a| 
[追加]*をクリックします。



 a| 
既存のパフォーマンスサービスレベルを編集する
 a| 
既存のパフォーマンスサービスレベルを選択し、 * 編集 * をクリックします。

|===
+
パフォーマンスサービスレベルを追加または編集するページが表示されます。

. パフォーマンスの目標を指定してパフォーマンスサービスレベルをカスタマイズし、 * Submit * をクリックしてパフォーマンスサービスレベルを保存します。


パフォーマンスサービスレベルの新規または変更後のパフォーマンスサービスレベルは、[ワークロード]ページから、または新しいワークロードのプロビジョニング時にワークロード（LUN、NFSファイル共有、CIFS共有）に適用できます。
