---
permalink: storage-mgmt/task_provision_luns.html 
sidebar: sidebar 
keywords: provision, luns 
summary: '[ワークロードのプロビジョニング]ページで、既存のクラスタとStorage Virtual Machine（Storage VM）にCIFS / SMBプロトコルとNFSプロトコルをサポートするLUNを作成できます。' 
---
= LUNのプロビジョニング
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
[ワークロードのプロビジョニング]ページで、既存のクラスタとStorage Virtual Machine（Storage VM）にCIFS / SMBプロトコルとNFSプロトコルをサポートするLUNを作成できます。

* 必要なもの *

* Storage VMにLUNをプロビジョニングするためのスペースが必要です。
* LUNを作成するStorage VMでiSCSIとFCPの両方が有効になっている必要があります。
* ワークロードにパフォーマンスサービスレベル（PSL）とストレージ効率化ポリシー（SEP）を選択して割り当てるには、ワークロードの作成を開始する前にポリシーを作成しておく必要があります。


.手順
. [* Provision Workload* ] ページで、作成するワークロードの名前を追加し、使用可能なリストからクラスタを選択します。
+
選択したクラスタに基づいて、 Storage VM * フィールドで、そのクラスタで使用可能な Storage VM がフィルタリングされます。

. iSCSIサービスとFCPサービスをサポートするStorage VMをリストから選択します。
+
選択した内容に応じて、[Host Information]セクションで[SAN]オプションが有効になります。

. 「ストレージと最適化 * 」セクションで、ストレージ容量と PSL を割り当てます。必要に応じて、ワークロードの SEP を割り当てます。
+
SEPの仕様はLUNに割り当てられ、ワークロードの作成時にPSLの定義が適用されます。

. 割り当てられている PSL をワークロードに適用する場合は、「 * パフォーマンス制限を適用する * 」チェックボックスを選択します。
+
ワークロードにPSLを割り当てると、ワークロードを作成するアグリゲートで、それぞれのポリシーで定義されているパフォーマンスと容量の目標をサポートできるようになります。たとえば、ワークロードに「最高レベルのパフォーマンス」PSLが割り当てられている場合、ワークロードをプロビジョニングするアグリゲートには、「最高レベルのパフォーマンス」ポリシーに定められたパフォーマンスと容量（SSDストレージなど）をサポートできる機能が必要です。

+
[NOTE]
====
このチェックボックスをオンにしないかぎり、PSLはワークロードに適用されず、ダッシュボードのワークロードのステータスはと表示されます `unassigned`。

====
. [*SAN* ] オプションを選択します。「 * san * 」オプションが有効になっていない場合は、選択した Storage VM で iSCSI と FCP がサポートされているかどうかを確認してください。
. ホストOSを選択します。
. ホストマッピングを指定して、LUNへのイニシエータのアクセスを制御します。既存のイニシエータグループ（igroup）を割り当てたり、新しいigroupを定義してマッピングしたりできます。
+
[NOTE]
====
LUNのプロビジョニング中に新しいigroupを作成した場合は、次回の検出サイクル（最大15分）まで使用する必要があります。したがって、使用可能なigroupのリストから既存のigroupを使用することを推奨します。

====
+
新しい igroup を作成する場合は、「 * 新しいイニシエータグループを作成する * 」ボタンを選択し、 igroup の情報を入力します。

. [ 保存（ Save ） ] をクリックします。
+
ストレージワークロードのリストにLUNが追加されます。


