---
permalink: storage-mgmt/task_edit_user_and_group_quota_email_addresses.html 
sidebar: sidebar 
keywords: edit, user, group, quota, email, addresses 
summary: 'クラスタ、 Storage Virtual Machine （ SVM ）、ボリューム、 qtree 、ユーザ、またはユーザグループに関連付けられたユーザクォータに基づいて、 E メールアドレスを変更することができます。Eメールアドレスを変更すると、[ユーザクォータとグループクォータのEメールアドレスを生成するルール]ダイアログボックスで指定したルールで生成されたEメールアドレスを上書きできます。' 
---
= ユーザクォータおよびグループクォータのEメールアドレスの編集
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラスタ、 Storage Virtual Machine （ SVM ）、ボリューム、 qtree 、ユーザ、またはユーザグループに関連付けられたユーザクォータに基づいて、 E メールアドレスを変更することができます。Eメールアドレスを変更すると、[ユーザクォータとグループクォータのEメールアドレスを生成するルール]ダイアログボックスで指定したルールで生成されたEメールアドレスを上書きできます。

* 必要なもの *

* オペレータ、アプリケーション管理者、またはストレージ管理者のロールが必要です。
* を確認しておく必要があります link:reference_rules_to_generate_user_and_group_quota.html["ルールの作成に関するガイドライン"]。


Eメールアドレスを編集すると、ユーザクォータおよびグループクォータのEメールアドレスを生成するルールがクォータに適用されなくなります。指定したルールで生成されたEメールアドレスに通知を送信するには、Eメールアドレスを削除して変更を保存する必要があります。

.手順
. 左側のナビゲーションペインで、 * Storage * > * SVMs * をクリックします。
. * Health ： All Storage VMs] ビューで SVM を選択し、 * User クォータと Group Quotas * タブをクリックします。
. タブの行の下にある * 電子メールアドレスの編集 * をクリックします。
. [ 電子メールアドレスの編集 *] ダイアログボックスで、適切なアクションを実行します。
+
|===
| 状況 | そしたら...。 


 a| 
指定したルールで生成されたEメールアドレスに通知を送信する
 a| 
.. [*Email Address*] フィールドの電子メールアドレスを削除します。
.. [ 保存（ Save ） ] をクリックします。
.. F5 キーを押して E メールアドレスの編集ダイアログボックスをリロードし、ブラウザをリフレッシュします。指定したルールによって生成された E メールアドレスが ［ * E メールアドレス * ］ フィールドに表示されます。




 a| 
指定したEメールアドレスに通知を送信する
 a| 
.. [*Email Address*] フィールドで電子メールアドレスを変更します。
.. [ 保存（ Save ） ] をクリックします。ユーザクォータおよびグループクォータのEメールアドレスを生成するルールがクォータに適用されなくなります。


|===

