---
permalink: storage-mgmt/task_provision_fileshares.html 
sidebar: sidebar 
keywords: provision, file, share, volumes 
summary: '[ワークロードのプロビジョニング]ページで、既存のクラスタとStorage Virtual Machine（Storage VM）にCIFS / SMBプロトコルとNFSプロトコルをサポートするファイル共有ボリュームを作成できます。' 
---
= ファイル共有ボリュームのプロビジョニング
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
[ワークロードのプロビジョニング]ページで、既存のクラスタとStorage Virtual Machine（Storage VM）にCIFS / SMBプロトコルとNFSプロトコルをサポートするファイル共有ボリュームを作成できます。

* 必要なもの *

* Storage VMにファイル共有ボリュームをプロビジョニングするためのスペースが必要です。
* Storage VMでSMBサービスとNFSサービスの一方または両方が有効になっている必要があります。
* ワークロードにパフォーマンスサービスレベル（PSL）とストレージ効率化ポリシー（SEP）を選択して割り当てるには、ワークロードの作成を開始する前にポリシーを作成しておく必要があります。


.手順
. [* Provision Workload* ] ページで、作成するワークロードの名前を追加し、使用可能なリストからクラスタを選択します。
. 選択したクラスタに基づいて、 Storage VM * フィールドで、そのクラスタで使用可能な Storage VM がフィルタリングされます。リストから必要なStorage VMを選択します。
+
Storage VMでサポートされているSMBサービスとNFSサービスに基づいて、[ホスト情報]セクションのNASオプションが有効になります。

. [ストレージと最適化]セクションで、ストレージ容量とPSLに加え、必要に応じてワークロードのSEPを割り当てます。
+
SEPの仕様はLUNに割り当てられ、ワークロードの作成時にPSLの定義が適用されます。

. ワークロードに割り当てた PSL を適用する場合は、「 * パフォーマンス制限を適用する * 」チェックボックスを選択します。
+
ワークロードにPSLを割り当てると、ワークロードを作成するアグリゲートで、それぞれのポリシーで定義されているパフォーマンスと容量の目標をサポートできるようになります。たとえば、ワークロードに「最高レベルのパフォーマンス」PSLが割り当てられている場合、ワークロードをプロビジョニングするアグリゲートには、「最高レベルのパフォーマンス」ポリシーに定められたパフォーマンスと容量（SSDストレージなど）がサポートされている必要があります。

+
[NOTE]
====
このチェックボックスをオンにしないかぎり、PSLはワークロードに適用されず、ダッシュボード上のワークロードのステータスは「未割り当て」と表示されます。

====
. [*NAS* ] オプションを選択します。
+
「 * NAS * 」オプションが有効になっていない場合は、選択した Storage VM が SMB 、 NFS 、またはその両方をサポートしているかどうかを確認してください。

+
[NOTE]
====
SMB サービスと NFS サービスの両方に対して Storage VM が有効になっている場合は、「 NFS で共有」チェックボックスと「 SMB で共有」チェックボックスを選択し、 NFS プロトコルと SMB プロトコルの両方をサポートするファイル共有を作成できます。SMB共有とCIFS共有のどちらかを作成する場合は、対応するチェックボックスのみを選択します。

====
. NFSファイル共有ボリュームの場合は、ファイル共有ボリュームにアクセスするホストまたはネットワークのIPアドレスを指定します。複数のホストの値をカンマで区切って入力できます。
+
ホストのIPアドレスを追加すると、ホストの詳細がStorage VMと一致しているかどうかの内部チェックが実行され、そのホストのエクスポートポリシーが作成されるか、既存のポリシーがある場合はそのポリシーが再利用されます。同じホストに対して複数のNFS共有が作成されている場合は、同じホストで使用可能な一致ルールを含むエクスポートポリシーが、すべてのファイル共有で再利用されます。APIを使用してNFS共有をプロビジョニングする場合は、個 々 のポリシーのルールを指定したり、特定のポリシーキーを指定してポリシーを再利用したりすることができます。

. SMB 共有の場合は、アクセスを許可するユーザまたはユーザグループを指定し、必要な権限を割り当てます。ユーザグループごとに、ファイル共有の作成時に新しいAccess Control List（ACL；アクセス制御リスト）が生成されます。
. [ 保存（ Save ） ] をクリックします。
+
ワークロードがストレージワークロードのリストに追加されます。


