---
permalink: storage-mgmt/task_change_performance_statistics_collection_interval.html 
sidebar: sidebar 
keywords: change, performance, statistics, collection, interval 
summary: パフォーマンス統計のデフォルトの収集間隔は5分です。大規模なクラスタからの収集がデフォルトの時間内に完了しない場合は、この間隔を10分または15分に変更できます。この設定は、この Unified Manager インスタンスで監視しているすべてのクラスタからの統計の収集に適用されます。 
---
= パフォーマンス統計の収集間隔の変更
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
パフォーマンス統計のデフォルトの収集間隔は5分です。大規模なクラスタからの収集がデフォルトの時間内に完了しない場合は、この間隔を10分または15分に変更できます。この設定は、この Unified Manager インスタンスで監視しているすべてのクラスタからの統計の収集に適用されます。

* 必要なもの *

Unified Managerサーバのメンテナンスコンソールへのログインが許可されているユーザIDとパスワードが必要です。

パフォーマンス統計の収集が時間どおりに完了しない問題は、バナーメッセージで示されます。 `Unable to consistently collect from cluster <cluster_name> or Data collection is taking too long on cluster <cluster_name>.`

収集間隔を変更する必要があるのは、統計の収集に問題があるためです。その他の理由でこの設定を変更しないでください。

[NOTE]
====
この値をデフォルト設定の 5 分から変更すると、 Unified Manager でレポートされるパフォーマンスイベントの数や頻度に影響する可能性があります。たとえば、システム定義のパフォーマンスしきい値では、ポリシーを超えた状態が30分続くとイベントがトリガーされます。5分間の収集を使用する場合は、6回の収集でポリシーの超過が連続して発生する必要があります。収集時間が15分の場合、2つの収集期間でのみポリシーの超過が必要です。

====
[Cluster Setup]ページの下部に、現在の統計データ収集間隔を示すメッセージが表示されます。

.手順
. SSH を使用して、 Unified Manager ホストにメンテナンスユーザとしてログインします。
+
Unified Managerメンテナンスコンソールのプロンプトが表示されます。

. 「パフォーマンスポーリング間隔の設定 * 」というラベルの付いたメニューオプションの番号を入力し、 Enter キーを押します。
. プロンプトが表示されたら、メンテナンスユーザのパスワードをもう一度入力します。
. 設定する新しいポーリング間隔の番号を入力し、Enterキーを押します。


外部データプロバイダ（ Graphite など）への接続を現在設定してある場合は、 Unified Manager の収集間隔を 10 分または 15 分に変更したあと、データプロバイダの送信間隔も Unified Manager の収集間隔以上に変更する必要があります。
