---
permalink: health-checker/concept_how_annotation_rules_work_in_unified_manager.html 
sidebar: sidebar 
keywords: annotation rules, work, unified manager 
summary: アノテーションルールとは、ストレージオブジェクト（ボリューム、クラスタ、または Storage Virtual Machine （ SVM ））をアノテートする基準を定義したものです。アノテーションルールは、条件グループまたは条件のいずれかを使用して定義できます。 
---
= Unified Managerでのアノテーションルールの仕組み
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アノテーションルールとは、ストレージオブジェクト（ボリューム、クラスタ、または Storage Virtual Machine （ SVM ））をアノテートする基準を定義したものです。アノテーションルールは、条件グループまたは条件のいずれかを使用して定義できます。

* アノテーションにはアノテーションルールを関連付ける必要があります。
* アノテーションルールにはオブジェクトタイプを関連付ける必要があります。関連付けることができるオブジェクトタイプは1つだけです。
* Unified Manager でストレージオブジェクトに対してアノテーションが追加または削除されるのは、各監視サイクルの完了後、およびルールの作成、編集、削除、順序変更時です。
* アノテーションルールには1つ以上の条件グループを、各条件グループには1つ以上の条件を含めることができます。
* ストレージオブジェクトには複数のアノテーションを設定できます。また、特定のアノテーションのアノテーションルールで別のアノテーションを使用して、すでにアノテートされているオブジェクトに別のアノテーションを追加することもできます。




== 条件

複数の条件グループを作成し、各条件グループに1つ以上の条件を含めることができます。アノテーションのアノテーションルールに定義されたすべての条件グループを適用してストレージオブジェクトをアノテートすることができます。

条件グループ内の条件は、論理ANDを使用して実行されます。条件グループのすべての条件が満たされている必要があります。アノテーションルールを作成または変更すると条件が作成され、条件グループのすべての条件を満たすストレージオブジェクトのみが適用、選択、およびアノテートされます。アノテートするストレージオブジェクトの範囲を限定する場合は、条件グループで複数の条件を使用できます。

次のオペランドと演算子を使用して必要な値を指定することで、ストレージオブジェクトの条件を作成できます。

[cols="2*"]
|===
| ストレージオブジェクトのタイプ | 適用可能なオペランド 


 a| 
ボリューム
 a| 
* オブジェクト名
* 所有クラスタ名
* 所有SVM名
* アノテーション




 a| 
SVM
 a| 
* オブジェクト名
* 所有クラスタ名
* アノテーション




 a| 
クラスタ
 a| 
* オブジェクト名
* アノテーション


|===
ストレージ・オブジェクトのオペランドとしてアノテーションを選択すると 'is' 演算子を使用できますそれ以外のオペランドについては ' 演算子として Is または Contains を選択できます「 Is 」演算子を選択した場合は、選択したオペランドの値が指定した値と完全に一致する場合に条件が評価されます。"`contains" 演算子を選択すると、条件は次のいずれかの条件を満たすように評価されます。

* 選択したオペランドの値が指定した値と完全に一致する。
* 選択したオペランドの値に指定した値が含まれる。




== 条件を使用したアノテーションルールの例

ボリュームに対して条件グループが1つ設定されたアノテーションルールで、次の2つの条件が設定されているとします。

* 名前に「 vol 」を含む
* SVM 名は「 `d ata_svm 」です。


このアノテーションルールでは、名前に「 vol 」を含み、「 `d ata_svm 」という名前の SVMs でホストされているすべてのボリュームが、選択したアノテーションとアノテーションタイプでアノテートされます。



== 条件グループ

条件グループは論理ORを使用して実行され、ストレージオブジェクトに適用されます。ストレージオブジェクトをアノテートするには、いずれかの条件グループの要件を満たしている必要があります。すべての条件グループの条件を満たすストレージオブジェクトがアノテートされます。条件グループを使用して、アノテートするストレージオブジェクトの範囲を広げることができます。



== 条件グループを使用したアノテーションルールの例

ボリュームに対して条件グループが2つ設定されたアノテーションルールで、各グループに次の2つの条件が設定されているとします。

* 条件グループ1
+
** 名前に「 vol 」を含む
** SVM 名が「 `d ATA_SVM` 」である場合、この条件グループでは、名前に「 vol 」を含み、「 `d ATA_SVM` 」という名前の SVM でホストされているすべてのボリュームがアノテートされます。


* 条件グループ2
+
** 名前に「 vol 」を含む
** data-priority のアノテーション値は「 critical 」ですこの条件グループは ' 名前に「 vol 」を含み ' data-priority アノテーションの値「 critical 」でアノテートされているすべてのボリュームをアノテートします




これらの2つの条件グループを含むアノテーションルールをストレージオブジェクトに適用すると、次のストレージオブジェクトがアノテートされます。

* 名前に「 vol 」を含み、「 'd ata_SVM' 」という名前の SVM でホストされているすべてのボリューム
* 名前に「 vol 」を含み、 data-priority アノテーションの値「 critical 」でアノテートされているすべてのボリューム

