---
permalink: health-checker/concept_configure_destination_and_schedule_for_database_dump_backups.html 
sidebar: sidebar 
keywords: configure, destination, schedule, database dump, backups, snapshot copy, copies 
summary: Unified Managerのデータベースダンプバックアップ設定で、データベースのバックアップパス、保持数、およびバックアップスケジュールを設定できます。毎日または毎週のスケジュールされたバックアップを有効にすることができます。デフォルトでは、スケジュールされたバックアップは無効になっていますが、バックアップスケジュールを設定する必要があります。 
---
= データベースダンプバックアップのデスティネーションとスケジュールの設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Managerのデータベースダンプバックアップ設定で、データベースのバックアップパス、保持数、およびバックアップスケジュールを設定できます。毎日または毎週のスケジュールされたバックアップを有効にすることができます。デフォルトでは、スケジュールされたバックアップは無効になっていますが、バックアップスケジュールを設定する必要があります。

* 必要なもの *

* オペレータ、アプリケーション管理者、またはストレージ管理者のロールが必要です。
* バックアップパスとして定義する場所に 150GB 以上の利用可能なスペースが必要です。
+
Unified Manager ホストシステムとは別のリモートの場所を使用することを推奨します。

* Unified ManagerをLinuxシステムにインストールし、MySQLのバックアップを使用している場合は、バックアップディレクトリに次の権限と所有権が設定されていることを確認してください。
+
権限： 0750 、所有権： jboss: maintenance

* Unified ManagerをWindowsシステムにインストールし、MySQLのバックアップを使用している場合は、バックアップディレクトリへのアクセスが管理者だけに許可されていることを確認してください。


初回のバックアップではフルバックアップが実行されるため、 2 回目以降のバックアップよりも時間がかかります。フルバックアップは1GBを超えることがあり、3~4時間かかることがあります。以降のバックアップは増分バックアップであり、所要時間は短くなります。

[NOTE]
====
* 増分バックアップファイルの数がバックアップ用に割り当てた容量に対して大きすぎる場合は、フルバックアップを定期的に実行して、古いバックアップとその増分ファイルを置き換えることができます。別の方法として、Snapshotコピーを使用してバックアップを作成することもできます。
* 新しいクラスタの追加の最初の15日間に作成されたバックアップは、過去のパフォーマンスデータを取得するには正確でない可能性があります。


====
.手順
. 左側のナビゲーションペインで、 * General * > * Database Backup * をクリックします。
. [* データベース・バックアップ * ] ページで、 [ * バックアップ設定 * ] をクリックします。
. バックアップパス、保持数、およびスケジュールの値を設定します。
+
保持数のデフォルト値は 10 です。バックアップを無制限に作成する場合は 0 に設定します。

. 「毎日スケジュール」または「毎週スケジュール」 * ボタンを選択し、スケジュールの詳細を指定します。
. [ 適用（ Apply ） ] をクリックします。


データベースダンプバックアップファイルはスケジュールに基づいて作成されます。使用可能なバックアップファイルは、[Database Backup]ページで確認できます。
