---
permalink: health-checker/concept_how_group_actions_work_on_storage_objects.html 
sidebar: sidebar 
keywords: group actions, work, storage, objects 
summary: グループ操作は、グループ内のすべてのストレージオブジェクトに対して実行される操作です。たとえば、ボリュームしきい値のグループ操作を設定して、グループ内のすべてのボリュームのしきい値を同時に変更できます。 
---
= ストレージオブジェクトでのグループ操作の仕組み
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
グループ操作は、グループ内のすべてのストレージオブジェクトに対して実行される操作です。たとえば、ボリュームしきい値のグループ操作を設定して、グループ内のすべてのボリュームのしきい値を同時に変更できます。

グループは、一意のグループアクションタイプをサポートします。ボリューム健全性しきい値タイプのグループアクションは1つだけです。ただし、可能な場合は、同じグループに対して別のタイプのグループアクションを設定できます。グループアクションがストレージオブジェクトに適用される順序は、グループアクションのランクによって決まります。ストレージオブジェクトに適用されているグループアクションの情報は、ストレージオブジェクトの詳細ページに表示されます。



== 固有のグループ操作の例

ボリュームAがグループG1とG2に属しており、これらのグループに対して次のボリューム健全性しきい値グループアクションが設定されているとします。

* `Change_capacity_threshold`ランク1のグループ操作。ボリュームの容量を設定します。
* `Change_snapshot_copies`ボリュームのSnapshotコピーを設定するためのランク2のグループ操作


 `Change_capacity_threshold`グループ操作はグループ操作よりも常に優先され `Change_snapshot_copies`、ボリュームAに適用されます。Unified Managerによる監視が1サイクル完了すると、ボリュームAの健常性しきい値関連イベントがグループ操作ごとに再評価され `Change_capacity_threshold`ます。G1またはG2のどちらのグループにも、ボリュームしきい値タイプの別のグループアクションを設定することはできません。
