---
permalink: health-checker/concept_common_unified_manager_administrative_workflows_and_tasks.html 
sidebar: sidebar 
keywords: Common, unified, manager, health, workflows, tasks 
summary: Unified Managerに関連する一般的な管理ワークフローと管理タスクには、監視対象のストレージクラスタの選択、データの可用性、容量、保護に悪影響を及ぼす状態の診断、失われたデータのリストア、ボリュームの設定と管理、診断データのバンドルとテクニカルサポートへの送信（必要な場合）などがあります。 
---
= Unified Managerの一般的な健全性ワークフローとタスク
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Managerに関連する一般的な管理ワークフローと管理タスクには、監視対象のストレージクラスタの選択、データの可用性、容量、保護に悪影響を及ぼす状態の診断、失われたデータのリストア、ボリュームの設定と管理、診断データのバンドルとテクニカルサポートへの送信（必要な場合）などがあります。

Unified Manager では、ストレージ管理者がダッシュボードを表示して管理対象ストレージクラスタの全体的な容量、可用性、保護の状態の健全性を評価できるほか、発生の可能性がある具体的な問題を突き止めて確認し、診断を行い、解決のための割り当てを行うことができます。

管理対象ストレージオブジェクトのストレージ容量やデータ可用性に影響する、クラスタ、Storage Virtual Machine（SVM）、ボリューム、またはFlexGroupボリュームに関連する最も重要な問題が、[ダッシュボード]ページのシステムヘルスグラフおよびイベントに表示されます。重大な問題が特定されると、このページに適切なトラブルシューティングワークフローをサポートするためのリンクが表示されます。

関連する管理ツール（OnCommand Workflow Automation（WFA）など）が含まれるワークフローにUnified Managerを組み込むことで、ストレージリソースを直接設定できるようにすることもできます。

このドキュメントでは、次の管理タスクに関連する一般的なワークフローについて説明します。

* 可用性の問題の診断と管理
+
ハードウェア障害やストレージリソース設定の問題によってデータ可用性イベントが[Dashboard]ページに表示される場合、ストレージ管理者は組み込みのリンクを参照して、影響を受けるストレージリソースに関する接続情報を確認し、トラブルシューティングのアドバイスを確認し、他の管理者に問題の解決を割り当てることができます。

* パフォーマンスインシデントの設定と監視
+
管理者は、監視対象のストレージ・システム・リソースのパフォーマンスを監視および管理できます。詳細については、link:../performance-checker/concept_introduction_to_unified_manager_performance_monitoring.html["Active IQ Unified Managerパフォーマンス監視の概要"]を参照してください。

* ボリューム容量の問題の診断と管理
+
ボリュームのストレージ容量の問題が[ダッシュボード]ページに表示された場合、ストレージ管理者はリンクをたどって、該当するボリュームのストレージ容量に関連する現在と過去の傾向を確認したり、トラブルシューティングのアドバイスを参照したり、他の管理者に問題の解決を割り当てたりできます。

* 保護関係の設定、監視、問題の診断
+
保護関係を作成して設定したあと、ストレージ管理者は、保護関係に関連する潜在的な問題、保護関係の現在の状態、該当する関係に対して成功した現在と過去の保護ジョブの情報、およびトラブルシューティングのアドバイスを確認できます。詳細については、link:../data-protection/concept_create_and_monitor_protection_relationships.html["保護関係の作成、監視、およびトラブルシューティング"]を参照してください。

* バックアップファイルの作成とバックアップファイルからのデータの復元。
* ストレージオブジェクトとアノテーションの関連付け
+
ストレージ管理者は、ストレージオブジェクトにアノテーションを関連付けることで、ストレージオブジェクトに関連するイベントをフィルタリングして表示できます。これにより、イベントに関連する問題に優先順位を付けて解決することができます。

* REST APIを使用してUnified Managerで収集された健全性、容量、パフォーマンスの情報を表示することで、クラスタの管理に役立ちます。詳細については、を参照してください link:../api-automation/concept_get_started_with_um_apis.html["Active IQ Unified Manager REST APIでの作業の開始"] 。
* テクニカルサポートへのサポートバンドルの送信
+
ストレージ管理者は、メンテナンスコンソールを使用して、サポートバンドルを取得してテクニカルサポートに送信できます。AutoSupportメッセージよりも詳細な診断とトラブルシューティングが必要な問題の場合は、サポートバンドルをテクニカルサポートに送信する必要があります。


