---
permalink: health-checker/concept_how_group_rules_work_for_groups.html 
sidebar: sidebar 
keywords: group rules, work, groups 
summary: グループルールとは、ストレージオブジェクト（ボリューム、クラスタ、またはSVM）を特定のグループに含めるための基準を定義したものです。グループのグループルールは、条件グループまたは条件を使用して定義できます。 
---
= グループでのグループルールの仕組み
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
グループルールとは、ストレージオブジェクト（ボリューム、クラスタ、またはSVM）を特定のグループに含めるための基準を定義したものです。グループのグループルールは、条件グループまたは条件を使用して定義できます。

* グループにはグループルールを関連付ける必要があります。
* グループルールにはオブジェクトタイプを関連付ける必要があります。グループルールに関連付けられるオブジェクトタイプは1つだけです。
* ストレージオブジェクトは、各監視サイクルの完了後、またはルールの作成、編集、削除時にグループに対して追加または削除されます。
* グループルールには1つ以上の条件グループを、各条件グループには1つ以上の条件を含めることができます。
* ストレージオブジェクトは、作成したグループルールに基づいて複数のグループに属することができます。




== 条件

複数の条件グループを作成し、各条件グループに1つ以上の条件を含めることができます。グループのグループルールに定義されているすべての条件グループを適用して、グループに含めるストレージオブジェクトを指定できます。

条件グループ内の条件は、論理ANDを使用して実行されます。条件グループのすべての条件が満たされている必要があります。グループルールを作成または変更すると条件が作成され、条件グループのすべての条件を満たすストレージオブジェクトのみが適用、選択、およびグループ化されます。グループに含めるストレージオブジェクトの範囲を限定する場合は、条件グループで複数の条件を使用できます。

次のオペランドと演算子を使用して必要な値を指定することで、ストレージオブジェクトの条件を作成できます。

[cols="2*"]
|===
| ストレージオブジェクトのタイプ | 適用可能なオペランド 


 a| 
ボリューム
 a| 
* オブジェクト名
* 所有クラスタ名
* 所有SVM名
* アノテーション




 a| 
SVM
 a| 
* オブジェクト名
* 所有クラスタ名
* アノテーション




 a| 
クラスタ
 a| 
* オブジェクト名
* アノテーション


|===
ストレージ・オブジェクトのオペランドとしてアノテーションを選択すると 'is' 演算子を使用できますそれ以外のオペランドについては ' 演算子として Is または Contains を選択できます

* オペランド
+
Unified Manager では、選択したオブジェクトタイプによってリストに表示されるオペランドが変わります。リストには、オブジェクト名、所有クラスタ名、所有 SVM 名、および Unified Manager で定義したアノテーションが含まれます。

* 運用者
+
演算子のリストは、条件に対して選択したオペランドによって変わります。Unified Manager でサポートされる演算子は「 Is 」で、「 contains 」です。

+
「 Is 」演算子を選択すると、選択したオペランドの値が指定した値と完全に一致する場合に条件が評価されます。

+
"`contains" 演算子を選択すると、条件は次のいずれかの条件を満たすように評価されます。

+
** 選択したオペランドの値が指定した値と完全に一致する
** 選択したオペランドの値に指定した値が含まれています。


* 値
+
値のフィールドは、選択したオペランドによって変わります。





== 条件を使用したグループルールの例

ボリュームの条件グループで、次の2つの条件が設定されているとします。

* 名前に「 vol 」を含む
* SVM 名は「 `d ata_svm 」です。


この条件グループでは、名前に「 vol 」を含み、「 `d ata_svm 」という名前の SVM でホストされているすべてのボリュームが選択されます。



== 条件グループ

条件グループは論理ORを使用して実行され、ストレージオブジェクトに適用されます。ストレージオブジェクトがグループに追加されるには、いずれかの条件グループを満たしている必要があります。すべての条件グループのストレージオブジェクトが組み合わされます。条件グループを使用して、グループに含めるストレージオブジェクトの範囲を広げることができます。



== 条件グループを使用したグループルールの例

ボリュームに対して2つの条件グループがあり、各グループに次の2つの条件が含まれているとします。

* 条件グループ1
+
** 名前に「 vol 」を含む
** SVM 名が「 `d ata_svm 」の場合、条件グループ 1 では、名前に「 vol 」を含み、名前が「 `d ata_svm 」の SVM でホストされているすべてのボリュームが選択されます。


* 条件グループ2
+
** 名前に「 vol 」を含む
** data-priority のアノテーション値は「 critical 」条件グループ 2 では、名前に「 vol 」を含み、 data-priority アノテーションの値「 critical 」とアノテートされているすべてのボリュームが選択されます。




これらの2つの条件グループを含むグループルールをストレージオブジェクトに適用すると、選択したグループに次のストレージオブジェクトが追加されます。

* 名前に「 vol 」を含み、「 'data_svm 」という名前の SVM でホストされているすべてのボリューム
* 名前に「 vol 」を含み、 data-priority アノテーションの値「 critical 」でアノテートされているすべてのボリューム

