---
permalink: health-checker/reference_cluster_compliance_categories.html 
sidebar: sidebar 
keywords: cluster compliance, categories 
summary: 次の表に、 Unified Manager で評価されるクラスタセキュリティコンプライアンスのパラメータ、ネットアップの推奨事項、およびクラスタが準拠か非準拠かの総合的な判断にパラメータが影響するかどうかを示します。 
---
= クラスタコンプライアンスのカテゴリ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
次の表に、 Unified Manager で評価されるクラスタセキュリティコンプライアンスのパラメータ、ネットアップの推奨事項、およびクラスタが準拠か非準拠かの総合的な判断にパラメータが影響するかどうかを示します。

クラスタに非準拠の SVM があると、クラスタのコンプライアンスに影響します。そのため、クラスタのセキュリティが準拠とみなされる前に、SVMのセキュリティの問題の修正が必要になる場合があります。

以下のパラメータは、すべてのインストール環境で表示されるわけではありません。たとえば、ピアクラスタがない場合やクラスタでAutoSupportを無効にしている場合はAutoSupport、UIページに[クラスタピアリング]または[HTTPS転送]の項目は表示されません。

[cols="4*"]
|===
| パラメータ | 製品説明 | 推奨事項 | クラスタコンプライアンスに影響します 


 a| 
グローバル FIPS
 a| 
グローバルFIPS（Federal Information Processing Standard）140-2準拠モードが有効になっているか無効になっているかを示します。FIPSを有効にすると、TLSv1とSSLv3は無効になり、TLSv1.1とTLSv1.2のみが許可されます。
 a| 
有効
 a| 
はい



 a| 
Telnet
 a| 
システムへのTelnetアクセスが有効か無効かを示します。NetAppでは、セキュアなリモートアクセスにセキュアシェル（SSH）を推奨しています。
 a| 
無効
 a| 
はい



 a| 
安全でないSSH設定
 a| 
SSH でセキュアでない暗号を使用しているかどうかを示します。たとえば、 CBC で始まる暗号などです。
 a| 
いいえ
 a| 
はい



 a| 
ログインバナー
 a| 
システムにアクセスするユーザに対してログインバナーが有効か無効かを示します。
 a| 
有効
 a| 
はい



 a| 
クラスタピアリング
 a| 
ピアクラスタ間の通信が暗号化されているかどうかを示します。このパラメータが準拠とみなされるためには、ソースとデスティネーションの両方のクラスタで暗号化が設定されている必要があります。
 a| 
暗号化
 a| 
はい



 a| 
ネットワークタイムプロトコル
 a| 
クラスタにNTPサーバが設定されているかどうかを示します。ネットアップでは、冗長性と最適なサービスを実現するために最低 3 台の NTP サーバをクラスタに関連付けることを推奨しています。
 a| 
設定済み
 a| 
はい



 a| 
OCSP
 a| 
9.14.1以降のActive IQ Unified Managerでは、オンライン証明書ステータスプロトコル（OCSP）のステータス情報がStorage Virtual Machine（SVM、旧Vserver）レベルで提供されます。つまり、SVMへのすべてのSSL/TLS接続にOCSP検証が適用され、それらの接続で使用される証明書の整合性と有効性が保証されます。
 a| 
有効
 a| 
いいえ



 a| 
リモート監査ログ
 a| 
ログ転送（syslog）が暗号化されているかどうかを示します。
 a| 
暗号化
 a| 
はい



 a| 
AutoSupport HTTPS 転送
 a| 
ネットアップサポートに AutoSupport メッセージを送信するためのデフォルトの転送プロトコルとして HTTPS が使用されているかどうかを示します。
 a| 
有効
 a| 
はい



 a| 
デフォルトの管理ユーザ
 a| 
デフォルトの管理ユーザ（組み込み）が有効になっているかどうかを示します。ネットアップでは、不要な組み込みアカウントはすべてロック（無効化）することを推奨しています。
 a| 
無効
 a| 
はい



 a| 
SAMLユーザ
 a| 
SAMLが設定されているかどうかを示します。SAMLを使用すると、シングルサインオンのログイン方法として多要素認証（MFA）を設定できます。
 a| 
いいえ
 a| 
いいえ



 a| 
Active Directory ユーザ
 a| 
Active Directoryが設定されているかどうかを示します。Active DirectoryとLDAPは、クラスタにアクセスするユーザに推奨される認証メカニズムです。
 a| 
いいえ
 a| 
いいえ



 a| 
LDAPユーザ
 a| 
LDAPが設定されているかどうかを示します。Active DirectoryとLDAPは、ローカルユーザよりもクラスタを管理するユーザに推奨される認証メカニズムです。
 a| 
いいえ
 a| 
いいえ



 a| 
証明書ユーザ
 a| 
証明書ユーザがクラスタにログインするように設定されているかどうかを示します。
 a| 
いいえ
 a| 
いいえ



 a| 
ローカルユーザ
 a| 
ローカルユーザがクラスタにログインするように設定されているかどうかを示します。
 a| 
いいえ
 a| 
いいえ



 a| 
リモートシェル
 a| 
RSHが有効になっているかどうかを示します。セキュリティ上の理由から、RSHを無効にする必要があります。セキュアなリモートアクセスには、Secure Shell（SSH）を使用することを推奨します。
 a| 
無効
 a| 
はい



 a| 
MD5使用中
 a| 
ONTAPユーザーアカウントが安全性の低いMD5ハッシュ関数を使用しているかどうかを示します。MD5ハッシュ化されたユーザアカウントは、SHA-512のようなより安全な暗号化ハッシュ関数に移行することが推奨されます。
 a| 
いいえ
 a| 
はい



 a| 
証明書発行者タイプ
 a| 
使用されているデジタル証明書のタイプを示します。
 a| 
CAシヨメイ
 a| 
いいえ

|===