---
permalink: health-checker/reference_health_aggregate_details_page.html 
sidebar: sidebar 
keywords: unified manager, aggregate, health details page 
summary: '[アグリゲート/健全性の詳細]ページでは、選択したアグリゲートに関する詳細情報（容量、ディスク情報、設定の詳細、生成されたイベントなど）を確認できます。また、そのアグリゲートに関連するオブジェクトやアラートに関する情報も参照できます。' 
---
= アグリゲート / 健全性の詳細ページ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
[アグリゲート/健全性の詳細]ページでは、選択したアグリゲートに関する詳細情報（容量、ディスク情報、設定の詳細、生成されたイベントなど）を確認できます。また、そのアグリゲートに関連するオブジェクトやアラートに関する情報も参照できます。



== コマンドボタン

[NOTE]
====
FabricPool対応アグリゲートを監視している場合、このページのコミット済み容量とオーバーコミット容量の値はローカル（パフォーマンス階層）の容量のみに関連します。クラウド階層で使用可能なスペースの量は、オーバーコミット容量の値に反映されません。同様に、アグリゲートのしきい値もローカルのパフォーマンス階層のみに対する値となります。

====
選択したアグリゲートについて、各コマンドボタンを使用して次のタスクを実行できます。

* * パフォーマンスビューに切り替え *
+
[アグリゲート/パフォーマンスの詳細]ページに移動できます。

* * アクション *
+
** アラートの追加
+
選択したアグリゲートにアラートを追加できます。

** しきい値の編集
+
選択したアグリゲートのしきい値の設定を変更できます。



* * アグリゲートを表示 *
+
健常性：すべてのアグリゲートビューに移動できます。





== [容量]タブ

[容量]タブには、選択したアグリゲートについて、容量、しきい値、日次増加率などの詳細情報が表示されます。

デフォルトでは、ルートアグリゲートに対して容量イベントは生成されません。また、 Unified Manager で使用されるしきい値のノードのルートアグリゲートには適用されません。これらのイベントが生成されるように設定を変更できるのは、テクニカルサポート担当者だけです。テクニカルサポート担当者が設定を変更すると、しきい値がノードのルートアグリゲートに適用されます。

* * 容量 *
+
データ容量のグラフとSnapshotコピーのグラフに、アグリゲートの容量の詳細が表示されます。

+
** 使用済みの論理スペース
+
アグリゲートに格納されているデータの実際のサイズ。ONTAPのStorage Efficiencyテクノロジによる削減を適用する前のサイズです。

** 使用済み
+
アグリゲート内のデータに使用されている物理容量。

** オーバーコミット
+
アグリゲートのスペースがオーバーコミットされている場合、グラフにフラグとオーバーコミット容量が表示されます。

** 警告
+
警告しきい値が設定されている（アグリゲートのスペースがほぼフルである）場所に点線が表示されます。このしきい値を超えると、「スペースがほぼフル」イベントが生成されます。

** エラー
+
エラーしきい値が設定されている（アグリゲートのスペースがフルである）場所に実線が表示されます。このしきい値を超えると、「スペースがフル」イベントが生成されます。

** Snapshot コピーのグラフ
+
このグラフは、Snapshot使用容量またはSnapshotリザーブが0でない場合にのみ表示されます。



+
どちらのグラフにも、Snapshot使用容量がSnapshotリザーブを超えた場合に超過した容量が表示されます。

* * クラウド階層 *
+
FabricPool対応アグリゲートについて、クラウド階層でデータに使用されているスペースが表示されます。FabricPoolには、ライセンスが設定されているかどうかを指定できます。

+
クラウド階層が別のクラウドプロバイダ（「ミラーリング層」）にミラーリングされている場合、両方のクラウド階層がここに表示されます。

* * 詳細 *
+
容量に関する詳細情報が表示されます。

+
** 合計容量
+
アグリゲートの合計容量が表示されます。

** データ容量
+
アグリゲートで使用されているスペース（使用済み容量）とアグリゲートの使用可能なスペース（空き容量）が表示されます。

** Snapshot リザーブ
+
アグリゲートのSnapshotの使用済み容量と空き容量が表示されます。

** オーバーコミット容量
+
アグリゲートオーバーコミットが表示されます。アグリゲートオーバーコミットを使用すると、すべてのストレージが使用中でないかぎり、アグリゲートの実際の使用可能容量よりも多くのストレージを割り当てることができます。シンプロビジョニングを使用している場合は、アグリゲート内のボリュームの合計サイズがアグリゲートの合計容量を超えることがあります。

+
[NOTE]
====
アグリゲートをオーバーコミットした場合は、アグリゲートの空きスペースを注意深く監視し、必要に応じてストレージを追加して、スペース不足による書き込みエラーを回避する必要があります。

====
** クラウド階層
+
FabricPool対応アグリゲートについて、クラウド階層でデータに使用されているスペースが表示されます。FabricPoolには、ライセンスが設定されているかどうかを指定できます。クラウド階層が別のクラウドプロバイダ（ミラー階層）にミラーリングされている場合、両方のクラウド階層が表示されます。

** 合計キャッシュスペース
+
Flash Poolアグリゲートに追加されているソリッドステートドライブ（SSD）または割り当て単位の合計スペースが表示されます。アグリゲートで Flash Pool を有効にしているが、 SSD が追加されていない場合、キャッシュスペースは 0KB と表示されます。

+
[NOTE]
====
このフィールドは、アグリゲートで Flash Pool が無効になっている場合は表示されません。

====
** アグリゲートのしきい値
+
アグリゲート容量の次のしきい値が表示されます。

+
*** ほぼフルのしきい値
+
アグリゲートがほぼフルであるとみなす割合を示します。

*** フルのしきい値
+
アグリゲートがフルであるとみなす割合を示します。

*** 「ほぼオーバーコミット」しきい値
+
アグリゲートがほぼオーバーコミットされているとみなす割合を示します。

*** オーバーコミットのしきい値
+
アグリゲートがオーバーコミットされたとみなす割合を示します。



** その他の詳細：日次増加率
+
最後の2つのサンプル間の変更率が24時間続く場合に、アグリゲートで使用されているディスクスペースが表示されます。

+
たとえば、アグリゲートが午後2時に10GB、午後6時に12GBのディスクスペースを使用している場合、このアグリゲートの日次増加率（GB）は2GBです。

** ボリューム移動
+
現在実行中のボリューム移動処理の数が表示されます。

+
*** 送信されたボリューム
+
アグリゲートから移動中のボリュームの数と容量が表示されます。

+
リンクをクリックすると、ボリューム名、ボリュームの移動先のアグリゲート、ボリューム移動処理のステータス、推定終了時刻などの詳細を確認できます。

*** 追加されたボリューム
+
アグリゲートに移動中のボリュームの数と残りの移動容量が表示されます。

+
リンクをクリックすると、ボリューム名、ボリュームの移動元のアグリゲート、ボリューム移動処理のステータス、推定終了時刻などの詳細を確認できます。

*** ボリューム移動後の推定使用容量
+
ボリューム移動処理の完了後のアグリゲートの推定使用済みスペース（割合とKB、MB、GBなど）が表示されます。





* * 容量の概要 - ボリューム *
+
アグリゲートに含まれるボリュームの容量に関する情報がグラフで表示されます。ボリュームで使用されているスペース（使用済み容量）とボリュームの使用可能なスペース（空き容量）が表示されます。シンプロビジョニングボリュームについて「シンプロビジョニングボリュームにスペースリスクあり」イベントが生成された場合は、ボリュームで使用されているスペース（使用済み容量）と、ボリュームで使用可能なスペースのうちアグリゲートの容量の問題が原因で使用できないスペース（使用不可の容量）が表示されます。

+
表示するグラフをドロップダウンリストから選択できます。グラフに表示されるデータをソートして、使用済みサイズ、プロビジョニング済みサイズ、使用可能な容量、1日あたりの最大増加率、最小増加率などの詳細を表示できます。アグリゲート内のボリュームを含む Storage Virtual Machine （ SVM ）でデータをフィルタリングできます。シンプロビジョニングボリュームの詳細も確認できます。グラフの特定のポイントにカーソルを合わせると、その時点の詳細を確認できます。デフォルトでは、アグリゲート内の上位30個のボリュームがフィルタリングされて表示されます。





== [ディスク情報]タブ

選択したアグリゲート内のディスクに関する詳細情報（RAIDタイプとサイズ、アグリゲートで使用されているディスクのタイプなど）が表示されます。このタブには、RAIDグループと使用されているディスクのタイプ（SAS、ATA、FCAL、SSD、VMDISKなど）も図で表示されます。パリティディスクとデータディスクにカーソルを合わせると、ディスクのベイ、シェルフ、回転速度などの詳細を確認できます。

* * データ *
+
専用データディスク、共有データディスク、またはその両方の詳細が図で表示されます。データディスクに共有ディスクが含まれている場合は、共有ディスクの詳細がグラフィカルに表示されます。データディスクに専用ディスクと共有ディスクが含まれている場合は、専用データディスクと共有データディスクの両方の詳細図が表示されます。

+
** * RAIDの詳細*
+
専用ディスクの場合のみ、RAIDの詳細が表示されます。

+
*** タイプ
+
RAIDタイプ（RAID 0、RAID 4、RAID-DP、またはRAID-TEC）が表示されます。

*** グループサイズ
+
RAIDグループで許可されている最大ディスク数が表示されます。

*** グループ
+
アグリゲート内のRAIDグループの数が表示されます。



** * 使用されているディスク *
+
*** 実質的タイプ
+
アグリゲート内のデータディスクのタイプ（ATA、SATA、FCAL、SSD、VMDISKなど）が表示されます。

*** データディスク
+
アグリゲートに割り当てられているデータディスクの数と容量が表示されます。データディスクの詳細は、アグリゲートに共有ディスクしか含まれていない場合は表示されません。

*** パリティディスク
+
アグリゲートに割り当てられているパリティディスクの数と容量が表示されます。パリティディスクの詳細は、アグリゲートに共有ディスクしか含まれていない場合は表示されません。

*** 共有ディスク
+
アグリゲートに割り当てられている共有データディスクの数と容量が表示されます。共有ディスクの詳細は、アグリゲートに共有ディスクが含まれている場合にのみ表示されます。



** * スペアディスク *
+
選択したアグリゲートのノードで使用可能なスペアデータディスクの実質的タイプ、数、および容量が表示されます。

+
[NOTE]
====
Unified Manager では、アグリゲートがパートナーノードにフェイルオーバーされた場合、アグリゲートと互換性があるすべてのスペアディスクが表示されないことがあります。

====


* * SSD キャッシュ *
+
専用キャッシュSSDディスクと共有キャッシュSSDディスクの詳細が表示されます。

+
専用キャッシュSSDディスクについて次の詳細が表示されます。

+
** * RAIDの詳細*
+
*** タイプ
+
RAIDタイプ（RAID 0、RAID 4、RAID-DP、またはRAID-TEC）が表示されます。

*** グループサイズ
+
RAIDグループで許可されている最大ディスク数が表示されます。

*** グループ
+
アグリゲート内のRAIDグループの数が表示されます。



** * 使用されているディスク *
+
*** 実質的タイプ
+
アグリゲートでキャッシュに使用されているディスクのタイプがSSDであることを示します。

*** データディスク
+
キャッシュ用にアグリゲートに割り当てられているデータディスクの数と容量が表示されます。

*** パリティディスク
+
キャッシュ用にアグリゲートに割り当てられているパリティディスクの数と容量が表示されます。



** * スペアディスク *
+
選択したアグリゲートのノードでキャッシュに使用できるスペアディスクの実質的タイプ、数、および容量が表示されます。

+
[NOTE]
====
Unified Manager では、アグリゲートがパートナーノードにフェイルオーバーされた場合、アグリゲートと互換性があるすべてのスペアディスクが表示されないことがあります。

====


+
共有キャッシュについては、次の情報が表示されます。

+
** * ストレージプール *
+
ストレージプールの名前が表示されます。ストレージプールの名前にカーソルを合わせると、次の詳細を確認できます。

+
*** ステータス
+
ストレージプールのステータス（正常または異常）が表示されます。

*** 割り当て合計
+
ストレージプール内の割り当て単位の合計とサイズが表示されます。

*** 割り当て単位のサイズ
+
アグリゲートに割り当て可能なストレージプール内の最小スペースが表示されます。

*** ディスク
+
ストレージプールの作成に使用されているディスクの数が表示されます。ストレージプールの列のディスク数とそのストレージプールの[ディスク情報]タブに表示されるディスク数が一致しない場合は、破損しているディスクがあり、ストレージプールが正常な状態でないことを示しています。

*** 使用済みの割り当て
+
アグリゲートで使用されている割り当て単位の数とサイズが表示されます。アグリゲート名をクリックすると、アグリゲートの詳細を確認できます。

*** 使用可能な割り当て
+
ノードで使用可能な割り当て単位の数とサイズが表示されます。ノード名をクリックすると、アグリゲートの詳細を確認できます。



** * 割り当て済みキャッシュ *
+
アグリゲートで使用されている割り当て単位のサイズが表示されます。

** * 割り当て単位 *
+
アグリゲートで使用されている割り当て単位の数が表示されます。

** * ディスク *
+
ストレージプールに含まれているディスクの数が表示されます。

** * 詳細 *
+
*** ストレージプール
+
ストレージプールの数が表示されます。

*** 合計サイズ
+
ストレージプールの合計サイズが表示されます。





* * クラウド階層 *
+
FabricPool対応アグリゲートを設定している場合は、クラウド階層の名前が表示され、使用済みの合計スペースが表示されます。クラウド階層が別のクラウドプロバイダ（ミラー階層）にミラーリングされている場合、両方のクラウド階層の詳細がここに表示されます。





== [Configuration]タブ

[構成]タブには、選択したアグリゲートについて、クラスタノード、ブロックタイプ、RAIDタイプ、RAIDサイズ、RAIDグループ数などの詳細が表示されます。

* * 概要 *
+
** ノード
+
選択したアグリゲートが含まれるノードの名前が表示されます。

** ブロックタイプ
+
アグリゲートのブロック形式（32ビットまたは64ビット）が表示されます。

** RAIDタイプ
+
RAIDタイプ（RAID 0、RAID 4、RAID-DP、RAID-TEC、またはMixed RAID）が表示されます。

** RAID サイズ
+
RAIDグループのサイズが表示されます。

** RAIDグループ
+
アグリゲート内のRAIDグループの数が表示されます。

** SnapLockタイプ
+
アグリゲートのSnapLockタイプが表示されます。



* * クラウド階層 *
+
FabricPool対応アグリゲートの場合は、クラウド階層の詳細が表示されます。一部のフィールドはストレージプロバイダによって異なります。クラウド階層が別のクラウドプロバイダ（「ミラーリング層」）にミラーリングされている場合、両方のクラウド階層がここに表示されます。

+
** プロバイダ
+
ストレージプロバイダの名前（StorageGRID、Amazon S3、IBM Cloud Object Storage、Microsoft Azureクラウド、Google Cloud Storage、Alibaba Cloud Object Storageなど）が表示されます。

** 名前
+
ONTAPでの作成時のクラウド階層の名前が表示されます。

** サーバ
+
クラウド階層のFQDNが表示されます。

** ポート
+
クラウドプロバイダとの通信に使用するポート。

** アクセスキーまたはアカウント
+
クラウド階層のアクセスキーまたはアカウントが表示されます。

** コンテナ名
+
クラウド階層のバケット名またはコンテナ名が表示されます。

** SSL
+
クラウド階層でSSL暗号化が有効になっているかどうかが表示されます。







== 履歴領域

[履歴]領域には、選択したアグリゲートの容量に関する情報がグラフで表示されます。また、 [ * エクスポート * ] ボタンをクリックして、表示しているチャートの CSV 形式でレポートを作成することもできます。

履歴ペインの上部にあるドロップダウンリストからグラフタイプを選択できます。1週間、1カ月、または1年を選択して、特定の期間の詳細を表示することもできます。履歴グラフは傾向を確認するのに役立ちます。たとえば、アグリゲートの使用量が継続的に「ほぼフル」のしきい値を超えていれば、それに応じた措置を講じることができます。

履歴グラフには次の情報が表示されます。

* * アグリゲート - 使用容量（ % ） *
+
折れ線グラフの形式で、アグリゲートの使用済み容量とアグリゲートの容量の使用履歴に基づく使用状況が縦軸（y軸）に表示されます。期間は横軸（x軸）に表示されます。期間は、週、月、または年を選択できます。グラフの特定のポイントにカーソルを合わせると、その時点の詳細を確認できます。該当する凡例をクリックすると、折れ線グラフの表示と非表示を切り替えることができます。たとえば、凡例で[使用済み容量]をクリックすると、使用済み容量を示す線が非表示になります。

* * アグリゲート - 使用容量と総容量 *
+
折れ線グラフの形式で、アグリゲートの容量の使用履歴と使用済み容量と合計容量（バイト、KB、MBなど）が縦軸（y軸）に表示されます。期間は横軸（x軸）に表示されます。期間は、週、月、または年を選択できます。グラフの特定のポイントにカーソルを合わせると、その時点の詳細を確認できます。該当する凡例をクリックすると、折れ線グラフの表示と非表示を切り替えることができます。たとえば、凡例で[トレンド-使用済み容量]をクリックすると、使用済み容量を示す線が非表示になります。

* * アグリゲート - 使用容量（ % ）対コミット容量（ % ） *
+
折れ線グラフの形式で、アグリゲートの容量使用履歴とコミット済みスペースの使用状況が縦軸（y軸）に表示されます。期間は横軸（x軸）に表示されます。期間は、週、月、または年を選択できます。グラフの特定のポイントにカーソルを合わせると、その時点の詳細を確認できます。該当する凡例をクリックすると、折れ線グラフの表示と非表示を切り替えることができます。たとえば、凡例で[スペースコミット済み]をクリックすると、[スペースコミット済み]グラフの線が非表示になります。





== [Events]リスト

[Events]リストには、新規および確認済みのイベントに関する詳細が表示されます。

* * 重大度 *
+
イベントの重大度が表示されます。

* * イベント *
+
イベント名が表示されます。

* * トリガー日時 *
+
イベントが生成されてからの経過時間が表示されます。1週間を過ぎたイベントには、生成時のタイムスタンプが表示されます。





== [Related Devices]ペイン

[Related Devices]ペインでは、アグリゲートに関連するクラスタノード、ボリューム、およびディスクを確認できます。

* * ノード *
+
アグリゲートが含まれるノードの容量と健全性ステータスが表示されます。容量は、総容量のうちの使用可能な合計容量を示します。

* * ノード内のアグリゲート *
+
選択したアグリゲートが含まれるクラスタノード内のすべてのアグリゲートの数と容量が表示されます。最も高い重大度レベルに基づいて、アグリゲートの健全性ステータスも表示されます。たとえば、クラスタノードに10個のアグリゲートがあり、そのうち5つのステータスが「警告」で残りの5つが「重大」の場合、ステータスは「重大」と表示されます。

* * ボリューム *
+
アグリゲート内のFlexVolボリュームとFlexGroupボリュームの数と容量が表示されます。FlexGroupコンスティチュエントは含まれません。最も高い重大度レベルに基づいて、ボリュームの健全性ステータスも表示されます。

* * リソースプール *
+
アグリゲートに関連するリソースプールが表示されます。

* * ディスク *
+
選択したアグリゲート内のディスクの数が表示されます。





== [Related Alerts]ペイン

[Related Alerts]ペインでは、選択したアグリゲートに対して作成されたアラートのリストを確認できます。[Add Alert]リンクをクリックしてアラートを追加したり、アラート名をクリックして既存のアラートを編集したりすることもできます。

* 関連情報 *

link:../health-checker/task_view_storage_pool_details.html["ストレージプールの詳細の表示"]
