---
permalink: health-checker/reference_setup_autosupport_page.html 
sidebar: sidebar 
keywords: autosupport, messages, support bundles, technical support 
summary: AutoSupportページでは、事前定義されたオンデマンドのAutoSupportメッセージをテクニカルサポートチームに送信して、環境が正しく運用されるようにしたり、環境の整合性を維持したりすることができます。AutoSupportはデフォルトで有効になっています。無効にしないでください。NetAppActive IQのメリットを活用できます。 
---
= テクニカルサポートへのAutoSupportメッセージとサポートバンドルの送信
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AutoSupportページでは、事前定義されたオンデマンドのAutoSupportメッセージをテクニカルサポートチームに送信して、環境が正しく運用されるようにしたり、環境の整合性を維持したりすることができます。AutoSupportはデフォルトで有効になっています。無効にしないでください。NetAppActive IQのメリットを活用できます。

Unified Managerサーバに関するシステムの診断情報や詳細なデータを必要に応じてメッセージで送信したり、メッセージを定期的に送信するようにスケジュール設定したりできます。また、サポートバンドルを生成してテクニカルサポートチームに送信することもできます。

[NOTE]
====
ストレージ管理者のロールを持つユーザは、オンデマンドのAutoSupportメッセージとサポートバンドルを生成してテクニカルサポートに送信できます。ただし、定期的なAutoSupportを有効または無効にしたり、HTTPプロキシサーバのセットアップのセクションの説明に従ってHTTPを設定したりできるのは、管理者ユーザまたはメンテナンスユーザだけです。HTTPプロキシサーバを使用する必要がある環境では、ストレージ管理者がテクニカルサポートにオンデマンドのAutoSupportメッセージとサポートバンドルを送信する前に、設定が完了している必要があります。

====


== オンテマントAutoSupportメツセエシノソウシン

オンデマンドメッセージを生成して、テクニカルサポート、指定したEメール受信者、またはその両方に送信できます。

.手順
. 「 * 一般 * > * AutoSupport * 」に移動し、次のいずれかまたは両方の操作を実行します。
. AutoSupport メッセージをテクニカルサポートに送信する場合は、 * テクニカルサポートに送信 * チェックボックスをオンにします。
. AutoSupport メッセージを特定の電子メール受信者に送信する場合は、 [* 電子メール受信者に送信 *] チェックボックスをオンにして、受信者の電子メールアドレスを入力します。
. [ 保存（ Save ） ] をクリックします。
. [Generate and Send AutoSupport （生成して送信） ] をクリックします。




== 定期的なAutoSupportの有効化

事前に定義された特定のメッセージをテクニカルサポートに定期的に送信して、問題の診断と解決を依頼できます。この機能はデフォルトで有効になっています。無効にした場合、管理者またはメンテナンスユーザは設定を有効にできます。

.手順
. 「 * 一般 * > * AutoSupport * 」に移動します。
. [ 定期的なデータ（ Periodic AutoSupport ） ] セクションで、 [ 定期的に AutoSupport データを Active IQ に送信する（ Enable Sending Data Periodically to ） ] チェックボックスをオン
. 必要に応じて、HTTPプロキシサーバのセットアップのセクションの説明に従って、HTTPプロキシサーバの名前、ポート、および認証情報を定義します。
. [ 保存（ Save ） ] をクリックします。




== オンデマンドサポートバンドルのアップロード

トラブルシューティングの要件に基づいて、サポートバンドルを生成してテクニカルサポートに送信できます。Unified Manager では、生成されたサポートバンドルのうち最新の 2 つだけが保持されます。それよりも古いサポートバンドルはシステムから削除されます。

サポートデータの種類によっては、クラスタリソースが大量に使用されたり、完了までに時間がかかることがあるため、フルサポートバンドルを選択した場合は、特定のデータタイプを含めるか除外してサポートバンドルのサイズを小さくすることができます。また、30日分のログと構成データベースのレコードを含む軽量なサポートバンドルを作成することもできます。このバンドルには、パフォーマンスデータ、取得記録ファイル、サーバヒープダンプは含まれません。

.手順
. 「 * 一般 * > * AutoSupport * 」に移動します。
. オンデマンドサポートバンドルセクションで、 * サポートバンドルの生成と送信 * をクリックします。
. 簡易サポートバンドルをテクニカルサポートに送信するには、サポートバンドルの生成と送信ポップアップで、 ** 簡易サポートバンドルの生成 ** チェックボックスをオンにします。
. または、完全なサポートバンドルを送信するには、 [*Generate full support Bundle*] チェックボックスをオンにします。サポートバンドルに含めるデータタイプまたは除外するデータタイプを選択します。
+
[NOTE]
====
いずれのデータタイプも選択しなかった場合でも、Unified Managerの他のデータでサポートバンドルが生成されます。

====
. バンドルを生成してテクニカルサポートに送信するには、 * Send the bundle to Technical Support * チェックボックスを選択します。このチェックボックスをオフにすると、バンドルが生成されてUnified Managerサーバにローカルに格納されます。生成されたサポートバンドルは、VMwareシステムの場合は/supportディレクトリ、Linuxシステムの場合はに、Windowsシステムの場合はに `ProgramData\NetApp\OnCommandAppData\ocum\support`あります `/opt/netapp/data/support/`。
. [ 送信（ Send ） ] をクリックします。




== HTTPプロキシサーバのセットアップ

Unified Managerサーバからの直接アクセスが環境で提供されない場合に、AutoSupportのコンテンツをサポートに送信するために、インターネットアクセスを提供するプロキシを指定できます。このセクションは、管理者およびメンテナンスユーザのみが使用できます。

* * HTTP プロキシ * を使用します
+
HTTPプロキシとして使用されているサーバを識別するには、このボックスをオンにします。

+
プロキシサーバのホスト名またはIPアドレス、およびサーバへの接続に使用するポート番号を入力します。

* * 認証を使用 *
+
HTTPプロキシとして使用されているサーバにアクセスするための認証情報を指定する必要がある場合は、このチェックボックスをオンにします。

+
HTTPプロキシでの認証に必要なユーザ名とパスワードを入力します。



[NOTE]
====
基本認証のみを提供するHTTPプロキシはサポートされていません。

====