---
permalink: health-checker/task_restore_mysql_db_on_linux_or_centos.html 
sidebar: sidebar 
keywords: restore, linux system, mysql, database, backup 
summary: データ損失やデータ破損が発生した場合、 Unified Manager を以前の安定した状態にリストアすることでデータ損失を最小限に抑えることができます。Unified Manager データベースは、 Unified Manager メンテナンスコンソールを使用してローカルとリモートのどちらの Red Hat Enterprise Linux または CentOS システムにもリストアできます。 
---
= LinuxシステムでのMySQLデータベースバックアップのリストア
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
データ損失やデータ破損が発生した場合、 Unified Manager を以前の安定した状態にリストアすることでデータ損失を最小限に抑えることができます。Unified Manager データベースは、 Unified Manager メンテナンスコンソールを使用してローカルとリモートのどちらの Red Hat Enterprise Linux または CentOS システムにもリストアできます。

* 必要なもの *

* Unified Manager がインストールされている Linux ホストの root ユーザのクレデンシャルが必要です。
* Unified Managerサーバのメンテナンスコンソールへのログインが許可されているユーザIDとパスワードが必要です。
* リストア処理を実行するシステムにUnified Managerのバックアップファイルとデータベースリポジトリディレクトリの内容をコピーしておく必要があります。
+
バックアップファイルをデフォルトのディレクトリ/`data/ocum`-backupにコピーすることを推奨します。データベースリポジトリファイルは、ディレクトリの下のサブディレクトリに/`ocum-backup`コピーする必要があり/`database-dumps-repo`ます。

* バックアップファイルのタイプはである必要があり `.7z`ます。


リストア機能は、プラットフォームおよびバージョンに固有の機能です。Unified Manager のバックアップは、同じバージョンの Unified Manager にのみリストアできます。Red Hat Enterprise LinuxまたはCentOSシステムにリストアできるのは、Linuxのバックアップファイルまたは仮想アプライアンスのバックアップファイルです。

[TIP]
====
バックアップフォルダ名にスペースが含まれている場合は、絶対パスまたは相対パスを二重引用符で囲む必要があります。

====
.手順
. 新しいサーバへのリストアを実行する場合は、Unified Managerのインストールの完了後に、UIを起動したり、クラスタ、ユーザ、または認証設定を設定したりしないでください。バックアップファイルには、リストアプロセス中にこの情報が入力されます。
. Secure Shell を使用して、 Unified Manager システムの IP アドレスまたは完全修飾ドメイン名に接続します。
. メンテナンスユーザ（umadmin）の名前とパスワードでシステムにログインします。
. コマンドを入力し `maintenance_console`、Enterキーを押します。
. メンテナンスコンソール * メインメニュー * で、 * バックアップリストア * オプションの番号を入力します。
. 「 MySQL バックアップのリストア」 * の番号を入力します。
. プロンプトが表示されたら、バックアップファイルの絶対パスを入力します。
+
[listing]
----
Bundle to restore from: /data/ocum-backup/UM_9.8.N151113.1348_backup_rhel_02-20-2020-04-45.7z
----
+
リストア処理が完了したら、Unified Managerにログインできます。



バックアップのリストア後にOnCommand Workflow Automationサーバが動作しない場合は、次の手順を実行します。

. Workflow Automationサーバで、Unified ManagerサーバのIPアドレスを最新のマシンを指すように変更します。
. 手順1で取得に失敗した場合は、Unified Managerサーバでデータベースパスワードをリセットします。

