---
permalink: health-checker/task_migrate_um_virtual_appliance_to_rhel_or_centos_system.html 
sidebar: sidebar 
keywords: unified manager, migrate, virtual, appliance, linux system 
summary: Unified Managerを実行するホストオペレーティングシステムを変更する場合は、Unified ManagerのMySQLデータベースダンプバックアップを仮想アプライアンスからRed Hat Enterprise LinuxまたはCentOS Linuxシステムにリストアすることができます。 
---
= LinuxシステムへのUnified Manager仮想アプライアンスの移行
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Managerを実行するホストオペレーティングシステムを変更する場合は、Unified ManagerのMySQLデータベースダンプバックアップを仮想アプライアンスからRed Hat Enterprise LinuxまたはCentOS Linuxシステムにリストアすることができます。

* 必要なもの *

* 仮想アプライアンス：
+
** オペレータ、アプリケーション管理者、またはストレージ管理者のロールが必要です。
** リストア処理用に、 Unified Manager のメンテナンスユーザの名前を確認しておく必要があります。


* Linuxシステムの場合：
+
** の手順に従って、LinuxサーバにUnified Managerをインストールしておく必要がありますlink:../install-linux/concept_install_unified_manager_on_rhel_or_centos.html["Linux システムへの Unified Manager のインストール"]。
** このサーバの Unified Manager のバージョンは、バックアップファイルを使用する仮想アプライアンスのバージョンと同じである必要があります。
** インストール後は、LinuxシステムでUIを起動したり、クラスタ、ユーザ、認証設定を設定したりしないでください。バックアップファイルには、リストアプロセス中にこの情報が入力されます。
** Linuxホストのrootユーザのクレデンシャルが必要です。




以下の手順では、仮想アプライアンスでバックアップファイルを作成し、そのバックアップファイルをRed Hat Enterprise LinuxまたはCentOSシステムにコピーして、新しいシステムにデータベースバックアップをリストアする方法について説明します。

.手順
. 仮想アプライアンスで、 * Management * > * Database Backup * をクリックします。
. [* データベース・バックアップ * ] ページで、 [ * バックアップ設定 * ] をクリックします。
. バックアップパスを/jail/supportに変更します。
. Schedule （スケジュール）セクションで、 Scheduled Daily （毎日のスケジュール）を選択し、バックアップがすぐに作成されるように、現在の時刻から数分経過した時刻を入力します。
. [ 適用（ Apply ） ] をクリックします。
. バックアップが生成されるまで数時間待ちます。
+
フルバックアップは1GBを超えることがあり、完了までに3~4時間かかることがあります。

. Unified ManagerがインストールされているLinuxホストにrootユーザとしてログインし、仮想アプライアンスの/supportからSCPを使用してバックアップファイルをコピーします。.`root@<rhel_server>:/# scp -r admin@<vapp_server_ip_address>:/support/* .`
+
`root@ocum_rhel-21:/# scp -r admin@10.10.10.10:/support/* .`

+
/database-dumps-repoサブディレクトリに.7zバックアップファイルとすべての.7zリポジトリファイルがコピーされていることを確認します。

. コマンドプロンプトで、バックアップをリストアします。 `um backup restore -f /<backup_file_path>/<backup_file_name>`
+
`um backup restore -f /UM_9.7.N151113.1348_backup_unix_02-12-2019-04-16.7z`

. リストア処理が完了したら、 Unified Manager Web UI にログインします。


次のタスクを実行する必要があります。

* 新しい HTTPS セキュリティ証明書を生成し、 Unified Manager サーバを再起動します。
* Linuxシステムに/jail/supportパスがないため、バックアップパスをLinuxシステムのデフォルト設定（/data/ocum-backup）に変更するか、任意の新しいパスに変更します。
* WFA を使用している場合は、 Workflow Automation の接続の両側を再設定します。
* SAML認証を再設定します（SAMLを使用する場合）。


Linux システムですべてが想定どおりに動作していることを確認したら、 Unified Manager 仮想アプライアンスをシャットダウンして削除できます。
