---
permalink: health-checker/task_resolve_capacity_issues.html 
sidebar: sidebar 
keywords: resolve, capacity issues 
summary: このワークフローでは、容量の問題を解決する方法の例を示します。このシナリオでは、管理者またはオペレータが、 Unified Manager のダッシュボードページにアクセスして、監視対象のストレージオブジェクトに容量の問題がないかどうかを確認します。問題の考えられる原因と解決策を特定する必要があります。 
---
= 容量の問題の解決
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
このワークフローでは、容量の問題を解決する方法の例を示します。このシナリオでは、管理者またはオペレータがUnified Managerの[Dashboard]ページにアクセスして、監視対象のストレージオブジェクトに容量の問題がないかどうかを確認します。問題の考えられる原因と解決策を特定する必要があります。

* 必要なもの *

オペレータ、アプリケーション管理者、またはストレージ管理者のロールが必要です。

ダッシュボードページでは ' イベントのドロップダウン・リストの下にある Capacity パネルで ' Volume Space Full エラー・イベントを探します

.手順
. ダッシュボード * ページの * 容量 * パネルで、ボリュームスペースがフルエラーイベントの名前をクリックします。
+
エラーの[イベントの詳細]ページが表示されます。

. イベント * の詳細ページでは、次のタスクを 1 つ以上実行できます。
+
** 原因フィールドのエラーメッセージを確認し、 Suggested Remedial Actions の下の提案をクリックして、考えられる修正方法の説明を確認します。
** [Source]フィールドでオブジェクト（ここではボリューム）の名前をクリックして、オブジェクトの詳細を表示します。
** このイベントについて追加されたメモを探します。
** イベントにメモを追加します。
** イベントを別のユーザに割り当てます。
** イベントに応答します。
** イベントを解決済みとマークします。




* 関連情報 *

link:../events/reference_event_details_page.html["[Event]詳細ページ"]
