---
permalink: health-checker/task_restore_mysql_database_backup_on_windows.html 
sidebar: sidebar 
keywords: restore, windows, mysql, database, backup 
summary: データ損失やデータ破損が発生した場合は、リストア機能を使用してUnified Managerを以前の安定した状態にリストアし、損失を最小限に抑えることができます。Unified ManagerのMySQLデータベースは、Unified Managerメンテナンスコンソールを使用してローカルとリモートのどちらのWindowsシステムにもリストアできます。 
---
= WindowsでのMySQLデータベースバックアップのリストア
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
データ損失やデータ破損が発生した場合は、リストア機能を使用してUnified Managerを以前の安定した状態にリストアし、損失を最小限に抑えることができます。Unified ManagerのMySQLデータベースは、Unified Managerメンテナンスコンソールを使用してローカルとリモートのどちらのWindowsシステムにもリストアできます。

* 必要なもの *

* Windows管理者Privilegesが必要です。
* リストア処理を実行するシステムにUnified Managerのバックアップファイルとデータベースリポジトリディレクトリの内容をコピーしておく必要があります。
+
バックアップファイルをデフォルトのディレクトリにコピーすることを推奨します `\ProgramData\NetApp\OnCommandAppData\ocum\backup`。データベースリポジトリファイルは、ディレクトリの下のサブディレクトリに `\backup`コピーする必要があり `\database_dumps_repo`ます。

* バックアップファイルのタイプはである必要があり `.7z`ます。


リストア機能は、プラットフォームおよびバージョンに固有の機能です。Unified ManagerのMySQLバックアップは同じバージョンのUnified Managerにのみリストアできます。また、WindowsのバックアップはWindowsプラットフォームにのみリストアできます。

[TIP]
====
フォルダ名にスペースが含まれている場合は、バックアップファイルの絶対パスまたは相対パスを二重引用符で囲む必要があります。

====
.手順
. 新しいサーバへのリストアを実行する場合は、Unified Managerのインストールの完了後に、UIを起動したり、クラスタ、ユーザ、または認証設定を設定したりしないでください。バックアップファイルには、リストアプロセス中にこの情報が入力されます。
. 管理者のクレデンシャルでUnified Managerシステムにログインします。
. Windows管理者としてPowerShellまたはコマンドプロンプトを起動します。
. コマンドを入力し `maintenance_console`、Enterキーを押します。
. メンテナンスコンソール * メインメニュー * で、 * バックアップリストア * オプションの番号を入力します。
. 「 MySQL バックアップのリストア」 * の番号を入力します。
. プロンプトが表示されたら、バックアップファイルの絶対パスを入力します。
+
[listing]
----
Bundle to restore from: \ProgramData\NetApp\OnCommandAppData\ocum\backup\UM_9.8.N151118.2300_backup_windows_02-20-2020-02-51.7z
----
+
リストア処理が完了したら、Unified Managerにログインできます。



バックアップのリストア後にOnCommand Workflow Automationサーバが動作しない場合は、次の手順を実行します。

. Workflow Automationサーバで、Unified ManagerサーバのIPアドレスを最新のマシンを指すように変更します。
. 手順1で取得に失敗した場合は、Unified Managerサーバでデータベースパスワードをリセットします。

