---
permalink: health-checker/task_configure_global_volume_health_threshold_values.html 
sidebar: sidebar 
keywords: configure, global, volume, health, threshold values 
summary: すべてのボリュームに対するグローバル健全性しきい値を設定して、しきい値の違反を追跡することができます。健全性しきい値の違反が発生すると該当するイベントが生成されるため、それらのイベントに基づいて予防策を講じることが可能です。監視対象のすべてのボリュームに適用されるしきい値について、ベストプラクティスの設定に基づいてグローバルな値を設定することができます。 
---
= ボリュームのグローバル健全性しきい値の設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
すべてのボリュームに対するグローバル健全性しきい値を設定して、しきい値の違反を追跡することができます。健全性しきい値の違反が発生すると該当するイベントが生成されるため、それらのイベントに基づいて予防策を講じることが可能です。監視対象のすべてのボリュームに適用されるしきい値について、ベストプラクティスの設定に基づいてグローバルな値を設定することができます。

* 必要なもの *

アプリケーション管理者またはストレージ管理者のロールが必要です。

ほとんどのしきい値オプションには、監視しやすくするためにデフォルト値が設定されています。ただし、それぞれの環境の要件に合わせて値を変更することができます。

ボリュームで自動拡張が有効になっている場合、元のボリュームサイズではなく、自動拡張で設定された最大ボリュームサイズに基づいて容量のしきい値を超えているとみなされることに注意してください。

[NOTE]
====
デフォルト値の 1000 は、 ONTAP のバージョンが 9.4 以降である FlexVol ボリューム、および ONTAP のバージョンが 9.8 以降である FlexGroup ボリュームにのみ適用されます。古いバージョンのONTAPソフトウェアがインストールされたクラスタの場合、ボリュームあたりのSnapshotコピーの最大数は250です。古いバージョンでは、1000（および1000~250の間の任意の数）をUnified Managerは250と解釈するため、Snapshotコピーの数が250に達してもイベントが引き続き受信されます。これらの古いバージョンでこのしきい値を 250 未満に設定する場合は、しきい値を 250 以下に設定するか、 Health ： All Volumes ビューまたは Volume/Health details ページで設定する必要があります。

====
.手順
. 左側のナビゲーションペインで、 * イベントしきい値 * > * 音量 * をクリックします。
. 容量、Snapshotコピー、qtreeクォータ、ボリュームの増加率、およびinodeについて適切しきい値を設定します。
. [ 保存（ Save ） ] をクリックします。


* 関連情報 *

link:../config/task_add_users.html["ユーザの追加"]
