---
permalink: health-checker/task_resolve_volume_offline_issues.html 
sidebar: sidebar 
keywords: resolve, volume, offline issues 
summary: 'このワークフローでは、Unified Managerの[イベント管理]インベントリページに表示されるボリュームオフラインイベントを評価して解決する方法の例を示します。このシナリオでは、管理者が Unified Manager を使用してボリュームオフラインイベントをトラブルシューティングします。' 
---
= ボリュームのオフライン状態の問題の解決
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
このワークフローでは、Unified Managerの[イベント管理]インベントリページに表示されるボリュームオフラインイベントを評価して解決する方法の例を示します。このシナリオでは、管理者が Unified Manager を使用してボリュームオフラインイベントをトラブルシューティングします。

* 必要なもの *

オペレータ、アプリケーション管理者、またはストレージ管理者のロールが必要です。

ボリュームがオフラインと報告される理由はいくつかあります。

* SVM 管理者が意図的にボリュームをオフラインにした。
* ボリュームをホストしているクラスタノードが停止し、その HA ペアパートナーへのストレージフェイルオーバーも失敗した。
* ボリュームをホストしているStorage Virtual Machine（SVM）が停止したために、そのSVMのルートボリュームをホストしているノードが停止した。
* 2つのRAIDディスクで同時に障害が発生したため、ボリュームをホストしているアグリゲートが停止しています。


[イベント管理]インベントリページと[クラスタ/健全性]、[Storage VM /健全性]、[ボリューム/健全性]の詳細ページを使用して、該当する可能性を確認または排除できます。

.手順
. 左側のナビゲーションペインで、 * イベント管理 * をクリックします。
. [ * イベント管理 * ] インベントリページで、 [ アクティブな可用性イベント * ] を選択します。
. 「ボリュームはオフライン」イベントのハイパーテキストリンクをクリックします。
+
可用性インシデントの[イベントの詳細]ページが表示されます。

. このページで、 SVM 管理者が対象のボリュームをオフラインにしたことを示すメモがないか確認します。
. イベント * の詳細ページで、次のタスクの 1 つ以上に関する情報を確認できます。
+
** 考えられる診断ガイダンスについては、[原因]フィールドに表示される情報を確認してください。
+
この例では、[原因]フィールドの情報から、ボリュームがオフラインであることのみがわかります。

** Notes and Updates 領域で、 SVM 管理者が該当のボリュームを意図的にオフラインにしたかどうかを確認します。
** イベントのソース（ここではオフラインと報告されたボリューム）をクリックして、そのボリュームに関する詳細情報を表示します。
** イベントを管理者に割り当てます。
** イベントに応答するか、必要に応じて解決済みとしてマークします。



