---
permalink: health-checker/task_edit_individual_volume_health_threshold_settings.html 
sidebar: sidebar 
keywords: edit, individual, volume, health, threshold, settings 
summary: 1つ以上のボリュームの容量、増加率、クォータ、およびスペースリザベーションの健全性しきい値の設定を編集することができます。しきい値を超えるとアラートが生成され、通知が送信されます。これらの通知は、生成されたイベントに基づいて予防策を講じるのに役立ちます。 
---
= 個 々 のボリューム健全性しきい値の設定の編集
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
1つ以上のボリュームの容量、増加率、クォータ、およびスペースリザベーションの健全性しきい値の設定を編集することができます。しきい値を超えるとアラートが生成され、通知が送信されます。これらの通知は、生成されたイベントに基づいて予防策を講じるのに役立ちます。

* 必要なもの *

アプリケーション管理者またはストレージ管理者のロールが必要です。

しきい値の値を変更すると、次回の監視サイクルから、その値に基づいてイベントが生成または廃止されます。

ボリュームで自動拡張が有効になっている場合、元のボリュームサイズではなく、自動拡張で設定された最大ボリュームサイズに基づいて容量のしきい値を超えているとみなされることに注意してください。

[NOTE]
====
デフォルト値の 1000 は、 ONTAP のバージョンが 9.4 以降である FlexVol ボリューム、および ONTAP のバージョンが 9.8 以降である FlexGroup ボリュームにのみ適用されます。古いバージョンのONTAPソフトウェアがインストールされたクラスタの場合、ボリュームあたりのSnapshotコピーの最大数は250です。古いバージョンでは、1000（および1000~250の間の任意の数）をUnified Managerは250と解釈するため、Snapshotコピーの数が250に達してもイベントが引き続き受信されます。これらの古いバージョンでこのしきい値を 250 未満に設定する場合は、しきい値を 250 以下に設定するか、 Health ： All Volumes ビューまたは Volume/Health details ページで設定する必要があります。

====
.手順
. 左側のナビゲーションペインで、 * Storage * > * Volumes * をクリックします。
. * 健全性：すべてのボリューム * 表示で、 1 つ以上のボリュームを選択し、 * しきい値の編集 * をクリックします。
. ボリュームしきい値の編集 * ダイアログボックスで、該当するチェックボックスを選択して値を変更し、容量、 Snapshot コピー、 qtree クォータ、増加率、または inode についてのしきい値の設定を編集します。
. [ 保存（ Save ） ] をクリックします。


* 関連情報 *

link:../config/task_add_users.html["ユーザの追加"]
