---
permalink: health-checker/task_configure_global_health_threshold_settings.html 
sidebar: sidebar 
keywords: configure, global health, threshold settings 
summary: アグリゲート、ボリューム、qtreeのサイズを効果的に監視できるように、容量、増加率、Snapshotリザーブ、クォータ、およびinodeについてグローバル健全性しきい値条件を設定できます。また、遅延しきい値を超えた場合にイベントを生成する設定を編集することもできます。 
---
= グローバル健全性しきい値の設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アグリゲート、ボリューム、qtreeのサイズを効果的に監視できるように、容量、増加率、Snapshotリザーブ、クォータ、およびinodeについてグローバル健全性しきい値条件を設定できます。また、遅延しきい値を超えた場合にイベントを生成する設定を編集することもできます。

グローバル健全性しきい値の設定は、アグリゲートやボリュームなど、関連付けられているすべてのオブジェクトに適用されます。しきい値を超えるとイベントが生成され、アラートが設定されている場合はアラート通知も送信されます。しきい値はデフォルトで推奨値に設定されていますが、それらの値を変更することでイベントが生成される間隔をニーズに合わせて調整することができます。しきい値を変更した場合、次回の監視サイクルから反映され、その値に基づいてイベントが生成または廃止されます。

グローバル健常性しきい値の設定には、左側のナビゲーションメニューの「イベントしきい値」セクションからアクセスできます。個 々 のオブジェクトのインベントリページまたは詳細ページから、そのオブジェクトのしきい値の設定を変更することもできます。

* 詳細については、を参照してください link:task_configure_global_aggregate_health_threshold_values.html["アグリゲートのグローバル健全性しきい値の設定"]。
+
すべてのアグリゲートの容量、増加率、およびSnapshotコピーの健全性しきい値を設定して、しきい値の違反を追跡することができます。

* 詳細については、を参照してください link:task_configure_global_volume_health_threshold_values.html["ボリュームのグローバル健全性しきい値の設定"]。
+
すべてのボリュームの容量、Snapshotコピー、qtreeクォータ、ボリューム増加率、オーバーライトリザーブスペース、およびinodeの健全性しきい値の設定を編集して、しきい値の違反を追跡することができます。

* 詳細については、を参照してください link:task_configure_global_qtree_health_threshold_values.html["qtreeのグローバル健全性しきい値の設定"]。
+
すべてのqtreeの容量の健全性しきい値の設定を編集して、しきい値の違反を追跡することができます。

* 詳細については、を参照してください link:task_configure_lag_threshold_settings_for_unmanaged_protection.html["管理対象外の保護関係の遅延健全性しきい値の編集"]。
+
警告やエラーの遅延時間の割合を増やしたり減らしたりすることで、イベントが生成される間隔をニーズに合わせて調整することができます。


