---
permalink: health-checker/task_perform_suggested_remedial_actions_for_full_volume.html 
sidebar: sidebar 
keywords: perform, suggested, remedial actions, volume 
summary: 「ボリュームスペースがフル」エラーイベントを受け取ったら、イベントの詳細ページで推奨される修正策を確認し、推奨されるいずれかの操作を実行します。 
---
= ボリュームがフルになった場合の推奨修正策の実施
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「ボリューム容量がいっぱいです」エラーイベントを受け取った後、イベントの詳細ページで推奨される修正策を確認し、推奨されるアクションのいずれかを実行することにします。

* 必要なもの *

アプリケーション管理者またはストレージ管理者のロールが必要です。

Unified Manager を使用するこのワークフロー内のタスクは、どのロールのユーザでも実行できます。

この例では、Unified ManagerEvent Managementのインベントリページに「Volume Space Full」エラーイベントが表示され、イベント名をクリックしています。

ボリュームがフルになった場合に実施できる修正策には、次のものがあります。

* ボリュームでの自動拡張、重複排除、または圧縮の有効化
* ボリュームのサイズ変更または移動
* ボリュームのデータの削除または移動


これらの操作はいずれもONTAP System ManagerまたはONTAP CLIから実行する必要がありますが、実行する操作を決定するために必要な情報はUnified Managerで確認できます。

.手順
. イベント * の詳細ページで、ソースフィールドのボリューム名をクリックすると、該当するボリュームの詳細が表示されます。
. ボリューム / 健常性 * の詳細ページで * Configuration * をクリックすると、ボリュームで重複排除と圧縮がすでに有効になっていることがわかります。
+
ボリュームのサイズを変更することにします。

. Related Devices * ペインで、ホスティングアグリゲートの名前をクリックすると、アグリゲートがボリュームの拡張に対応できるかどうかがわかります。
. アグリゲート / 健常性 * の詳細ページには、フルボリュームをホストしているアグリゲートにコミットされていない容量が十分にあることが表示されます。そのため、 ONTAP システムマネージャを使用してボリュームのサイズを変更し、容量を拡大します。


* 関連情報 *

link:../events/reference_event_details_page.html["[Event]詳細ページ"]
