---
permalink: health-checker/task_generate_and_upload_support_bundle.html 
sidebar: sidebar 
keywords: generate, upload, support bundle 
summary: トラブルシューティングのサポートを受けるためにテクニカルサポートに送信できるように、診断情報が含まれたサポートバンドルを生成できます。メンテナンスコンソールからネットアップにサポートバンドルをアップロードすることもできます。 
---
= サポートバンドルの生成とアップロード
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
トラブルシューティングのサポートを受けるためにテクニカルサポートに送信できるように、診断情報が含まれたサポートバンドルを生成できます。

Unified Manager 9.8以降では、Unified Managerサーバがインターネットに接続されている場合は、メンテナンスコンソールからサポートバンドルをNetAppにアップロードすることもできます。

* 必要なもの *

メンテナンスコンソールにメンテナンスユーザとしてアクセスできる必要があります。

一部のタイプのサポートデータは大量のクラスタリソースを使用したり、完了までに時間がかかることがあるため、フルサポートバンドルを選択した場合は、対象に含めるデータタイプまたは除外するデータタイプを指定してサポートバンドルのサイズを小さくすることができます。また、30日分のログと構成データベースのレコードを含む軽量なサポートバンドルを作成することもできます。このバンドルには、パフォーマンスデータ、取得記録ファイル、サーバヒープダンプは含まれません。

Unified Manager では、生成されたサポートバンドルのうち最新の 2 つだけが保持されます。それよりも古いサポートバンドルはシステムから削除されます。

.手順
. メンテナンスコンソール * メインメニュー * で、 * サポート / 診断 * を選択します。
. サポートバンドルに含める詳細のレベルに応じて、 [Generate Light Support Bundle] または [*Generate Support Bundle] を選択します。
. フルサポートバンドルを選択した場合は、サポートバンドルに含めるまたは除外する次のデータタイプを選択または選択解除します。
+
** * データベースダンプ *
+
MySQL Serverデータベースのダンプ。

** * ヒープダンプ *
+
メインの Unified Manager サーバプロセスの状態の Snapshot 。このオプションはデフォルトでは無効になっており、カスタマーサポートから要求された場合にのみ選択してください。

** * 取得記録 *
+
Unified Manager と監視対象クラスタの間のすべての通信の記録。



+
[NOTE]
====
すべてのデータタイプを選択解除しても、それ以外の Unified Manager データでサポートバンドルが生成されます。

====
. と入力し `g`、Enterキーを押してサポートバンドルを生成します。
+
サポートバンドルの生成はメモリを大量に消費する処理であるため、この時点でサポートバンドルを生成するかどうかを確認するプロンプトが表示されます。

. と入力し `y`、Enterキーを押してサポートバンドルを生成します。
+
この時点でサポートバンドルを生成しない場合は、と入力して `n`Enterキーを押します。

. フルサポートバンドルにデータベースダンプファイルを含めた場合は、パフォーマンス統計を含める期間を指定するように求められます。パフォーマンス統計の取り込みには時間とスペースがかかることがあるため、パフォーマンス統計を含めずにデータベースをダンプすることもできます。
+
.. 開始日をYYYYMMDDの形式で入力します。
+
たとえば、2021年1月1日の場合はと入力し `20210101`ます。パフォーマンス統計を含めない場合はと入力します `n`。

.. 統計を収集する期間（指定した開始日の午前0時からの日数）を入力します。
+
1～10の数値を入力できます。



+
パフォーマンス統計を含める場合は、収集期間が表示されます。

. サポートバンドルが作成されると、そのサポートバンドルをNetAppにアップロードするかどうかを確認するメッセージが表示されます。と入力し `y`、Enterキーを押します。
+
サポートケース番号の入力を求められます。

. ケース番号がすでにある場合は、番号を入力してEnterキーを押します。それ以外の場合はEnterキーを押します。
+
サポートバンドルがNetAppにアップロードされます。



Unified Managerサーバがインターネットに接続されていない場合や、その他の理由でサポートバンドルをアップロードできない場合は、サーバを取得して手動で送信できます。データを取得するには、SFTPクライアントを使用するか、UNIXまたはLinuxのCLIコマンドを使用します。Windows環境では、Remote Desktop（RDP）を使用してサポートバンドルを取得できます。

生成されたサポートバンドルの場所は、VMwareシステムの/supportディレクトリ、NetApp Linuxシステムの/opt/vmware/data/support/、NetApp WindowsシステムのProgramData\OnCommandAppData\ocum\supportです。

* 関連情報 *

link:../config/reference_unified_manager_roles_and_capabilities.html["Unified Managerのユーザロールと機能"]
