---
permalink: health-checker/task_view_antiransomware_status_of_all_volumes_storage_vms.html 
sidebar: sidebar 
keywords: view, anti-ransomware status, volumes, storage VMs, SVMs 
summary: すべてのボリュームとStorage VM、および最新のランサムウェア対策ステータスのリストを表示して、ボリューム上のデータがランサムウェア攻撃から適切に保護されているかどうかを確認できます。 
---
= すべてのボリュームとStorage VMのランサムウェア対策ステータスの表示
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
すべてのボリュームとStorage VM（SVM）のリストとその現在のランサムウェア対策ステータスを表示して、ボリュームとSVM上のデータがランサムウェア攻撃から適切に保護されているかどうかを確認できます。

* 必要なもの *

オペレータ、アプリケーション管理者、またはストレージ管理者のロールが必要です。

さまざまなランサムウェア対策ステータスの詳細については、を参照してくださいlink:https://docs.netapp.com/us-en/ontap/anti-ransomware/enable-task.html#system-manager-procedure["ONTAP ：ランサムウェア対策を有効化"]。



== ランサムウェア対策検出機能を使用して、すべてのボリュームのセキュリティの詳細を表示する

.手順
. 左側のナビゲーションペインで、 * Storage * > * Volumes * をクリックします。
. [表示]メニューで、[* Health *>* Security *>* Anti-Ransomware *]を選択します
. セキュリティ：アンチランサムウェア*表示では、さまざまなフィールドでソートしたり、フィルタを使用したりできます。



NOTE: Anti-Ransomwareは、オフラインボリューム、制限されたボリューム、SnapLockボリューム、FlexGroupボリューム、FlexCacheボリューム、SAN専用ボリューム、停止しているStorage VMのボリューム、Storage VMのルートボリューム、データ保護ボリュームではサポートされていません。



== ランサムウェア対策検出機能付きで、すべてのStorage VMのセキュリティの詳細を表示

.手順
. 左側のナビゲーションペインで、* Storage > Storage VM*をクリックします。
. ［*表示］>［セキュリティ］>［ランサムウェア対策*］の順に選択します。ランサムウェア対策ステータスのSVMのリストが表示されます。



NOTE: NASプロトコルが有効になっていないStorage VMでは、ランサムウェア対策の監視はサポートされません。
