---
permalink: health-checker/task_determine_if_volume_is_offline_because_of_broken_disks.html 
sidebar: sidebar 
keywords: determine, volume, offline, broken disks, aggregate 
summary: Unified Manager Web UI を使用して、ボリュームがオフラインになっている原因が、 RAID ディスクの問題によりそのホストアグリゲートがオフラインになったためであるかどうかを確認することができます。 
---
= ボリュームのオフライン状態の原因がアグリゲート内の破損ディスクであるかどうかの判別
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager Web UI を使用して、ボリュームがオフラインになっている原因が、 RAID ディスクの問題によりそのホストアグリゲートがオフラインになったためであるかどうかを確認することができます。

* 必要なもの *

オペレータ、アプリケーション管理者、またはストレージ管理者のロールが必要です。

ボリュームのオフライン状態の原因がRAIDディスクの問題によってホストアグリゲートがオフラインになったことであるかどうかを確認するには、次の手順を実行します。

.手順
. 「 * Volume/Health * details 」ページの「 Aggregate 」（アグリゲート）に表示されているハイパーテキストリンクを探してクリックします。
+
[アグリゲート/健全性の詳細]ページには、ホストしているアグリゲートのオンラインステータスまたはオフラインステータスが表示されます。アグリゲートのステータスがオンラインの場合、ボリュームがオフラインになっている原因はRAIDディスクの問題ではありません。

. アグリゲートのステータスがオフラインの場合は、 * ディスク情報 * をクリックし、 * ディスク情報 * タブの * イベント * リストで破損ディスクイベントを探します。
. 破損ディスクをさらに特定するには、 [*Related Devices* （関連デバイス） ] ペインの [Node （ノード） ] に表示されるハイパーテキストリンクをクリックします。
+
[クラスタ/健全性の詳細]ページが表示されます。

. [ * ディスク ] をクリックし、 [ * フィルタ * ] ペインで [ * 破損 * ] を選択して、破損状態のすべてのディスクを一覧表示します。
+
破損状態のディスクがホストアグリゲートのオフライン状態の原因となった場合は、[影響を受けるアグリゲート]列にアグリゲートの名前が表示されます。



ボリュームのオフライン状態の原因がRAIDディスクの破損とそれに伴うホストアグリゲートのオフライン化であることを確認したら、適切な管理者またはオペレータに連絡して、破損ディスクを手動で交換し、アグリゲートをオンラインに戻します。
