---
permalink: install-vapp/concept_virtual_infrastructure_or_hardware_system_requirements.html 
sidebar: sidebar 
keywords: virtual, infrastructure, hardware, system, requirements, virtual appliance 
summary: Unified Managerを仮想インフラまたは物理システムにインストールするには、メモリ、CPU、およびディスクスペースの最小要件を満たす必要があります。 
---
= 仮想インフラとハードウェアシステムの要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Managerを仮想インフラまたは物理システムにインストールするには、メモリ、CPU、およびディスクスペースの最小要件を満たす必要があります。

次の表に、メモリ、CPU、およびディスクスペースの各リソースに推奨される値を示します。これらの値は、Unified Managerが許容されるパフォーマンスレベルを達成することが確認されている値です。

[cols="2*"]
|===
| ハードウェア構成 | 推奨設定 


 a| 
RAM
 a| 
12GB（最小要件は8GB）



 a| 
プロセッサ
 a| 
CPU×4



 a| 
CPUサイクル容量
 a| 
合計9572MHz（最小要件9572MHz）



 a| 
空きディスクスペース
 a| 
* 5GB（シンプロビジョニング）
* 152GB（シックプロビジョニング）


|===
Unified Managerはメモリの少ないシステムにもインストールできますが、推奨される12GBのRAMがあれば最適なパフォーマンスが保証されるだけでなく、拡張時にクラスタやストレージオブジェクトの追加にも対応できます。Unified Managerを導入するVMにはメモリの上限を設定しないでください。また、ソフトウェアがシステムで割り当てられているメモリを利用できなくなる機能（バルーニングなど）は有効にしないでください。

また、1つのUnified Managerインスタンスで監視できるノードの数には上限があり、この上限を超える場合は2つ目のUnified Managerインスタンスをインストールします。詳細については、を参照してください link:https://www.netapp.com/pdf.html?item=/media/13504-tr4621pdf.pdf["Unified Managerベストプラクティスガイド"^]。

メモリページスワッピングは、システムと管理アプリケーションのパフォーマンスに悪影響を及ぼします。ホスト全体の利用率が原因で使用できないCPUリソースを競合すると、パフォーマンスが低下する可能性があります。



== 専用使用の要件

Unified Managerをインストールする物理システムまたは仮想システムは、他のアプリケーションとは共有せず、Unified Manager専用にする必要があります。他のアプリケーションにシステムリソースが消費されると、Unified Managerのパフォーマンスが大幅に低下する可能性があります。



== バックアップ用のスペース要件

Unified Manager のバックアップとリストア機能を使用する場合は、「 data 」ディレクトリまたはディスクに 150GB のスペースがあるように追加の容量を割り当ててください。バックアップはローカルにもリモートにも保存できますが、Unified Managerホストシステムとは別の、150GB以上のスペースがあるリモートの場所に保存することを推奨します。



== ホスト接続の要件

Unified Managerをインストールする物理システムまたは仮想システムは、ホスト自体からホスト名にを実行できるように設定する必要があります `ping`。IPv6構成の場合は、Unified Managerを正しくインストールするために、ホスト名へのが成功することを確認する必要があります `ping6`。

製品のWeb UIには、ホスト名（またはホストのIPアドレス）を使用してアクセスできます。導入時にネットワークに静的IPアドレスを設定した場合は、ネットワークホストの名前を指定します。DHCPを使用してネットワークを設定した場合は、DNSからホスト名を取得する必要があります。

完全修飾ドメイン名（FQDN）またはIPアドレスの代わりに短縮名を使用したUnified Managerへのアクセスをユーザに許可する場合は、短縮名が有効なFQDNに解決されるようにネットワークを設定する必要があります。
