---
permalink: install-vapp/task_upgrade_unified_manager_virtual_appliance_vapp.html 
sidebar: sidebar 
keywords: upgrade, unified manager, virtual, appliance 
summary: Unified Manager 仮想アプライアンスはアップグレードできます 
---
= Unified Manager仮想アプライアンスのアップグレード
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager仮想アプライアンスをリリース9.12または9.13から9.14にアップグレードできます。

* 必要なもの *

次の点を確認します。

* アップグレードファイル（ISOイメージ）をNetAppサポートサイトからダウンロードしておきます。
* Unified Managerをアップグレードするシステムがシステム要件とソフトウェア要件を満たしている。
+
を参照して link:concept_virtual_infrastructure_or_hardware_system_requirements.html["仮想インフラの要件"]

+
を参照して link:reference_vmware_software_and_installation_requirements.html["VMwareソフトウェアとインストールの要件"]

* vSphere 6.5以降を使用している場合は、VMware Remote Console（VMRC）をインストールしておきます。
* アップグレードの実行中、パフォーマンスデータの保持期間について、以前のデフォルト設定である13カ月のままにするか6カ月に変更するかを確認するプロンプトが表示されることがあります。確認すると、6カ月後に履歴パフォーマンスデータがパージされます。
* 次の情報が必要です。
+
** NetApp Support Siteのログインクレデンシャル
** VMware vCenter ServerおよびvSphere Web Clientにアクセスするためのクレデンシャル
** Unified Manager のメンテナンスユーザのクレデンシャル




アップグレードプロセスの実行中は、Unified Managerを使用できなくなります。実行中の処理がある場合は、Unified Managerをアップグレードする前に完了してください。

Workflow AutomationとUnified Managerを連携させて使用している場合は、Workflow Automationでホスト名を手動で更新する必要があります。

.手順
. vSphere Client で、 * Home * > * Inventory * > * VMs and Templates * をクリックします。
. Unified Manager仮想アプライアンスがインストールされている仮想マシン（VM）を選択します。
. Unified Manager VM が実行されている場合は、「 * 概要 * > * コマンド * > * ゲストのシャットダウン * 」に移動します。
. Unified Manager VMのバックアップコピー（Snapshotやクローンなど）を作成して、アプリケーションと整合性のあるバックアップを作成します。
. vSphere Clientで、Unified Manager VMの電源をオンにします。
. VMware Remote Consoleを起動します。
. [* CDROM * ] アイコンをクリックし、 [* ディスクイメージファイル (.ISO)* に接続 ] を選択します。
. ファイルを選択し `ActiveIQUnifiedManager-<version>-virtual-update.iso`、*開く*をクリックします。
. [* コンソール * ] タブをクリックします。
. Unified Managerメンテナンスコンソールにログインします。
. メインメニューで、 * アップグレード * を選択します。
+
アップグレードプロセスの実行中はUnified Managerを使用できなくなり、完了後に再開されることを示すメッセージが表示されます。

. と入力 `y`して続行します。
+
仮想アプライアンスが配置されている仮想マシンをバックアップするように通知する警告が表示されます。

. と入力 `y`して続行します。
+
アップグレードプロセスが完了してUnified Managerサービスが再起動されるまでに数分かかることがあります。

. いずれかのキーを押して続行します。
+
メンテナンスコンソールから自動的にログアウトされます。

. * オプション：メンテナンスコンソールにログインし、 Unified Manager のバージョンを確認します。


サポートされているWebブラウザの新しいウィンドウでWeb UIを起動し、ログインしてアップグレード後のバージョンのUnified Managerを使用できます。検出プロセスが完了してからUIでのタスクを実行する必要があります。
