---
permalink: install-vapp/task_deploy_unified_manager_virtual_appliance_vapp.html 
sidebar: sidebar 
keywords: deploy, unified manager, virtual appliance 
summary: インストールファイルをダウンロードしたら、Unified Managerを仮想アプライアンスとして導入します。vSphere Web Clientを使用して、ESXiサーバに仮想アプライアンスを導入します。仮想アプライアンスを導入すると、仮想マシンが作成されます。 
---
= Unified Manager仮想アプライアンスの導入
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
インストールファイルをダウンロードしたら、Unified Managerを仮想アプライアンスとして導入します。vSphere Web Clientを使用して、ESXiサーバに仮想アプライアンスを導入します。仮想アプライアンスを導入すると、仮想マシンが作成されます。

* 必要なもの *

システム要件を確認しておく必要があります。Unified Manager仮想アプライアンスを導入する前に、必要な変更を行ってください。

を参照して link:concept_virtual_infrastructure_or_hardware_system_requirements.html["仮想インフラの要件"]

を参照して link:reference_vmware_software_and_installation_requirements.html["VMwareソフトウェアとインストールの要件"]

Dynamic Host Configuration Protocol（DHCP；動的ホスト構成プロトコル）を使用する場合は、DHCPサーバが使用可能であること、およびDHCPと仮想マシン（VM）ネットワークアダプタの設定が正しいことを確認してください。DHCPはデフォルトで設定されています。

静的なネットワーク設定を使用する場合は、IPアドレスが同じサブネット内で重複していないこと、および適切なDNSサーバエントリが設定されていることを確認してください。

仮想アプライアンスを導入する前に、次の情報を入手します。

* VMware vCenter ServerおよびvSphere Web Clientにアクセスするためのクレデンシャル
* Unified Manager 仮想アプライアンスを導入する ESXi サーバの IP アドレス
* データセンターの詳細（使用可能なストレージスペースなど）
* DHCPを使用していない場合は、接続するネットワークデバイスのIPv4アドレスまたはIPv6アドレスを取得します。
+
** ホストの完全修飾ドメイン名（FQDN）
** ホストのIPアドレス
** ネットワークマスク
** デフォルトゲートウェイのIPアドレス
** プライマリおよびセカンダリDNSアドレス
** 検索ドメイン




Unified Manager 9.8以降では、VMware ToolsがOpen VM Toolsに置き換えられて `_open-vm-tools_`います）。はUnified Managerのインストールパッケージに含まれているため、インストールプロセスでVMware Toolsをインストールする必要はありません `_open-vm-tools_`。

仮想アプライアンスを導入すると、HTTPSアクセス用の一意の自己署名証明書が生成されます。Unified Manager Web UI にアクセスする際に、信頼された証明書でないことを示す警告がブラウザに表示されることがあります。

Unified Manager仮想アプライアンスではVMware High Availabilityがサポートされます。

.手順
. vSphere Client で、 * File * > * Deploy OVF Template * をクリックします。
. Deploy OVF Template ウィザードを実行して、 Unified Manager 仮想アプライアンスを導入します。
+
[Review Details]ページで、

+
** Publisherセクションの詳細を確認します。「* Entrust Code Signing - OVCS2（Trusted certificate）*」というメッセージは、ダウンロードしたファイルの整合性を確認します `OVA`。+「Entrust Code Signing - OVCS2（Invalid certificate）」というメッセージが表示された場合は、VMware vCenter Serverを7.0U3E以降のバージョンにアップグレードします。
+
[テンプレートのカスタマイズ]ページで、次の操作を行います。

** DHCPおよびIPv4アドレスを使用する場合は、すべてのフィールドを空白のままにします。
** DHCP と IPv6 アドレスを使用する場合は '[Enable Auto IPv6 addressing] チェックボックスをオンにし ' その他のフィールドはすべて空白のままにします
** 静的なネットワーク設定を使用する場合は、このページの各フィールドに値を入力すると、それらの設定が導入時に適用されます。IPアドレスが導入先のホストで一意であること、まだ使用されていないこと、および有効なDNSエントリが設定されていることを確認してください。


. Unified Manager 仮想アプライアンスを ESXi サーバに導入したら、 VM を右クリックして電源をオンにし、 * 電源オン * を選択します。
+
[NOTE]
====
リソースが十分でないために電源投入に失敗した場合は、リソースを追加してからインストールを再試行してください。

====
. [* コンソール * ] タブをクリックします。
+
初期ブートプロセスが完了するまでに数分かかります。

. タイムゾーンを設定するには、 VM コンソールウィンドウに表示される指示に従って、地理的な地域と都市または地域を入力します。
+
表示されるすべての日付情報には、管理対象デバイスのタイムゾーンの設定に関係なく、 Unified Manager 用に設定されているタイムゾーンが使用されます。ストレージシステムと管理サーバが同じNTPサーバを使用して設定されている場合は、表示方法が異なっていても、同じインスタントインタイムを参照しています。たとえば、管理サーバとは異なるタイムゾーンを使用して設定されたデバイスを使用してSnapshotコピーを作成した場合、タイムスタンプは管理サーバの時刻になります。

. 使用可能なDHCPサービスがない場合、または静的なネットワーク設定の詳細に誤りがある場合は、次のいずれかのオプションを選択します。
+
[cols="2*"]
|===
| 状況 | 操作 


 a| 
DHCP
 a| 
[DHCP の再試行 *] を選択します。DHCPを使用する場合は、正しく設定されていることを確認する必要があります。

DHCP対応のネットワークを使用する場合は、FQDNとDNSサーバのエントリが仮想アプライアンスに自動的に割り当てられます。DHCP に DNS が適切に設定されていないと、ホスト名「 UnifiedManager 」が自動的に割り当てられ、セキュリティ証明書に関連付けられます。DHCP対応のネットワークをセットアップしていない場合は、ネットワーク設定情報を手動で入力する必要があります。



 a| 
静的なネットワーク設定
 a| 
.. 「 * Enter the details for static network configuration * 」を選択します。
+
設定プロセスが完了するまでに数分かかります。

.. 入力した値を確認し、 * Y * を選択します。


|===
. プロンプトでメンテナンスユーザの名前を入力し、 * Enter * をクリックします。
+
メンテナンスユーザの名前は、1文字目はa ~ z、続けて-、a ~ z、または0 ~ 9を任意に組み合わせて指定する必要があります。

. プロンプトでパスワードを入力し、 * Enter * をクリックします。
+
VM コンソールに Unified Manager Web UI の URL が表示されます。



Web UIにアクセスしてUnified Managerの初期セットアップを実行できます。手順については、を参照してlink:../config/concept_configure_unified_manager.html["Active IQ Unified Managerの設定"]ください。
