---
permalink: install-windows/qsg-windows.html 
sidebar: sidebar 
keywords: quick start guide, getting started, QSG, Windows QSG, quick installation, Windows installer 
summary: Windowsプラットフォーム向けのUnified Managerクイックスタートガイドです。 
---
= クイックスタートガイド（Windowsのインストール）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
インストールパッケージをダウンロードしてUnified Managerをインストールすることで、データストレージの容量、可用性、パフォーマンス、保護の問題を監視してトラブルシューティングすることができます。



== システム要件

* オペレーティングシステム
+
** Microsoft Windows Server 2019 Standard EditionおよびDatacenter Edition
** Microsoft Windows Server 2022 Standard EditionおよびDatacenter Edition
+
Unified Managerは、64ビットのWindowsオペレーティングシステムで次の言語に対応しています。

** 英語
** 日本語
** 簡体字中国語


* RAM ： 12GB
* CPU：合計9572MHz
* 空きディスクスペース：100GB（インストールディレクトリ用）、50GB（MySQLデータディレクトリ用）


詳細なシステム要件については、およびを参照してlink:../install-windows/concept_requirements_for_installing_unified_manager.html["Unified Managerのインストール要件"]link:http://mysupport.netapp.com/matrix["Interoperability Matrix"^]ください。



== Active IQ Unified Managerのインストール



=== インストーラをダウンロードする

. インストールパッケージをダウンロードし `ActiveIQUnifiedManager-<version>.exe`ます。
. インストールファイルをターゲットシステムのディレクトリにコピーします。




=== Unified Managerをインストールする

Unified Managerをインストールするには、Microsoft .NET 4.5.2以降のバージョンがインストールされている必要があります。Unified Managerのインストールプロセスでは、必要に応じて他のサードパーティパッケージがインストールされます。依存ソフトウェアパッケージの詳細については、を参照してlink:../install-windows/reference_windows_software_and_installation_requirements.html["Windowsソフトウェアとインストールの要件"]ください。

. デフォルトのローカル管理者アカウントを使用してWindowsにログインします。
. インストールファイルをダウンロードしたディレクトリで、Unified Managerの実行可能ファイル（.exe）を管理者として実行します。
. プロンプトが表示されたら、ユーザ名とパスワードを入力してUnified Managerメンテナンスユーザを作成します。
. データベース接続ウィザードで、MySQLのrootパスワードを入力します。
. 画面の指示に従ってインストールを完了します。
. インストールの完了時に * Finish * をクリックすると、 Unified Manager Web UI が表示されます。

