---
permalink: install-windows/task_upgrade_to_unified_manager_on_microsoft_windows.html 
sidebar: sidebar 
keywords: upgrade, unified manager 
summary: Unified Manager をアップグレードするには、 Windows プラットフォームでインストールファイルをダウンロードして実行します。 
---
= Unified Managerのアップグレード
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
WindowsプラットフォームでUnified Manager 9.12または9.13から9.14にアップグレードするには、インストールファイルをダウンロードして実行します。

* 必要なもの *

* Unified Managerをアップグレードするシステムがシステム要件とソフトウェア要件を満たしている必要があります。
+
を参照して link:concept_virtual_infrastructure_or_hardware_system_requirements.html["ハードウェアシステムの要件"]

+
を参照して link:reference_windows_software_and_installation_requirements.html["Windowsソフトウェアとインストールの要件"]

+
[NOTE]
====
Unified Manager 9.5以降では、OpenJDKはインストールパッケージに含まれており、自動的にインストールされます。Unified Manager 9.5以降ではOracle Javaがサポートされません。

====
+
[NOTE]
====
アップグレードを開始する前に、Microsoft .NET 4.5.2以降がシステムにインストールされていることを確認してください。

====
* MySQL Community Editionは、Unified Managerのアップグレード時に自動的にアップグレードされます。システムにインストールされているMySQLのバージョンが8.0.34より前の場合は、Unified Managerのアップグレードプロセスによって8.0.34に自動的にアップグレードされます。MySQLの旧バージョンから8.0.34へのスタンドアロンアップグレードを実行しないでください。
* Windows管理者Privilegesが必要です。ユーザ名の先頭に感嘆符が付いていないことを確認してください!`". Installation of Unified Manager might fail if the user name of user running the installation begins with "`。
* NetAppサポートサイトにログインするための有効なクレデンシャルが必要です。
* アップグレードで問題が発生した場合にデータが失われないようにするために、Unified Managerマシンのバックアップを作成しておく必要があります。
* アップグレードを実行するための十分なディスクスペースが必要です。
+
インストールドライブには、データディレクトリのサイズよりも2.5GB大きくする必要があります。十分な空きスペースがないと、アップグレードが停止し、追加するスペースの量を示すエラーメッセージが表示されます。

* アップグレードの実行中、パフォーマンスデータの保持期間について、以前のデフォルト設定である13カ月のままにするか6カ月に変更するかを確認するプロンプトが表示されることがあります。確認すると、6カ月を経過した過去のパフォーマンスデータがパージされます。
* アップグレードする前に、 _<InstallDir>\JDK_and _MySQL Data Directory_ の開いているファイルまたはフォルダをすべて閉じてください。
* Windowsシステムにアクティブなウィルス対策ソフトウェアがインストールされていると、Unified Managerのアップグレードが失敗することがあります。Unified Managerをアップグレードする前に、システムのウィルススキャンソフトウェアをすべて無効にする必要があります。


アップグレードプロセスの実行中は、Unified Managerを使用できなくなります。実行中の処理がある場合は、Unified Managerをアップグレードする前に完了してください。

Unified ManagerをOnCommand Workflow Automationのインスタンスとペアにしていて、両方の製品で新しいバージョンのソフトウェアを使用できる場合は、2つの製品の接続を解除し、アップグレードの実行後に新しいWorkflow Automation接続をセットアップする必要があります。いずれかの製品のみをアップグレードする場合は、アップグレード後にWorkflow Automationにログインし、Unified Managerからデータを取得していることを確認します。

.手順
. NetAppサポートサイトにログインし、Unified Managerのダウンロードページに移動します。
+
https://mysupport.netapp.com/site/products/all/details/activeiq-unified-manager/downloads-tab["NetAppサポートサイト"^]です。

. 必要なUnified Managerのバージョンを選択し、エンドユーザライセンス契約（EULA）に同意します。
. Unified Manager WindowsインストールファイルをWindowsシステムのターゲットディレクトリにダウンロードします。
. Unified Managerインストーラの実行可能ファイル（.exe）を右クリックし、管理者として実行します。
+
Unified Managerから次のメッセージが表示されます。

+
[listing]
----
This setup will perform an upgrade of Unified Manager. Do you want to continue?
----
. [ はい ] をクリックし、 [ 次へ ] をクリックします。
. インストール時に設定した MySQL8 root パスワードを入力し、 * Next * をクリックします。
. サポートされているWebブラウザの新しいウィンドウでWeb UIを起動し、アップグレード後のバージョンのUnified Managerを使用するにはログインします。
. Windowsシステムにアクティブなアンチウイルスソフトウェアがインストールされている場合は、アップグレードの完了後、アンチウイルススキャンから次のパスを手動で除外してください。
+
** Unified Managerデータディレクトリ
** Unified Managerインストールディレクトリ
** MySQLデータディレクトリ




[NOTE]
====
Unified Managerのサイレントアップグレードを実行するには、次のコマンドを実行します。
`ActiveIQUnifiedManager-<version\>.exe /s /v"MYSQL_PASSWORD=<password> /qn /l*v <system_drive>:\install.log"`

====