---
permalink: install-windows/task_change_jboss_password_on_windows.html 
sidebar: sidebar 
keywords: change, jboss, password 
summary: インストール時に設定されたインスタンス固有のJBossパスワードをリセットできます。このセキュリティ機能によって Unified Manager のインストール設定が上書きされてしまいます。必要に応じて、パスワードをリセットすることもできます。この処理を実行すると、MySQLへのアクセスにJBossが使用するパスワードも変更されます。 
---
= JBossパスワードの変更
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
インストール時に設定されたインスタンス固有のJBossパスワードをリセットできます。このセキュリティ機能によって Unified Manager のインストール設定が上書きされてしまいます。必要に応じて、パスワードをリセットすることもできます。この処理を実行すると、MySQLへのアクセスにJBossが使用するパスワードも変更されます。

* 必要なもの *

* Unified Manager がインストールされている Windows システムに対する admin 権限が必要です。
* MySQLのrootユーザのパスワードが必要です。
* ディレクトリにあるNetAppが提供するスクリプトにアクセスできる必要があります。 `password.bat`
+
`C:\Program Files\NetApp\essentials\bin`です。



.手順
. Unified Managerホストマシンにadminユーザとしてログインします。
. Windowsの[サービス]コンソールを使用して、Unified Managerの次のサービスを停止します。
+
** NetApp Active IQ取得サービス（Ocie-au）
** NetApp Active IQ管理サーバサービス（Oncommandsvc）


. スクリプトを起動し `password.bat`て、パスワードの変更プロセスを開始します。
+
`C:\Program Files\NetApp\essentials\bin> password.bat resetJBossPassword`

. プロンプトが表示されたら、MySQL rootユーザのパスワードを入力します。
. プロンプトが表示されたら、新しいJBossユーザのパスワードを入力し、確認のためにもう一度入力します。
+
パスワードは8~16文字で指定し、数字、大文字、小文字、および次の特殊文字を少なくとも1文字使用する必要があります。

+
`+!@%^*-_+=[]:<>.?/~+`

. スクリプトが完了したら、 Windows サービスコンソールを使用して Unified Manager サービスを開始します。
+
** NetApp Active IQ管理サーバサービス（Oncommandsvc）
** NetApp Active IQ取得サービス（Ocie-au）


. すべてのサービスが開始されたら、 Unified Manager UI にログインできます。

