---
permalink: config/concept_audit_logging.html 
sidebar: sidebar 
keywords: audit, logging 
summary: 監査ログを使用すると、監査ログが侵害されていないかどうかを検出できます。ユーザが実行したすべてのアクティビティが監視され、監査ログに記録されます。監査は、 Active IQ Unified Manager のすべてのユーザーインターフェイスと公開されている API の機能に対して実行されます。 
---
= 監査ログ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
監査ログを使用すると、監査ログが侵害されていないかどうかを検出できます。ユーザが実行したすべてのアクティビティが監視され、監査ログに記録されます。監査は、 Active IQ Unified Manager のすべてのユーザーインターフェイスと公開されている API の機能に対して実行されます。

Active IQ Unified Manager で使用可能なすべての監査ログファイルを表示してアクセスするには、*監査ログ：ファイルビュー*を使用します。監査ログ：ファイルビュー内のファイルは、作成日に基づいて一覧表示されます。このビューには、インストールまたはアップグレードからシステムに存在するまでキャプチャされたすべての監査ログの情報が表示されます。Unified Managerで操作を実行すると、情報が更新されてログに記録されます。各ログファイルのステータスは、ログファイルの改ざんや削除を検出するためにアクティブに監視される「 File Integrity Status 」属性を使用して取得されます。監査ログがシステムで利用可能になると、次のいずれかの状態になります。

[cols="2*"]
|===
| 都道府県 | 製品説明 


 a| 
アクティブ
 a| 
ログが現在ログに記録されているファイル。



 a| 
標準
 a| 
非アクティブで、圧縮され、システムに保存されているファイル。



 a| 
改ざん
 a| 
ファイルを手動で編集したユーザーによって侵害されたファイル。



 a| 
手動削除
 a| 
許可されたユーザーによって削除されたファイル。



 a| 
rollover_delete
 a| 
ローリング設定ポリシーに基づいてローリングオフされたために削除されたファイル。



 a| 
予期しない削除
 a| 
不明な理由で削除されたファイル。

|===
[Audit Log]ページには、次のコマンドボタンがあります。

* 設定
* 削除
* ダウンロード


*delete* ボタンを使用すると、 Audit Logs ビューに表示されている監査ログを削除できます。監査ログを削除したり、必要に応じてファイルを削除する理由を指定したりできます。これは、あとで有効な削除を判断するのに役立ちます。[理由]列には、削除操作を実行したユーザーの名前とともに理由が一覧表示されます。

[NOTE]
====
ログファイルを削除するとシステムからファイルが削除されますが、DBテーブルのエントリは削除されません。

====
監査ログは、監査ログセクションの * download * ボタンを使用して Active IQ Unified Manager からダウンロードし、監査ログファイルをエクスポートできます。「正常」または「改ざん」とマークされたファイルは、圧縮された形式でダウンロードされ `.gzip`ます。

監査ログファイルは定期的にアーカイブされ、参照用にデータベースに保存されます。セキュリティと整合性を維持するために、アーカイブの前に監査ログがデジタル署名されます。

フルAutoSupportバンドルが生成されると、アーカイブ済みとアクティブの両方の監査ログファイルがサポートバンドルに含まれます。ただし、簡易サポートバンドルが生成された場合は、アクティブな監査ログのみが含まれます。アーカイブされた監査ログは含まれません。
