---
permalink: config/concept_policy_based_storage_management.html 
sidebar: sidebar 
keywords: slo, storage efficiency policy, storage workloads 
summary: ポリシーベースのストレージ管理オプションを使用すると、サービスレベル目標（ SLO ）に基づいてストレージを管理できます。このオプションはデフォルトで有効になっています。 
---
= ポリシーベースのストレージ管理の有効化
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ポリシーベースのストレージ管理 * オプションを使用すると、サービスレベル目標（ SLO ）に基づいてストレージを管理できます。このオプションはデフォルトで有効になっています。

この機能をアクティブ化すると、Active IQ Unified Managerインスタンスに追加されたONTAPクラスタでストレージワークロードをプロビジョニングし、割り当てられているパフォーマンスサービスレベルとストレージ効率化ポリシーに基づいてワークロードを管理できます。

この機能のアクティブ化または非アクティブ化は、 * General * > * Feature Settings * > * Policy-Based Storage Management * から選択できます。この機能をアクティブ化すると、次のページを操作および監視に使用できます。

* プロビジョニング（ストレージワークロードのプロビジョニング）
* * ポリシー * > * パフォーマンスサービスレベル *
* * ポリシー * > * ストレージ効率化 *
* クラスタセットアップページのパフォーマンスサービスレベルで管理されるワークロードの列
* ダッシュボード上のワークロードのパフォーマンスパネル *


各画面を使用して、パフォーマンスサービスレベルとストレージ効率化ポリシーを作成し、ストレージワークロードをプロビジョニングできます。また、割り当てられているパフォーマンスサービスレベルに準拠しているストレージワークロードと準拠していないストレージワークロードを監視することもできます。ワークロードのパフォーマンスとワークロードの IOPS パネルでは、データセンター内のクラスタの合計容量、使用可能容量、使用済み容量、およびパフォーマンス（ IOPS ）を、プロビジョニングされたストレージワークロードに基づいて評価することもできます。

この機能をアクティブ化したら、 Unified Manager REST API を実行して、 * メニューバー * > * ヘルプボタン * > * API ドキュメント * > * ストレージプロバイダ * カテゴリからこれらの機能の一部を実行できます。または、ホスト名またはIPアドレスと<hostname> APIページにアクセスするためのURLを+https：// rest /docs/api/+の形式で入力することもできます。

APIの詳細については、を参照してくださいlink:../api-automation/concept_get_started_with_um_apis.html["Active IQ Unified Manager REST APIでの作業の開始"]。
