---
permalink: config/concept_api_gateway.html 
sidebar: sidebar 
keywords: api gateway 
summary: API ゲートウェイ機能を使用すると、 ONTAP を個別にログインせずに、複数の Active IQ Unified Manager クラスタを一元的に管理できます。 
---
= APIゲートウェイの有効化
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
API ゲートウェイ機能を使用すると、 ONTAP を個別にログインせずに、複数の Active IQ Unified Manager クラスタを一元的に管理できます。

この機能は、 Unified Manager に最初にログインしたときに表示される設定ページから有効にできます。または、 * 一般 * > * 機能設定 * > * API ゲートウェイ * からこの機能を有効または無効にすることもできます。

Unified Manager REST API と ONTAP REST API は別のものであり、 Unified Manager REST API を使用して ONTAP REST API のすべての機能を利用できるわけではありません。ただし、 Unified Manager では提供されていない特定の機能を管理するために ONTAP API にアクセスする必要がある場合は、 API ゲートウェイ機能を有効にして ONTAP API を実行できます。ゲートウェイは、ヘッダーと本文の要求をONTAP APIと同じ形式で維持することで、API要求をトンネリングするプロキシとして機能します。Unified Manager のクレデンシャルを使用して特定の API を実行することで、個々のクラスタのクレデンシャルを渡すことなく ONTAP クラスタにアクセスして管理することができます。Unified Manager は単一の管理ポイントとして機能し、 Unified Manager インスタンスで管理される ONTAP クラスタ全体で API を実行できます。APIから返される応答は、ONTAPから直接実行された対応するONTAP REST APIから返される応答と同じです。

この機能を有効にしたあと、 * メニューバー * > * ヘルプボタン * > * API ドキュメント * > * ゲートウェイ * カテゴリから Unified Manager REST API を実行できます。または、ホスト名またはIPアドレスとURLをの形式で入力してREST APIページにアクセスすることもできます。 `https://<hostname>/docs/api/`

APIの詳細については、を参照してくださいlink:../api-automation/concept_get_started_with_um_apis.html["Active IQ Unified Manager REST APIでの作業の開始"]。
