---
permalink: config/reference_definitions_of_user_types.html 
sidebar: sidebar 
keywords: definitions, user types 
summary: ユーザタイプは、ユーザが保持するアカウントの種類を指定します。このタイプには、リモートユーザ、リモートグループ、ローカルユーザ、データベースユーザ、メンテナンスユーザが含まれます。それぞれのタイプには、管理者ロールを持つユーザによって独自のロールが割り当てられます。 
---
= ユーザタイプの定義
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ユーザタイプは、ユーザが保持するアカウントの種類を指定します。このタイプには、リモートユーザ、リモートグループ、ローカルユーザ、データベースユーザ、メンテナンスユーザが含まれます。それぞれのタイプには、管理者ロールを持つユーザによって独自のロールが割り当てられます。

Unified Manager には次のユーザタイプがあります。

* * メンテナンスユーザー *
+
Unified Manager の初期設定時に作成されます。メンテナンスユーザは、追加のユーザを作成してロールを割り当てます。メンテナンスコンソールにアクセスできる唯一のユーザでもあります。Unified Manager を Red Hat Enterprise Linux または CentOS システムにインストールしている場合、メンテナンスユーザのユーザ名は「 umadmin 」です。

* * ローカルユーザー *
+
Unified Manager UIにアクセスし、メンテナンスユーザまたはアプリケーション管理者ロールを持つユーザから割り当てられたロールに基づいて操作を実行します。

* * リモートグループ *
+
認証サーバに保存されているクレデンシャルを使用して Unified Manager UI にアクセスするユーザのグループです。このアカウントの名前は、認証サーバに保存されているグループの名前と一致する必要があります。リモートグループのユーザは、各自のユーザクレデンシャルを使用して Unified Manager UI にアクセスできます。リモートグループに割り当てられたロールに従って機能を実行できます。

* * リモートユーザー *
+
認証サーバに保存されているクレデンシャルを使用して Unified Manager UI にアクセスします。リモートユーザは、メンテナンスユーザまたはアプリケーション管理者ロールを持つユーザから割り当てられたロールに基づいて操作を実行します。

* * データベースユーザー *
+
Unified Manager データベースのデータへの読み取り専用アクセスが許可されます。 Unified Manager の Web インターフェイスやメンテナンスコンソールにはアクセスできず、 API 呼び出しも実行できません。


