---
permalink: config/reference_regenerate_https_certificate_dialog_box.html 
sidebar: sidebar 
keywords: regenerate, https certificate, dialog, box 
summary: '[HTTPS証明書の再生成]ダイアログボックスでは、セキュリティ情報をカスタマイズし、その情報を使用して新しいHTTPS証明書を生成できます。' 
---
= [HTTPS証明書の再生成]ダイアログボックス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
[HTTPS証明書の再生成]ダイアログボックスでは、セキュリティ情報をカスタマイズし、その情報を使用して新しいHTTPS証明書を生成できます。

このページには現在の証明書の情報が表示されます。

[ 現在の証明書属性を使用して再生成 ] および [ 現在の証明書属性を更新 ] を選択すると ' 現在の情報で証明書を再生成するか ' 新しい情報で証明書を生成できます

* * 共通名 *
+
必須。保護するFully Qualified Domain Name（FQDN；完全修飾ドメイン名）。

+
Unified Manager のハイアベイラビリティ構成では、仮想 IP アドレスを使用します。

* * 電子メール *
+
オプション。組織に連絡するEメールアドレス。通常は証明書管理者またはIT部門のEメールアドレスです。

* * 会社名 *
+
オプション。通常、会社の法人名です。

* * 部門 *
+
オプション。社内の部署の名前。

* * 都市 *
+
オプション。会社の所在地の市区町村。

* * 状態 *
+
オプション。会社の所在地の都道府県。

* * 国 *
+
オプション。会社の所在地の国。これは通常、国の2文字のISOコードです。

* * 別名 *
+
必須。既存のlocalhostまたはその他のネットワークアドレスに加えて、このサーバへのアクセスに使用できる追加の非プライマリドメイン名。各代行ユーザ名はカンマで区切ります。

+
証明書の代替名フィールドからローカル識別情報を削除する場合は ' ローカル識別情報を除外 (localhost など ) チェックボックスをオンにしますこのチェックボックスをオンにすると、 [ 代替名 ] フィールドに入力したフィールドのみが使用されます。空白のままにすると、生成される証明書に[別名]フィールドは表示されません。

* * キーサイズ（キーアルゴリズム： RSA ） *
+
キーアルゴリズムはRSAに設定されています。キーサイズは 2048 、 3072 、または 4096 のいずれかを選択できます。デフォルトのキーサイズは2048ビットに設定されています。

* * 有効期間 *
+
デフォルトの有効期間は397日です。以前のバージョンからアップグレードした場合は、以前の証明書の有効性が変更されていないことがあります。



詳細については、を参照してください link:../config/task_generate_an_https_security_certificate_ocf.html["HTTPS証明書の生成"]。
