---
permalink: config/reference_network_configuration_menu.html 
sidebar: sidebar 
keywords: network configuration menu 
summary: Network Configuration メニューでは、ネットワーク設定を管理できます。このメニューは、 Unified Manager ユーザインターフェイスを使用できない場合に使用してください。 
---
= [Network Configuration]メニュー
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Network Configuration メニューでは、ネットワーク設定を管理できます。このメニューは、 Unified Manager ユーザインターフェイスを使用できない場合に使用してください。

[NOTE]
====
Unified Manager が Red Hat Enterprise Linux 、 CentOS 、または Microsoft Windows にインストールされている場合は、このメニューを使用できません。

====
次のメニュー項目を使用できます。

* * IP アドレス設定 * を表示します
+
仮想アプライアンスの現在のネットワーク設定（IPアドレス、ネットワーク、ブロードキャストアドレス、ネットマスク、ゲートウェイ、DNSサーバなど）が表示されます。

* * IP アドレス設定の変更 *
+
仮想アプライアンスのネットワーク設定（IPアドレス、ネットマスク、ゲートウェイ、DNSサーバなど）を変更できます。メンテナンスコンソールを使用してネットワーク設定をDHCPから静的ネットワークに切り替えた場合、ホスト名を編集することはできません。変更を実行するには、 [* 変更をコミットする *] を選択する必要があります。

* * ドメイン名検索設定を表示 *
+
ホスト名の解決に使用されるドメイン名検索リストが表示されます。

* * ドメイン名検索設定の変更 *
+
ホスト名を解決するときに検索するドメイン名を変更できます。変更を実行するには、 [* 変更をコミットする *] を選択する必要があります。

* * スタティックルートを表示 *
+
現在の静的ネットワークルートを表示します。

* * スタティックルートの変更 *
+
静的ネットワークルートを追加または削除できます。変更を実行するには、 [* 変更をコミットする *] を選択する必要があります。

+
** * ルートを追加 *
+
静的ルートを追加できます。

** * ルートの削除 *
+
静的ルートを削除できます。

** * 戻る *
+
メインメニュー * に戻ります。

** * 終了 *
+
メンテナンスコンソールを終了します。



* * ネットワークインターフェイスを無効にします。 *
+
使用可能なネットワークインターフェイスを無効にします。使用可能なネットワークインターフェイスが1つしかない場合、無効にすることはできません。変更を実行するには、 [* 変更をコミットする *] を選択する必要があります。

* * ネットワーク・インターフェイスを有効にする *
+
使用できるネットワークインターフェイスを有効にします。変更を実行するには、 [* 変更をコミットする *] を選択する必要があります。

* * 変更を確定 *
+
仮想アプライアンスのネットワーク設定に加えた変更を適用します。変更を有効にするには、このオプションを選択する必要があります。そうしないと、変更は行われません。

* * ホストに Ping を実行します *
+
ターゲットホストにpingを実行して、IPアドレスの変更またはDNS設定を確認します。

* * デフォルト設定に復元 *
+
すべての設定を工場出荷時のデフォルトにリセットします。変更を実行するには、 [* 変更をコミットする *] を選択する必要があります。

* * 戻る *
+
メインメニュー * に戻ります。

* * 終了 *
+
メンテナンスコンソールを終了します。


