---
permalink: config/reference_remote_authentication_page.html 
sidebar: sidebar 
keywords: remote authentication, page 
summary: '[リモート認証]ページでは、Unified Managerが認証サーバと通信してUnified Manager Web UIにログインするリモートユーザを認証するように設定できます。' 
---
= [Remote Authentication]ページ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
[リモート認証]ページでは、Unified Managerが認証サーバと通信してUnified Manager Web UIにログインするリモートユーザを認証するように設定できます。

アプリケーション管理者またはストレージ管理者のロールが必要です。

[リモート認証を有効にする]チェックボックスをオンにすると、認証サーバを使用したリモート認証を有効にできます。

* * 認証サービス *
+
Active DirectoryやOpenLDAPなどのディレクトリサービスプロバイダでユーザを認証するように管理サーバを設定したり、独自の認証メカニズムを指定したりできます。認証サービスは、リモート認証を有効にした場合にのみ指定できます。

+
** * Active Directory *
+
*** 管理者名
+
認証サーバの管理者名を指定します。

*** パスワード
+
認証サーバにアクセスするためのパスワードを指定します。

*** ベース識別名
+
認証サーバ内のリモートユーザの場所を指定します。たとえば、認証サーバのドメイン名が + ou@domain.com + である場合、ベース識別名は * cn=ou 、 dc=domain 、 dc=com * です。

*** ネストされたグループの検索を無効化
+
ネストされたグループの検索を有効にするか無効にするかを指定します。デフォルトでは、このオプションは無効になっています。Active Directoryを使用する場合は、ネストされたグループのサポートを無効にすることで認証を高速化できます。

*** セキュアな接続を使用
+
認証サーバとの通信に使用する認証サービスを指定します。



** * OpenLDAP *
+
*** バインド識別名
+
認証サーバでリモートユーザを検索するためにベース識別名とともに使用されるバインド識別名を指定します。

*** バインドパスワード
+
認証サーバにアクセスするためのパスワードを指定します。

*** ベース識別名
+
認証サーバ内のリモートユーザの場所を指定します。たとえば、認証サーバのドメイン名が + ou@domain.com + である場合、ベース識別名は * cn=ou 、 dc=domain 、 dc=com * です。

*** セキュアな接続を使用
+
LDAP認証サーバとの通信にSecure LDAPを使用することを指定します。



** * その他 *
+
*** バインド識別名
+
設定した認証サーバでリモートユーザを検索するためにベース識別名とともに使用されるバインド識別名を指定します。

*** バインドパスワード
+
認証サーバにアクセスするためのパスワードを指定します。

*** ベース識別名
+
認証サーバ内のリモートユーザの場所を指定します。たとえば、認証サーバのドメイン名が + ou@domain.com + である場合、ベース識別名は * cn=ou 、 dc=domain 、 dc=com * です。

*** プロトコルバージョン
+
認証サーバでサポートされるLightweight Directory Access Protocol（LDAP）のバージョンを指定します。プロトコルバージョンを自動的に検出するか、バージョンを2または3に設定するかを指定できます。

*** ユーザ名属性
+
管理サーバによって認証されるユーザログイン名を含む認証サーバ内の属性の名前を指定します。

*** グループメンバーシップ属性
+
ユーザの認証サーバで指定された属性と値に基づいて、管理サーバグループメンバーシップをリモートユーザに割り当てる値を指定します。

*** UGID
+
リモートユーザが認証サーバのGroupOfUniqueNamesオブジェクトのメンバーとして含まれている場合、このオプションを使用すると、そのGroupOfUniqueNamesオブジェクト内の指定された属性に基づいて、管理サーバのグループメンバーシップをリモートユーザに割り当てることができます。

*** ネストされたグループの検索を無効化
+
ネストされたグループの検索を有効にするか無効にするかを指定します。デフォルトでは、このオプションは無効になっています。Active Directoryを使用する場合は、ネストされたグループのサポートを無効にすることで認証を高速化できます。

*** メンバー
+
認証サーバがグループの個々のメンバーに関する情報を格納するために使用する属性の名前を指定します。

*** ユーザオブジェクトクラス
+
リモート認証サーバ内のユーザのオブジェクトクラスを指定します。

*** グループオブジェクトクラス
+
リモート認証サーバ内のすべてのグループのオブジェクトクラスを指定します。

+

NOTE: _Member_,_User Object Class_,_GroupオブジェクトClass_attributesに入力する値は、Active Directory、OpenLDAP、およびLDAPの設定に追加する値と同じである必要があります。そうしないと、認証が失敗する可能性があります。

*** セキュアな接続を使用
+
認証サーバとの通信に使用する認証サービスを指定します。





+
[NOTE]
====
認証サービスを変更する場合は、既存の認証サーバをすべて削除し、新しい認証サーバを追加してください。

====




== [Authentication Servers]領域

[Authentication Servers]領域には、管理サーバがリモートユーザを検索して認証するために通信する認証サーバが表示されます。リモートのユーザまたはグループのクレデンシャルは、認証サーバで管理されます。

* * コマンドボタン *
+
認証サーバを追加、編集、削除できます。

+
** 追加
+
認証サーバを追加できます。

+
追加する認証サーバがハイアベイラビリティペア（同じデータベースを使用）の一部である場合は、パートナーの認証サーバも追加できます。これにより、いずれかの認証サーバに到達できない場合でも、管理サーバがパートナーと通信できるようになります。

** 編集
+
選択した認証サーバの設定を編集できます。

** 削除
+
選択した認証サーバを削除します。



* * 名前または IP アドレス *
+
管理サーバでユーザの認証に使用される認証サーバのホスト名またはIPアドレスが表示されます。

* * ポート *
+
認証サーバのポート番号が表示されます。

* * 認証のテスト *
+
このボタンでは、リモートのユーザまたはグループを認証することで認証サーバの設定を検証します。

+
テスト時にユーザ名のみを指定すると、管理サーバは認証サーバでリモートユーザを検索しますが、ユーザの認証は行いません。ユーザ名とパスワードの両方を指定すると、管理サーバはリモートユーザを検索して認証します。

+
リモート認証が無効になっている場合は、認証をテストできません。


