---
permalink: config/reference_system_configuration_menu.html 
sidebar: sidebar 
keywords: system, configuration, menu 
summary: '[System Configuration]メニューでは、サーバステータスの表示、仮想マシンのリブートとシャットダウンなど、さまざまなオプションを使用して仮想アプライアンスを管理できます。' 
---
= [System Configuration]メニュー
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
[System Configuration]メニューでは、サーバステータスの表示、仮想マシンのリブートとシャットダウンなど、さまざまなオプションを使用して仮想アプライアンスを管理できます。

[NOTE]
====
Unified Manager を Linux または Microsoft Windows システムにインストールしている場合、このメニューには「 Restore from a Unified Manager Backup 」オプションのみが表示されます。

====
次のメニューオプションを使用できます。

* * サーバーステータスを表示 *
+
現在のサーバステータスを表示します。ステータスオプションには、RunningとNot Runningがあります。

+
サーバが実行されていない場合は、テクニカルサポートへの連絡が必要になることがあります。

* * 仮想マシンの再起動 *
+
すべてのサービスを停止して仮想マシンをリブートします。リブート後、仮想マシンとサービスが再起動します。

* * 仮想マシンのシャットダウン *
+
仮想マシンをシャットダウンし、すべてのサービスを停止します。

+
このオプションは、仮想マシンコンソールからのみ選択できます。

* * < ログインユーザー > ユーザーパスワード * を変更します
+
現在ログインしているユーザ（メンテナンスユーザのみ）のパスワードを変更します。

* * データディスクのサイズを増やします。 *
+
仮想マシンのデータディスク（ディスク3）のサイズを拡張します。

* * スワップ・ディスク・サイズの増加 *
+
仮想マシンのスワップディスク（ディスク2）のサイズを拡張します。

* * タイムゾーンの変更 *
+
タイムゾーンを現在地に変更します。

* * NTP サーバーを変更 *
+
IPアドレスや完全修飾ドメイン名（FQDN）など、NTPサーバの設定を変更します。

* * NTP サービスの変更 *
+
サービスと `systemd-timesyncd`サービスを切り替えます `ntp`。

* * Unified Manager バックアップからのリストア *
+
以前にバックアップしたバージョンから Unified Manager データベースと設定をリストアします。

* * サーバー証明書をリセット *
+
サーバセキュリティ証明書をリセットします。

* * ホスト名を変更 *
+
仮想アプライアンスがインストールされているホストの名前を変更します。

* * 戻る *
+
[System Configuration]メニューを終了し、[Main Menu]に戻ります。

* * 終了 *
+
メンテナンスコンソールメニューを終了します。


