---
permalink: config/task_change_um_host_name_on_rhel_or_centos.html 
sidebar: sidebar 
keywords: change, unified manager, host name, linux systems 
summary: 必要に応じて、 Unified Manager をインストールした Red Hat Enterprise Linux または CentOS マシンのホスト名をあとから変更することができます。たとえば、タイプ、ワークグループ、監視対象のクラスタグループなどがわかるような名前に変更すると、 Linux マシンのリストで Unified Manager サーバを識別しやすくなります。 
---
= Linux システムで Unified Manager ホスト名を変更する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
必要に応じて、 Unified Manager をインストールした Red Hat Enterprise Linux または CentOS マシンのホスト名をあとから変更することができます。たとえば、タイプ、ワークグループ、監視対象のクラスタグループなどがわかるような名前に変更すると、 Linux マシンのリストで Unified Manager サーバを識別しやすくなります。

* 必要なもの *

Unified Manager がインストールされている Linux システムへの root ユーザアクセスが必要です。

Unified Manager Web UI には、ホスト名（またはホストの IP アドレス）を使用してアクセスできます。導入時にネットワークに静的IPアドレスを設定した場合は、ネットワークホストの名前を指定します。DHCPを使用してネットワークを設定した場合は、DNSサーバからホスト名を取得する必要があります。

ホスト名を変更した場合、 Unified Manager Web UI へのアクセスに新しいホスト名を使用するには、ホスト名の元の割り当て方法に関係なく、必ず新しいセキュリティ証明書を生成する必要があります。

ホスト名ではなくサーバのIPアドレスを使用してWeb UIにアクセスする場合は、ホスト名を変更しても新しい証明書を生成する必要はありません。ただし、証明書のホスト名が実際のホスト名と同じになるように証明書を更新することを推奨します。新しい証明書は、Linuxマシンを再起動するまで有効になりません。

Unified Managerでホスト名を変更した場合は、OnCommand Workflow Automation（WFA）でホスト名を手動で更新する必要があります。ホスト名はWFAで自動的に更新されません。

.手順
. 変更する Unified Manager システムに root ユーザとしてログインします。
. 次のコマンドを入力して、Unified Managerソフトウェアと関連するMySQLソフトウェアを停止します。
+
`systemctl stop ocieau ocie mysqld`

. Linuxのコマンドを使用してホスト名を変更し `hostnamectl`ます。
+
`hostnamectl set-hostname new_FQDN`

+
`hostnamectl set-hostname nuhost.corp.widget.com`

. サーバのHTTPS証明書を再生成します。
+
`/opt/netapp/essentials/bin/cert.sh create`

. ネットワークサービスを再起動します。
+
`systemctl restart NetworkManager.service`

. サービスが再起動されたら、新しいホスト名でpingを実行できるかどうかを確認します。
+
`ping new_hostname`

+
`ping nuhost`

+
このコマンドは、元のホスト名に対して以前に設定したIPアドレスと同じIPアドレスを返す必要があります。

. ホスト名を変更して確認したら、次のコマンドを入力してUnified Managerを再起動します。
+
`systemctl start mysqld ocie ocieau`


