---
permalink: config/task_generate_an_https_security_certificate_ocf.html 
sidebar: sidebar 
keywords: generate, https, security, certificate 
summary: Active IQ Unified Managerを初めてインストールすると、デフォルトのHTTPS証明書がインストールされます。新しいHTTPSセキュリティ証明書を生成して、既存の証明書と置き換えることができます。 
---
= HTTPSセキュリティ証明書の生成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Managerを初めてインストールすると、デフォルトのHTTPS証明書がインストールされます。新しいHTTPSセキュリティ証明書を生成して、既存の証明書と置き換えることができます。

* 必要なもの *

アプリケーション管理者のロールが必要です。

証明書を再生成する理由は複数あります。たとえば、識別名（DN）の値をより適切に設定する場合、キーサイズを大きくする場合、有効期限を長くする場合、現在の証明書の有効期限が切れている場合などです。

Unified Manager Web UIにアクセスできない場合は、メンテナンスコンソールを使用して同じ値でHTTPS証明書を再生成できます。証明書を再生成する際に、キーのサイズと有効期間を定義できます。メンテナンスコンソールのオプションを使用すると、 `Reset Server Certificate`397日間有効な新しいHTTPS証明書が作成されます。この証明書には、サイズが2048ビットのRSAキーがあります。

.手順
. 左側のナビゲーションペインで、 * General * > * HTTPS Certificate * をクリックします。
. [* HTTPS 証明書の再生成 * ] をクリックします。
+
HTTPS 証明書の再生成ダイアログボックスが表示されます。

. 証明書の生成方法に応じて、次のいずれかのオプションを選択します。
+
[cols="2*"]
|===
| 状況 | 操作 


 a| 
現在の値で証明書を再生成する
 a| 
[ 現在の証明書属性を使用して再生成（ Regenerate using current Certificate Attributes ） ] オプションをクリックし



 a| 
別の値を使用して証明書を生成する
 a| 
[ 現在の証明書属性を更新する *] オプションをクリックします。

新しい値を入力しない場合は、 [ 共通名 ] フィールドと [ 代替名 ] フィールドに既存の証明書の値が使用されます。「共通名」は、ホストの FQDN に設定する必要があります。その他のフィールドには値は必要ありませんが、電子メール、会社、部署、 証明書に値を入力する場合は、 [ 市区町村 ] 、 [ 都道府県 ] 、および [ 国 ] を選択します。使用可能なキー・サイズ（キー・アルゴリズムは「 RSA 」）と有効期間から選択することもできます。

[NOTE]
====
** キーサイズに指定できる値は `2048`、 `3072`および `4096`です。
** 有効期間は最低1日から最高36500日です。
+
36500日の有効期間が許可されていますが、397日または13カ月以内の有効期間を使用することをお勧めします。397日を超える有効期間を選択し、この証明書のCSRをエクスポートして既知のCAによる署名を取得する場合、CAから返される署名済み証明書の有効期間は397日に短縮されます。

** 証明書の[Alternative Names]フィールドからローカルの識別情報を削除する場合は、[Exclude local identifying information (e.g. localhost)]チェックボックスをオンにします。このチェックボックスをオンにすると、 [ 代替名 ] フィールドに入力したフィールドのみが使用されます。空白のままにすると、生成される証明書に[別名]フィールドは表示されません。


====
|===
. [ はい ] をクリックして証明書を再生成します。
. 新しい証明書を有効にするために Unified Manager サーバを再起動します。
. HTTPS証明書を表示して新しい証明書の情報を確認します。

