---
permalink: config/task_configure_event_notification_settings.html 
sidebar: sidebar 
keywords: configure, event, notification, settings 
summary: Unified Manager では、イベントが生成されたときやユーザに割り当てられたときにアラート通知を送信するように設定することができます。アラートの送信に使用するSMTPサーバを設定したり、さまざまな通知メカニズムを設定したりできます。たとえば、アラート通知をEメールやSNMPトラップとして送信できます。 
---
= イベント通知の設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager では、イベントが生成されたときやユーザに割り当てられたときにアラート通知を送信するように設定することができます。アラートの送信に使用するSMTPサーバを設定したり、さまざまな通知メカニズムを設定したりできます。たとえば、アラート通知をEメールやSNMPトラップとして送信できます。

* 必要なもの *

次の情報が必要です。

* アラート通知の送信元Eメールアドレス
+
メール・アドレスは ' 送信されたアラート通知の送信元フィールドに表示されます何らかの理由でメールを配信できない場合、このメールアドレスは配信できないメールの受信者としても使用されます。

* SMTPサーバのホスト名、およびサーバにアクセスするためのユーザ名とパスワード
* SNMPトラップとSNMPバージョン、アウトバウンドトラップポート、コミュニティ、およびその他の必要なSNMP設定値を受信するトラップ送信先ホストのホスト名またはIPアドレス
+
トラップ送信先を複数指定するには、各ホストをカンマで区切ります。この場合、他のすべてのSNMP設定（バージョンやアウトバウンドトラップポートなど）がリスト内のすべてのホストで同じである必要があります。



アプリケーション管理者またはストレージ管理者のロールが必要です。

.手順
. 左側のナビゲーションペインで、 * 一般 * > * 通知 * をクリックします。
. [Notifications]ページで、適切な設定を行います。
+
* 注： *

+
** 送信元アドレスに「 + ActiveIQUnifiedManager@localhost.com + 」というアドレスが事前に入力されている場合は、実際の作業用 E メールアドレスに変更して、すべての E メール通知が正常に配信されるようにしてください。
** SMTPサーバのホスト名を解決できない場合は、ホスト名の代わりにSMTPサーバのIPアドレス（IPv4またはIPv6）を指定できます。


. [ 保存（ Save ） ] をクリックします。
. [*Use STARTTLS *]または[*Use SSL *]オプションを選択した場合は、[*Save]ボタンをクリックすると証明書ページが表示されます。証明書の詳細を確認し、証明書を受け入れて通知設定を保存します。
+
証明書の詳細を表示するには、[証明書の詳細を表示*]ボタンをクリックします。既存の証明書の有効期限が切れた場合は、「* STARTTLSを使用」または「* SSLを使用」チェックボックスをオフにし、通知設定を保存してから「* STARTTLSを使用*」または「SSLを使用*」チェックボックスを再度オンにして新しい証明書を表示します。


