---
permalink: config/task_disable_saml_authentication_um.html 
sidebar: sidebar 
keywords: disable, saml authentication 
summary: Unified Manager Web UI にログインするリモートユーザのセキュアなアイデンティティプロバイダ（ IdP ）による認証を中止する場合は、 SAML 認証を無効にします。SAML認証が無効な場合は、Active DirectoryやLDAPなどの設定済みのディレクトリサービスプロバイダがサインオン認証を実行します。 
---
= SAMLニンシヨウノムコウカ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager Web UI にログインするリモートユーザのセキュアなアイデンティティプロバイダ（ IdP ）による認証を中止する場合は、 SAML 認証を無効にします。SAML認証が無効な場合は、Active DirectoryやLDAPなどの設定済みのディレクトリサービスプロバイダがサインオン認証を実行します。

SAML認証を無効にすると、設定されているリモートユーザに加えて、ローカルユーザとメンテナンスユーザもグラフィカルユーザインターフェイスにアクセスできるようになります。

グラフィカルユーザインターフェイスにアクセスできない場合は、Unified Managerメンテナンスコンソールを使用してSAML認証を無効にすることもできます。

[NOTE]
====
SAML 認証を無効にしたあと、 Unified Manager が自動的に再起動されます。

====
.手順
. 左側のナビゲーションペインで、 * General * > * SAML Authentication * をクリックします。
. [SAML 認証を有効にする *] チェックボックスをオフにします。
. [ 保存（ Save ） ] をクリックします。
+
設定を完了して Unified Manager を再起動するかどうかの確認を求めるメッセージボックスが表示されます。

. [ 確認してログアウト * ] をクリックすると、 Unified Manager が再起動します。


リモートユーザが Unified Manager のグラフィカルインターフェイスにアクセスする際にクレデンシャルを入力するページが、次回から IdP のログインページではなく Unified Manager のログインページに変わります。

IdP にアクセスし、 Unified Manager サーバの URI とメタデータを削除します。
