---
permalink: config/task_add_space_to_data_directory_of_um_linux_host.html 
sidebar: sidebar 
keywords: add, space, data directory, linux, host 
summary: 'Linuxホストの最初のセットアップ時にUnified Managerをサポートするための十分なディスクスペースをに割り当てていなかった場合は `/opt/netapp/data`、Unified Managerのインストール後にディレクトリのディスクスペースを増やしてディスクスペースを追加できます。 `/opt/netapp/data`' 
---
= Linuxホストのデータディレクトリへのスペースの追加
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Linuxホストの最初のセットアップ時にUnified Managerをサポートするための十分なディスクスペースをに割り当てていなかった場合は `/opt/netapp/data`、Unified Managerのインストール後にディレクトリのディスクスペースを増やしてディスクスペースを追加できます。 `/opt/netapp/data`

* 必要なもの *

Unified Manager がインストールされている Red Hat Enterprise Linux マシンまたは CentOS Linux マシンへの root ユーザアクセスが必要です。

データディレクトリのサイズを拡張する前に Unified Manager データベースをバックアップすることを推奨します。

.手順
. ディスクスペースを追加するLinuxマシンにrootユーザとしてログインします。
. Unified Manager サービスと関連する MySQL ソフトウェアを次の順序で停止します。
+
`systemctl stop ocieau ocie mysqld`

. 現在のディレクトリのデータを格納するのに十分なディスクスペースがある一時バックアップフォルダ（など）を `/opt/netapp/data`作成します `/backup-data`。
. 既存のディレクトリの内容と権限の設定をバックアップデータディレクトリにコピーし `/opt/netapp/data`ます。
+
`cp -arp /opt/netapp/data/* /backup-data`

. SE Linuxが有効な場合：
+
.. 既存のフォルダのフォルダのSE Linuxタイプを取得し `/opt/netapp/data`ます。
+
`se_type= ls -Z /opt/netapp/data | awk '{print $4}' | awk -F: '{print $3}' | head -1`

+
次のような情報が返されます。

+
[listing]
----
echo $se_type
mysqld_db_t
----
.. chconコマンドを実行して、バックアップディレクトリのSE Linuxタイプを設定します。
+
`chcon -R --type=mysqld_db_t /backup-data`



. ディレクトリの内容を削除し `/opt/netapp/data`ます。
+
.. `cd /opt/netapp/data`
.. `rm -rf *`


. LVMコマンドを使用するかディスクを追加して、ディレクトリのサイズを150GB以上に拡張します `/opt/netapp/data`。
+
[NOTE]
====
をディスクから作成した場合は `/opt/netapp/data`、をNFS共有またはCIFS共有としてマウントしないで `/opt/netapp/data`ください。この場合、ディスクスペースを拡張しようとすると、や `extend`などの一部のLVMコマンドが想定どおりに動作しない可能性があるためです `resize`。

====
. ディレクトリの所有者（mysql）とグループ（root）が変更されていないことを確認し `/opt/netapp/data`ます。
+
`ls -ltr /opt/netapp/ | grep data`

+
次のような情報が返されます。

+
[listing]
----
drwxr-xr-x.  17 mysql root  4096 Aug 28 13:08 data
----
. SE Linuxが有効になっている場合は、ディレクトリのコンテキストが引き続きmysqld_db_tに設定されていることを確認し `/opt/netapp/data`ます。
+
.. `touch /opt/netapp/data/abc`
.. `ls -Z /opt/netapp/data/abc`
+
次のような情報が返されます。

+
[listing]
----
-rw-r--r--. root root unconfined_u:object_r:mysqld_db_t:s0 /opt/netapp/data/abc
----


. この無関係なファイルが将来データベースエラーの原因にならないように、ファイルabcを削除します。
. backup-dataから展開したディレクトリに内容をコピーし `/opt/netapp/data`ます。
+
`cp -arp /backup-data/* /opt/netapp/data/`

. SE Linuxが有効になっている場合は、次のコマンドを実行します。
+
`chcon -R --type=mysqld_db_t /opt/netapp/data`

. MySQLサービスを開始します。
+
`systemctl start mysqld`

. MySQLサービスが開始されたら、ocieサービスとocieauサービスを次の順序で開始します。
+
`systemctl start ocie ocieau`

. すべてのサービスが開始されたら、バックアップフォルダを削除し `/backup-data`ます。
+
`rm -rf /backup-data`


