---
permalink: install-linux/task_change_jboss_password.html 
sidebar: sidebar 
keywords: change, jboss password 
summary: インストール時に設定されたインスタンス固有のJBossパスワードをリセットできます。このセキュリティ機能によって Unified Manager のインストール設定が上書きされてしまいます。必要に応じて、パスワードをリセットすることもできます。この処理を実行すると、MySQLへのアクセスにJBossが使用するパスワードも変更されます。 
---
= JBossパスワードの変更
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
インストール時に設定されたインスタンス固有のJBossパスワードをリセットできます。このセキュリティ機能によって Unified Manager のインストール設定が上書きされてしまいます。必要に応じて、パスワードをリセットすることもできます。この処理を実行すると、MySQLへのアクセスにJBossが使用するパスワードも変更されます。

* Unified Manager がインストールされている Red Hat Enterprise Linux または CentOS のシステムへの root ユーザアクセスが必要です。
* ディレクトリにあるNetAppが提供するスクリプト `/opt/netapp/essentials/bin`にアクセスできる必要があります `password.sh`。


.手順
. システムにrootユーザとしてログインします。
. 次のコマンドを記載された順序で入力して、 Unified Manager サービスを停止します。
+
`systemctl stop ocieau`

+
`systemctl stop ocie`

+
関連付けられているMySQLソフトウェアは停止しないでください。

. 次のコマンドを入力して、パスワードの変更プロセスを開始します。
+
`/opt/netapp/essentials/bin/password.sh resetJBossPassword`

. プロンプトが表示されたら、新しいJBossパスワードを入力し、確認のためにもう一度入力します。
+
パスワードは8~16文字で指定し、数字、大文字、小文字、および次の特殊文字を少なくとも1文字使用する必要があります。

+
`+!@%^*-_+=[]:<>.?/~+`

. スクリプトが完了したら、次のコマンドを記載された順序で入力して、 Unified Manager サービスを開始します。
+
`systemctl start ocie`

+
`systemctl start ocieau`

. すべてのサービスが開始されたら、 Unified Manager UI にログインできます。

