---
permalink: install-linux/task_manually_configure_mysql_repository.html 
sidebar: sidebar 
keywords: manually configure mysql repository, mysql key, keys update 
summary: Unified Manager をインストールするシステムが MySQL Community Edition リポジトリにアクセスできない場合、インストールが成功するためにはリポジトリを手動でダウンロードして設定する必要があります。 
---
= MySQLリポジトリの手動設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager をインストールするシステムが MySQL Community Edition リポジトリにアクセスできない場合、インストールが成功するためにはリポジトリを手動でダウンロードして設定する必要があります。

MySQLリポジトリは、システムにインストールする必要があるMySQLソフトウェアへのアクセスを提供します。

[NOTE]
====
システムがインターネットに接続されていない場合、このタスクは失敗することがあります。Unified Managerをインストールするシステムがインターネットにアクセスできない場合は、MySQLのドキュメントを参照してください。

====
.手順
. インストールに対応するMySQLリポジトリをダウンロードします。Red Hat Enterprise Linux 7の場合は、次のサイトからダウンロードします。
+
`+wget http://repo.mysql.com/yum/mysql-8.0-community/el/7/x86_64/mysql80-community-release-el7-3.noarch.rpm+`

+
バージョン8の場合は、次のサイトからダウンロードします。

+
`+wget http://repo.mysql.com/yum/mysql-8.0-community/el/8/x86_64/mysql80-community-release-el8-1.noarch.rpm+`

. MySQLリポジトリを設定します。
+
`yum install mysql80-community-release-<version>.noarch.rpm`



Red Hat Enterprise Linux 8システムで、AppStreamリポジトリが提供するjava-11-openjdk、p7zip、およびその他のソフトウェアパッケージを含む内部リポジトリがある場合は、AppStreamリポジトリを無効にしてMySQL Community Serverをインストールする必要があります。次のコマンドを実行します。

[listing]
----
# sudo yum --disablerepo=rhel-8-for-x86_64-appstream-rpms install  mysql-community-server
----
キーの欠落またはキーの不一致に関するエラーが表示され、インストールが失敗した場合は、次の手順を実行してください。

* 接続されているシステムで、次のコマンドを実行して、更新されたMySQLキーをインポートします。


[listing]
----
rpm --import https://repo.mysql.com/RPM-GPG-KEY-mysql-<xxxx>

for example:

rpm --import https://repo.mysql.com/RPM-GPG-KEY-mysql-2022
----
* インターネットに接続されていないシステムでは、MySQLリポジトリファイルを更新し、をマークして `gpgcheck=0`無効にします `gpgcheck`。

