---
permalink: events/concept_what_event_management_system_events_are.html 
sidebar: sidebar 
keywords: event management, system, 
summary: イベント管理システム（EMS）は、ONTAPカーネルのさまざまな部分からイベントデータを収集し、イベント転送メカニズムを提供します。Unified Manager では、このような ONTAP イベントを EMS イベントとして報告できます。一元的な監視と管理により、重大なEMSイベントとそれらのEMSイベントに基づくアラート通知を簡単に設定できます。 
---
= イベント管理システムイベントとは
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
イベント管理システム（EMS）は、ONTAPカーネルのさまざまな部分からイベントデータを収集し、イベント転送メカニズムを提供します。Unified Manager では、このような ONTAP イベントを EMS イベントとして報告できます。一元的な監視と管理により、重大なEMSイベントとそれらのEMSイベントに基づくアラート通知を簡単に設定できます。

Unified Manager にクラスタを追加すると、 Unified Manager のアドレスが通知の送信先としてクラスタに追加されます。クラスタでイベントが発生するとすぐにEMSイベントが報告されます。

Unified Manager で EMS イベントを受け取る方法は 2 つあります。

* 一定数の重要なEMSイベントが自動的に報告されます。
* EMSイベントを個別に受け取るようにサブスクライブすることができます。


Unified Manager で生成される EMS イベントの報告方法は、イベントが生成された方法によって異なります。

|===
| 機能 | 自動の EMS メッセージ | 登録した EMS メッセージ 


 a| 
使用可能なEMSイベント
 a| 
一部のEMSイベント
 a| 
すべてのEMSイベント



 a| 
EMSメッセージがトリガーされたときの名前
 a| 
Unified Manager のイベント名（ EMS のイベント名から変換）
 a| 
固有ではない（「Error EMS Received」の形式）。詳細なメッセージには、実際のEMSイベントのドット表記形式が記載されています。



 a| 
受信したメッセージ
 a| 
クラスタが検出されるとすぐに
 a| 
必要な各 EMS イベントが Unified Manager に追加されたあと、 15 分間隔の次回のポーリング時



 a| 
イベントのライフサイクル
 a| 
Unified Manager の他のイベントと同じで、「新規」、「確認済み」、「解決済み」、「廃止」の状態があります
 a| 
EMSイベントはクラスタの更新後（イベントが作成されてから15分後）に廃止になります。



 a| 
Unified Manager が停止しているときのイベントのキャプチャ
 a| 
システムの起動時に各クラスタと通信して不足しているイベントを取得
 a| 
いいえ



 a| 
イベントの詳細
 a| 
推奨される対処方法をONTAPから直接インポートして、一貫した解決策を提供
 a| 
[ イベントの詳細 ] ページで修正アクションを使用できません

|===
[NOTE]
====
新しい自動EMSイベントの一部は、以前のイベントが解決されたことを示す情報イベントです。たとえば、「FlexGroupコンスティチュエントのスペースステータスがすべて正常」という情報イベントは、「FlexGroupコンスティチュエントのスペースに問題があります」エラーイベントが解決されたことを示しています。情報イベントは、他の重大度タイプのイベントと同じライフサイクルを使用して管理することはできませんが、同じボリュームが別の「スペースの問題」エラーイベントを受信した場合、イベントは自動的に廃止されます。

====