---
permalink: events/concept_guidelines_for_adding_alerts.html 
sidebar: sidebar 
keywords: guidelines, adding, alerts 
summary: アラートは、リソース（クラスタ、ノード、アグリゲート、ボリュームなど）と特定の重大度タイプのイベントに基づいて追加できます。ベストプラクティスとして、重要なオブジェクトが属するクラスタを追加したあと、それらのすべてのオブジェクトについてのアラートを追加することを推奨します。 
---
= アラートの追加に関するガイドライン
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アラートは、リソース（クラスタ、ノード、アグリゲート、ボリュームなど）と特定の重大度タイプのイベントに基づいて追加できます。ベストプラクティスとして、重要なオブジェクトが属するクラスタを追加したあと、それらのすべてのオブジェクトについてのアラートを追加することを推奨します。

アラートを作成する際は、システムを効率的に管理できるように次のガイドラインと考慮事項を参考にしてください。

* アラートの説明
+
アラートを効果的に追跡できるように、アラートの説明を指定する必要があります。

* リソース
+
アラートが必要な物理リソースまたは論理リソースを決める必要があります。必要に応じて、リソースを含めたり除外したりできます。たとえば、アラートを設定してアグリゲートを詳細に監視する場合は、リソースのリストから必要なアグリゲートを選択する必要があります。

+
リソースのカテゴリ（*+*など）を選択すると、<<All User or Group Quotas>>そのカテゴリ内のすべてのオブジェクトに関するアラートが送信されます。

+
[NOTE]
====
リソースとしてクラスタを選択しても、そのクラスタ内のストレージオブジェクトは自動的には選択されません。たとえば、すべてのクラスタのすべての重大イベントに対するアラートを作成すると、クラスタの重大イベントに対するアラートのみが送信されます。ノードやアグリゲートなどの重大イベントに対するアラートは受信しません。

====
* イベントの重大度
+
指定した重大度タイプ（Critical、Error、Warning）のイベントでアラートをトリガーするかどうかを決め、トリガーする場合はどの重大度タイプをトリガーするかを決定する必要があります。

* 選択したイベント
+
生成されるイベントのタイプに基づいてアラートを追加する場合は、アラートが必要なイベントを決める必要があります。

+
イベントの重大度を選択しても、個 々 のイベントを選択しない場合（[Selected Events]列を空のままにした場合）、カテゴリ内のすべてのイベントに関するアラートが表示されます。

* アクション
+
通知を受信するユーザのユーザ名とEメールアドレスを指定する必要があります。通知モードとしてSNMPトラップを指定することもできます。アラートが生成されたときに実行されるように、アラートにスクリプトを関連付けることができます。

* 通知の頻度
+
指定した期間、受信者に繰り返し通知を送信するようにアラートを設定できます。アラートに対してイベント通知をアクティブにする時間を決める必要があります。イベントが確認されるまでイベント通知を再送する場合は、通知を再送する頻度を決める必要があります。

* スクリプトの実行
+
アラートにスクリプトを関連付けることができます。スクリプトはアラートが生成されると実行されます。


