---
permalink: events/concept_what_active_iq_platform_events_are.html 
sidebar: sidebar 
keywords: active iq, platform, events 
summary: Unified Managerでは、Active IQプラットフォームで検出されたイベントを表示できます。これらのイベントは、Unified Managerで監視されているすべてのストレージシステムから生成されたAutoSupportメッセージに対して一連のルールを実行することで作成されます。 
---
= Active IQプラットフォームイベントとは
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Managerでは、Active IQプラットフォームで検出されたイベントを表示できます。これらのイベントは、Unified Managerで監視されているすべてのストレージシステムから生成されたAutoSupportメッセージに対して一連のルールを実行することで作成されます。

詳細については、を参照してください link:../events/concept_how_active_iq_platform_events_are_generated.html["Active IQプラットフォームイベントの生成方法"]。

Unified Managerは新しいルールファイルの有無を自動的にチェックし、ある場合にのみ新しいファイルをダウンロードします。外部ネットワークへのアクセスがないサイトでは、 * Storage Management * > * Event Setup * > * Upload Rules * からルールを手動でアップロードする必要があります。

これらのActive IQイベントは既存のUnified Managerイベントと重複せず、システム構成、ケーブル接続、ベストプラクティス、可用性の問題に関するインシデントやリスクが特定されます。

プラットフォームイベントのイネーブル化の詳細については、を参照してくださいlink:../config/concept_active_iq_platform_events.html["Active IQポータルイベントの有効化"]。ルールファイルのアップロードの詳細については、を参照してくださいlink:../events/task_upload_new_active_iq_rules_file.html["新しいActive IQルールファイルのアップロード"]。

NetApp Active IQ は、ネットアップのハイブリッドクラウド全体にわたってストレージシステムの運用を最適化するのに役立つ、予測分析とプロアクティブなサポートを提供するクラウドベースのサービスです。詳細については、を参照してください https://www.netapp.com/us/products/data-infrastructure-management/active-iq.aspx["NetApp Active IQ"] 。
