---
permalink: events/concept_event_state_definitions.html 
sidebar: sidebar 
keywords: event, state, definitions 
summary: イベントの状態を確認すると、対処が必要かどうかを特定するのに役立ちます。「新規」、「確認済み」、「解決済み」、「廃止」のいずれかです。「新規」と「確認済み」のイベントの両方がアクティブなイベントとみなされます。 
---
= イベントの状態の定義
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
イベントの状態を確認すると、対処が必要かどうかを特定するのに役立ちます。「新規」、「確認済み」、「解決済み」、「廃止」のいずれかです。「新規」と「確認済み」のイベントの両方がアクティブなイベントとみなされます。

イベントの状態は次のとおりです。

* * 新 *
+
新しいイベントの状態。

* * 承認済み *
+
イベントを確認したときの状態。

* * 解決済み *
+
イベントが解決済みとマークされたときの状態。

* * 廃止 *
+
イベントが自動的に修正されたとき、またはイベントの原因が無効になったときの状態。

+
[NOTE]
====
廃止状態のイベントを確認または解決することはできません。

====




== イベントのさまざまな状態の例

次の例は、手動および自動でイベントの状態が変化する様子を示しています。

「クラスタに到達できません」イベントがトリガーされると、イベントの状態は「新規」になります。イベントに確認応答すると、イベントの状態が「確認済み」に変わります。適切に対処したら、イベントを解決済みとしてマークする必要があります。その後、イベントの状態が「解決済み」に変わります。

停電が原因で「クラスタに到達できません」イベントが生成された場合は、電源が復旧すると、管理者の介入なしでクラスタが動作を開始します。そのため、「クラスタに到達できません」イベントは有効でなくなり、イベントの状態が次回の監視サイクルで「廃止」に変わります。

Unified Managerは、イベントの状態が「廃止」または「解決済み」になるとアラートを送信します。アラートのEメールの件名と内容には、イベントの状態に関する情報が表示されます。SNMPトラップには、イベントの状態に関する情報も含まれます。
