---
permalink: events/reference_dynamic_performance_event_chart_details.html 
sidebar: sidebar 
keywords: dynamic, performance, event, chart, details 
summary: '動的なパフォーマンスイベントについては、[イベントの詳細]ページの[システム診断]セクションに、レイテンシが高いワークロードまたは競合状態のクラスタコンポーネントの使用量が多い上位のワークロードが表示されます。パフォーマンス統計は、パフォーマンスイベントが検出されてからイベントが最後に分析されるまでの時間に基づいています。このグラフには、競合状態にあるクラスタコンポーネントの過去のパフォーマンス統計も表示されます。' 
---
= 動的なパフォーマンスイベントグラフの詳細
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
動的なパフォーマンスイベントについては、[イベントの詳細]ページの[システム診断]セクションに、レイテンシが高いワークロードまたは競合状態のクラスタコンポーネントの使用量が多い上位のワークロードが表示されます。

パフォーマンス統計は、パフォーマンスイベントが検出されてからイベントが最後に分析されるまでの時間に基づいています。このグラフには、競合状態にあるクラスタコンポーネントの過去のパフォーマンス統計も表示されます。

たとえば、コンポーネントの利用率が高いワークロードを特定して、利用率が低いコンポーネントに移動するワークロードを特定できます。ワークロードを移動すると、現在のコンポーネントでの作業量が減り、コンポーネントの競合が解消される可能性があります。このセクションの上部には、イベントが検出されて最後に分析された日時の範囲が表示されます。アクティブなイベント（新規または確認済みのイベント）の場合は、最後に分析された時刻が更新されます。

レイテンシとアクティビティのグラフにカーソルを合わせると、上位のワークロードの名前が表示されます。グラフの右側にあるワークロードのタイプメニューをクリックすると、イベントでのワークロードのロールに基づいてワークロードをソートできます。これには、 _Shark 、 _Bully 、 _Victim の各ワークロードのレイテンシと競合しているクラスタコンポーネントでの使用状況の詳細が表示されます。実際の値と想定値を比較して、ワークロードがレイテンシまたは使用量の想定範囲を外れたタイミングを確認できます。詳細については、を参照してください link:..//performance-checker/concept_types_of_workloads_monitored_by_unified_manager.html["Unified Managerで監視されるワークロードのタイプ"]。

[NOTE]
====
レイテンシのピーク偏差でソートする場合は、システム定義のワークロードがテーブルに表示されません。これは、レイテンシがユーザ定義のワークロードにのみ適用されるためです。レイテンシの値が小さいワークロードはこのテーブルに表示されません。

====
動的なパフォーマンスしきい値の詳細については、を参照してくださいlink:../performance-checker/concept_analyze_events_from_dynamic_performance_thresholds.html["動的なパフォーマンスしきい値で発生したイベントの分析"]。

Unified Managerでワークロードをランク付けしてソート順序を決定する方法については、を参照してくださいlink:../performance-checker/concept_how_um_determines_performance_impact_for_incident.html["Unified Managerがイベントによるパフォーマンスへの影響を判定する仕組み"]。

グラフのデータには、イベントが最後に分析される24時間前のパフォーマンス統計が表示されます。各ワークロードの実際の値と想定値は、ワークロードがイベントに関連した時間に基づいています。たとえば、イベント検出後にワークロードがイベントに関連するようになった場合、パフォーマンス統計がイベント検出時の値と一致しないことがあります。デフォルトでは、レイテンシのピーク（最大）偏差でワークロードがソートされます。

[NOTE]
====
Unified Manager では 5 分ごとのパフォーマンスとイベントの履歴データが最大 30 日分保持されるため、 30 日前より古いイベントの場合、パフォーマンスデータは表示されません。

====
* * ワークロードソート列 *
+
** * レイテンシグラフ *
+
前回の分析中の、ワークロードのレイテンシに対するイベントの影響が表示されます。

** * コンポーネント使用状況列 *
+
競合状態のクラスタコンポーネントのワークロードの使用量に関する詳細が表示されます。グラフでは、実際の使用量は青い線で表示されます。赤いバーは、検出時刻から最後に分析された時刻までのイベント期間を示します。詳細については、を参照してください link:../performance-checker/reference_workload_performance_measurement_values.html["ワークロードパフォーマンスの測定値"]。

+
[NOTE]
====
ネットワークコンポーネントの場合、ネットワークパフォーマンス統計はクラスタ外のアクティビティに基づくため、この列は表示されません。

====
** * コンポーネント使用率 *
+
ネットワーク処理、Data Processing、およびアグリゲートコンポーネントの利用率の履歴（パーセント）、またはQoSポリシーグループコンポーネントのアクティビティの履歴（パーセント）が表示されます。ネットワークコンポーネントまたはインターコネクトコンポーネントのグラフは表示されません。統計にカーソルを合わせると、特定の時点における使用状況を表示できます。

** * 書き込み MBps の合計履歴 *
+
MetroClusterリソースコンポーネントの場合のみ、MetroCluster構成のパートナークラスタにミラーリングされるすべてのボリュームワークロードについて、合計書き込みスループットが1秒あたりのメガバイト数（MBps）で表示されます。

** * イベント履歴 *
+
競合状態のコンポーネントの過去のイベントを示す赤い影付きの線が表示されます。廃止イベントの場合は、選択したイベントが検出される前および解決後に発生したイベントがグラフに表示されます。




