---
permalink: events/reference_ems_events_that_are_added_automatically_to_um.html 
sidebar: sidebar 
keywords: ems events, added, automatically, unified manager 
summary: 次のONTAP EMSイベントがUnified Managerに自動的に追加されます。これらのイベントは、 Unified Manager が監視しているいずれかのクラスタでトリガーされると生成されます。 
---
= Unified Manager に自動的に追加される EMS イベント
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
次のONTAP EMSイベントがUnified Managerに自動的に追加されます。これらのイベントは、 Unified Manager が監視しているいずれかのクラスタでトリガーされると生成されます。

ONTAP 9 .5以降のソフトウェアを実行しているクラスタの監視では、次のEMSイベントを使用できます。

|===
| Unified Manager のイベント名 | EMS のイベント名 | 影響を受けるリソース | Unified Manager の重大度 


 a| 
アグリゲートの再配置でクラウド階層へのアクセス拒否
 a| 
arl.netra.ca.check.failed
 a| 
アグリゲート
 a| 
エラー



 a| 
ストレージフェイルオーバー時のアグリゲートの再配置でクラウド階層へのアクセス拒否
 a| 
gb.netra.ca.check.failed
 a| 
アグリゲート
 a| 
エラー



 a| 
FabricPoolのミラーレプリケーションの再同期が完了しました
 a| 
wafl.ca.resync.complete
 a| 
クラスタ
 a| 
エラー



 a| 
FabricPoolスペースがほぼフル
 a| 
FabricPoolほぼフル
 a| 
クラスタ
 a| 
エラー



 a| 
NVMFの猶予期間-開始
 a| 
nvmf.graceperiod.start
 a| 
クラスタ
 a| 
警告



 a| 
NVMF の猶予期間 - アクティブ
 a| 
nvmf.graceperiod.active
 a| 
クラスタ
 a| 
警告



 a| 
NVMF の猶予期間 - 終了
 a| 
nvmf.graceperiod.expired
 a| 
クラスタ
 a| 
警告



 a| 
LUNを破棄
 a| 
lun.destroy
 a| 
LUN
 a| 
情報



 a| 
Cloud AWS メタデータ接続エラー
 a| 
Cloud.aws.metadataConnFail
 a| 
ノード
 a| 
エラー



 a| 
Cloud AWS IAMクレデンシャルが期限切れ
 a| 
Cloud.aws.iamCredsExpired
 a| 
ノード
 a| 
エラー



 a| 
Cloud AWS IAMクレデンシャルが無効
 a| 
Cloud.aws.iamCredsInvalid
 a| 
ノード
 a| 
エラー



 a| 
Cloud AWS IAM クレデンシャルが見つからない
 a| 
Cloud.aws.iamCredsNotFound
 a| 
ノード
 a| 
エラー



 a| 
Cloud AWS IAM クレデンシャルが初期化されていない
 a| 
Cloud.aws.iamNotInitialized
 a| 
ノード
 a| 
情報



 a| 
Cloud AWS IAMロールが無効
 a| 
Cloud.aws.iamRoleInvalid
 a| 
ノード
 a| 
エラー



 a| 
Cloud AWS IAM ロールが見つからない
 a| 
Cloud.aws.iamRoleNotFound
 a| 
ノード
 a| 
エラー



 a| 
クラウド階層のホスト解決不可
 a| 
objstore.host.unresolvable
 a| 
ノード
 a| 
エラー



 a| 
クラウド階層のクラスタ間ネットワーク インターフェイスが停止
 a| 
objstore.interclusterlifDown
 a| 
ノード
 a| 
エラー



 a| 
要求とクラウド階層シグネチャの不一致
 a| 
osc.signatureMismatch
 a| 
ノード
 a| 
エラー



 a| 
NFSv4プールの1つに空きなし
 a| 
Nblade.nfsV4PoolExhaust
 a| 
ノード
 a| 
重大



 a| 
QoS 監視メモリの最大化
 a| 
qos.monitor.memory.maxed
 a| 
ノード
 a| 
エラー



 a| 
QoS 監視メモリの縮小
 a| 
qoS. monitor. memory.縮小
 a| 
ノード
 a| 
情報



 a| 
NVMeネームスペースの破棄
 a| 
NVMeNS.destroy
 a| 
ネームスペース
 a| 
情報



 a| 
NVMeネームスペースオンライン
 a| 
NVMeNS.offline
 a| 
ネームスペース
 a| 
情報



 a| 
NVMeネームスペースオフライン
 a| 
NVMeNS.online
 a| 
ネームスペース
 a| 
情報



 a| 
NVMeネームスペーススペース不足
 a| 
NVMeNS.out.of.space
 a| 
ネームスペース
 a| 
警告



 a| 
同期レプリケーションが同期されていません
 a| 
sms.status.out.of.sync
 a| 
SnapMirror関係
 a| 
警告



 a| 
同期レプリケーションをリストア
 a| 
sms.status.in.sync
 a| 
SnapMirror関係
 a| 
情報



 a| 
同期レプリケーションの自動再同期失敗
 a| 
sms.resync.attempt.failed
 a| 
SnapMirror関係
 a| 
エラー



 a| 
多数の CIFS 接続
 a| 
Nblade.cifsManyAuth
 a| 
SVM
 a| 
エラー



 a| 
最大CIFS接続数を超過
 a| 
Nblade.cifsMaxOpenSameFile
 a| 
SVM
 a| 
エラー



 a| 
ユーザあたりの最大CIFS接続数を超過
 a| 
Nblade.cifsMaxSessPerUsrConn
 a| 
SVM
 a| 
エラー



 a| 
CIFS NetBIOS名が競合しています
 a| 
Nblade.cifsNbNameConflict
 a| 
SVM
 a| 
エラー



 a| 
存在しないCIFS共有への接続試行
 a| 
Nblade.cifsNoPrivShare
 a| 
SVM
 a| 
重大



 a| 
CIFSシャドウコピー処理が失敗しました
 a| 
cifs.shadowcopy.failure
 a| 
SVM
 a| 
エラー



 a| 
AVサーバでウィルスが検出されました
 a| 
nblade.vscanVirusDetected
 a| 
SVM
 a| 
エラー



 a| 
ウィルススキャン用のAVサーバ接続がありません
 a| 
Nblade.vscanNoScannerConn
 a| 
SVM
 a| 
重大



 a| 
AVサーバが登録されていない
 a| 
Nblade.vscanNoRegdScanner
 a| 
SVM
 a| 
エラー



 a| 
応答するAVサーバ接続がありません
 a| 
nblade.vscanConnInactive
 a| 
SVM
 a| 
情報



 a| 
AV サーバがビジーのため新しいスキャン要求の受け入れ不可
 a| 
Nblade.vscanConnBackPressure
 a| 
SVM
 a| 
エラー



 a| 
許可されていないユーザによるAVサーバへの試行
 a| 
Nblade.vscanBadUserPrivAccess
 a| 
SVM
 a| 
エラー



 a| 
FlexGroup コンスティチュエントのスペースに問題あり
 a| 
FlexGroupコンスティチュエントhave.space.issues
 a| 
ボリューム
 a| 
エラー



 a| 
FlexGroupコンスティチュエントのスペースステータスがすべて正常
 a| 
FlexGroupコンスティチュエントスペースステータスオールOK
 a| 
ボリューム
 a| 
情報



 a| 
FlexGroupコンスティチュエントのinodeに問題あり
 a| 
flexgroup.constituents.have.inodes.issues
 a| 
ボリューム
 a| 
エラー



 a| 
FlexGroupコンスティチュエントのinodeステータスがすべて正常
 a| 
flexgroup.constituents.inodes.status.all.ok
 a| 
ボリューム
 a| 
情報



 a| 
ボリューム論理スペースがほぼフル
 a| 
monitor.vol.nearFull.inc.sav
 a| 
ボリューム
 a| 
警告



 a| 
ボリューム論理スペースがフル
 a| 
monitor.vol.full.inc.sav
 a| 
ボリューム
 a| 
エラー



 a| 
ボリューム論理スペースが正常
 a| 
monitor.vol.one.ok.inc.sav
 a| 
ボリューム
 a| 
情報



 a| 
WAFLボリュームのオートサイズが失敗
 a| 
wafl.vol.autoSize.fail
 a| 
ボリューム
 a| 
エラー



 a| 
WAFL ボリュームのオートサイズ完了
 a| 
wafl.vol.autoSize.done
 a| 
ボリューム
 a| 
情報



 a| 
WAFL READDIR ファイル処理タイムアウト
 a| 
wafl.readdir.expired
 a| 
ボリューム
 a| 
エラー

|===