---
permalink: events/reference_metrocluster_switch_events.html 
sidebar: sidebar 
keywords: metrocluster, switch, events, impact area, availability 
summary: MetroClusterスイッチイベントは、MetroClusterスイッチのステータス情報を提供します。これにより、潜在的な問題を監視できます。影響範囲別にイベントがグループ化され、イベントとトラップの名前、影響レベル、ソースタイプ、および重大度が表示されます。 
---
= MetroClusterスイッチイベント
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MetroCluster over FC構成のMetroClusterスイッチイベントは、MetroClusterスイッチのステータス情報を提供します。これにより、潜在的な問題を監視できます。影響範囲別にイベントがグループ化され、イベントとトラップの名前、影響レベル、ソースタイプ、および重大度が表示されます。



== 影響範囲：可用性

|===
| イベント名（トラップ名） | 影響レベル | ソースタイプ | 重大度 


 a| 
スイッチの温度が異常（ocumEvtSwitchTemperatureAbnormal）
 a| 
インシデント
 a| 
MetroClusterスイッチ
 a| 
重大



 a| 
スイッチに到達不能（ocumEvtSwitchUnreachable）
 a| 
インシデント
 a| 
MetroClusterスイッチ
 a| 
重大



 a| 
スイッチのファンに障害が発生しました（ocumEvtSwitchFansOneOrMoreFailed）
 a| 
インシデント
 a| 
MetroClusterスイッチ
 a| 
重大



 a| 
スイッチの電源装置で障害が発生しました（ocumEvtSwitchPowerSuppliesOneOrMoreFailed）
 a| 
インシデント
 a| 
MetroClusterスイッチ
 a| 
重大



 a| 
スイッチの温度センサーで障害が発生しました（ocumEvtSwitchTemperatureSensorFailed）

[NOTE]
====
このイベントはCiscoスイッチにのみ該当します。

==== a| 
インシデント
 a| 
MetroClusterスイッチ
 a| 
重大

|===