---
permalink: events/reference_supported_unified_manager_cli_commands.html 
sidebar: sidebar 
keywords: supported, unified manager, cli, commands, cmd, um cli, um run, 
summary: ストレージ管理者は、CLIコマンドを使用して、クラスタ、アグリゲート、ボリューム、qtree、LUNなどのストレージオブジェクトに対してクエリを実行できます。 
---
= サポートされるUnified ManagerのCLIコマンド
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージ管理者は、CLIコマンドを使用して、クラスタ、アグリゲート、ボリューム、qtree、LUNなどのストレージオブジェクトに対してクエリを実行できます。CLI コマンドを使用して、 Unified Manager の内部データベースと ONTAP データベースを照会できます。CLIコマンドは、処理の開始時または終了時に実行されるスクリプトや、アラートがトリガーされたときに実行されるスクリプトでも使用できます。

すべてのコマンドの前に、コマンド、および認証用の有効なユーザ名とパスワードを入力する必要があります `um cli login`。


NOTE: _um run_commandを実行するには、アカウントに_console_applicationアクセス権があることを確認します。

|===
| CLIコマンド | 製品説明 | 出力 


 a| 
`um cli login -u <username> [-p <password>]`
 a| 
CLIにログインします。セキュリティ上の理由から、「-u」オプションのあとにはユーザ名のみを入力してください。この方法で使用すると、パスワードの入力を求められ、パスワードは履歴テーブルやプロセステーブルに記録されません。セッションはログインしてから3時間後に期限切れになり、その後ユーザは再度ログインする必要があります。
 a| 
対応するメッセージを表示します。



 a| 
`um cli logout`
 a| 
CLIからログアウトします。
 a| 
対応するメッセージを表示します。



 a| 
`um help`
 a| 
第1レベルのサブコマンドをすべて表示します。
 a| 
第1レベルのサブコマンドをすべて表示します。



 a| 
`um run cmd [ -t <timeout> ] <cluster> <command>`
 a| 
1つ以上のホストでコマンドを実行する最も簡単な方法です。主に、ONTAPで操作を取得または実行するためのアラートスクリプトに使用されます。オプションのtimeout引数は、コマンドがクライアントで完了するまでの最大時間（秒）を設定します。デフォルトは0（無期限に待機）です。
 a| 
ONTAPから受信したもの。



 a| 
`um run query <sql command>`
 a| 
SQLクエリを実行します。データベースから読み取るクエリのみが許可されます。更新、挿入、削除操作はサポートされていません。
 a| 
結果は表形式で表示されます。空のセットが返された場合、または構文エラーや不正な要求がある場合は、該当するエラーメッセージが表示されます。



 a| 
`um datasource add -u <username> -P <password> [ -t <protocol> ] [ -p <port> ] <hostname-or-ip>`
 a| 
管理対象ストレージシステムのリストにデータソースを追加します。データソースは、ストレージシステムへの接続方法を定義したものです。データソースを追加するときは、-u（ユーザ名）オプションと-P（パスワード）オプションを指定する必要があります。オプション-t（プロトコル）では、クラスタとの通信に使用するプロトコル（httpまたはhttps）を指定します。プロトコルが指定されていない場合は、両方のプロトコルが試行されます。オプション-p（port）は、クラスタとの通信に使用するポートを指定します。ポートが指定されていない場合は、該当するプロトコルのデフォルト値が試行されます。このコマンドは、ストレージ管理者のみが実行できます。
 a| 
ユーザに証明書の受け入れを求めるプロンプトが表示され、対応するメッセージが出力されます。



 a| 
`um datasource list [ <datasource-id>]`
 a| 
管理対象ストレージシステムのデータソースを表示します。
 a| 
次の値が表形式で表示されます。 `ID Address Port, Protocol Acquisition Status, Analysis Status, Communication status, Acquisition Message, and Analysis Message`



 a| 
`um datasource modify [ -h <hostname-or-ip> ] [ -u <username> ] [ -P <password> ] [ -t <protocol> ] [ -p <port> ] <datasource-id>`
 a| 
1つ以上のデータソースオプションを変更します。ストレージ管理者のみが実行できます。
 a| 
対応するメッセージを表示します。



 a| 
`um datasource remove <datasource-id>`
 a| 
Unified Managerからデータソース（クラスタ）を削除します。
 a| 
対応するメッセージを表示します。



 a| 
`um option list [ <option> .. ]`
 a| 
に、setコマンドを使用して設定できるすべてのオプションを示します。
 a| 
次の値が表形式で表示されます。 `Name, Value, Default Value, and Requires Restart.`



 a| 
`um option set <option-name>=<option-value> [ <option-name>=<option-value> ... ]`
 a| 
1つまたは複数のオプションを設定します。このコマンドは、ストレージ管理者のみが実行できます。
 a| 
対応するメッセージを表示します。



 a| 
`um version`
 a| 
Unified Managerソフトウェアのバージョンが表示されます。
 a| 
`Version ("9.6")`



 a| 
`um lun list [-q] [ -ObjectType <object-id>]`
 a| 
指定したオブジェクトでフィルタリングしたLUNのリストを表示します。-qは、ヘッダーを表示しないすべてのコマンドに適用されます。ObjectTypeには、lun、qtree、cluster、volume、quota、svmのいずれかを指定できます。

例：

*`um lun list -cluster 1`*

この例では、objectTypeが「-cluster」で、objectIdが「1」です。このコマンドを実行すると、IDが1のクラスタに含まれるすべてのLUNのリストが表示されます。
 a| 
次の値が表形式で表示されます。 `ID and LUN path.`



 a| 
`um svm list [-q] [ -ObjectType <object-id>]`
 a| 
指定したオブジェクトでフィルタリングしたStorage VMのリストを表示します。ObjectTypeには、lun、qtree、cluster、volume、quota、svmのいずれかを指定できます。

例：

*`um svm list -cluster 1`*

この例では、objectTypeが「-cluster」で、objectIdが「1」です。このコマンドを実行すると、IDが1のクラスタに含まれるすべてのStorage VMのリストが表示されます。
 a| 
次の値が表形式で表示されます。 `Name and Cluster ID.`



 a| 
`um qtree list [-q] [ -ObjectType <object-id>]`
 a| 
指定したオブジェクトでフィルタリングしたqtreeのリストを表示します。-qは、ヘッダーを表示しないすべてのコマンドに適用されます。ObjectTypeには、lun、qtree、cluster、volume、quota、svmのいずれかを指定できます。

例：

*`um qtree list -cluster 1`*

この例では、objectTypeが「-cluster」で、objectIdが「1」です。このコマンドを実行すると、IDが1のクラスタに含まれるすべてのqtreeのリストが表示されます。
 a| 
次の値が表形式で表示されます。 `Qtree ID and Qtree Name.`



 a| 
`um disk list [-q] [-ObjectType <object-id>]`
 a| 
指定したオブジェクトでフィルタリングしたディスクのリストを表示します。ObjectTypeには、disk、aggr、node、clusterのいずれかを指定できます。

例：

*`um disk list -cluster 1`*

この例では、objectTypeが「-cluster」で、objectIdが「1」です。このコマンドを実行すると、IDが1のクラスタに含まれるすべてのディスクのリストが表示されます。
 a| 
次の値が表形式で表示され `ObjectType and object-id`ます。



 a| 
`um cluster list [-q] [-ObjectType <object-id>]`
 a| 
指定したオブジェクトでフィルタリングしたクラスタのリストを表示します。ObjectTypeには、disk、aggr、node、cluster、lun、qtree、volume、quota、svmのいずれかを指定できます。

例：

*`um cluster list -aggr 1`*

この例では、objectTypeが「-aggr」、objectIdが「1」です。このコマンドを実行すると、IDが1のアグリゲートが属するクラスタが表示されます。
 a| 
次の値が表形式で表示されます。 `Name, Full Name, Serial Number, Datasource Id, Last Refresh Time, and Resource Key`



 a| 
`um cluster node list [-q] [-ObjectType <object-id>]`
 a| 
指定したオブジェクトでフィルタリングしたクラスタノードのリストを表示します。ObjectTypeには、disk、aggr、node、clusterのいずれかを指定できます。

例：

*`um cluster node list -cluster 1`*

この例では、objectTypeが「-cluster」で、objectIdが「1」です。このコマンドを実行すると、IDが1のクラスタに含まれるすべてのノードのリストが表示されます。
 a| 
次の値が表形式で表示され `Name and Cluster ID`ます。



 a| 
`um volume list [-q] [-ObjectType <object-id>]`
 a| 
指定したオブジェクトでフィルタリングしたボリュームのリストを表示します。ObjectTypeには、lun、qtree、cluster、volume、quota、svm、aggregateのいずれかを指定できます。

例：

*`um volume list -cluster 1`*

この例では、objectTypeが「-cluster」で、objectIdが「1」です。このコマンドを実行すると、IDが1のクラスタに含まれるすべてのボリュームのリストが表示されます。
 a| 
次の値が表形式で表示され `Volume ID and Volume Name`ます。



 a| 
`um quota user list [-q] [-ObjectType <object-id>]`
 a| 
指定したオブジェクトでフィルタリングしたクォータユーザのリストを表示します。ObjectTypeには、qtree、cluster、volume、quota、svmのいずれかを指定できます。

例：

*`um quota user list -cluster 1`*

この例では、objectTypeが「-cluster」で、objectIdが「1」です。このコマンドを実行すると、IDが1のクラスタに含まれるすべてのクォータユーザのリストが表示されます。
 a| 
次の値が表形式で表示され `ID, Name, SID and Email`ます。



 a| 
`um aggr list [-q] [-ObjectType <object-id>]`
 a| 
指定したオブジェクトでフィルタリングしたアグリゲートのリストを表示します。ObjectTypeには、disk、aggr、node、cluster、volumeのいずれかを指定できます。

例：

*`um aggr list -cluster 1`*

この例では、objectTypeが「-cluster」で、objectIdが「1」です。このコマンドを実行すると、IDが1のクラスタに含まれるすべてのアグリゲートのリストが表示されます。
 a| 
次の値が表形式で表示され `Aggr ID, and Aggr Name`ます。



 a| 
`um event ack <event-ids>`
 a| 
1つ以上のイベントを確認します。
 a| 
対応するメッセージを表示します。



 a| 
`um event resolve <event-ids>`
 a| 
1つ以上のイベントを解決します。
 a| 
対応するメッセージを表示します。



 a| 
`um event assign -u <username> <event-id>`
 a| 
イベントをユーザに割り当てます。
 a| 
対応するメッセージを表示します。



 a| 
`um event list [ -s <source> ] [ -S <event-state-filter-list>.. ] [ <event-id> .. ]`
 a| 
システムまたはユーザによって生成されたイベントを一覧表示します。ソース、状態、およびIDに基づいてイベントをフィルタリングします。
 a| 
次の値が表形式で表示され `Source, Source type, Name, Severity, State, User and Timestamp`ます。



 a| 
`um backup restore -f <backup_file_path_and_name>`
 a| 
.7zファイルを使用してMySQLデータベースのバックアップをリストアします。
 a| 
対応するメッセージを表示します。

|===