---
permalink: events/reference_what_system_diagnosis_section_displays.html 
sidebar: sidebar 
keywords: system, diagnosis, section, displays 
summary: '[イベントの詳細]ページの[システム診断]セクションには、イベントの原因となった可能性がある問題の診断に役立つ情報が表示されます。' 
---
= [システム診断]セクションに表示される内容
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
[イベントの詳細]ページの[システム診断]セクションには、イベントの原因となった可能性がある問題の診断に役立つ情報が表示されます。

この領域は、一部のイベントに対してのみ表示されます。

一部のパフォーマンスイベントには、トリガーされたイベントに関連するグラフが表示されます。通常は、過去10日間のIOPSまたはMBpsのグラフとレイテンシのグラフを表示します。このように配置すると、イベントがアクティブなときにレイテンシに影響している、またはレイテンシの影響を受けているストレージコンポーネントを確認できます。

動的なパフォーマンスイベントについては、次のグラフが表示されます。

* ワークロードレイテンシ-競合状態のコンポーネントのVictim、Bully、Sharkの上位のワークロードについて、レイテンシの履歴が表示されます。
* ワークロードアクティビティ-競合状態のクラスタコンポーネントのワークロードの使用量に関する詳細が表示されます。
* リソースアクティビティ-競合状態のクラスタコンポーネントの過去のパフォーマンス統計が表示されます。


一部のクラスタコンポーネントが競合状態にある場合は、他のグラフが表示されます。

その他のイベントには、ストレージオブジェクトに対して実行されている分析タイプの簡単な説明が表示されます。複数のパフォーマンスカウンタを分析するシステム定義のパフォーマンスポリシーについては、分析されたコンポーネントごとに1行以上の行が表示される場合があります。このシナリオでは、診断の横に緑または赤のアイコンが表示され、特定の診断で問題が見つかったかどうかが示されます。
