---
permalink: events/reference_edit_alert_dialog_box.html 
sidebar: sidebar 
keywords: edit, alert, dialog box, name, resources, events, actions 
summary: 関連付けられているリソース、イベント、スクリプト、通知オプションなど、アラートのプロパティを編集することができます。 
---
= [Edit Alert]ダイアログボックス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
関連付けられているリソース、イベント、スクリプト、通知オプションなど、アラートのプロパティを編集することができます。



== 名前

この領域では、アラートの名前と説明を編集できます。

* * アラート名 *
+
アラート名を編集できます。

* * Alert 概要 *
+
アラートの説明を指定できます。

* * アラートの状態 *
+
アラートを有効または無効にできます。





== リソース

この領域では、アラートをトリガーするリソースを個別に選択したり、動的ルールに基づいてリソースをグループ化したりできます。ドロップダウンリストからリソースタイプを選択してリソースを検索するか、正確なリソース名を指定して特定のリソースを表示できます。

* * インクルード *
+
アラートをトリガーする対象に含めるリソースを指定できます。テキスト文字列を指定して、その文字列に一致するリソースをグループ化し、アラートに含めるグループを選択できます。たとえば、「 vol0 」という文字列が名前に含まれるすべてのボリュームをグループ化することができます。

* * 除外 *
+
アラートをトリガーする対象から除外するリソースを指定できます。たとえば、「 xyz 」という文字列が名前に含まれるすべてのボリュームを除外することができます。

+
[NOTE]
====
[除外]タブは、特定のリソースタイプのすべてのリソース（++や<<All Volumes whose name contains 'xyz'>>++など）を選択した場合にのみ表示され<<All Volumes>>ます。

====




== イベント

この領域では、アラートをトリガーするイベントを選択できます。アラートは特定の重大度のイベントに対してトリガーするか、一連のイベントを指定してトリガーできます。

* * イベントの重大度 *
+
重大度タイプに基づいてイベントを選択できます。タイプは、「重大」、「エラー」、「警告」のいずれかです。

* * イベント名に * が含まれています
+
名前に指定した文字を含むイベントを選択できます。





== アクション

この領域では、通知方式と通知頻度を指定できます。

* * これらのユーザーに警告 *
+
通知を受信するEメールアドレスまたはユーザ名を編集したり、新しいEメールアドレスまたはユーザ名を指定したりできます。

* * 通知頻度 *
+
イベントが確認または解決されるか、廃止状態になるまで、管理サーバが通知を送信する頻度を編集できます。

+
次のいずれかの通知方式を選択できます。

+
** 1回のみ通知
** 指定した頻度で通知
** 指定した時間範囲内で指定した頻度で通知する


* * 問題 SNMP トラップ *
+
グローバルに設定されたSNMPホストにSNMPトラップを送信するかどうかを指定できます。

* * スクリプトの実行 *
+
アラートにスクリプトを関連付けることができます。このスクリプトはアラートが生成されたときに実行されます。





== コマンドボタン

* * 保存 *
+
変更を保存してダイアログボックスを閉じます。

* * キャンセル *
+
変更内容を破棄してダイアログボックスを閉じます。


