---
permalink: events/reference_storage_failover_settings_events.html 
sidebar: sidebar 
keywords: storage, failover, settings, events, impact area, availability 
summary: ストレージフェイルオーバー（SFO）の設定イベントは、ストレージフェイルオーバーが無効になっているかどうか、または設定されていないかどうかに関する情報を提供します。これにより、潜在的な問題を監視できます。影響範囲別にイベントがグループ化され、イベントとトラップの名前、影響レベル、ソースタイプ、および重大度が表示されます。 
---
= ストレージフェイルオーバー設定イベント
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージフェイルオーバー（SFO）の設定イベントは、ストレージフェイルオーバーが無効になっているかどうか、または設定されていないかどうかに関する情報を提供します。これにより、潜在的な問題を監視できます。影響範囲別にイベントがグループ化され、イベントとトラップの名前、影響レベル、ソースタイプ、および重大度が表示されます。



== 影響範囲：可用性

|===
| イベント名（トラップ名） | 影響レベル | ソースタイプ | 重大度 


 a| 
ストレージフェイルオーバーインターコネクトの1つ以上のリンクが停止しています（ocumEvtSfoInterconnectOneOrMoreLinksDown）
 a| 
リスク
 a| 
ノード
 a| 
警告



 a| 
ストレージフェイルオーバーが無効（ocumEvtSfoSettingsDisabled）
 a| 
リスク
 a| 
ノード
 a| 
エラー



 a| 
ストレージフェイルオーバーが設定されていません（ocumEvtSfoSettingsNotConfigured）
 a| 
リスク
 a| 
ノード
 a| 
エラー



 a| 
ストレージフェイルオーバーの状態-テイクオーバー（ocumEvtSfoStateTakeover）
 a| 
リスク
 a| 
ノード
 a| 
警告



 a| 
ストレージフェイルオーバーの状態-部分的なギブバック（ocumEvtSfoStatePartialGiveback）
 a| 
リスク
 a| 
ノード
 a| 
エラー



 a| 
ストレージフェイルオーバーノードのステータス-停止（ocumEvtSfoNodeStatusDown）
 a| 
リスク
 a| 
ノード
 a| 
エラー



 a| 
ストレージフェイルオーバーのテイクオーバーを実行できない（ocumEvtSfoTakeoverNotPosible）
 a| 
リスク
 a| 
ノード
 a| 
エラー

|===