---
permalink: events/reference_aggregate_events.html 
sidebar: sidebar 
keywords: aggregate events, impact, area, availability, capacity, configuration, performance 
summary: アグリゲートイベントは、アグリゲートのステータス情報を提供します。これにより、潜在的な問題を監視できます。影響範囲別にイベントがグループ化され、イベントとトラップの名前、影響レベル、ソースタイプ、および重大度が表示されます。 
---
= アグリゲートイベント
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アグリゲートイベントは、アグリゲートのステータス情報を提供します。これにより、潜在的な問題を監視できます。影響範囲別にイベントがグループ化され、イベントとトラップの名前、影響レベル、ソースタイプ、および重大度が表示されます。



== 影響範囲：可用性

アスタリスク（ * ）は、 Unified Manager イベントに変換された EMS イベントを示します。

|===
| イベント名（トラップ名） | 影響レベル | ソースタイプ | 重大度 


 a| 
アグリゲートがオフライン（ocumEvtAggregateStateOffline）
 a| 
インシデント
 a| 
アグリゲート
 a| 
重大



 a| 
アグリゲートで障害が発生しました（ocumEvtAggregateStateFailed）
 a| 
インシデント
 a| 
アグリゲート
 a| 
重大



 a| 
Aggregate Restricted（ocumEvtAggregateStateRestricted）
 a| 
リスク
 a| 
アグリゲート
 a| 
警告



 a| 
アグリゲートの再構築（ocumEvtAggregateRaidStateReconstructing）
 a| 
リスク
 a| 
アグリゲート
 a| 
警告



 a| 
アグリゲートがデグレード状態（ocumEvtAggregateRaidStateDegraded）
 a| 
リスク
 a| 
アグリゲート
 a| 
警告



 a| 
クラウド階層に一部到達可能（ocumEventCloudTierPartiallyReachable）
 a| 
リスク
 a| 
アグリゲート
 a| 
警告



 a| 
クラウド階層に到達不能（ocumEventCloudTierUnreachable）
 a| 
リスク
 a| 
アグリゲート
 a| 
エラー



 a| 
アグリゲートの再配置でクラウド階層へのアクセス拒否 * （ arlNetraCaCheckFailed ）
 a| 
リスク
 a| 
アグリゲート
 a| 
エラー



 a| 
ストレージフェイルオーバー時のアグリゲートの再配置でクラウド階層へのアクセス拒否 * （ gbNetraCaCheckFailed ）
 a| 
リスク
 a| 
アグリゲート
 a| 
エラー



 a| 
MetroClusterで残ったアグリゲート（ocumEvtMetroClusterAggregateLeftBehind）
 a| 
リスク
 a| 
アグリゲート
 a| 
エラー



 a| 
MetroClusterアグリゲートのミラーリングがデグレード状態（ocumEvtMetroClusterAggregateMirrorDegraded）
 a| 
リスク
 a| 
アグリゲート
 a| 
エラー

|===


== 影響範囲：容量

|===
| イベント名（トラップ名） | 影響レベル | ソースタイプ | 重大度 


 a| 
アグリゲートスペースがほぼフル（ocumEvtAggregateNearlyFull）
 a| 
リスク
 a| 
アグリゲート
 a| 
警告



 a| 
アグリゲートスペースがフル（ocumEvtAggregateFull）
 a| 
リスク
 a| 
アグリゲート
 a| 
エラー



 a| 
アグリゲートのフルまでの日数（ocumEvtAggregateDaysUntilFullSoon）
 a| 
リスク
 a| 
アグリゲート
 a| 
エラー



 a| 
アグリゲートがオーバーコミット（ocumEvtAggregateOvercommitted）
 a| 
リスク
 a| 
アグリゲート
 a| 
エラー



 a| 
アグリゲートがほぼオーバーコミット（ocumEvtAggregateAlmostOvercommitted）
 a| 
リスク
 a| 
アグリゲート
 a| 
警告



 a| 
アグリゲートのSnapshotリザーブがフル（ocumEvtAggregateSnapReserveFull）
 a| 
リスク
 a| 
アグリゲート
 a| 
警告



 a| 
アグリゲートの増加率が異常（ocumEvtAggregateGrowthRateAbnormal）
 a| 
リスク
 a| 
アグリゲート
 a| 
警告

|===


== 影響範囲：構成

|===
| イベント名（トラップ名） | 影響レベル | ソースタイプ | 重大度 


 a| 
アグリゲートを検出（該当なし）
 a| 
イベント
 a| 
アグリゲート
 a| 
情報



 a| 
アグリゲートの名前を変更（該当なし）
 a| 
イベント
 a| 
アグリゲート
 a| 
情報



 a| 
アグリゲートが削除されました（該当なし）
 a| 
イベント
 a| 
ノード
 a| 
情報

|===


== 影響範囲：パフォーマンス

|===
| イベント名（トラップ名） | 影響レベル | ソースタイプ | 重大度 


 a| 
アグリゲートIOPSの重大しきい値を超過（ocumAggregateIopsIncident）
 a| 
インシデント
 a| 
アグリゲート
 a| 
重大



 a| 
アグリゲートIOPSの警告しきい値を超過（ocumAggregateIopsWarning）
 a| 
リスク
 a| 
アグリゲート
 a| 
警告



 a| 
アグリゲートMBpsの重大しきい値を超過（ocumAggregateMbpsIncident）
 a| 
インシデント
 a| 
アグリゲート
 a| 
重大



 a| 
アグリゲートMBpsの警告しきい値を超過（ocumAggregateMbpsWarning）
 a| 
リスク
 a| 
アグリゲート
 a| 
警告



 a| 
アグリゲートレイテンシの重大しきい値を超過（ocumAggregateLatencyIncident）
 a| 
インシデント
 a| 
アグリゲート
 a| 
重大



 a| 
アグリゲートレイテンシの警告しきい値を超過（ocumAggregateLatencyWarning）
 a| 
リスク
 a| 
アグリゲート
 a| 
警告



 a| 
アグリゲート使用済みパフォーマンス容量の重大しきい値を超過（ocumAggregatePerfCapacityUsedIncident）
 a| 
インシデント
 a| 
アグリゲート
 a| 
重大



 a| 
アグリゲート使用済みパフォーマンス容量の警告しきい値を超過（ocumAggregatePerfCapacityUsedWarning）
 a| 
リスク
 a| 
アグリゲート
 a| 
警告



 a| 
アグリゲート利用率の重大しきい値を超過（ocumAggregateUtilizationIncident）
 a| 
インシデント
 a| 
アグリゲート
 a| 
重大



 a| 
アグリゲート利用率の警告しきい値を超過（ocumAggregateUtilizationWarning）
 a| 
リスク
 a| 
アグリゲート
 a| 
警告



 a| 
利用率の高いアグリゲートディスクのしきい値を超過（ocumAggregateDisksOverUtilizedWarning）
 a| 
リスク
 a| 
アグリゲート
 a| 
警告



 a| 
アグリゲート動的しきい値を超過（ocumAggregateDynamicEventWarning）
 a| 
リスク
 a| 
アグリゲート
 a| 
警告

|===