---
permalink: events/reference_add_alert_dialog_box.html 
sidebar: sidebar 
keywords: add, alert, dialog, box, name, resources, events, actions, command buttons 
summary: アラートを作成して特定のイベントが生成されたときに通知することで、問題に迅速に対処し、環境への影響を最小限に抑えることができます。アラートは、単一のリソース、一連のリソース、および特定の重大度タイプのイベントについて作成することができます。アラートの通知方式と通知頻度を指定することもできます。 
---
= [Add Alert]ダイアログボックス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アラートを作成して特定のイベントが生成されたときに通知することで、問題に迅速に対処し、環境への影響を最小限に抑えることができます。アラートは、単一のリソース、一連のリソース、および特定の重大度タイプのイベントについて作成することができます。アラートの通知方式と通知頻度を指定することもできます。

アプリケーション管理者またはストレージ管理者のロールが必要です。



== 名前

この領域では、アラートの名前と説明を指定できます。

* * アラート名 *
+
アラート名を指定できます。

* * Alert 概要 *
+
アラートの説明を指定できます。





== リソース

この領域では、アラートをトリガーするリソースを個別に選択したり、動的ルールに基づいてリソースをグループ化したりできます。a_dynamic rule_ は、指定したテキスト文字列に基づいてフィルタリングされるリソースのセットです。ドロップダウンリストからリソースタイプを選択してリソースを検索するか、正確なリソース名を指定して特定のリソースを表示できます。

いずれかのストレージオブジェクトの詳細ページからアラートを作成する場合は、ストレージオブジェクトが自動的にアラートに含まれます。

* * インクルード *
+
アラートをトリガーする対象に含めるリソースを指定できます。テキスト文字列を指定して、その文字列に一致するリソースをグループ化し、アラートに含めるグループを選択できます。たとえば、「abc」という文字列を名前に含むすべてのボリュームをグループ化できます。

* * 除外 *
+
アラートをトリガーする対象から除外するリソースを指定できます。たとえば、「xyz」という文字列を名前に含むすべてのボリュームを除外できます。

+
[除外]タブは、特定のリソースタイプのすべてのリソース（+や<<All Volumes whose name contains 'xyz'>>+など）を選択した場合にのみ表示され<<All Volumes>>ます。

+
あるリソースが対象に含めるルールと除外するルールの両方に該当する場合は、除外するルールが優先され、イベントについてはアラートが生成されません。





== イベント

この領域では、アラートを作成するイベントを選択できます。特定の重大度に基づくイベントまたは一連のイベントに対してアラートを作成できます。

複数のイベントを選択するには、Ctrlキーを押しながら選択します。

* * イベントの重大度 *
+
重大度タイプに基づいてイベントを選択できます。タイプは、「重大」、「エラー」、「警告」のいずれかです。

* * イベント名に * が含まれています
+
名前に指定した文字を含むイベントを選択できます。





== アクション

この領域では、アラートがトリガーされたときに通知するユーザを指定できます。通知方式と通知頻度を指定することもできます。

* * これらのユーザーに警告 *
+
通知を受信するユーザのEメールアドレスまたはユーザ名を指定できます。

+
ユーザに指定したEメールアドレスを変更し、アラートを編集用に再度開くと、変更したEメールアドレスが以前に選択したユーザにマッピングされなくなるため、[Name]フィールドには何も表示されません。また、[ユーザ]ページで選択したユーザのEメールアドレスを変更しても、変更したEメールアドレスは更新されません。

* * 通知頻度 *
+
イベントが確認または解決されるか、廃止状態に設定されるまでの間、管理サーバが通知を送信する頻度を指定できます。

+
次のいずれかの通知方式を選択できます。

+
** 1回のみ通知
** 指定した頻度で通知
** 指定した時間範囲内で指定した頻度で通知する


* * 問題 SNMP トラップ *
+
このボックスを選択すると、グローバルに設定されたSNMPホストにSNMPトラップを送信するかどうかを指定できます。

* * スクリプトの実行 *
+
アラートにカスタムスクリプトを追加できます。このスクリプトはアラートが生成されたときに実行されます。

+
[NOTE]
====
この機能がユーザインターフェイスに表示されない場合は、管理者によって無効にされています。この機能は、必要に応じて、 * Storage Management * > * Feature Settings * から有効にできます。

====




== コマンドボタン

* * 保存 *
+
アラートを作成してダイアログボックスを閉じます。

* * キャンセル *
+
変更内容を破棄してダイアログボックスを閉じます。


