---
permalink: events/reference_event_details_page.html 
sidebar: sidebar 
keywords: event, details, page 
summary: '[イベントの詳細]ページでは、選択したイベントの重大度、影響レベル、影響領域、イベントソースなどの詳細を確認できます。また、問題を解決するための考えられる修正方法に関する追加情報を確認することもできます。' 
---
= [Event]詳細ページ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
[イベントの詳細]ページでは、選択したイベントの重大度、影響レベル、影響領域、イベントソースなどの詳細を確認できます。また、問題を解決するための考えられる修正方法に関する追加情報を確認することもできます。

* * イベント名 *
+
イベントの名前と最終確認時刻。

+
パフォーマンスイベント以外のイベントの場合は、状態が「新規」または「確認済み」のときは最後に確認された情報が不明なため非表示になります。

* * イベント概要 *
+
イベントの簡単な説明。

+
イベントの説明にイベントがトリガーされた理由が記載されている場合があります。

* * 競合状態のコンポーネント *
+
動的なパフォーマンスイベントについては、クラスタの論理コンポーネントと物理コンポーネントを表すアイコンが表示されます。コンポーネントが競合状態にある場合は、アイコンが赤い丸で強調表示されます。

+
表示されるコンポーネントの概要については、「 _ クラスタコンポーネントとその競合の原因」を参照してください。



[イベント情報]、[システム診断]、[推奨される操作]の各セクションについては、他のトピックで説明しています。



== コマンドボタン

各コマンドボタンを使用して次のタスクを実行できます。

* * メモアイコン *
+
イベントに関するメモを追加または更新したり、他のユーザが残したすべてのメモを確認したりできます。



* アクションメニュー *

* * 自分に割り当て *
+
イベントを自分に割り当てます。

* * 他のユーザーに割り当て *
+
[所有者の割り当て]ダイアログボックスを開きます。このダイアログボックスで、イベントを他のユーザに割り当てたり、再割り当てしたりできます。

+
イベントをユーザに割り当てると、イベントリストの選択したイベントの該当するフィールドに、そのユーザの名前とイベントが割り当てられた時刻が追加されます。

+
所有権のフィールドを空白にすると、イベントの割り当てを解除できます。

* * 確認 *
+
選択したイベントに確認応答し、アラート通知が繰り返し送信されないようにします。

+
イベントに確認応答すると、イベントリストの選択したイベントの該当するフィールド（[確認者]）に、自分のユーザ名とイベントに応答した時刻が追加されます。確認応答したイベントは、ユーザが管理する必要があります。

* * 解決済みとしてマーク *
+
イベントの状態を解決済みに変更できます。

+
イベントを解決すると、イベントリストの選択したイベントの該当するフィールド（[解決者]）に、自分のユーザ名とイベントを解決した時刻が追加されます。イベントに対処したら、そのイベントを解決済みとしてマークする必要があります。

* * アラートの追加 *
+
[アラートの追加]ダイアログボックスが表示されます。このダイアログボックスで、選択したイベントのアラートを追加できます。


