---
permalink: events/reference_snapmirror_and_vault_relationship_events.html 
sidebar: sidebar 
keywords: asynchronous, mirror, vault, relationship, events, impact area, protection 
summary: 非同期ミラーバックアップ関係イベントは、非同期SnapMirrorおよびバックアップ関係のステータス情報を提供します。これにより、潜在的な問題を監視できます。非同期ミラーバックアップ関係イベントは、ボリュームとStorage VMの両方の保護関係でサポートされます。ただし、Storage VMディザスタリカバリではバックアップ関係のみがサポートされません。影響範囲別にイベントがグループ化され、イベントとトラップの名前、影響レベル、ソースタイプ、および重大度が表示されます。 
---
= 非同期ミラーバックアップ関係イベント
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
非同期ミラーバックアップ関係イベントは、非同期SnapMirrorおよびバックアップ関係のステータス情報を提供します。これにより、潜在的な問題を監視できます。非同期ミラーバックアップ関係イベントは、ボリュームとStorage VMの両方の保護関係でサポートされます。ただし、Storage VMディザスタリカバリではバックアップ関係のみがサポートされません。影響範囲別にイベントがグループ化され、イベントとトラップの名前、影響レベル、ソースタイプ、および重大度が表示されます。



== 影響範囲：保護

[NOTE]
====
SnapMirror関係イベントとバックアップ関係イベントは、Storage VMディザスタリカバリで保護されているが、コンスティチュエントオブジェクト関係に対しては生成されないStorage VMについても生成されます。

====
|===
| イベント名（トラップ名） | 影響レベル | ソースタイプ | 重大度 


 a| 
非同期ミラーバックアップは正常でない（ocumEvtMirrorVaultRelationshipUnhealthy）
 a| 
リスク
 a| 
SnapMirror関係
 a| 
警告



 a| 
非同期ミラーバックアップを切断（ocumEvtMirrorVaultRelationshipStateBrokenoff）
 a| 
リスク
 a| 
SnapMirror関係
 a| 
エラー



 a| 
非同期ミラーバックアップの初期化失敗（ocumEvtMirrorVaultRelationshipInitializeFailed）
 a| 
リスク
 a| 
SnapMirror関係
 a| 
エラー



 a| 
非同期ミラーバックアップの更新失敗（ocumEvtMirrorVaultRelationshipUpdateFailed）
 a| 
リスク
 a| 
SnapMirror関係
 a| 
エラー



 a| 
非同期ミラーバックアップの遅延エラー（ocumEvtMirrorVaultRelationshipLagError）
 a| 
リスク
 a| 
SnapMirror関係
 a| 
エラー



 a| 
非同期ミラーバックアップの遅延警告（ocumEvtMirrorVaultRelationshipLagWarning）
 a| 
リスク
 a| 
SnapMirror関係
 a| 
警告



 a| 
非同期ミラーバックアップの再同期失敗（ocumEvtMirrorVaultRelationshipResyncFailed）
 a| 
リスク
 a| 
SnapMirror関係
 a| 
エラー

|===
[NOTE]
====
「SnapMirror update failure」イベントがActive IQ portal（Config Advisor）によって生成されます。

====