---
permalink: events/reference_what_suggested_actions_section_displays.html 
sidebar: sidebar 
keywords: suggest, actions, section, displays 
summary: '[イベントの詳細]ページの[推奨される操作]セクションには、イベントの考えられる理由とイベントを解決するための推奨される対処方法が表示されます。推奨される対処方法は、イベントのタイプまたは違反したしきい値のタイプに基づいてカスタマイズされます。' 
---
= [推奨される操作]セクションに表示される内容
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
[イベントの詳細]ページの[推奨される操作]セクションには、イベントの考えられる理由とイベントを解決するための推奨される対処方法が表示されます。推奨される対処方法は、イベントのタイプまたは違反したしきい値のタイプに基づいてカスタマイズされます。

この領域は、一部のタイプのイベントに対してのみ表示されます。

特定のアクションを実行するための手順など、推奨される多くのアクションについて追加情報を参照する * Help * リンクがページに表示される場合があります。一部の処理では、Unified Manager、ONTAP System Manager、OnCommand Workflow Automation、ONTAP CLIコマンド、またはこれらのツールを組み合わせて使用します。

ここで推奨される対処方法は、このイベントを解決するためのガイダンスとしてのみ考慮してください。このイベントを解決するためのアクションは、環境の状況に基づいて実行する必要があります。

オブジェクトやイベントを詳しく分析するには、 * ワークロードの分析 * ボタンをクリックしてワークロードの分析ページを表示します。

イベントによっては、Unified Managerの詳細な診断によって単一の解決策が提供されることがあります。解決策がある場合は、 * Fix it * ボタンで表示されます。このボタンをクリックすると、Unified Managerでイベントの原因となっている問題が修正されます。

Active IQ プラットフォームイベントの場合、問題と解決策について解説したネットアップのナレッジベースの記事へのリンクがこのセクションに表示されることがあります。外部ネットワークへのアクセスがないサイトでは、ナレッジベースの記事の PDF がローカルで開きます。この PDF は、 Unified Manager インスタンスに手動でダウンロードしたルールファイルに含まれています。
