---
permalink: events/reference_description_of_event_impact_areas.html 
sidebar: sidebar 
keywords: description, event, impact, areas 
summary: イベントは6つの影響領域（可用性、容量、構成、パフォーマンス、保護、セキュリティ）に分類され、担当するイベントのタイプに集中できます。 
---
= イベントの影響範囲の説明
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
イベントは6つの影響領域（可用性、容量、構成、パフォーマンス、保護、セキュリティ）に分類され、担当するイベントのタイプに集中できます。

* * 利用可能性 *
+
可用性イベントは、ストレージオブジェクトがオフラインになった場合、プロトコルサービスが停止した場合、ストレージフェイルオーバーで問題が発生した場合、またはハードウェアで問題が発生した場合に通知するイベントです。

* * 容量 *
+
容量イベントは、アグリゲート、ボリューム、LUN、またはネームスペースのサイズがしきい値に近づいているか達した場合、または環境の通常の増加率とは異なる場合に通知するイベントです。

* * コンフィグレーション *
+
構成イベントは、ストレージオブジェクトの検出、削除、追加、削除、または名前変更を通知するイベントです。構成イベントの影響レベルは「イベント」、重大度タイプは「情報」です。

* * パフォーマンス *
+
パフォーマンスイベントは、監視対象のストレージオブジェクトでのデータストレージの入力速度や読み出し速度に悪影響を及ぼす可能性がある、クラスタのリソース、設定、またはアクティビティの状態について通知するイベントです。

* * 保護 *
+
保護イベントは、SnapMirror関係に関連するインシデントやリスク、デスティネーションの容量の問題、SnapVault関係の問題、保護ジョブの問題について通知するイベントです。セカンダリボリュームおよび保護関係をホストする ONTAP オブジェクト（アグリゲート、ボリューム、および SVM ）は、いずれもこの影響領域に分類されます。

* * セキュリティ *
+
セキュリティイベントは、で定義されたパラメータに基づいて、ONTAPクラスタ、Storage Virtual Machine（SVM）、およびボリュームがどの程度セキュアであるかを通知します https://www.netapp.com/pdf.html?item=/media/10674-tr4569pdf.pdf["ONTAP 9 セキュリティ設定ガイド"^]。

+
また、この領域には、 Active IQ プラットフォームから報告されるアップグレードイベントも含まれます。


