---
permalink: events/task_add_alerts_for_performance_events.html 
sidebar: sidebar 
keywords: add, alerts, performance, events 
summary: パフォーマンスイベントのアラートは、 Unified Manager で受信する他のイベントと同様に、イベントごとに個別に設定することができます。また、すべてのパフォーマンスイベントを同じように扱い、同じユーザにEメールを送信する場合は、重大または警告のパフォーマンスイベントがトリガーされたときに通知する単一のアラートを作成できます。 
---
= パフォーマンスイベントのアラートの追加
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
パフォーマンスイベントのアラートは、 Unified Manager で受信する他のイベントと同様に、イベントごとに個別に設定することができます。また、すべてのパフォーマンスイベントを同じように扱い、同じユーザにEメールを送信する場合は、重大または警告のパフォーマンスイベントがトリガーされたときに通知する単一のアラートを作成できます。

* 必要なもの *

アプリケーション管理者またはストレージ管理者のロールが必要です。

次の例は、レイテンシ、IOPS、MBpsのすべての重大イベントのイベントを作成する方法を示しています。同じ方法で、すべてのパフォーマンスカウンタからイベントを選択し、すべての警告イベントを選択できます。

.手順
. 左側のナビゲーションペインで、 * Storage Management * > * Alert Setup * をクリックします。
. [* Alert Setup* ] ページで、 [* Add] をクリックします。
. [ * アラートの追加 * ] ダイアログボックスで、 [ * 名前 * ] をクリックし、アラートの名前と概要を入力します。
. [* リソース ] ページでは、リソースを選択しないでください。
+
リソースが選択されていないため、これらのイベントを受信したすべてのクラスタ、アグリゲート、ボリュームなどにアラートが適用されます。

. [* Events （イベント） ] をクリックして、次の操作を実行します。
+
.. イベントの重大度リストで、 * クリティカル * を選択します。
.. [Event Name Contains]フィールドに*`latency`「*」と入力し、矢印をクリックして一致するすべてのイベントを選択します。
.. [Event Name Contains]フィールドに*`iops`「*」と入力し、矢印をクリックして一致するすべてのイベントを選択します。
.. [Event Name Contains]フィールドに*`mbps`「*」と入力し、矢印をクリックして一致するすべてのイベントを選択します。


. [* アクション * ] をクリックし、 [ これらのユーザーに警告 ] フィールドで警告メールを受信するユーザーの名前を選択します。
. SNMPトラップの発行およびスクリプトの実行について、このページのその他のオプションを設定します。
. [ 保存（ Save ） ] をクリックします。

