---
permalink: events/task_disable_unwanted_events.html 
sidebar: sidebar 
keywords: disable, unwanted, events 
summary: デフォルトでは、すべてのイベントが有効になっています。環境で重要でないイベントについては、グローバルに無効にして通知が生成されないようにすることができます。無効にしたイベントの通知を再開する場合は、それらのイベントを有効にすることができます。 
---
= 不要なイベントの無効化
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
デフォルトでは、すべてのイベントが有効になっています。環境で重要でないイベントについては、グローバルに無効にして通知が生成されないようにすることができます。無効にしたイベントの通知を再開する場合は、それらのイベントを有効にすることができます。

* 必要なもの *

アプリケーション管理者またはストレージ管理者のロールが必要です。

イベントを無効にすると、システムで以前に生成されたイベントは「廃止」とマークされ、それらのイベントに設定されたアラートはトリガーされなくなります。無効にしたイベントを有効にすると、それらのイベントの通知が次の監視サイクルから生成されます。

オブジェクト（イベントなど）のイベントを無効にしたあとにそのイベントを有効にした場合、 `vol offline`イベントが無効状態のときにオフラインになったオブジェクトについては、Unified Managerで新しいイベントは生成されません。Unified Manager では、イベントを再度有効にしたあとにオブジェクトの状態に変更があった場合にのみ新規のイベントが生成されます。

.手順
. 左側のナビゲーションペインで、 * Storage Management * > * Event Setup * をクリックします。
. イベント設定 * ページで、次のいずれかのオプションを選択してイベントを無効または有効にします。
+
|===
| 状況 | 操作 


 a| 
イベントを無効にする
 a| 
.. [*Disable*] をクリックします。
.. [Disable Events]ダイアログボックスで、イベントの重大度を選択します。
.. [Matching Events]列で、イベントの重大度に基づいて無効にするイベントを選択し、右矢印をクリックして[Disable Events]列に移動します。
.. [ 保存して閉じる ] をクリックします。
.. 無効にしたイベントが[Event Setup]ページのリストビューに表示されていることを確認します。




 a| 
イベントを有効にする
 a| 
.. 有効にするイベントのチェックボックスを選択します。
.. [*Enable*] をクリックします。


|===

