---
permalink: events/task_exclude_disaster_recovery_destination_volumes_from_alerts.html 
sidebar: sidebar 
keywords: exclude, disaster, recovery, destination, volumes, generate, alerts 
summary: ボリュームアラートを設定するときに、ボリュームまたはボリュームグループを識別する文字列をアラートダイアログボックスで指定できます。ただし、 SVM のディザスタリカバリを設定している場合は、ソースボリュームとデスティネーションボリュームの名前が同じであるため、両方のボリュームについてアラートを受け取ることになります。 
---
= ディザスタリカバリのデスティネーションボリュームのアラート生成対象からの除外
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ボリュームアラートを設定するときに、ボリュームまたはボリュームグループを識別する文字列をアラートダイアログボックスで指定できます。ただし、 SVM のディザスタリカバリを設定している場合は、ソースボリュームとデスティネーションボリュームの名前が同じであるため、両方のボリュームについてアラートを受け取ることになります。

* 必要なもの *

アプリケーション管理者またはストレージ管理者のロールが必要です。

ディザスタリカバリのデスティネーションボリュームに対するアラートを無効にするには、デスティネーション SVM の名前を含むボリュームを除外します。これは、ボリュームイベントの識別子に SVM 名とボリューム名の両方が「 <svm_name> ： /<volume_name> 」の形式で含まれていることを確認したものです。

次の例は、プライマリSVM「vs1」上のボリューム「vol1」に対するアラートを作成し、SVM「vs1-dr」上の同じ名前のボリュームではアラートは生成されないようにする方法を示しています。

[Add Alert]ダイアログボックスで、次の手順を実行します。

.手順
. [* 名前 *] をクリックして、アラートの名前と概要を入力します。
. [* リソース（ * Resources ） ] をクリックし、 [* 含める * （ * Include * ） ] タブを選択します。
+
.. ドロップダウンリストから*[ボリューム]**`vol1`を選択し、*[名前に次の文字を含む]*フィールドに*と入力して、名前に「vol1」を含むボリュームを表示します。
.. [Available Resources]領域で*+*を選択し<<All Volumes whose name contains 'vol1'>>、*[Selected Resources]領域に移動します。


. [除外]*タブを選択し、*[ボリューム]**`vs1-dr`を選択し、*[名前に次の文字を含む]*フィールドに*と入力して、*[追加]*をクリックします。
+
SVM「vs1-dr」上のボリューム「vol1」に対してアラートは生成されません。

. 「 * Events 」をクリックして、ボリュームに適用するイベントを選択します。
. [* アクション * ] をクリックし、 [ これらのユーザーに警告 ] フィールドで警告メールを受信するユーザーの名前を選択します。
. SNMP トラップを発行してスクリプトを実行するために、このページの他のオプションを設定し、 * Save * をクリックします。

