---
permalink: data-protection/concept_types_of_snapmirror_protection.html 
sidebar: sidebar 
keywords: types, snapmirror, protection, consistency group, SnapMirror active sync 
summary: 導入するデータストレージのトポロジに応じて、複数のタイプの SnapMirror 保護関係を Unified Manager で設定できます。SnapMirror保護では、フェイルオーバーによるディザスタリカバリによる保護がすべて提供されますが、パフォーマンス、バージョンの柔軟性、複数のバックアップコピーによる保護の機能は異なります。 
---
= SnapMirror保護の種類
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
導入するデータストレージのトポロジに応じて、複数のタイプの SnapMirror 保護関係を Unified Manager で設定できます。SnapMirror保護では、フェイルオーバーによるディザスタリカバリによる保護がすべて提供されますが、パフォーマンス、バージョンの柔軟性、複数のバックアップコピーによる保護の機能は異なります。



== 従来のSnapMirror非同期保護関係

従来のSnapMirror非同期保護は、ソースボリュームとデスティネーションボリューム間のブロックレプリケーションによるミラー保護を提供します。

従来のSnapMirror関係では、ブロックレプリケーションに基づいてミラー処理が行われるため、他のSnapMirror関係よりも高速なミラー処理が可能です。ただし、従来のSnapMirror保護を使用するには、デスティネーションボリュームで実行されているONTAPソフトウェアのマイナーバージョンがソースボリュームと同じかそれ以降である必要があります（バージョン8.xから8.x、9.xから9.xなど）。9.1ソースから9.0デスティネーションへのレプリケーションは、デスティネーションで以前のメジャーバージョンが実行されているためサポートされません。



== バージョンに依存しないレプリケーションによるSnapMirror非同期保護

バージョンに依存しないレプリケーションを使用したSnapMirror非同期保護では、ソースボリュームとデスティネーションボリュームの間で論理レプリケーションによるミラー保護が提供されます。ボリュームがONTAP 8.3以降の異なるバージョン（バージョン8.3から8.3.1、8.3から9.1、9.2.2から9.2など）で実行されている場合でも同様です。

バージョンに依存しないレプリケーションを使用するSnapMirror関係では、ミラー処理が従来のSnapMirror関係ほど高速ではありません。

実行速度が遅いため、次のいずれかの状況では、バージョンに依存しないレプリケーション保護を使用したSnapMirrorの実装は適していません。

* ソースオブジェクトには保護対象のファイルが1、000万個以上含まれています。
* 保護されるデータの目標復旧時点が2時間以下である。（つまり、ソースのデータよりも2時間以上古いリカバリ可能なミラーデータがデスティネーションに常に含まれている必要があります）。


上記のいずれかの状況では、デフォルトのSnapMirror保護をブロックレプリケーションベースで高速に実行する必要があります。



== バージョンに依存しないレプリケーションとバックアップオプションによるSnapMirror非同期保護

バージョンに依存しないレプリケーションとバックアップオプションを使用したSnapMirror非同期保護では、ソースボリュームとデスティネーションボリューム間のミラー保護と、ミラーされたデータの複数のコピーをデスティネーションに格納する機能が提供されます。

ストレージ管理者は、ソースからデスティネーションにミラーリングするSnapshotコピーを指定できます。また、ソースのコピーが削除された場合でも、それらのコピーをデスティネーションに保持する期間を指定することもできます。

バージョンに依存しないレプリケーションとバックアップオプションを使用するSnapMirror関係では、ミラー処理が従来のSnapMirror関係ほど高速ではありません。



== SnapMirrorユニファイドレプリケーション（ミラーとバックアップ）

SnapMirrorユニファイドレプリケーションを使用すると、同じデスティネーションボリュームでディザスタリカバリとアーカイブを設定できます。SnapMirrorと同様に、一元化されたデータ保護機能を初めて起動したときにベースライン転送が実行されます。デフォルトの一元化されたデータ保護ポリシー「 MirrorAllSnapshots 」に基づくベースライン転送では、ソースボリュームの Snapshot コピーが作成され、そのコピーおよびコピーが参照するデータブロックがデスティネーションボリュームに転送されます。SnapVaultと同様に、一元化されたデータ保護ではベースラインに古いSnapshotコピーは含まれません。



== 厳密な同期を使用したSnapMirror同期保護

「 stict 」同期を使用した SnapMirror 同期保護では、プライマリボリュームとセカンダリボリュームが常に相互の完全なコピーになります。セカンダリボリュームへのデータの書き込み時にレプリケーションエラーが発生すると、プライマリボリュームへのクライアントI/Oが中断されます。



== 通常の同期を使用したSnapMirror同期保護

「ル」同期を使用した SnapMirror 同期保護では、プライマリボリュームとセカンダリボリュームが常に相互の完全なコピーである必要はないため、プライマリボリュームの可用性が確保されます。セカンダリボリュームへのデータの書き込み時にレプリケーションエラーが発生すると、プライマリボリュームとセカンダリボリュームの同期が失われ、プライマリボリュームへのクライアントI/Oが続行されます。

[NOTE]
====
同期保護関係を Health ： All Volumes ビューまたは Volume/Health Details ページから監視する場合、 Restore ボタンと Relationship 操作ボタンは使用できません。

====


== SnapMirrorアクティブ同期

SnapMirrorのアクティブな同期機能はONTAP 9.8以降で使用できます。この機能を使用すると、LUNでアプリケーションを保護できます。これにより、アプリケーションが透過的にフェイルオーバーされ、災害発生時にビジネス継続性が確保されます。

クラスタおよびStorage Virtual Machineで使用可能な整合グループ（CG）の同期SnapMirror関係をUnified Managerから検出および監視することができます。SnapMirrorアクティブ同期は、AFFクラスタまたはオールSANアレイ（ASA）クラスタでサポートされます。プライマリクラスタとセカンダリクラスタには、AFFまたはASAを使用できます。SnapMirror Active Syncは、iSCSI LUNまたはFCP LUNを使用してアプリケーションを保護します。

SnapMirrorのアクティブな同期関係で保護されているボリュームとLUNを表示すると、保護関係、ボリュームインベントリ内のコンシステンシグループ、コンシステンシグループ関係の保護トポロジ、コンシステンシグループ関係の過去1年間の履歴データの表示が統一されます。レポートをダウンロードすることもできます。また'コンシステンシ・グループ関係の概要の表示'コンシステンシ・グループ関係のサポートの検索'コンシステンシ・グループによって保護されているボリュームに関する情報の取得も可能です

[Relationships]ページでは、ソースストレージオブジェクトとデスティネーションストレージオブジェクト、およびコンシステンシグループによって保護されているそれらの関係に対して、保護のソート、フィルタ、拡張を行うこともできます。

SnapMirrorアクティブ同期の詳細については、を参照してくださいlink:https://docs.netapp.com/us-en/ontap/smbc/index.html["SnapMirror Active Sync（旧SM-BC）に関するONTAP 9ドキュメント"]。
