---
permalink: data-protection/concept_what_resource_pools_are.html 
sidebar: sidebar 
keywords: resource pools 
summary: リソースプールは、 Unified Manager を使用してストレージ管理者が作成するアグリゲートのグループであり、バックアップ管理用のパートナーアプリケーションにプロビジョニングを提供します。 
---
= リソースプールとは
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
リソースプールは、 Unified Manager を使用してストレージ管理者が作成するアグリゲートのグループであり、バックアップ管理用のパートナーアプリケーションにプロビジョニングを提供します。

リソースは、パフォーマンス、コスト、物理的な場所、可用性などの属性に基づいてプールにまとめることができます。関連するリソースをプールにグループ化することで、監視とプロビジョニングのためにプールを1つのユニットとして扱うことができます。これにより、リソースの管理が簡易化され、柔軟かつ効率的にストレージを使用できるようになります。

Unified Managerでは、セカンダリストレージのプロビジョニング時にリソースプールから保護に最適なアグリゲートが次の基準で選択されます。

* アグリゲートが（ルートアグリゲートではなく）データアグリゲートであり、オンラインになっている。
* アグリゲートがデスティネーションクラスタノードにあり、ONTAPのバージョンがソースクラスタのメジャーバージョン以上である。
* アグリゲートには、リソースプール内のすべてのアグリゲートのうち、使用可能なスペースが最も大きいスペースがあります。
* デスティネーションボリュームのプロビジョニング後、アグリゲートスペースがアグリゲートに定義されている「ほぼフル」および「ほぼオーバーコミット」のしきい値（グローバルまたはローカルのしきい値のいずれか該当する値）の範囲内に収まっている。
* デスティネーションノードのFlexVolボリュームの数がプラットフォームの制限を超えないようにする必要があります。

