---
permalink: data-protection/reference_resynchronize_dialog_box.html 
sidebar: sidebar 
keywords: resynchronize, dialog box 
summary: '[Resynchronize]ダイアログボックスでは、以前に解除してデスティネーションが読み書き可能ボリュームになったSnapMirror関係またはSnapVault関係のデータを再同期できます。再同期は、必要な共通のSnapshotコピーがソースボリュームで削除されたためにSnapMirrorまたはSnapVaultの更新が失敗した場合にも実行できます。' 
---
= [Resynchronize]ダイアログボックス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
[Resynchronize]ダイアログボックスでは、以前に解除してデスティネーションが読み書き可能ボリュームになったSnapMirror関係またはSnapVault関係のデータを再同期できます。再同期は、必要な共通のSnapshotコピーがソースボリュームで削除されたためにSnapMirrorまたはSnapVaultの更新が失敗した場合にも実行できます。



== 再同期オプションタブ

[Resynchronization Options]タブでは、再同期する保護関係の転送の優先順位と最大転送速度を設定できます。

* * 転送優先順位 *
+
転送を実行する優先順位。標準（Normal）または低（Low）を選択できます。ポリシーで転送の優先順位「Normal」が指定されている関係は、転送の優先順位「Low」が指定された関係よりも先に実行されます。

* * 最大転送速度 *
+
ネットワークを介してクラスタ間でデータを転送する最大速度を指定します。このオプションを選択すると、ネットワーク帯域幅は指定した値に制限されます。数値を入力してから、KBps（1秒あたりのキロバイト数）、MBps（1秒あたりのメガバイト数）、GBps（1秒あたりのギガバイト数）、Tbpsのいずれかを選択できます。最大転送速度を指定しない場合は、関係間でベースライン転送が制限されません。





== [Source Snapshot Copies]タブ

[ソースSnapshotコピー]タブには、ベースライン転送に使用されるソースSnapshotコピーに関する次の情報が表示されます。

* * ソースボリューム *
+
対応するソースボリュームの名前が表示されます。

* * デスティネーションボリューム *
+
選択したデスティネーションボリュームの名前が表示されます。

* * ソースタイプ *
+
ボリュームタイプ（読み取り/書き込みまたはデータ保護）が表示されます。

* * Snapshot コピー *
+
データ転送に使用されるSnapshotコピーが表示されます。[Snapshot copy]の値をクリックすると、[ソースSnapshotコピーの選択]ダイアログボックスが表示されます。このダイアログボックスで、確立されている保護関係のタイプと実行中の処理に応じて、転送用のSnapshotコピーを選択できます。





== コマンドボタン

* * 送信 *
+
再同期プロセスを開始して、再同期ダイアログボックスを閉じます。

* * キャンセル *
+
選択内容をキャンセルして[Resynchronize]ダイアログボックスを閉じます。


