---
permalink: data-protection/reference_initialize_update_relationship_dialog_box.html 
sidebar: sidebar 
keywords: initialize, update, dialog box 
summary: '[初期化/更新]ダイアログボックスでは、新しい保護関係の初回のベースライン転送を実行できます。また、すでに初期化されている関係でスケジュールされていない増分更新を手動で実行する場合は、関係を更新できます。' 
---
= [初期化/更新]ダイアログボックス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
[初期化/更新]ダイアログボックスでは、新しい保護関係の初回のベースライン転送を実行できます。また、すでに初期化されている関係でスケジュールされていない増分更新を手動で実行する場合は、関係を更新できます。



== [ 転送オプション ] タブ

[転送オプション]タブでは、転送の初期化優先度を変更したり、転送中に使用する帯域幅を変更したりできます。

* * 転送優先順位 *
+
転送を実行する優先順位。標準（Normal）または低（Low）を選択できます。関係のポリシーで転送の優先順位「Normal」が指定されている場合、その関係は転送の優先順位「Lowデフォルトでは[Normal]が選択されます。

* * 最大転送速度 *
+
ネットワークを介してクラスタ間でデータを転送する最大速度を指定します。最大転送速度を指定しない場合は、関係間でベースライン転送が制限されません。最大転送速度が異なる複数の関係を選択する場合は、次のいずれかの最大転送速度設定を指定できます。

+
** 個 々 の関係の設定または編集時に指定した値を使用する
+
選択した場合、初期化処理と更新処理では、各関係の作成時または編集時に指定された最大転送速度が使用されます。このフィールドは、転送速度が異なる複数の関係を初期化または更新する場合にのみ表示されます。

** 無制限
+
関係間の転送に帯域幅の制限がないことを示します。このフィールドは、転送速度が異なる複数の関係を初期化または更新する場合にのみ表示されます。

** 帯域幅の制限
+
このオプションを選択すると、ネットワーク帯域幅は指定した値に制限されます。数値を入力し、KBps（1秒あたりのキロバイト数）、MBps（1秒あたりのメガバイト数）、GBps（1秒あたりのギガバイト数）、TBps（1秒あたりのテラバイト数）のいずれかを選択できます。最大転送速度は1KBps以上4TBps未満にする必要があります。







== [Source Snapshot Copies]タブ

[ソースSnapshotコピー]タブには、ベースライン転送に使用されるソースSnapshotコピーに関する次の情報が表示されます。

* * ソースボリューム *
+
対応するソースボリュームの名前が表示されます。

* * デスティネーションボリューム *
+
選択したデスティネーションボリュームの名前が表示されます。

* * ソースタイプ *
+
ボリュームタイプが表示されます。「読み取り/書き込み」または「データ保護」のいずれかです。

* * Snapshot コピー *
+
データ転送に使用されるSnapshotコピーが表示されます。[Snapshot copy]の値をクリックすると、[ソースSnapshotコピーの選択]ダイアログボックスが表示されます。このダイアログボックスで、確立されている保護関係のタイプと実行中の処理に応じて、転送用のSnapshotコピーを選択できます。データ保護タイプのソースには、別のSnapshotコピーを指定するオプションは使用できません。





== コマンドボタン

各コマンドボタンを使用して次のタスクを実行できます。

* * キャンセル *
+
選択内容を破棄して、[初期化/更新]ダイアログボックスを閉じます。

* * 送信 *
+
選択内容を保存し、初期化ジョブまたは更新ジョブを開始します。


