---
permalink: data-protection/reference_create_schedule_dialog_box.html 
sidebar: sidebar 
keywords: create, schedule, dialog box 
summary: '[スケジュールの作成]ダイアログボックスでは、SnapMirror関係およびSnapVault関係の転送の基本または詳細な保護スケジュールを作成できます。新しいスケジュールを作成して、データ更新を頻繁に行うためにデータ転送の頻度を増やすことも、データがあまり変更されない場合は少ない頻度のスケジュールを作成することもできます。' 
---
= [Create Schedule]ダイアログボックス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
[スケジュールの作成]ダイアログボックスでは、SnapMirror関係およびSnapVault関係の転送の基本または詳細な保護スケジュールを作成できます。新しいスケジュールを作成して、データ更新を頻繁に行うためにデータ転送の頻度を増やすことも、データがあまり変更されない場合は少ない頻度のスケジュールを作成することもできます。

SnapMirror同期関係に対してスケジュールを設定することはできません。

* * デスティネーションクラスタ *
+
[保護の設定]ダイアログボックスの[保護]タブまたは[保護の設定]タブで選択したクラスタの名前SnapVault SnapMirror。

* * スケジュール名 *
+
スケジュールに指定する名前。スケジュール名には、A~Z、a~z、0~9、および特殊文字「！@ # $ % ｛ キャレット ｝ & * （） _ - 。スケジュール名には、以下の文字は使用できません。

* * Basic または Advanced *
+
使用するスケジュールモード。

+
基本モードには、次の要素が含まれます。

+
** リピート
+
スケジュールされた転送が発生する頻度。選択できるのは、Hourly、Daily、Weeklyです。

** 日
+
「Weekly」の繰り返しを選択した場合、転送が発生する曜日。

** 時間
+
「毎日」または「毎週」を選択した場合に転送が発生する時刻。



+
詳細モードには、次の要素が含まれます。

+
** 月
+
カンマで区切った数値のリスト。月を表します。有効な値は0~11です。0は1月を表し、以降も同様です。この要素はオプションです。このフィールドを空にすると、毎月転送が発生します。

** 日
+
カンマで区切った数値のリスト。日にちを表します。有効な値は1~31です。この要素はオプションです。このフィールドを空にすると、指定した月に毎日転送が発生します。

** 平日
+
カンマで区切った数値のリスト。曜日を表します。有効な値は0~6です。0は日曜日を表し、以降も同様です。この要素はオプションです。このフィールドを空にすると、指定した週に毎日転送が発生します。曜日を指定しても日にちを指定しない場合、毎日ではなく指定した曜日にのみ転送が実行されます。

** 時間
+
カンマで区切った数値のリスト。1日の時間数を表します。有効な値は0~23です。0は午前0時を表します。この要素はオプションです。

** 分
+
カンマで区切った数値のリスト。1時間の分数を表します。有効な値は0~59です。この要素は必須です。




