---
permalink: data-protection/reference_relationship_last_1_month_transfer_rate_view.html 
sidebar: sidebar 
keywords: relationship, 1 month, transfer rate, view 
summary: Relationship ： Last 1 month Transfer Rate ビューを使用すると、非同期関係にあるボリュームについて、転送されるデータボリュームの量を 1 日単位で分析できます。また、このページには、日次転送に関する詳細と、ボリュームとStorage VMの転送処理を完了するために必要な時間も表示されます。 
---
= 関係：過去 1 カ月の転送速度ビュー
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Relationship ： Last 1 month Transfer Rate ビューを使用すると、非同期関係にあるボリュームについて、転送されるデータボリュームの量を 1 日単位で分析できます。また、このページには、日次転送に関する詳細と、ボリュームとStorage VMの転送処理を完了するために必要な時間も表示されます。

ページの上部にあるコントロールを使用すると、検索を実行して特定のオブジェクトを検索したり、フィルタを作成して適用して表示データのリストを絞り込んだり、ページ上の列を追加/削除/並べ替えたり、ページ上のデータを.csv、.pdf、または.xlsxファイルにエクスポートしたりできます。ページをカスタマイズしたら、結果をカスタムビューとして保存し、このデータのレポートを定期的に生成してEメールで送信するようにスケジュール設定できます。たとえば、ボリュームの関係を表示するには、 * Storage * > * Volumes * > * Relationship ： Last 1 Month Transfer Rate * メニュー、または * Protection * > * Relationships ： Last 1 Month Transfer Rate * メニューのいずれかにアクセスし、 * Filter * を使用してボリュームのデータのみを表示できます。

* * 合計転送サイズ *
+
ボリューム転送の合計サイズ（GB）が表示されます。

* * 日 *
+
ボリューム転送が開始された日にちが表示されます。

* * 終了時間 *
+
ボリューム転送が終了した日時が表示されます。



* 関連情報 *

* 関係：MetroCluster *ビューの詳細については、を参照してくださいlink:../storage-mgmt/task_monitor_metrocluster_configurations.html["MetroCluster設定の監視"]。
* [関係：過去1カ月の転送ステータス]*ビューの詳細については、を参照してくださいlink:../data-protection/reference_relationship_last_1_month_transfer_status_view.html["関係：過去 1 カ月の転送ステータス画面"]。
* [関係：すべての関係]*ビューの詳細については、を参照してください。link:../data-protection/reference_relationship_last_1_month_transfer_rate_view.html["関係：過去 1 カ月の転送速度ビュー"]

