---
permalink: data-protection/reference_edit_relationship_dialog_box.html 
sidebar: sidebar 
keywords: edit, relationship, dialog box 
summary: 既存の保護関係を編集して、最大転送速度、保護ポリシー、保護スケジュールを変更することができます。 
---
= [Edit Relationship]ダイアログボックス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
既存の保護関係を編集して、最大転送速度、保護ポリシー、保護スケジュールを変更することができます。



== デスティネーション情報

* * デスティネーションクラスタ *
+
選択したデスティネーションクラスタの名前。

* * デスティネーション SVM *
+
選択した SVM の名前

* * 関係設定 *
+
保護関係で使用する最大転送速度、SnapMirrorポリシー、およびスケジュールを指定できます。

+
** 最大転送速度
+
ネットワークを介してクラスタ間でベースラインデータを転送する最大速度を指定します。このオプションを選択すると、ネットワーク帯域幅は指定した値に制限されます。数値を入力し、KBps（1秒あたりのキロバイト数）、MBps（1秒あたりのメガバイト数）、GBps（1秒あたりのギガバイト数）、TBps（1秒あたりのテラバイト数）のいずれかを選択できます。最大転送速度は1KBps以上4TBps未満にする必要があります。最大転送速度を指定しない場合は、関係間でベースライン転送が制限されません。プライマリクラスタとセカンダリクラスタが同じ場合、この設定は無効になります。

** SnapMirror ポリシー
+
関係のONTAP SnapMirrorポリシーを指定します。デフォルトはDPDefaultです。

** ポリシーの作成
+
[ SnapMirrorポリシーの作成]ダイアログボックスが開きます。このダイアログボックスで、新しいSnapMirrorポリシーを作成して使用できます。

** SnapMirror スケジュール
+
関係のONTAP SnapMirrorポリシーを指定します。スケジュールには、None、5min、8hour、daily、hourly、weeklyがあります。デフォルトは[なし]で、関係にスケジュールが関連付けられていません。スケジュールのない関係については、ストレージサービスに属している場合を除き、遅延ステータスの値は表示されません。

** スケジュールの作成
+
[スケジュールの作成]ダイアログボックスを開きます。このダイアログボックスで、新しいSnapMirrorスケジュールを作成できます。







== コマンドボタン

各コマンドボタンを使用して次のタスクを実行できます。

* * キャンセル *
+
選択内容を破棄して[保護の設定]ダイアログボックスを閉じます。

* * 送信 *
+
選択内容を適用して[関係の編集]ダイアログボックスを閉じます。


