---
permalink: data-protection/reference_protection_storage_virtual_machine_associations_page.html 
sidebar: sidebar 
keywords: svm, association, page 
summary: Storage VMの関連付けページでは、ソースとデスティネーションのStorage VM間の既存のStorage VMの関連付けを表示できます。 
---
= Storage VMの関連付けの概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Storage Virtual Machine（Storage VM）の関連付けは、ソースStorage VMからデスティネーションStorage VMへのマッピングであり、リソースの選択やセカンダリボリュームのプロビジョニングのためにパートナーアプリケーションで使用されます。

デスティネーションStorage VMがセカンダリデスティネーションであるか3番目のデスティネーションであるかに関係なく、ソースStorage VMとデスティネーションStorage VMの間に関連付けが作成されます。セカンダリデスティネーションStorage VMをソースとして使用して、3番目のデスティネーションStorage VMとの関連付けを作成することはできません。

アプリケーション管理者またはストレージ管理者は、環境内のStorage VMの関連付けを* Protection *>* Storage VM Associations *ページで確認できます。

SVMを関連付ける方法は3つあります。

* *任意のStorage VMを関連付け*：任意のプライマリソースStorage VMと1つ以上のデスティネーションSVMの間で関連付けを作成できます。つまり、現時点で保護を必要とする既存のすべてのSVMおよび今後作成されるすべてのSVMが指定したデスティネーションSVMに関連付けられます。たとえば、異なる場所にある複数のソースのアプリケーションを1箇所にある1つ以上のデスティネーションSVMにバックアップできます。
* *特定のStorage VMを関連付け*：特定のソースStorage VMと1つ以上の特定のデスティネーションSVMの間で関連付けを作成できます。たとえば、データを互いに分離する必要がある多数のクライアントにストレージサービスを提供する場合は、このオプションを選択して、特定のソースStorage VMを、そのクライアントにのみ割り当てられる特定のデスティネーションStorage VMに関連付けることができます。
* *外部Storage VMと関連付け*：ソースStorage VMとデスティネーションStorage VMの外部のフレキシブルボリュームとの間で関連付けを作成できます。




== Storage VMの関連付けを作成

[Create Storage Virtual Machine Associations]ウィザードを使用すると、パートナーの保護アプリケーションでソースStorage VMをデスティネーションStorage VMに関連付けて、SnapMirror関係とSnapVault関係で使用できます。パートナーアプリケーションは、デスティネーションボリュームの初期プロビジョニング時にこれらの関連付けを使用して、選択するリソースを決定します。dd

* 必要なもの *

* 関連付けるStorage VMがすでに存在している必要があります。
* アプリケーション管理者またはストレージ管理者のロールが必要です。


ソースStorage VMと関係タイプについては、各デスティネーションクラスタでデスティネーションStorage VMを1つだけ選択できます。

削除機能と作成機能を使用して関連付けを変更すると、以降のプロビジョニング処理にのみ影響します。既存のデスティネーションボリュームは移動されません。

.手順
. 左側のナビゲーションペインで、* Protection *>* Storage VM Associations *をクリックします。
. [* Storage VM Associations]ページで、[* Create]をクリックします。
+
Create Storage Virtual Machine Associations *ウィザードが起動します。

. 次のいずれかのソースを選択します。
+
** * 任意 *
+
任意のプライマリStorage VMソースと1つ以上のデスティネーションStorage VMの間で関連付けを作成する場合は、このオプションを選択します。つまり、現在保護が必要なすべての既存のStorage VMと今後作成されるすべてのStorage VMが、指定したデスティネーションStorage VMに関連付けられます。たとえば、異なる場所にある複数のソースのアプリケーションを、1箇所にある1つ以上のデスティネーションStorage VMにバックアップできます。

** * シングル *
+
1つ以上のデスティネーションStorage VMに関連付けられている特定のソースStorage VMを選択する場合は、このオプションを選択します。たとえば、データを互いに分離する必要がある多数のクライアントにストレージサービスを提供する場合、このオプションを選択して、特定のStorage VMソースを、そのクライアントにのみ割り当てられる特定のStorage VMデスティネーションに関連付けます。

** * なし（外部） *
+
ソースStorage VMとデスティネーションStorage VMの外部フレキシブルボリュームの間で関連付けを作成する場合は、このオプションを選択します。



. 作成する保護関係タイプを1つまたは両方選択します。
+
** * SnapMirror *
** * SnapVault *


. 「 * 次へ * 」をクリックします。
. Storage VM保護デスティネーションを1つ以上選択してください。
. [ 完了 ] をクリックします。




== Storage VMの関連付けを削除

パートナーアプリケーションに対するStorage VMの関連付けを削除して、ソースとデスティネーションのStorage VM間のセカンダリプロビジョニング関係を削除できます。たとえば、デスティネーションStorage VMがいっぱいになったときに、Storage VM保護の新しい関連付けを作成する場合などに削除できます。

* 必要なもの *

アプリケーション管理者またはストレージ管理者のロールが必要です。

Delete *ボタンは、Storage VMとの関連付けが少なくとも1つ選択されるまで無効になります。関連付けの削除機能と作成機能を使用して変更すると、以降のプロビジョニング処理にのみ影響します。既存のデスティネーションボリュームは移動されません。

.手順
. 左側のナビゲーションペインで、* Protection *>* Storage VM Associations *をクリックします。
. Storage VMの関連付けを少なくとも1つ選択してください。
+
* Delete * （削除）ボタンが有効になっています。

. [ 削除 ] をクリックします。 *
+
警告ダイアログボックスが表示されます。

. 続行するには、 [ はい ] をクリックします。
+
選択したStorage VMの関連付けがリストから削除されます。


