---
permalink: data-protection/reference_create_snapvault_policy_dialog_box.html 
sidebar: sidebar 
keywords: create, snapvault, policy, dialog box 
summary: '[Create SnapVault Policy]ダイアログボックスでは、SnapVault転送の優先度を設定するポリシーを作成できます。ポリシーを使用すると、プライマリボリュームからセカンダリボリュームへの転送効率を最大限に高めることができます。' 
---
= [Create SnapVault Policy]ダイアログボックス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
[Create SnapVault Policy]ダイアログボックスでは、SnapVault転送の優先度を設定するポリシーを作成できます。ポリシーを使用すると、プライマリボリュームからセカンダリボリュームへの転送効率を最大限に高めることができます。

* * デスティネーションクラスタ *
+
[保護の設定]ダイアログボックスの[保護]タブで選択したクラスタの名前SnapVault。

* * デスティネーション SVM *
+
[保護の設定]ダイアログボックスの[ SnapVault ]タブで選択したSVMの名前。

* * ポリシー名 *
+
新しいポリシーに指定する名前。ポリシー名には、A~Z、a~z、0~9、ピリオド（.）、ハイフン（-）、アンダースコア（_）を使用できます。

* * 転送優先順位 *
+
転送を実行する優先順位。標準（Normal）または低（Low）を選択できます。転送の優先順位として「標準」を指定したポリシーを使用する関係の転送は、「低」を指定したポリシーを使用する関係の転送の前に実行されます。デフォルト設定は[Normal]です。

* * コメント *
+
オプションのフィールド。SnapVaultポリシーに関する最大255文字のコメントを追加できます。

* * アクセス時間を無視 *
+
アクセス時間だけが変更されたファイルを差分転送で無視するかどうかを指定します。

* * レプリケーションラベル *
+
ポリシー内の特定のレプリケーションラベルが設定されたONTAPによって選択されたSnapshotコピーに関連付けられているルールを表形式で表示します。次の情報とアクションも使用できます。

+
** コマンドボタン
+
各コマンドボタンを使用して次の操作を実行できます。

+
*** 追加
+
Snapshotコピーラベルと保持数を作成できます。

*** 保持数の編集
+
既存のSnapshotコピーラベルの保持数を変更できます。保持数は1~251の数字にする必要があります。すべてのルールのすべての保持数の合計は251個以下にする必要があります。

*** 削除
+
既存のSnapshotコピーラベルを削除できます。



** Snapshotコピーラベル
+
Snapshotコピーラベルが表示されます。同じローカルSnapshotコピーポリシーを使用するボリュームを1つ以上選択すると、ポリシー内の各ラベルのエントリが表示されます。複数のローカルSnapshotコピーポリシーが設定された複数のボリュームを選択すると、すべてのポリシーのすべてのラベルがテーブルに表示されます。

** スケジュール
+
各Snapshotコピーラベルに関連付けられているスケジュールが表示されます。ラベルに複数のスケジュールが関連付けられている場合は、そのラベルのスケジュールがカンマで区切ったリストに表示されます。同じラベルでスケジュールが異なる複数のボリュームを選択すると、スケジュールには「 Various 」と表示され、選択したボリュームに複数のスケジュールが関連付けられていることが示されます。

** デスティネーションの保持数
+
指定したラベルに一致するSnapVaultセカンダリに保持されているSnapshotコピーの数が表示されます。複数のスケジュールを使用するラベルの保持数として、各ラベルとスケジュールのペアの保持数の合計が表示されます。2つ以上のローカルSnapshotコピーポリシーを使用する複数のボリュームを選択した場合、保持数は空になります。




