---
permalink: data-protection/reference_configure_protection_dialog_box.html 
sidebar: sidebar 
keywords: configure, protection, dialog box 
summary: '[保護の設定]ダイアログボックスを使用して、クラスタ上のすべての読み取り、書き込み、データ保護ボリュームに対してSnapMirror関係とSnapVault関係を作成し、ソースボリュームまたはプライマリボリューム上のデータがレプリケートされるようにすることができます。' 
---
= [Configure Protection]ダイアログボックス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
[保護の設定]ダイアログボックスを使用して、クラスタ上のすべての読み取り、書き込み、データ保護ボリュームに対してSnapMirror関係とSnapVault関係を作成し、ソースボリュームまたはプライマリボリューム上のデータがレプリケートされるようにすることができます。



== [ ソース ] タブ

* * トポロジビュー *
+
作成する関係が視覚的に表示されます。デフォルトでは、トポロジ内のソースが強調表示されます。

* * ソース情報 *
+
選択したソースボリュームに関する次の情報を含む詳細が表示されます。

+
** ソースクラスタ名
** ソース SVM 名
** ボリュームの累積合計サイズ
+
選択したすべてのソースボリュームの合計サイズが表示されます。

** ボリュームの累積使用サイズ
+
選択したすべてのソースボリュームのボリュームの累積使用サイズが表示されます。

** ソースボリューム
+
次の情報が表形式で表示されます。

+
*** ソースボリューム
+
選択したソースボリュームの名前が表示されます。

*** タイプ
+
ボリュームタイプが表示されます。

*** SnapLockタイプ
+
ボリュームのSnapLockタイプが表示されます。オプションは、[Compliance]、[Enterprise]、およびSnapLockです。

*** Snapshot コピー
+
ベースライン転送に使用されるSnapshotコピーが表示されます。ソースボリュームが読み取り/書き込みの場合、[Snapshot copy]列の[Default]の値は、新しいSnapshotコピーがデフォルトで作成され、ベースライン転送に使用されることを示します。ソースボリュームがデータ保護ボリュームの場合、[Snapshot copy]列の[Default]の値は、新しいSnapshotコピーが作成されず、既存のすべてのSnapshotコピーがデスティネーションに転送されることを示します。[Snapshot copy]の値をクリックすると、ベースライン転送に使用する既存のSnapshotコピーを選択できるSnapshotコピーのリストが表示されます。ソースタイプがデータ保護の場合、別のデフォルトSnapshotコピーを選択することはできません。









== SnapMirror タブ

保護関係のデスティネーションクラスタ、Storage Virtual Machine（SVM）、アグリゲート、およびSnapMirror関係を作成する際のデスティネーションの命名規則を指定できます。SnapMirrorポリシーとスケジュールを指定することもできます。

* * トポロジビュー *
+
作成する関係が視覚的に表示されます。デフォルトでは、トポロジ内のSnapMirror宛先リソースが強調表示されます。

* * 目的地情報 *
+
保護関係のデスティネーションリソースを選択できます。

+
** 詳細リンク
+
SnapMirror関係の作成時に[詳細なデスティネーション設定]ダイアログボックスを開きます。

** クラスタ
+
保護デスティネーションホストとして使用できるクラスタが表示されます。このフィールドは必須です。

** Storage Virtual Machine （ SVM ）
+
選択したクラスタで使用可能な SVM が表示されます。このリストに SVM を表示するには、クラスタを選択する必要があります。このフィールドは必須です。

** アグリゲート
+
選択した SVM で使用できるアグリゲートが表示されます。このリストにアグリゲートを表示するには、クラスタを選択する必要があります。このフィールドは必須です。[Aggregate]リストには次の情報が表示されます。

+
*** ランク
+
複数のアグリゲートがデスティネーションの要件をすべて満たす場合、この順位は、次の条件に従ってアグリゲートを表示する優先順位を示します。

+
.... ソースボリュームのノードとは別のノードに配置されているアグリゲートが優先され、フォールトドメインの分離が可能になります。
.... ボリュームの数が少ないノード上のアグリゲートが優先され、クラスタ内のノード間で負荷を分散できます。
.... 他のアグリゲートよりも空きスペースの多いアグリゲートが優先され、容量の分散が可能になります。ランク1は、3つの条件に基づいてアグリゲートが最も優先されることを意味します。


*** アグリゲート名
+
アグリゲートの名前

*** 使用可能容量
*** データ用のアグリゲートで使用可能なスペースの量
*** リソースプール
+
アグリゲートが属するリソースプールの名前



** 命名規則
+
デスティネーションボリュームに適用されるデフォルトの命名規則を指定します。用意されている命名規則をそのまま使用することも、カスタムの命名規則を作成することもできます。命名規則には、 %C 、 %M 、 %V 、 %N という属性を指定できます。 %C はクラスタ名、 %M は SVM 名、 %V はソースボリューム、 %N はトポロジのデスティネーションノード名です。

+
エントリが無効な場合は、[命名規則]フィールドが赤で強調表示されます。「名前のプレビュー」リンクをクリックすると、入力した命名規則のプレビューが表示され、テキストフィールドに命名規則を入力するとプレビューテキストが動的に更新されます。関係の作成時にデスティネーション名に001~999のサフィックスが追加され、プレビューテキストに表示されるnnnが置き換えられます。001が最初に割り当てられ、002が2番目に割り当てられます（以降も同様）。



* * 関係設定 *
+
保護関係で使用する最大転送速度、SnapMirrorポリシー、およびスケジュールを指定できます。

+
** 最大転送速度
+
ネットワークを介してクラスタ間でデータを転送する最大速度を指定します。最大転送速度を指定しない場合は、関係間でベースライン転送が制限されません。

** SnapMirror ポリシー
+
関係のONTAP SnapMirrorポリシーを指定します。デフォルトはDPDefaultです。

** ポリシーの作成
+
[ SnapMirrorポリシーの作成]ダイアログボックスが開きます。このダイアログボックスで、新しいSnapMirrorポリシーを作成して使用できます。

** SnapMirror スケジュール
+
関係のONTAP SnapMirrorポリシーを指定します。スケジュールには、None、5min、8hour、daily、hourly、weeklyがあります。デフォルトは[なし]で、関係にスケジュールが関連付けられていません。スケジュールのない関係については、ストレージサービスに属している場合を除き、遅延ステータスの値は表示されません。

** スケジュールの作成
+
[スケジュールの作成]ダイアログボックスを開きます。このダイアログボックスで、新しいSnapMirrorスケジュールを作成できます。







== SnapVault タブ

保護関係のセカンダリクラスタ、 SVM 、アグリゲート、および SnapVault 関係を作成する際のセカンダリボリュームの命名規則を指定できます。SnapVaultポリシーとスケジュールを指定することもできます。

* * トポロジビュー *
+
作成する関係が視覚的に表示されます。デフォルトでは、トポロジ内のSnapVaultセカンダリリソースが強調表示されます。

* * 二次情報 *
+
保護関係のセカンダリリソースを選択できます。

+
** 詳細リンク
+
[Advanced Secondary Settings]ダイアログボックスを開きます。

** クラスタ
+
セカンダリ保護ホストとして使用できるクラスタが表示されます。このフィールドは必須です。

** Storage Virtual Machine （ SVM ）
+
選択したクラスタで使用可能な SVM が表示されます。このリストに SVM を表示するには、クラスタを選択する必要があります。このフィールドは必須です。

** アグリゲート
+
選択した SVM で使用できるアグリゲートが表示されます。このリストにアグリゲートを表示するには、クラスタを選択する必要があります。このフィールドは必須です。[Aggregate]リストには次の情報が表示されます。

+
*** ランク
+
複数のアグリゲートがデスティネーションの要件をすべて満たす場合、この順位は、次の条件に従ってアグリゲートを表示する優先順位を示します。

+
.... プライマリボリュームノードとは別のノードに配置されたアグリゲートが優先され、フォールトドメインの分離が可能になります。
.... ボリュームの数が少ないノード上のアグリゲートが優先され、クラスタ内のノード間で負荷を分散できます。
.... 他のアグリゲートよりも空きスペースの多いアグリゲートが優先され、容量の分散が可能になります。ランク1は、3つの条件に基づいてアグリゲートが最も優先されることを意味します。


*** アグリゲート名
+
アグリゲートの名前

*** 使用可能容量
*** データ用のアグリゲートで使用可能なスペースの量
*** リソースプール
+
アグリゲートが属するリソースプールの名前



** 命名規則
+
セカンダリボリュームに適用されるデフォルトの命名規則を指定します。用意されている命名規則をそのまま使用することも、カスタムの命名規則を作成することもできます。命名規則には、 %C 、 %M 、 %V 、 %N という属性を指定できます。 %C はクラスタ名、 %M は SVM 名、 %V はソースボリューム、 %N はトポロジのセカンダリノード名です。

+
エントリが無効な場合は、[命名規則]フィールドが赤で強調表示されます。「名前のプレビュー」リンクをクリックすると、入力した命名規則のプレビューが表示され、テキストフィールドに命名規則を入力するとプレビューテキストが動的に更新されます。無効な値を入力すると、プレビュー領域には無効な情報が赤い疑問符で表示されます。関係が作成されると、セカンダリ名に001~999のサフィックスが追加され、プレビューテキストに表示されるnnnが置き換えられます。001が最初に割り当てられ、002が2番目に割り当てられます（以降も同様）。



* * 関係設定 *
+
保護関係で使用される最大転送速度、SnapVaultポリシー、およびSnapVaultスケジュールを指定できます。

+
** 最大転送速度
+
ネットワークを介してクラスタ間でデータを転送する最大速度を指定します。最大転送速度を指定しない場合は、関係間でベースライン転送が制限されません。

** SnapVault ポリシー
+
関係のONTAP SnapVaultポリシーを指定します。デフォルトはXDPDefaultです。

** ポリシーの作成
+
[ SnapVaultポリシーの作成]ダイアログボックスが開きます。このダイアログボックスで、新しいSnapVaultポリシーを作成して使用できます。

** SnapVault スケジュール
+
関係のONTAP SnapVaultスケジュールを指定します。スケジュールには、None、5min、8hour、daily、hourly、weeklyがあります。デフォルトは[なし]で、関係にスケジュールが関連付けられていません。スケジュールのない関係については、ストレージサービスに属している場合を除き、遅延ステータスの値は表示されません。

** スケジュールの作成
+
[Create Schedule]ダイアログボックスを開きます。このダイアログボックスで、SnapVaultスケジュールを作成できます。







== コマンドボタン

各コマンドボタンを使用して次のタスクを実行できます。

* * キャンセル *
+
選択内容を破棄して[保護の設定]ダイアログボックスを閉じます。

* * 適用 *
+
選択項目を適用して保護プロセスを開始します。


