---
permalink: data-protection/reference_advanced_secondary_setting_dialog_box.html 
sidebar: sidebar 
keywords: advanced, secondary, settings, dialog box 
summary: '[セカンダリの詳細設定]ダイアログボックスを使用して、セカンダリボリュームのバージョンに依存しないレプリケーション、複数コピーのバックアップ、およびスペース関連の設定を有効にできます。[セカンダリの詳細設定]ダイアログボックスは、現在の設定の有効化または無効化を変更する場合に使用できます。' 
---
= [Advanced Secondary Settings]ダイアログボックス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
[セカンダリの詳細設定]ダイアログボックスを使用して、セカンダリボリュームのバージョンに依存しないレプリケーション、複数コピーのバックアップ、およびスペース関連の設定を有効にできます。[セカンダリの詳細設定]ダイアログボックスは、現在の設定の有効化または無効化を変更する場合に使用できます。

スペース関連の設定では、重複排除、データ圧縮、自動拡張、スペースギャランティなど、格納されるデータの量を最大限に増やすことができます。

このダイアログボックスには、次のフィールドがあります。

* * バージョンに依存しないレプリケーション * を有効にします
+
バージョンに依存しないレプリケーションでSnapMirrorを有効にします。バージョンに依存しないレプリケーションを使用すると、デスティネーションボリュームでソースボリュームよりも前のバージョンのONTAPが実行されている場合でも、ソースボリュームのSnapMirror保護が可能になります。

+
** バックアップを有効にする
+
バージョンに依存しないレプリケーションを有効にすると、SnapMirrorソースデータの複数のSnapshotコピーをSnapMirrorデスティネーションに転送して保持することもできます。



* * 重複排除を有効にする *
+
SnapVault関係のセカンダリボリュームで重複排除を有効にして、重複するデータブロックを排除してスペースを削減します。重複排除は、スペース削減率が10%以上で、データが頻繁に上書きされない場合に使用できます。重複排除は、仮想環境、ファイル共有、バックアップデータによく使用されます。この設定はデフォルトでは無効になっています。有効にすると、転送が完了するたびにこの処理が開始されます。

+
** 圧縮を有効にする
+
透過的なデータ圧縮を有効にします。圧縮は、スペース削減率が10%以上で、潜在的なオーバーヘッドを許容できる場合や、ピーク時以外の時間帯に圧縮を完了できるだけの十分なシステムリソースがある場合に使用します。SnapVault関係では、この設定はデフォルトで無効になっています。圧縮は、重複排除を選択した場合にのみ使用できます。

** インラインで圧縮
+
ディスクに書き込む前にデータを圧縮することで、スペース削減効果を即座に実現できます。インライン圧縮は、システムのピーク時の利用率が50%以下で、ピーク時に新しい書き込みやCPUの追加に対応できる場合に使用します。この設定は、「圧縮を有効にする」が選択されている場合にのみ使用できます。



* * 自動拡張を有効にします。 *
+
空きスペースの割合が指定したしきい値を下回ったときに、関連付けられているアグリゲートに使用可能なスペースが残っていれば、デスティネーションボリュームを自動的に拡張できます。

* * 最大サイズ *
+
ボリュームを拡張できる最大割合を設定します。デフォルトでは、ソースボリュームサイズよりも20%大きくなります。現在のサイズが自動拡張時の最大サイズ以上の場合、ボリュームは自動的に拡張されません。このフィールドは、自動拡張の設定を有効にした場合にのみ有効になります。

* * 増分サイズ *
+
ボリュームがソースボリュームの最大割合に達するまでに自動的に拡張される割合を指定します。

* * スペース保証 *
+
データ転送が常に成功するように、セカンダリボリュームに十分なスペースを割り当てます。スペースギャランティは次のいずれかに設定できます。

+
** ファイル
** ボリューム
** none + たとえば、 200GB のボリュームに合計 50GB のファイルが格納されており、それらのファイルに実際に格納されているデータは 10GB だけであるとします。Volume Guaranteeは、ソースの内容に関係なく、200GBをデスティネーションボリュームに割り当てます。[File]を選択すると、ソースでファイル用に十分なスペースが確保されるように50GBが割り当てられます。このシナリオで[None]を選択すると、ソースで実際にファイルデータに使用されているスペースに対して10GBだけがデスティネーションに割り当てられます。


+
スペースギャランティはデフォルトで[Volume]に設定されています。





== コマンドボタン

各コマンドボタンを使用して次のタスクを実行できます。

* * 適用 *
+
選択した効率化設定を保存し、 [ 保護の設定 ] ダイアログボックスで [ 適用 ] をクリックしたときに適用します。

* * キャンセル *
+
選択内容を破棄して、[詳細なデスティネーション設定]ダイアログボックスを閉じます。


