---
permalink: data-protection/reference_reverse_resync_dialog_box.html 
sidebar: sidebar 
keywords: reverse, resync, dialog box 
summary: ソースボリュームが無効になったために保護関係を解除し、デスティネーションを読み取り/書き込みボリュームにした場合は、逆再同期によって関係の方向を反転して、デスティネーションが新しいソースになり、ソースが新しいデスティネーションになるようにすることができます。 
---
= [Reverse Resync]ダイアログボックス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ソースボリュームが無効になったために保護関係を解除し、デスティネーションを読み取り/書き込みボリュームにした場合は、逆再同期によって関係の方向を反転して、デスティネーションが新しいソースになり、ソースが新しいデスティネーションになるようにすることができます。

災害によって保護関係のソースボリュームが機能しなくなった場合は、ソースの修理や交換、ソースの更新、関係の再確立を行う間、デスティネーションボリュームを読み書き可能に変換してデータの提供を継続できます。逆再同期処理を実行すると、共通の Snapshot コピーのデータよりも新しいソース上のデータは削除されます。



== キヤクサイトウキセン

逆再同期処理を実行する前の関係のソースとデスティネーションが表示されます。

* * ソースボリューム *
+
逆再同期処理を実行する前のソースボリュームの名前と場所。

* * デスティネーションボリューム *
+
逆再同期処理を実行する前のデスティネーションボリュームの名前と場所。





== キヤクサイトウキコ

リザーブ再同期処理を実行したあとの関係のソースとデスティネーションが表示されます。

* * ソースボリューム *
+
逆再同期処理を実行したあとのソースボリュームの名前と場所。

* * デスティネーションボリューム *
+
逆再同期処理を実行したあとのデスティネーションボリュームの名前と場所。





== コマンドボタン

各コマンドボタンを使用して次の操作を実行できます。

* * 送信 *
+
逆再同期プロセスを開始します。

* * キャンセル *
+
逆再同期処理を開始せずに[Reverse Resync]ダイアログボックスを閉じます。


