---
permalink: data-protection/task_resynchronize_protection_relationships.html 
sidebar: sidebar 
keywords: resynchronize, protection, relationships, volume, relationships page 
summary: '[Volume Relationships]ページでは、ソースボリュームを無効にしたイベントからリカバリする場合や現在のソースを別のボリュームに変更する場合に、関係を再同期できます。' 
---
= [ボリューム関係]ページでの保護関係の再同期
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
[Volume Relationships]ページでは、ソースボリュームを無効にしたイベントからリカバリする場合や現在のソースを別のボリュームに変更する場合に、関係を再同期できます。

* 必要なもの *

* アプリケーション管理者またはストレージ管理者のロールが必要です。
* Workflow Automationのセットアップが完了している必要があります。


.手順
. ボリュームの関係 * ページで、関係が休止中のボリュームを 1 つ以上選択し、ツールバーの * 再同期 * をクリックします。
+
[Resynchronize]ダイアログボックスが表示されます。

. [* Resynchronization Options] * タブで、転送の優先順位と最大転送速度を選択します。
. [ * ソース Snapshot コピー * ] をクリックし、 [ * Snapshot コピー * ] 列で [ * デフォルト * ] をクリックします。
+
[ソースSnapshotコピーの選択]ダイアログボックスが表示されます。

. デフォルトの Snapshot コピーを転送するのではなく、既存の Snapshot コピーを指定する場合は、 * 既存の Snapshot コピー * をクリックし、リストから Snapshot コピーを選択します。
. [Submit （送信） ] をクリックします。
+
[Resynchronize]ダイアログボックスに戻ります。

. 再同期するソースを複数選択した場合は、既存の Snapshot コピーを指定する次のソースに対して * Default * をクリックします。
. Submit * をクリックして、再同期ジョブを開始します。
+
再同期ジョブが開始されると、[Volume Relationships]ページに戻り、ページの上部にジョブのリンクが表示されます。

. * オプション： * Volume Relationships * ページで * View Jobs * をクリックして、各再同期ジョブのステータスを追跡します。
+
フィルタリングされたジョブのリストが表示されます。

. * オプション：ブラウザの * 戻る * 矢印をクリックして、 * ボリューム関係 * ページに戻ります。
+
すべてのタスクが正常に終了すれば再同期処理は終了です。


