---
permalink: data-protection/task_create_snapmirror_relationship_from_health_volume.html 
sidebar: sidebar 
keywords: create, snapmirror, protection, relationship,  volume, health details page 
summary: '[ボリューム/健全性の詳細]ページでは、データレプリケーションを保護用に有効にするためのSnapMirror関係を作成できます。SnapMirrorレプリケーションを使用すると、ソースでデータ損失が発生した場合にデスティネーションボリュームからデータをリストアできます。' 
---
= [ボリューム/健全性の詳細]ページでのSnapMirror保護関係の作成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
[ボリューム/健全性の詳細]ページでは、データレプリケーションを保護用に有効にするためのSnapMirror関係を作成できます。SnapMirrorレプリケーションを使用すると、ソースでデータ損失が発生した場合にデスティネーションボリュームからデータをリストアできます。

* 必要なもの *

* アプリケーション管理者またはストレージ管理者のロールが必要です。
* Workflow Automationのセットアップが完了している必要があります。


次の場合、 * Protect * メニューは表示されません。

* RBACの設定でこの操作が許可されていない場合：たとえば、オペレータのPrivilegesしかない場合
* ボリュームIDが不明な場合：クラスタ間関係が確立されているがデスティネーションクラスタが検出されていない場合など


保護ジョブは最大10個まで同時に実行でき、パフォーマンスに影響はありません。11~30個のジョブを同時に実行すると、パフォーマンスが低下することがあります。30を超えるジョブを同時に実行することは推奨されません。

.手順
. [* Volume/Health* （ボリューム / ヘルス * の詳細） ] ページの [* 保護 ] タブ * で、保護するボリュームの名前をトポロジビューで右クリックします。
. メニューから * Protect * > * SnapMirror * を選択します。
+
[Configure Protection]ダイアログボックスが表示されます。

. 「 * SnapMirror * 」をクリックして、「 * SnapMirror * 」タブを表示し、デスティネーション情報を設定します。
. 必要に応じて「 * 詳細設定 * 」をクリックしてスペースギャランティを設定し、「 * 適用 * 」をクリックします。
. [ 保護の設定 *] ダイアログボックスの [ 接続先情報 *] 領域と [ 関係設定 *] 領域に入力します。
. [ 適用（ Apply ） ] をクリックします。
+
[ボリューム/健全性の詳細]ページに戻ります。

. 「 * Volume/Health * details 」ページの上部にある保護設定ジョブのリンクをクリックします。
+
ジョブのタスクと詳細が[Job details]ページに表示されます。

. [ * ジョブ * の詳細 ] ページで、 [ * 更新 * ] をクリックして、保護設定ジョブに関連するタスクリストとタスクの詳細を更新し、ジョブが完了したかどうかを確認します。
. ジョブのタスクが完了したら、ブラウザの * 戻る * をクリックして * 音量 / ヘルス * の詳細ページに戻ります。
+
新しい関係が[ボリューム/健全性の詳細]ページのトポロジビューに表示されます。



設定時に指定したデスティネーションSVMや詳細設定で有効にしたオプションに応じて、次のいずれかのSnapMirror関係が作成されます。

* ソースボリュームと同じかそれよりも新しいバージョンのONTAPで実行されているデスティネーションSVMを指定した場合は、デフォルトでブロックレプリケーションベースのSnapMirror関係が作成されます。
* ソースボリュームと同じか新しいバージョンのONTAPで実行されているデスティネーションSVMを指定し、[詳細]設定でバージョンに依存しないレプリケーションを有効にした場合は、バージョンに依存しないレプリケーションを使用したSnapMirror関係が作成されます。
* 以前のバージョンのONTAPまたはソースボリュームよりも新しいバージョンで実行されているデスティネーションSVMを指定した場合、以前のバージョンでバージョンに依存しないレプリケーションがサポートされていれば、バージョンに依存しないレプリケーションを使用するSnapMirror関係が自動的に作成されます。

