---
permalink: data-protection/task_reverse_protection_relationships_from_health_volume_details.html 
sidebar: sidebar 
keywords: reverse, protection, relationships volume, health details page 
summary: 災害によって保護関係のソースボリュームが機能しなくなった場合は、ソースの修理や交換を行う間、デスティネーションボリュームを読み書き可能に変換してデータの提供を継続することができます。ソースがデータを受信できる状態に戻ったら、逆再同期処理を使用して逆方向の関係を確立し、ソースのデータを読み書き可能なデスティネーションのデータと同期できます。 
---
= [ボリューム/健全性の詳細]ページでの保護関係の反転
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
災害によって保護関係のソースボリュームが機能しなくなった場合は、ソースの修理や交換を行う間、デスティネーションボリュームを読み書き可能に変換してデータの提供を継続することができます。ソースがデータを受信できる状態に戻ったら、逆再同期処理を使用して逆方向の関係を確立し、ソースのデータを読み書き可能なデスティネーションのデータと同期できます。

* 必要なもの *

* アプリケーション管理者またはストレージ管理者のロールが必要です。
* Workflow Automationのセットアップが完了している必要があります。
* SnapVault関係を使用することはできません。
* 保護関係がすでに存在している必要があります。
* 保護関係が解除されている必要があります。
* ソースとデスティネーションの両方がオンラインになっている必要があります。
* ソースを別のデータ保護ボリュームのデスティネーションにすることはできません。
* このタスクを実行すると、共通のSnapshotコピーのデータよりも新しいソース上のデータが削除されます。
* 逆再同期した関係に対して作成されるポリシーとスケジュールは、元の保護関係と同じになります。
+
ポリシーとスケジュールが存在しない場合は作成されます。



.手順
. ボリューム / 健常性 * の詳細ページの * 保護 * タブで、トポロジからソースとデスティネーションを反転する SnapMirror 関係を探して右クリックします。
. メニューから * 逆再同期 * を選択します。
+
[Reverse Resync]ダイアログボックスが表示されます。

. 逆再同期を実行する関係が * 逆再同期 * （ Reverse Resync * ）ダイアログボックスに表示されていることを確認し、 * 送信 * （ Submit * ）をクリックします。
+
[逆再同期]ダイアログボックスが閉じ、[ボリューム/健全性の詳細]ページの上部にジョブのリンクが表示されます。

. * オプション： * Volume/Health * details ページで * View Jobs * をクリックして、各逆再同期ジョブのステータスを追跡します。
+
フィルタリングされたジョブのリストが表示されます。

. * オプション：ブラウザの * 戻る * 矢印をクリックして、 * 音量 / ヘルス * の詳細ページに戻ります。
+
すべてのタスクが正常に完了すれば逆再同期処理は終了です。


