---
permalink: data-protection/task_quiesce_protection_relationship_from_health_volume_details.html 
sidebar: sidebar 
keywords: quiesce, protection, relationship, volume, health details page 
summary: 保護関係を休止してデータ転送を一時的に停止できます。関係の休止は、データベースが格納されているSnapMirrorデスティネーションボリュームのSnapshotコピーを作成する場合に、Snapshotコピーの実行中にデータベース内容の安定を確保するために行うことができます。 
---
= [ボリューム/健全性の詳細]ページでの保護関係の休止
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
保護関係を休止してデータ転送を一時的に停止できます。関係の休止は、データベースが格納されているSnapMirrorデスティネーションボリュームのSnapshotコピーを作成する場合に、Snapshotコピーの実行中にデータベース内容の安定を確保するために行うことができます。

* 必要なもの *

* アプリケーション管理者またはストレージ管理者のロールが必要です。
* Workflow Automationのセットアップが完了している必要があります。


次の場合は休止操作が表示されません。

* RBACの設定でこの操作が許可されていない場合（オペレータのPrivilegesしかない場合など）
* ボリュームIDが不明な場合：クラスタ間関係が確立されているがデスティネーションクラスタが検出されていない場合など
* Workflow Automation と Unified Manager を連携させていない場合


.手順
. ボリューム / 健全性 * の詳細ページの * 保護 * タブで、休止する保護関係のトポロジビューで関係を右クリックします。
. メニューから「 * 休止」を選択します。
. 続行するには、 [ はい ] をクリックします。
+
休止ジョブのステータスは、[ボリューム/健全性の詳細]ページの上部にジョブの詳細へのリンクとともに表示されます。

. [ * 詳細の表示 * ] リンクをクリックして、 [ * ジョブ * 詳細 ] ページに移動し、詳細とジョブの進捗状況を確認します。
. * オプション：ブラウザの [ 戻る ] 矢印をクリックして、 * Volume/Health * の詳細ページに戻ります。
+
すべてのジョブタスクが正常に完了すれば休止ジョブは終了です。


