---
permalink: data-protection/task_create_cascade_or_fanout_relationships_to_extend_protection.html 
sidebar: sidebar 
keywords: create, cascade fanout, relationships, extend protection, existing protection relationship 
summary: 既存の関係のソースボリュームからのファンアウトまたはデスティネーションボリュームからのカスケードを作成することで、既存の関係から保護を拡張できます。この処理は、1つのサイトから複数のサイトにデータをコピーする場合や、バックアップを追加で作成して保護を強化する場合に実行します。 
---
= 保護を既存の保護関係から拡張するためのカスケード関係またはファンアウト関係の作成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
既存の関係のソースボリュームからのファンアウトまたはデスティネーションボリュームからのカスケードを作成することで、既存の関係から保護を拡張できます。この処理は、1つのサイトから複数のサイトにデータをコピーする場合や、バックアップを追加で作成して保護を強化する場合に実行します。

複数のボリュームを格納するコンテナである整合グループを使用してボリュームの保護を拡張し、すべてのボリュームを1つのエンティティとして管理できます。Unified Managerの[関係]ページで、SnapMirrorアクティブな同期整合性グループと同期整合性グループ関係を確認できます。

* 必要なもの *

* アプリケーション管理者またはストレージ管理者のロールが必要です。
* Workflow Automationのセットアップが完了している必要があります。


.手順
. [* 保護 *>] 、 [* 関係 *] の順にクリックします。また、[ボリュームの詳細]ページで関係を確認することもできます。
. * Volume Relationships * ページで、保護の拡張元の SnapMirror 関係を選択します。
. アクションバーで、 * 保護の拡張 * をクリックします。
. メニューで、ソースからファンアウト関係を作成するか、デスティネーションからカスケード関係を作成するかに応じて、ソースから * を選択するか、デスティネーションから * を選択します。
. 作成する保護関係のタイプに応じて、「 * with SnapMirror * 」または「 * with SnapVault * 」のいずれかを選択します。
+
[ 保護の設定 * （ Configure Protection * ） ] ダイアログボックスが表示されます。

+
[NOTE]
====
これは、[統合関係/ボリューム関係]および[ボリューム/健全性]の詳細ページで確認できます。

====
. [ 保護の設定 *] ダイアログボックスに示されている情報を入力します。

