---
permalink: data-protection/task_update_protection_voldtls_page.html 
sidebar: sidebar 
keywords: initialize, update, protection, relationships, volume, health details page 
summary: 新しい保護関係では初回のベースライン転送を実行できます。また、すでに初期化されている関係でスケジュールされていない増分更新を手動で実行してデータをただちに転送する場合は、関係を更新できます。 
---
= [ボリューム/健全性の詳細]ページでの保護関係の初期化または更新
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
新しい保護関係では初回のベースライン転送を実行できます。また、すでに初期化されている関係でスケジュールされていない増分更新を手動で実行してデータをただちに転送する場合は、関係を更新できます。

* 注：コンシステンシ・グループで保護されているボリュームは ' 初期化または更新できません

* 必要なもの *

* アプリケーション管理者またはストレージ管理者のロールが必要です。
* OnCommand Workflow Automation のセットアップが完了している必要があります。


.手順
. ボリューム / 健全性 * の詳細ページの * 保護 * タブで、初期化または更新する保護関係をトポロジから探して右クリックします。
. メニューから [Initialize] / [Update] を選択します。
+
または、 * アクション * メニューから * 関係 * > * 初期化 / 更新 * を選択して、現在詳細を表示している関係を初期化または更新します。

+
初期化/更新（Initialize/Update）ダイアログボックスが表示されます。

. 転送オプション * タブで、転送の優先順位と最大転送速度を選択します。
. [ * ソース Snapshot コピー * ] をクリックし、 [ * Snapshot コピー * ] 列で [ * デフォルト * ] をクリックします。
+
[ソースSnapshotコピーの選択]ダイアログボックスが表示されます。

. デフォルトの Snapshot コピーを転送するのではなく、既存の Snapshot コピーを指定する場合は、 * 既存の Snapshot コピー * をクリックし、リストから Snapshot コピーを選択します。
. [Submit （送信） ] をクリックします。
+
[初期化/更新（Initialize/Update）]ダイアログボックスに戻ります。

. 複数のソースを選択して初期化または更新する場合は、既存の Snapshot コピーを指定する次の読み取り / 書き込みソースに対して「 * Default 」をクリックします。
+
データ保護ボリュームには別のSnapshotコピーを選択できません。

. [Submit] をクリックして、初期化ジョブまたは更新ジョブを開始します。
+
初期化ジョブまたは更新ジョブが開始されると、[ボリューム/健全性の詳細]ページに戻り、ページの上部にジョブのリンクが表示されます。

. * オプション： * Volume/Health * の詳細ページで * View Jobs * をクリックして、各初期化ジョブまたは更新ジョブのステータスを追跡します。
+
フィルタリングされたジョブのリストが表示されます。

. * オプション： * 各ジョブをクリックすると詳細が表示されます。
. * オプション：ブラウザの [ 戻る ] 矢印をクリックして、 * Volume/Health * の詳細ページに戻ります。
+
すべてのジョブタスクが正常に完了すれば、初期化処理または更新処理は終了です。


