---
permalink: data-protection/task_create_snapmirror_relationship_with_version_flexible_replication.html 
sidebar: sidebar 
keywords: create, snapmirror, relationship, version-flexible, replication 
summary: バージョンに依存しないレプリケーションを使用してSnapMirror関係を作成できます。バージョンに依存しないレプリケーションを使用すると、ソースボリュームとデスティネーションボリュームで異なるバージョンのONTAPが実行されている場合でも、SnapMirror保護を実装できます。 
---
= バージョンに依存しないレプリケーションを使用したSnapMirror関係の作成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
バージョンに依存しないレプリケーションを使用してSnapMirror関係を作成できます。バージョンに依存しないレプリケーションを使用すると、ソースボリュームとデスティネーションボリュームで異なるバージョンのONTAPが実行されている場合でも、SnapMirror保護を実装できます。

* 必要なもの *

* アプリケーション管理者またはストレージ管理者のロールが必要です。
* Workflow Automationのセットアップが完了している必要があります。
* ソースとデスティネーションの SVM でそれぞれ、 SnapMirror ライセンスが有効になっている必要があります。
* ソースとデスティネーションのSVMが、それぞれバージョンに依存しないレプリケーションをサポートするバージョンのONTAPソフトウェアで実行されている必要があります。


バージョンに依存しないレプリケーションを使用するSnapMirrorでは、すべてのストレージが1つのバージョンのONTAPで実行されていない異機種混在ストレージ環境でもSnapMirror保護を実装できます。ただし、バージョンに依存しないレプリケーションを使用するSnapMirrorで実行されるミラー処理は、従来のブロックレプリケーションSnapMirrorで実行されるミラー処理ほど高速ではありません。

.手順
. 保護するボリュームの * 保護の設定 * ダイアログボックスを表示します。
+
** ボリューム / 健全性の詳細ページの保護タブを表示している場合は、保護するボリュームの名前を含むトポロジビューを右クリックし、メニューから * 保護 * > * SnapMirror * を選択します。
** Health ： All Volumes （すべてのボリューム）ビューを表示している場合は、保護するボリュームを探して右クリックし、メニューから * Protect * > * SnapMirror * * を選択します。[Configure Protection]ダイアログボックスが表示されます。


. 「 * SnapMirror * 」をクリックして、「 * SnapMirror * 」タブを表示します。
. [ 保護の設定 *] ダイアログボックスの [ 接続先情報 *] 領域と [ 関係設定 *] 領域に入力します。
+
保護するソースボリュームよりも前のバージョンのONTAPで実行されているデスティネーションSVMを指定し、以前のバージョンでバージョンに依存しないレプリケーションがサポートされている場合は、SnapMirrorでバージョンに依存しないレプリケーションが自動的に設定されます。

. ソースボリュームと同じバージョンの ONTAP で実行されているデスティネーション SVM を指定し、バージョンに依存しないレプリケーションで SnapMirror を設定する場合は、 * アドバンスト * をクリックしてバージョンに依存しないレプリケーションを有効にし、 * 適用 * をクリックします。
. [ 適用（ Apply ） ] をクリックします。
+
[ボリューム/健全性の詳細]ページに戻ります。

. 「 * Volume/Health * details 」ページの上部にある保護設定ジョブのリンクをクリックします。
+
ジョブのタスクと詳細が[Job details]ページに表示されます。

. [ * ジョブ * の詳細 ] ページで、 [ * 更新 * ] をクリックして、保護設定ジョブに関連するタスクリストとタスクの詳細を更新し、ジョブが完了したかどうかを確認します。
. ジョブのタスクが完了したら、ブラウザの * 戻る * をクリックして * 音量 / ヘルス * の詳細ページに戻ります。
+
新しい関係が[ボリューム/健全性の詳細]ページのトポロジビューに表示されます。


