---
permalink: data-protection/task_create_snapvault_protection_relationship_from_health_volume_details.html 
sidebar: sidebar 
keywords: create, snapvault, protection, relationship, volume, health details page 
summary: 'ボリュームでデータバックアップを有効にして保護するには、[ボリューム/健全性の詳細]ページを使用してSnapVault関係を作成します。' 
---
= [ボリューム/健全性の詳細]ページでのSnapVault保護関係の作成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ボリュームでデータバックアップを有効にして保護するには、[ボリューム/健全性の詳細]ページを使用してSnapVault関係を作成します。

* 必要なもの *

* アプリケーション管理者またはストレージ管理者のロールが必要です。
* このタスクを実行するには、 Workflow Automation をセットアップしておく必要があります。


次の場合、 * Protect * メニューは表示されません。

* RBACの設定でこの操作が許可されていない場合：たとえば、オペレータのPrivilegesしかない場合
* ボリュームIDが不明な場合：クラスタ間関係が確立されているがデスティネーションクラスタが検出されていない場合など


.手順
. [* Volume/Health* （ボリューム / ヘルス * の詳細） ] ページの [* 保護 ] タブで、保護するボリュームをトポロジビューで右クリックします。
. メニューから * Protect * > * SnapVault * を選択します。
+
[Configure Protection]ダイアログボックスが表示されます。

. SnapVault * をクリックして、 * SnapVault * タブを表示し、セカンダリ・リソース情報を設定します。
. [ * 詳細設定 * ] をクリックして、必要に応じて重複排除、圧縮、自動拡張、およびスペースギャランティを設定し、 [ * 適用 * ] をクリックします。
. [ 保護の設定 *] ダイアログボックスの [ 接続先情報 *] 領域と [ 関係設定 *] 領域に入力します。
. [ 適用（ Apply ） ] をクリックします。
+
[ボリューム/健全性の詳細]ページに戻ります。

. 「 * Volume/Health * details 」ページの上部にある保護設定ジョブのリンクをクリックします。
+
[Job details]ページが表示されます。

. 保護設定ジョブに関連するタスクリストとタスクの詳細を更新し、ジョブが完了したかどうかを確認するには、 [* Refresh] をクリックします。
+
ジョブタスクが完了すると、新しい関係が[ボリューム/健全性の詳細]ページのトポロジビューに表示されます。


