---
permalink: data-protection/task_abort_an_active_data_protection_transfer.html 
sidebar: sidebar 
keywords: abort, active data protection, transfer, volume relationships page, SnapMirror active sync 
summary: 実行中のSnapMirrorレプリケーションを停止する場合は、アクティブなデータ保護転送を中止できます。ベースライン転送後の転送については、再開チェックポイントをクリアすることもできます。転送を中止する状況としては、ボリューム移動などの別の処理と競合する場合などがあります。 
---
= [ボリューム関係]ページでのアクティブなデータ保護転送の中止
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
実行中のSnapMirrorレプリケーションを停止する場合は、アクティブなデータ保護転送を中止できます。ベースライン転送後の転送については、再開チェックポイントをクリアすることもできます。転送を中止する状況としては、ボリューム移動などの別の処理と競合する場合などがあります。


NOTE: 整合性グループで保護されているボリューム関係を中止することはできません。

* 必要なもの *

* アプリケーション管理者またはストレージ管理者のロールが必要です。
* Workflow Automationのセットアップが完了している必要があります。


中止処理は、次の場合には表示されません。

* RBACの設定でこの操作が許可されていない場合：たとえば、オペレータのPrivilegesしかない場合
* ボリュームIDが不明な場合：クラスタ間関係が確立されているがデスティネーションクラスタが検出されていない場合など


ベースライン転送の再開チェックポイントは消去できません。

.手順
. 1 つ以上の保護関係の転送を中止するには、 * ボリューム関係 * ページで 1 つ以上のボリュームを選択し、ツールバーで * 中止 * をクリックします。
+
[Abort Transfer]ダイアログボックスが表示されます。

. ベースライン転送以外の転送の再開チェックポイントをクリアする場合は、「 * チェックポイントのクリア * 」を選択します。
. [* Continue （続行） ] をクリックします
+
[転送の中止]ダイアログボックスが閉じ、[ボリューム関係]ページの上部に中止ジョブのステータスとジョブの詳細へのリンクが表示されます。

. * オプション： * View details * リンクをクリックして、 * Job * details ページで詳細を確認し、ジョブの進捗状況を確認します。

